### ISSUE TITLE
[Demand] Move emoji symbol to constant file

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1007]
Improve semantics.

**Comment by septs** [comment]
@Jack-Works @guanbinrui

**Comment by Jack-Works** [comment]
I thought emojis should be removed and use svg instead. Because they render differently on fonts

**Comment by neruthes** [comment]
Could you add more elaboration?

**Comment by Tedko** [comment]
> I thought emojis should be removed and use svg instead. Because they render differently on fonts

@Jack-Works will this affect ux?

**Comment by septs** [comment]
> I thought emojis should be removed and use svg instead. Because they render differently on fonts

all use SVG replace? (without bio text)

**Comment by Jack-Works** [comment]
> > I thought emojis should be removed and use svg instead. Because they render differently on fonts
> 
> all use SVG replace? (without bio text)

Yes if possible.

**Comment by septs** [comment]
@Jack-Works can close this issue?
