### ISSUE TITLE
Comment Encryption UX cannot deal with nested comment/reply

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#101]
<img width="520" alt="Screen Shot 2019-08-10 at 13 16 27" src="https://user-images.githubusercontent.com/6687437/62817912-2819f880-bb71-11e9-9765-e468c23649a5.png">
<img width="667" alt="Screen Shot 2019-08-10 at 13 16 55" src="https://user-images.githubusercontent.com/6687437/62817913-28b28f00-bb71-11e9-8ad0-ce00228adbde.png">

Another bug:

<img width="665" alt="Screen Shot 2019-08-10 at 13 20 25" src="https://user-images.githubusercontent.com/6687437/62817945-ba220100-bb71-11e9-9436-e3a1cba515c3.png">

See the pictures above.
For the 1st 2 pics: Easy to reproduce if you are trying to write comment with nested comments. Only one of the comment box with display the 'encryption comment box'. 
For the last pics: Click 'reply' on someone and then type sth in the  'encryption comment box' and post it, it will display like that.

Potential fix:
- Display multiple  'encryption comment box'

**Comment by Jack-Works** [comment]
Design limitation. Not easy to support multiple comment box for one post

**Comment by Tedko** [comment]
Can we do this: After click on one comment box the maskbook comment box
will show under that one

**Comment by neruthes** [comment]
Any update?
