### ISSUE TITLE
[Demand] Update red packet default image 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1010]
![Screen Shot 2020-04-26 at 17 33 26](https://user-images.githubusercontent.com/6687437/80303814-1f438280-87e5-11ea-9c79-bdcfef5f841a.png)
## Metadata
just Rm the Happy Chinese New Yr part - 
Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/gTMLz5RGFEIegKM8RT0eSd/redpacket_cover?node-id=0%3A1
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
Good.

In future we can explore the possibility of automatic seasonality.

**Comment by OiCkilL** [comment]
figma link: https://www.figma.com/file/gTMLz5RGFEIegKM8RT0eSd/redpacket_cover?node-id=0%3A1

**Comment by Tedko** [comment]
ok @guanbinrui let replace the img

**Comment by guanbinrui** [comment]
@OiCkilL Forget to mention that we have different base images for DAI and ETH. Need a DAI icon added base on the ETH one.

![maskbook-steganography-dai](https://user-images.githubusercontent.com/52657989/80356185-abb87880-88ab-11ea-9ca9-0e4c4f8ab84b.png)

**Comment by Tedko** [comment]
> @OiCkilL Forget to mention that we have different base images for DAI and ETH. Need a DAI icon added base on the ETH one.
> 
> ![maskbook-steganography-dai](https://user-images.githubusercontent.com/52657989/80356185-abb87880-88ab-11ea-9ca9-0e4c4f8ab84b.png)

@OiCkilL

**Comment by OiCkilL** [comment]
> @OiCkilL Forget to mention that we have different base images for DAI and ETH. Need a DAI icon added base on the ETH one.
> 
> ![maskbook-steganography-dai](https://user-images.githubusercontent.com/52657989/80356185-abb87880-88ab-11ea-9ca9-0e4c4f8ab84b.png)

done
