### ISSUE TITLE
[Demand] @dimensiondev/* npm packages Unauthorized

### ISSUE THREAD

**Issue by sandianyu** [DimensionDev/Maskbook#10208]
dimensiondev packages is not yet fully open source?

**Comment by Jack-Works** [comment]
hi @magicweirdben it's open-sourced and publicly available (to anyone with a GitHub account), but you need to follow this guide:

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

**Comment by sandianyu** [comment]
@Jack-Works Thanks, it's works.I have another question, **pnpm install** may get stuck. Is there any good solution.Thanks again.

**Comment by Jack-Works** [comment]
> @Jack-Works Thanks, it's works.I have another question, **pnpm install** may get stuck. Is there any good solution.Thanks again.

Please try https://pnpm.io/npmrc#https-proxy if you're in China

**Comment by sandianyu** [comment]
> 

Thanks a lot.
