### ISSUE TITLE
[Bug] Auto Paste Fail on Maskbook Mobile for Fb encrypted comment

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1024]
# Bug Report

Auto paste for Fb encrypted comment failed on both Maskbook iOS and Android (latest store ver)

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
hi @guanbinrui @Jack-Works take a look? should be a quick fix -

**Comment by Tedko** [comment]
@Jack-Works @guanbinrui

**Comment by Jack-Works** [comment]
let me investigate this

**Comment by Jack-Works** [comment]
@Tedko IMO it's working on the master branch
![image](https://user-images.githubusercontent.com/5390719/82175288-281c0580-9906-11ea-9913-e422aec902c4.png)

**Comment by Tedko** [comment]
Let’s try publish one mobile version based on that?

**Comment by neruthes** [comment]
New release 🎉

**Comment by Tedko** [comment]
@Tlaster @MainasuK

**Comment by Tedko** [comment]
Fixed on Android. Not fixed on iOS

**Comment by Tedko** [comment]
Will close this for now and leave all to #1158
