### ISSUE TITLE
[Demand] Add ERC20 token OKB

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1028]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/gTMLz5RGFEIegKM8RT0eSd/redpacket_cover?node-id=0:1 https://www.figma.com/file/VrUbo5q4bGh3GxOmNOxFWV/Red-Packet-Dai?node-id=0:1
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by Tedko** [comment]
LGTM. Just need to revise on the decimal. ;)
