### ISSUE TITLE
[Demand] Advanced Wallet Import Options

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1033]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Introduction
- UI Changes
- Keygen Changes

## Part 1: Introduction

We are going to migrate to password-insensitive keygen for wallets without impairing the compatibility with existing wallets and previously exported wallets.

### Import Wallet modal

Above the Import button, there will be a checkbox labeling "Advanced Options" to toggle the "Advanced Options" area below it.

The area contains 1 option:

Type | Field Name
--- | ---
Single-line input | Extra Passphrase

When the modal is rendered, the checkbox is unchecked by default.

When toggling the checkbox, the input data in the area should not be purged.

If the checkbox is unchecked, the input data inside will not participate the importing operation.

## Part 3: Keygen Changes

For wallet keygen, the password field shall be removed.

## Notes

- This will not affect Persona.
- Using checkbox instead of toggle control is an intentional decision. The checkbox informs the user that these options do not participate the importing operation when it is unchecked, while toggle control is merely a visibility matter.
- MetaMask does not support wallet-specific passwords.

**Comment by Tedko** [comment]
Good.
Maybe the best way is add a checkbox and say `Legacy/Old` Maskbook Wallet mem word.

For Private key export it will not be affected

**Comment by guanbinrui** [comment]
Why not do same thing on the persona importing modal?

**Comment by neruthes** [comment]
> Why not do same thing on the persona importing modal?

Let the discussions concerning Persona happen in #1051.

**Comment by Jack-Works** [comment]
is it already implemented?

**Comment by guanbinrui** [comment]
> is it already implemented?

<img width="445" alt="test-01" src="https://user-images.githubusercontent.com/52657989/95644362-b62c9e80-0ae8-11eb-9b93-f01cf59c4e88.png">
