### ISSUE TITLE
[Bug] Unable to decrypt long encrypted post on fb

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1039]
![IMG_6930](https://user-images.githubusercontent.com/6687437/80924293-b8146800-8dba-11ea-8a36-f4b708cea21f.PNG)
# Bug Report

Should able to get the content after `more` and auto decrypt 

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version: Latest Mobile/Chrome Store
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Such strange...

**Comment by Tedko** [comment]
One potential solution- like the script ignore the `more` and get the full content

**Comment by Jack-Works** [comment]
fixed in #1343
