### ISSUE TITLE
[Demand] Some adjustments on Red Packet images (OKB)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1048]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Introduction
- ...

## Part 1: Introduction

// To be specified by @OiCkilL

## Notes

**Comment by Tedko** [comment]
NOTE #1049 is not related with this issue

**Comment by neruthes** [comment]
Both issues in M3B should be published ASAP (i.e. today).

cc @guanbinrui @Jack-Works
