### ISSUE TITLE
[Demand] Post Payload Version Integrity

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1050]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Introduction
- Specification

## Part 1: Introduction

It is possible that an attack can take advantage of post-based Update Alert by counterfeiting a post payload which appears to be generated by a newer version of Maskbook.

We may maintain a private key which signs latest version declaration (to be attached in a post payload or any payload which may trigger update alerts). The private key can be replaced when we publish a new version.

## Part 2: Specification

// TODO

## Notes

- None.

**Comment by Jack-Works** [comment]
You can't predict the future so how do you know the future version payload is true or false?

**Comment by neruthes** [comment]
> You can't predict the future so how do you know the future version payload is real or fake?

That is why there may be a signature for the LatestVersionDeclaration which should be verified before triggering update alert from a Post.

However, it remains to be determined whether triggering update alerts from Posts is a good idea. 🤔
