### ISSUE TITLE
[Demand] Image-based payload should not cover original post content

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1052]
## Metadata

There's no reason to compress/cover the _original post content_ for image based payload.
For magic url/text payload based post we still want to partially cover/hide the payload to improve the UX but no reason for mage based payload.

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
Could you add more details in your description?

**Comment by neruthes** [comment]
More elaboration, please.

**Comment by guanbinrui** [comment]
> More elaboration, please.

I think @Tedko means no need to compress user text as single line when post with image payload.

**Comment by Tedko** [comment]
@guanbinrui yeah -

I mean no need to compress user text like this -

<img width="658" alt="Screen Shot 2020-05-10 at 15 38 21" src="https://user-images.githubusercontent.com/6687437/81493611-6d23b480-92d4-11ea-8b5a-da876afbf3d3.png">

**Comment by neruthes** [comment]
Good point. Will be arranged.

**Comment by Jack-Works** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/1086/commits/7aac75a4ffa0de4a610a099ba4f7101ad20c945f
