### ISSUE TITLE
[Demand] Add tests for upgrading from previous releases

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1054]
## Metadata

Field | Value
--- | ---
Expected engineering due | 2020-05-15
Corresponding Pull Request | -
Completion Version | - 1.10.13

## Catalogue

- E2E tests

## Part 1: 
Add tests to cover the case to upgrade from previous releases to ensure the upgrade doesn't break any internal database behavior.

**Comment by neruthes** [comment]
Make data reliable again!

**Comment by neruthes** [comment]
Which priority should be preferable? 🤔

**Comment by Tedko** [comment]
do we still need this issue for now?

**Comment by Jack-Works** [comment]
Maybe, yes
