### ISSUE TITLE
[Bug] Red Packet Detail View "Source" Area Behavior Inconsistency

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1059]
# Bug Report

### Maskbook

- Maskbook Version: *
- Installation: Store

### Expected Behavior

Area: Source

#634:

> This is the URL of the post where the current Persona initially tried opening.
> Note that a Red Packet may appear in multiple Posts. All such Posts present the same Red Packet.

The "Source URL" property should be written when/ and only when the user initially tried opening.

### Actual Behavior

Reports say that the URL is changed every time the user witnesses the same red packet in different posts.

### How To Reproduce

NULL

**Comment by yisiliu** [comment]
source: https://dimension.chat/group/maskbook?msg=8cSLrxTFDSXZFsrHx

**Comment by Tedko** [comment]
close for now. lots of red packet related feature is fixed already.
