### ISSUE TITLE
[Bug] CI tag conflict when fetching new commits

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1065]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

https://dimension.chat/group/maskbook-qa?msg=KQd9E5MokZXrDAtZM

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Jack-Works** [comment]
is this resolved? @guanbinrui

**Comment by guanbinrui** [comment]
resolved
