### ISSUE TITLE
[Demand] Update text payload

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1067]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Example

https://twitter.com/fakemaskbook/status/1259747828005388288

## Preview

![](https://dimension.chat/file-upload/t6qGXd8hwwrwSQ4Xt/%E6%88%AA%E5%B1%8F2020-05-11%20%E4%B8%8B%E5%8D%883.56.31.png)

![](https://dimension.chat/file-upload/r6dsFQgLmjTcM6FZE/%E6%88%AA%E5%B1%8F2020-05-11%20%E4%B8%8B%E5%8D%883.32.59.png)

**Comment by neruthes** [comment]
Please use "Do not" instead of "Don't". cc @Miaommmisokay

**Comment by Tedko** [comment]
yeah use `do not`
