### ISSUE TITLE
Feature: popup interface that does deconstructPayload and/or verifyOthersProve

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#107]
This could be an easier path to working around some failures than going into the console and messing with the exposed services even for Power Users (TM).

[WebExt popup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups)

**Comment by SunriseFox** [comment]
This ext shall work on both chrome and firefox, desktop and mobile... It seems not work quite well on mobile, e.g., a new tab have to be opened... And is it supported by chrome too?  Emm...The key issue is that, should we really need to expose the errors to end users, and which kinds of errors need we do?... a lot to consider before adopting that...

**Comment by Artoria2e5** [comment]
mobile screen is narrow, so i don't really think turning a popup into a new tab is a major usability issue; in fact it probably is the only logical way to translate such a thing into mobile.

**Comment by SunriseFox** [comment]
So... What do we need to put on the popup?

e.g.: 

+ A toggle to switch Maskbook on and off
+ A quick preview to get / set current identity, persona, profile, etc.
+ A inspector / aduitor to overview the current status, such as, whether it is initialized, errors encountered, etc.
+ A quick link to our settings page / dashboard
+ A bottom navigator with several buttons to maskbook.com / github / etc.

@neruthes @Artoria2e5

**Comment by Tedko** [comment]
Personally I think 2/3/4 is great. Don’t need to worry about 1 since we’re
not Adblock and won’t broke UIs. 5 is unnecessary for most user.

**Comment by Artoria2e5** [comment]
We don't have anything on persona yet, so 2 has to wait. 4 can be done with the `browser.runtime.openOptionsPage() /* please catch 4 storybook */` thing, and I guess it will be a button. For 3 there isn't really a thing for "opening inspector on this `window` object" so... are we making our own console buffer there?

```JSX
// plz catch
        <Button variant="contained" onClick={(e) => }>
            OPTIONSSS!!!!!
        </Button>
```

**Comment by Tedko** [comment]
@Artoria2e5  you can do it. Let's see @neruthes 's opinion

**Comment by neruthes** [comment]
> @Artoria2e5 you can do it. Let's see @neruthes 's opinion

Let the current path continue. We will clear things up in #70.

**Comment by Tedko** [comment]
For the latest Chrome Store ver, at least we have the pop up. : ) What's the next step and how about #70 ?
