### ISSUE TITLE
[Demand] Replace GUN server address

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1077]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

1. New server address `hk.gun.dimension.chat`.
2. Failover to origin server?

CC @yisiliu

**Comment by neruthes** [comment]
BTW Let there be a better title at the top left corner, e.g. machine hostname. 🤔

**Comment by septs** [comment]
Reference:

Does gun have multi-region capabilities?
https://github.com/amark/gun/issues/309

**Comment by yisiliu** [comment]
Since we have multiple gun instances now, we should consider adding multi-region support later.

**Comment by Jack-Works** [comment]
Please clarify, `replace` or `add`?

**Comment by septs** [comment]
add `hk.gun.dimension.chat` to first.

CC @yisiliu
