### ISSUE TITLE
[Demand] Add a twitter link into Say Thanks payload

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1078]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## The Link

@Miaommmisokay

**Comment by Tedko** [comment]
should be a quick update -
