### ISSUE TITLE
[Bug] Not able to decrypt image based payload (url based as well) on twitter

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1081]
# Bug Report

Tested with latest store ver of Chrome and FF. 

Not able to decrypt any twitter image based payload. (fb is ok)

<img width="1516" alt="Screen Shot 2020-05-13 at 03 38 23" src="https://user-images.githubusercontent.com/6687437/81740490-9f4d3600-94cf-11ea-9bda-923f87ed82ea.png">
<img width="1221" alt="Screen Shot 2020-05-13 at 03 38 17" src="https://user-images.githubusercontent.com/6687437/81740493-a07e6300-94cf-11ea-9807-04233127532c.png">
<img width="1351" alt="Screen Shot 2020-05-13 at 03 45 07" src="https://user-images.githubusercontent.com/6687437/81740496-a1af9000-94cf-11ea-83cd-7180d5e8f447.png">
<img width="1351" alt="Screen Shot 2020-05-13 at 03 46 05" src="https://user-images.githubusercontent.com/6687437/81740498-a2e0bd00-94cf-11ea-82a4-dd78ef8b8b19.png">

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
<img width="1221" alt="Screen Shot 2020-05-13 at 04 21 01" src="https://user-images.githubusercontent.com/6687437/81741516-45e60680-94d1-11ea-9eba-b04c45ae0348.png">
https://twitter.com/cdrToday/status/1260303764465971200


Reproduced

**Comment by Tedko** [comment]
> <img alt="Screen Shot 2020-05-13 at 04 21 01" width="1221" src="https://user-images.githubusercontent.com/6687437/81741516-45e60680-94d1-11ea-9eba-b04c45ae0348.png">
> 
> https://twitter.com/cdrToday/status/1260303764465971200
> Reproduced

magicURL based cannot decry as well 
<img width="402" alt="Screen Shot 2020-05-13 at 04 24 09" src="https://user-images.githubusercontent.com/6687437/81741839-bd1b9a80-94d1-11ea-810a-89f47a005d04.png">

https://twitter.com/cdrToday/status/1260303764465971200

**Comment by Tedko** [comment]
not able to decrypt by sender aswell

<img width="625" alt="Screen Shot 2020-05-13 at 04 25 08" src="https://user-images.githubusercontent.com/6687437/81742007-ffdd7280-94d1-11ea-8439-ff3ae549538e.png">

**Comment by guanbinrui** [comment]
The DOM representation of the tweet was changed since the selector fails to parse the name of the post.

**Comment by Jack-Works** [comment]
It's likely the first time we met the "selector outdated" case. Maybe we should discuss about it?

**Comment by guanbinrui** [comment]
Here is another example on Facebook which I fixed a few days ago. 

https://github.com/DimensionDev/Maskbook/pull/1062/files#diff-35bdf4ef47bc139fa1701c0c1523a0f5R117
