### ISSUE TITLE
[Demand] Apply better UUID to the text part of Image-Based Payload feature

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1084]
## Metadata

Field | Value
--- | ---
Previous Stage | #472
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Purposes

- Counter anti-spam calculations.
- Allow users to satisfy account security questions.

## Content

Let there be a timestamp at the beginning or ending of the text.

Precision level: second.

## Notes

- None.

**Comment by Tedko** [comment]
No need for time stamp. Just use random 0width string combination

**Comment by Tedko** [comment]
For account security question it’s tricky... time stamp is not helpful as well ummm

**Comment by Tedko** [comment]
in order to achieve 
- Allow users to satisfy account security questions.

It's better to be human readable leading char. and the design can solve the problem of  `satisfy account security questions with text payload`.

Any better idea than time stamp?

**Comment by Jack-Works** [comment]
IMO let the user write something unencrypted is enough.

**Comment by Tedko** [comment]
yeah good idea

**Comment by neruthes** [comment]
Just like we made prefix randomization in #198 and #373, we can have Shell randomization for Image-Based Payload as well.
