### ISSUE TITLE
[Bug] Not able to compose encrypted tweet on firefox mobile

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1087]
# Bug Report
Not able to compose encrypted tweet on firefox mobile; Maskbok Version 1.10.16
### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by guanbinrui** [comment]
Duplicate with #867, which has been fixed in the master branch but not released yet.

<img width="381" alt="Screen Shot 2020-05-14 at 11 10 55 AM" src="https://user-images.githubusercontent.com/52657989/81888281-9ba2d780-95d3-11ea-8868-4bb46bab9e85.png">

**Comment by Tedko** [comment]
Ok let’s release this in the next ver as well?

**Comment by neruthes** [comment]
M4 will be published 28 hours later.
