### ISSUE TITLE
Bug: yarn add/remove always disables @holoflows/kit

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#109]
After doing

```bash
// add already resolved by task('install/holoflows')
yarn add anything-here
// or
yarn remove anything-here
```

I get:

```
Failed to compile.

./src/extension/background-script/WelcomeService.ts
Module not found: Can't resolve '@holoflows/kit' in 'src\extension\background-script'
```

**Comment by Misaka-0x447f** [comment]
Tested. This problem only exist during installing run. Although it shows 'task complete' please do not stop the process. Will working on task complete printed before actually complete.

**Comment by Misaka-0x447f** [comment]
OK the author of this issue means, ```yarn install``` removed compiled holoflow files, but this is intended. yarn install will refresh the whole ```node_modules``` and make sure that everything is exactly match what comes from the package manager, not only install everything missing. You may understand ```yarn install``` as ```yarn synchronize```.

**Comment by Misaka-0x447f** [comment]
So the author told me that ```yarn just install/holoflows``` fixes this problem, this is also intended.

**Comment by Misaka-0x447f** [comment]
ok this is not what i thought, ```yarn remove``` may not calling ```yarn install```

**Comment by Misaka-0x447f** [comment]
https://github.com/DimensionDev/holoflows-kit/pull/13
