### ISSUE TITLE
[Demand] Set an input char upper limit within Maskbook compose window

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1094]
## Metadata

Even if it is possible we do not want user to input for example 2000-3000 words in an encrypted tweet/fb post. Let's set a limit.

This might be platform specific (means fb/twitter may have different size limit)

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
The actual limit may be subject to the physical limitations which are imposed by [Shell formats](https://confluence.dimension.chat/x/qIAf).

At this moment, we will find the lowest cap among all Shell formats.

**Comment by guanbinrui** [comment]
+ The Red Packet Image: (floor(1200 * 680 / 64 * 3 / 8) = 4781 bytes)
+ The Godness Image: (floor(1024 * 1240 / 64 * 3 / 8)= 7440 bytes)

**Comment by guanbinrui** [comment]
> The actual limit may be subject to the physical limitations which are imposed by [Shell formats](https://confluence.dimension.chat/x/qIAf).
> 
> At this moment, we will find the lowest cap among all Shell formats. Maybe Image-Based Payload has the lowest cap. cc @guanbinrui

+ The Red Packet Image: `floor(1200 * 680 / 64 * 3 / 8) = 4781 bytes`
+ The Godness Image: `floor(1024 * 1240 / 64 * 3 / 8)= 7440 bytes`

**Comment by Tedko** [comment]
The size of goodness image will update to be the same of the red packet one
for better UX soon. Let’s use the red packet one for the limit

**Comment by neruthes** [comment]
4781 * 50% (utilization rate, pessimistic assumption) ÷ 3 (UTF-8 3-byte characters) = 796.8

We can safely specify a number lower than 796. I prefer 560.

**Comment by septs** [comment]
I think a CRC32 checksum is needed.

**Comment by neruthes** [comment]
> I think a CRC32 checksum is needed.

Leave this for payload format discussions?

**Comment by septs** [comment]
bingo

**Comment by Jack-Works** [comment]
how much should it be ?

**Comment by neruthes** [comment]
> how much should it be ?

560 characters instead of 280 since threading is really popular nowadays.

(Will consider raising to 768 in future if the demand from the users is strong.)
