### ISSUE TITLE
[Bug] Red packet sender should able to see details about red packet instead of `?/?`

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1096]
# Bug Report
![Screen Shot 2020-05-16 at 02 49 31](https://user-images.githubusercontent.com/6687437/82092451-e8012b00-972b-11ea-8411-a53d0babf809.png)
Now during the pending sender cannot see details about the red packet
### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
Also will show up strange error some time.

![Screen Shot 2020-05-16 at 04 17 06](https://user-images.githubusercontent.com/6687437/82092700-5b0aa180-972c-11ea-8af7-92a788b7613f.png)

**Comment by neruthes** [comment]
Should be a bug
