### ISSUE TITLE
[Bug] Misleading UX (wording) when sending red packet

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1097]
# Bug Report

![Screen Shot 2020-05-16 at 21 47 39](https://user-images.githubusercontent.com/6687437/82121513-3cee8100-97c0-11ea-9bd2-7c6921346d24.png)

`A Red Packet with $7 OKB etc` will confuse the user since it might refer to the USD value of OKB or 7 OKB (erc20 token).

Suggestion `A Red Packet with 7 $OKB etc` *(which is widely used on twitter) or maybe skip the `$`

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Yes this text should be updated.
