### ISSUE TITLE
[Bug] After import db (with connected fb/twitter profile) Maskbook will not ask access to the sites (fb/twitter)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1098]
# Bug Report

After restore/import db successfully (with connected fb/twitter profile) Maskbook will not ask access on the sites (fb/twitter). However the browser/user have not granted access to these sites by that time, so user cannot user maskbook properly .

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
So in this case, Maskbook should ask these permission after the import of db

**Comment by guanbinrui** [comment]
Do import it again works?

**Comment by Tedko** [comment]
> Do import it again works? Maskbook denies importing DB if permissions were rejected. Select the backup file and import it again will show the asking dialog again.

No i mean the permission to access fb.com /twitter.com ; not permission to import file

**Comment by neruthes** [comment]
Strange bug indeed.

**Comment by Tedko** [comment]
Is this fixed? Or can anyone reproduce this issue?

**Comment by neruthes** [comment]
Cannot reproduce.
