### ISSUE TITLE
Feature: Backup alert

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#11]
![Backup Alert](https://user-images.githubusercontent.com/2139261/56014917-b0cd7880-5ce6-11e9-87d3-6f5e4e2153aa.png)

Such a backup alert shall appear if:

- Last saved backup was 168 hours ago; or
- No backup saved ever

... and:

- The last time the user manually clicked "close" was within the last 168 hours.

The alert text shall differ according to the case.

- `Last backup was 7 days ago.`
- `Create your first backup!`

Notice:

- There can be saved backup (saved) and unsaved backup (user clicked "cancel").
- Regardless of manual closings, the time span for "X days" always starts from last saved backup.

**Comment by yisiliu** [comment]
We should also support Mnemonic Code for easy key restore, as is done in [https://github.com/DimensionDev/PriceDoge/blob/master/extension/src/utils/keyStore.ts](url)

**Comment by neruthes** [comment]
> We should also support Mnemonic Code for easy key restore, as is done in [https://github.com/DimensionDev/PriceDoge/blob/master/extension/src/utils/keyStore.ts](url)

Since the thing you wrote thereof may be classified as un proposed feature, I recommend opening un dedicated issue for it.

**Comment by neruthes** [comment]
Changes of circumstances have made this feature irrelevant or infeasible.
