### ISSUE TITLE
[Bug] Long waiting time for Maskbook compose button to show up on facebook

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1100]
# Bug Report

![IMG_69971](https://user-images.githubusercontent.com/6687437/82156460-a39d9880-98ad-11ea-8d73-7395fd17f12e.gif)

Can we reduce the responding time? Is this a problem of selector or?

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by guanbinrui** [comment]
I think the time required by the Facebook compose box to be fully loaded, which also a stable DOM structure is required by our mount point selector.

**Comment by Tedko** [comment]
@guanbinrui any idea to shorten the time?

**Comment by Jack-Works** [comment]
maybe we can find a mount point that appears early

**Comment by Tedko** [comment]
ggood

**Comment by Tedko** [comment]
> maybe we can find a mount point that appears early

Use the `post button` as mount point maybe?

**Comment by Tedko** [comment]
any update?

**Comment by Tedko** [comment]
this is only related w/ old fb ui. fixed now
