### ISSUE TITLE
[Task] Open Source Promotion Plan - Summer 2020 Task 2

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1107]
## Introduction

In Maskbook, we have an `Image Mode`, a.k.a steganography mode, in our experimental setting that enables users to post their ciphertext in an image instead of in a base64 encoded form. We are now using one dimensional FFT(fast Fourier transform) to encode the information in the images (https://github.com/DimensionDev/Stego-JS). The largest challenge in our scenario is **anti-compression**. Most platforms would compress the images in a lossy way so a traditional steganography algorithm like LSB encoding would fail. 1DFFT works well to tolerate the compressions but 2DFFT or DCT(Discrete Cosine Transform) works fairly poorly on this task. The only problem with 1DFFT is that it'll add a lot of visual "dots" on the image, as is shown in the below.
![image](https://user-images.githubusercontent.com/3343358/82185006-201a9080-991b-11ea-8d0e-ab61b36ef1b9.png)
These dots make Maskbook images visually detectable, which might cause some trouble. We are limiting the images only because our algorithm only works well on some types of images, for the sake of anti-compression.

## What We Are Looking For

In the short run, we are looking for **a steady (lossy compression tolerant) and less visually detectable solution** in Maskbook. Users may not be able to choose their own image as the base image to be encoded. 

In the long run, we are looking for an algorithm or a scheme that is **1. both visually and algorithmically hard to detect and 2. accepting all image types**.

For more info about Maskbook, refer to https://maskbook.com and this repo. Or for a broader overview of our company, please refer to https://www.odaily.com/post/5143749.

**Comment by Tedko** [comment]
is this one finished? @yisiliu 

but i guess we can close this issue for now

**Comment by septs** [comment]
@Tedko Upstream has been completed, but i need redesign working in WebWorker

see https://github.com/DimensionDev/Stego-JS/pull/12
see https://github.com/DimensionDev/Stego-JS/pull/5#issuecomment-720313632

**Comment by Tedko** [comment]
ok. Keep going

**Comment by septs** [comment]
Stego-JS Web Worker-ization need wait for #1905 done.

**Comment by yisiliu** [comment]
updates required on #2139 @septs
