### ISSUE TITLE
[Demand] Update image of image-based payload

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1115]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=985%3A0
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by Tedko** [comment]
any update on this one?
