### ISSUE TITLE
[Demand] Better on-boarding/feedback experience

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1118]
## Metadata

Here're several examples:
1. 
![Screen Shot 2020-05-19 at 14 26 58](https://user-images.githubusercontent.com/6687437/82297646-8966d600-99e5-11ea-954a-de43b415ae8e.png)
After finished installation of Dapper Wallet (https://chrome.google.com/webstore/detail/dapper/pghmmgdinmfblodenlenkcnmndlnffeo?hl=zh-CN ) , above page will be open ( https://meetdapper.com/welcome/ )

Similar example: Tampermonkey

2. 

![Screen Shot 2020-04-29 at 01 18 34](https://user-images.githubusercontent.com/6687437/82297834-cdf27180-99e5-11ea-8e36-96b23e4a1fa7.png)

After finished uninstallation of Neflix Party, above page will be opened. 
We can send parameter from the user to the specific website and conduct an optional user research *(can close the tab anyway) and Link to FAQ. Also add a button of `Reinstall the App` like Neflix Party  . 

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by Tedko** [comment]
A very cool gif from DApper Wallet
![screen-1fc62d2fe4f2c57d3a0c0a8049984472](https://user-images.githubusercontent.com/6687437/82299356-fda27900-99e7-11ea-9665-0cc33516ad7a.gif)

**Comment by Tedko** [comment]
What we need:

- A cool gif/video(?) 
- A welcome page for on-boarding 
- A user survey (and a page for sending optional data point) when Maskbook is uninstalled

**Comment by neruthes** [comment]
Nice discovery.

Auto-opening a webpage should be how Dashboard automatically opens upon installation in the current implementation.

Onboarding is exactly what the "Initialization" part of Dashboard is.

Although the normal usage of Maskbook usually does not require any interaction with the icon in the extensions bar, it can be good to have a more explicit notice to inform the user how to enter Maskbook Dashboard.

**Comment by Tedko** [comment]
> Nice discovery.
> 
> Auto-opening a webpage should be how Dashboard automatically opens upon installation in the current implementation.
> 
> Onboarding is exactly what the "Initialization" part of Dashboard is.
> 
> Although the normal usage of Maskbook usually does not require any interaction with the icon in the extensions bar, it can be good to have a more explicit notice to inform the user how to enter Maskbook Dashboard.

For now the `A user survey (and a page for sending optional data point) when Maskbook is uninstalled` will be very helpful to grow the user base etc. Let's prioritize this one
