### ISSUE TITLE
[Demand] "Post first encrypted post" workflow in Initialization

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1124]
## Metadata

Field | Value
--- | ---
Previous Stage | #407, #600, #409, #1026 
Figma Link | https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=1105%3A0
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

One more series of steps to be appended for Initialization.

## Documentation

https://confluence.dimension.chat/x/PIAf

Section "Workflow 3: Create the First Encrypted Post".

## Notes

- None.

**Comment by neruthes** [comment]
This should be delivered together with #952.

**Comment by Tedko** [comment]
Was discussing about name service related solutions
