### ISSUE TITLE
[Demand] Add a request permission button in the popup page if Maskbook has no access to the current opening domain

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1125]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
Could you offer more background on this matter?

**Comment by Tedko** [comment]
> Could you offer more background on this matter?

#1098

**Comment by neruthes** [comment]
> > Could you offer more background on this matter?
> 
> #1098

As noted in the [documentation](https://confluence.dimension.chat/x/PIAf):

- Maskbook awaits operation.
- Alice drops a file here or selects a file through file selection dialogue.
- If (environment is Browser Extension):
    - Browser asks Alice to allow Maskbook access webpages under the domain names which appear in the backup.
    - If (Alice allows):
        - Move forward.
    - Else:
        - Goto "Maskbook awaits operation".
- Maskbook imports the backup.
