### ISSUE TITLE
[Crash] TypeError: meta.keys is not a function

### ISSUE THREAD

**Issue by UlyC** [DimensionDev/Maskbook#11373]
When I try to CLAIM the  NFT Lucky Drop, I get this error:

> meta.keys is not a function

Error stack:

<pre>useDisabledPluginSuggestionFromMeta@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/chunk.6954.js:2097:17
DecryptedUI_PluginRendererWithSuggestion@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/chunk.6954.js:2210:50
Xh@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:376:137
Wk@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:499:337
Vk@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:489:391
Uk@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:489:322
Jk@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:489:180
Ok@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:480:88
Hk@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/npm.react-dom.js:477:429
J@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/284.js:3069:204
R@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/js/284.js:3070:128
@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/polyfill/ecmascript.js:3283:12
run@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/polyfill/ecmascript.js:3257:5
listener@moz-extension://928f1f89-bf84-4251-9f75-4084d815384a/polyfill/ecmascript.js:3268:6
</pre>

## Build info
- Version: 2.11.4
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- BUILD_DATE: 2023-02-08T13:32:25.327Z
- VERSION: v1.29.12-2854-g32b056805

## Git (*):

32b056805 (released)
https://github.com/DimensionDev/Maskbook

**Comment by AinuX** [comment]
The extension version is too low, please upgrade to the latest version and try it on the Chrome browser. Thanks for the feedback.
