### ISSUE TITLE
[Demand] Introduce Base1024Emoji as an optional payload

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1139]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=1192%3A107
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Introduction
- Documentation List

## Part 1: Introduction

We have been developing Base1024Emoji for a long time since #139. It is a good time to introduce it as an optional Limbo payload type for BasicPost.

## Part 2: Documentation List

- "Concept: Post Type" - https://confluence.dimension.chat/x/qIAf
- "Base1024Emoji Encoding Format Specification" - // TODO
- "Post Limbo Payload: Base1024Emoji" - https://confluence.dimension.chat/x/v4Ef

### Overview

- There should be a dropdown list for selecting payload format.

### Figma

https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=1192%3A107

## Notes

- See also #1249.

**Comment by septs** [comment]
```
[emoji-block] user inserted text [emoji-block]
```

How to recognize user splitted text in this case

1. Add checksum to emoji byte stream?

**Comment by neruthes** [comment]
> ```
> [emoji-block] user inserted text [emoji-block]
> ```
> 
> 
> How to recognize user splitted text in this case
> 
> 
> 
> 1. Add checksum to emoji byte stream?

Basic ideas:

- An emoji stream starts as arbitrary emoji and ends when a non-emoji character occurs.
- For each emoji stream, it should be checksum-protected. So that user-inserted emoji characters will not mess up with Maskbook emoji streams.
- We can consider supporting splitting — space, CR, and LF are not considered stream-terminating characters. Therefore marginal linebreaks can be inserted without impairing stream integrity.

**Comment by clearloop** [comment]
> If inserted text is other emoji sequence

The encoded base1024? I have a stupid idea...try inputing all of them into twitter and facebook, and find the answer.

**Comment by Tedko** [comment]
> > If inserted text is other emoji sequence
> 
> The encoded base1024? I have a stupid idea...try inputing all of them into twitter and facebook, and find the answer.

emoji payload will not work in twitter due to the input length limit

**Comment by Tedko** [comment]
any update so far @septs

**Comment by septs** [comment]
- [x] @clearloop some known issues have been cleared
- [ ] not started any ui design and logic design

CC @neruthes @OiCkilL

**Comment by Tedko** [comment]
@septs so @clearloop part is done already?

**Comment by septs** [comment]
Base1024Emoji for the end-user product name?
- Emoji encoding?

**Comment by Tedko** [comment]
Use ‘Emoji Payload’ (follow the image payload) etc for the end user product
name.
If this working and testing well we will replace the default encryption
method on fb.

**Comment by neruthes** [comment]
https://github.com/DimensionDev/Maskbook/issues/1249

**Comment by Tedko** [comment]
I think @OiCkilL already start some UX design based on #1249 and new ux/dashboard

**Comment by Tedko** [comment]
any update on this? @OiCkilL @septs

**Comment by septs** [comment]
> any update on this? @OiCkilL @septs

I reorganized https://github.com/DimensionDev/coda, I think it can be published to npm registry.

**Comment by neruthes** [comment]
The only unsatisfied dependency is the documentation of "Base1024Emoji Encoding Format Specification", before we remove "Draft" mark on this issue.

**Comment by Tedko** [comment]
> https://github.com/DimensionDev/coda

@septs ok lets do it. 
Also for UX i believe @OiCkilL already have it done

**Comment by septs** [comment]
Maybe need "Payload Version Control".
