### ISSUE TITLE
[Demand] Post Limbo payload "MagicURL" & Post Shell payload "BasicShell" revamp

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1140]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Introduction
- Post Limbo Payload "MagicURL" Update
- Post Shell Payload "BasicPost" Update

## Part 1: Introduction

Principles:

- Unify multiple links to one.
- Remove Prefix Randomization.

Documentations:

- https://confluence.dimension.chat/x/qIAf

### Overview

Previous version: #198. 

New:

```
https://maskbook.com/?PostData_v1=${postDataBinary_Base64url}
```

## Part 3: Post Shell Payload "BasicPost" Update

Previous version: #1067. 

New text:

```
This tweet is encrypted with #Maskbook (@realMaskbook). 📪🔑

Install ${magicUrl} to decrypt it.
```

## Notes

- See Also: https://github.com/DimensionDev/Maskbook-Talks/issues/41

**Comment by neruthes** [comment]
## Idea

If any SNS blocks hostname "maskbook.com", we can replace it with `https://bit.ly/2X3nGZi?magicUrl_v1p1=${postDataBinary_Base64url}`.
\

**Comment by Tedko** [comment]
> ## Idea
> If any SNS blocks hostname "maskbook.com", we can replace it with `https://bit.ly/2X3nGZi?magicUrl_v1p1=${postDataBinary_Base64url}`.

Not very likely on twitter but 100% sure on fb.
Since magic url is solution for twitter/Mastodon it should be fine

**Comment by Tedko** [comment]
is this part done already @guanbinrui ?

**Comment by Jack-Works** [comment]
> ## Idea
> 
> If any SNS blocks hostname "maskbook.com", we can replace it with `https://bit.ly/2X3nGZi?PostData_v1=${postDataBinary_Base64url}`.
> 

Then they can block this https://bit.ly/2X3nGZi
