### ISSUE TITLE
[Bug] Should not let  user send out empty fb encrypted comment

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1142]
# Bug Report

https://dimension.chat/group/maskbook?msg=hS7SKDHL2BYz9dCpJ

Try `return/enter` in the encrypted comment box w/o write anything in it.

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

Should not let  user send out empty fb encrypted comment

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Expected behavior: `If (input.value == "") { /* Do nothing */} else { /* Encrypt the comment */}`

**Comment by Tedko** [comment]
let's fix this next?
