### ISSUE TITLE
[Bug] Electron installation in China

### ISSUE THREAD

**Issue by liwenchi123000** [DimensionDev/Maskbook#1146]
# Bug Report

### System

- OS: windows
- OS Version: latest version

## Bug Info

I am in china. When I use "yarn install" command to try to preview project in development env. It shows following error infomation:
 
> error F:\project\Maskbook\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: F:\project\Maskbook\node_modules\electron
Output:
Downloading tmp-5208-0-electron-v5.0.10-win32-x64.zip
Error: getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com
F:\project\Maskbook\node_modules\electron\install.js:49
  throw err
  ^
Error: getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: -4058,
  code: 'ENOENT',

**i think it may because i can't access  "github-production-release-asset-2e65be.s3.amazonaws.com" domain.**

for this problem, i tried some ways to slove it, but all failed . for example:
- use vpn
- modify hosts file

**Comment by guanbinrui** [comment]
@liwenchi123000 Have you ever been tried this one https://www.electronjs.org/docs/tutorial/installation.

**Comment by Jack-Works** [comment]
Hi, if you won't need to run tests on your machine, you can install by the following way:

```
yarn --ignore-scripts
yarn run install
```

**Comment by Tedko** [comment]
Will close this for now since it's not within the scope of Maskbook development. But you can keep discussion freely in this thread.

**Comment by neruthes** [comment]
See also: https://github.com/DimensionDev/Maskbook-Talks
