### ISSUE TITLE
[Bounty]

### ISSUE THREAD

**Issue by Transport4Mirabel** [DimensionDev/Maskbook#11485]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [x] Security/Cryptography Feature
  - [ ] Documentation
  - [x] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] *PLACEHOLDER*
- Bounty Size
  - [x] *PLACEHOLDER*

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

## Part 3: Contact and Support

**Comment by Jack-Works** [comment]
cannot understand
