### ISSUE TITLE
[Bug] Auto paste (text and img based payload) on Twitter mobile failed

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1152]
# Bug Report

https://imgur.com/mGLTMTT

- After testing on Gecko on Android, #869  is working well on Twitter mobile, the icon should up and can be clicked & functional well (should merge this into `released` etc with double check)  
- However, Auto paste (text and img based payload) on Twitter mobile failed; might be due to some selector mismatch on mobile twitter 

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by jk234ert** [comment]
Related to #1208

**Comment by Jack-Works** [comment]
iirc #1351 has been merged into released branch and back to the master branch
