### ISSUE TITLE
[Crash] SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#11533]
In PC’s mobile mode, timeline feed has a lucky drop, then Mask reports an error.

> Invalid regular expression: invalid group specifier name

Error stack:

<pre>RegExp@[native code]
N@https://firefly-staging.mask.social/_next/static/chunks/7348-2948ca562195ef0f.js:1:27676
@https://firefly-staging.mask.social/_next/static/chunks/7590.3ecbc385dcc39679.js:1:31909
r5@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:46738
@https://firefly-staging.mask.social/_next/static/chunks/7590.3ecbc385dcc39679.js:1:31792
rk@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:40371
lI@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:59179
o4@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:94634
@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:94456
o3@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:94461
oQ@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:91950
n2@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:37384
n4@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:38119
@https://firefly-staging.mask.social/_next/static/chunks/cdd2ec7a-428b042eefed37a8.js:1:39152</pre>

## Build info
- Version: unknown
- NODE_ENV: production
- userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1
- build: stable
- BUILD_DATE: unknown

**Comment by Jack-Works** [comment]
hmm cc @UncleBill

https://github.com/DimensionDev/Maskbook/blame/7c46f08a04fb3b594498f85fe8b65002a9b2ac96/packages/web3-shared/base/src/helpers/number.ts#L124
