### ISSUE TITLE
[Demand] Maskbook iOS Cryptocurrency Features

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1179]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

Make #634 available on mobile again.

**Comment by Tedko** [comment]
I need this feature go live by Wed this week on Testflight etc on iOS.

**Comment by Tedko** [comment]
any updates

**Comment by neruthes** [comment]
Should have been closed by #1192.
