### ISSUE TITLE
[Demand] Watcher for breaking  DOM change

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1180]
## Metadata

As we encounter we need a Watcher for breaking  DOM change for twitter/fb. 
Any idea are welcomed. Priority of this demand is high.

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by jk234ert** [comment]
Periodically(1 time/day) performing our E2E test as a tradeoff solution for now.

**Comment by neruthes** [comment]
## Discussion Summary

Now we have 2 proposed solutions:

- A dedicated crawling service periodically performs selector operations on specific webpages and compare the innerText with the predefined expectation.
- Make this part of the E2E testing and catch error logs when unexpected innerText vaules appear.

The implementation requires the final decision between the 2 options. Let there be in-depth comparison reports.

cc @septs @yisiliu @guanbinrui @jk234ert @Jack-Works

**Comment by Tedko** [comment]
> ## Discussion Summary
> Now we have 2 proposed solutions:
> 
> * A dedicated crawling service periodically performs selector operations on specific webpages and compare the innerText with the predefined expectation.
> * Make this part of the E2E testing and catch error logs when unexpected innerText vaules appear.
> 
> The implementation requires the final decision between the 2 options. Let there be in-depth comparison reports.
> 
> cc @septs @yisiliu @guanbinrui @jk234ert @Jack-Works

which is easier to implement and to maintain ?:)

**Comment by Tedko** [comment]
@jk234ert @septs we need this asap for any breaking DOM. otherwise the outcome will be disaster

**Comment by Jack-Works** [comment]
or we need to develop #1552

**Comment by UncleBill** [comment]
I am working on this.

**Comment by UncleBill** [comment]
I just created an repo here https://github.com/UncleBill/sns-watchers. Let's see if it works.
