### ISSUE TITLE
[Bug] Should not pop up `auto-paste` alert for img-payload

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1181]
# Bug Report

![IMG_1485](https://user-images.githubusercontent.com/6687437/84029612-420cad80-a9c5-11ea-80aa-3175a7c6c265.png)

There's no need to pop up `auto-paste` alert for img-payload. User have no way to manually copy-paste it. Just leave a `auto-paste img payload func down` alert is good enough.

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/commit/2008f5517bd715e7e1aa793892ea0c6c38871430

IMO this feature is already disabled on the mobile 🤔

**Comment by neruthes** [comment]
Such strange 🤔

**Comment by Tedko** [comment]
Not disabled on mobile with yesterday’s latest update on google play. Will
test again

**Comment by Tedko** [comment]
@Jack-Works i mean this fallback logic should be removed (not only on mobile)

**Comment by Jack-Works** [comment]
Sound reasonable
