### ISSUE TITLE
[Bug] Not able to recognise Gitcoin link on Twitter for Gitcoin Plugin

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1195]
# Bug Report
<img width="665" alt="Screen Shot 2020-06-09 at 22 53 35" src="https://user-images.githubusercontent.com/6687437/84165012-be76bd80-aaa5-11ea-9241-cca51215cf03.png">
<img width="1370" alt="Screen Shot 2020-06-09 at 22 53 27" src="https://user-images.githubusercontent.com/6687437/84165025-c2a2db00-aaa5-11ea-994a-a0ff8305bfd3.png">

When posting:
` abc gitcoin.co/abc ` -- twitter will render the link differently, which results in Not able to recognise Gitcoin link on Twitter for Gitcoin Plugin

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
also this is not intended to support fb now right?

**Comment by Jack-Works** [comment]
The link becomes "https://t.co/seaSWzt0Ad?amp=1". I think we need a way to restore the original from it.

**Comment by Jack-Works** [comment]
```js

fetch('https://t.co/seaSWzt0Ad?amp=1', { redirect: 'error' }).then(async r => console.log(await r.text(), ...r.headers.entries()))
.catch(reason => {
  console.error(reason);
});

```

> <head><noscript><META http-equiv="refresh" content="0;URL=https://gitcoin.co/grants/159/maskbook-surrender-no-privacy-to-youknowwho-eg-fac?tab=description"></noscript><title>https://gitcoin.co/grants/159/maskbook-surrender-no-privacy-to-youknowwho-eg-fac?tab=description</title></head><script>window.opener = null; location.replace("https:\/\/gitcoin.co\/grants\/159\/maskbook-surrender-no-privacy-to-youknowwho-eg-fac?tab=description")</script> 

LGTM

**Comment by Jack-Works** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/1200
