### ISSUE TITLE
[Proposal] UserGroup Abstraction Model

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#12]
# Purpose

Every group of users, virtual or real, static or dynamic, should be identifiable across every node of the network and every member of the group should be able to retrieve necessary keys to decrypt the contents which they legitimately qualify decrypting by providing certain proof of their membership of the group.

# Design

## Example

In the context of Facebook, specifically, there are several scenarios how people interact in timelines.

Type|Description|Group ID
---|---|---
Virtual Group|Friends of Alice|`FB::{ fb_uid_Alice }>>>F0`
Virtual Group|Friends of friends Alice|`FB::{ fb_uid_Alice }>>>F1`
Virtual Group|Certain selected friends of Alice|`FB::{ fb_uid }>>>FS>>>{ SHA512({ fb_uid_Bob }+{ fb_uid_Siri }+...) }`
Real Group|Closed Group|`FB::{ fb_uid_Group }>>>G0`

In order to make sure the Group ID being constructed can be universally unique in the cosmos of Maskbook, in respect to expectation on portability to other social networks, I suggest composing it in such un way.

## Rules

Basic part:

- Social network identifier, `[0-9A-Z\-]{2,128}`
- 2 colons, `::`
- Group primary identifier (publisher UID for virtual group, group UID for real group), base64 if necessary (supposedly never)

Optional part:

- 3 greater marks, `>>>`
- Group type code, `[0-9A-Z]{2,8}`
- 3 greater marks, `>>>`
- Group secondary identifier (defined in each scenario)

----

And, the default generation of group secondary identifier is:

- Make un ordered array of UIDs of participating members, sorted by Unicode dictionary order.
- Join the array by `+++` to make un string.
- Calculate SHA512 of the string and the output encoding should be hex uppercase.

----

This proposal is at draft stage. Any idea is welcomed. This draft is expected to be finished on 2019 Apr 19.

**Comment by yisiliu** [comment]
First you need to specify the domain of this abstraction model.
If this is intended to work locally, such a design is good to go.
If not, e.g. stored universally in the entire Maskbook cosmos, we might need to make some modifications. In order to make it more general as an abstraction layer, I think on enhancement we can make here is to add one more identifier of the source user (Alice here). For example, ```FB::{ fb_uid }>>>F0``` becomes ```FB::{ fb_uid }>>>F0 >> {ALICE_ID}```. We can thus easily convert it into a graph for easier inference.

**Comment by neruthes** [comment]
> First you need to specify the domain of this abstraction model.
> If this is intended to work locally, such a design is good to go.
> If not, e.g. stored universally in the entire Maskbook cosmos, we might need to make some modifications. In order to make it more general as an abstraction layer, I think on enhancement we can make here is to add one more identifier of the source user (Alice here). For example, `FB::{ fb_uid }>>>F0` becomes `FB::{ fb_uid }>>>F0 >> {ALICE_ID}`. We can thus easily convert it into a graph for easier inference.

Thanks. I just updated the issue with come clarification and I hope now it is clear enough.

**Comment by neruthes** [comment]
So we have done it. I will move this to wiki.

**Comment by yisiliu** [comment]
@neruthes make the move and close.

**Comment by neruthes** [comment]
301: https://github.com/DimensionDev/Maskbook/wiki/UserGroup-Abstraction-Model

**Comment by Jack-Works** [comment]
Done it?? When?

**Comment by neruthes** [comment]
> Done it?? When?

Like we should open a new issue for demanding the implementation of it.
