### ISSUE TITLE
Fail to retrieve public keys from profile bio

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#120]
<img width="221" alt="Screen Shot 2019-08-22 at 00 52 02" src="https://user-images.githubusercontent.com/6687437/63496649-24db1280-c477-11e9-9e08-af33696e9630.png">
<img width="233" alt="Screen Shot 2019-08-22 at 00 51 56" src="https://user-images.githubusercontent.com/6687437/63496653-260c3f80-c477-11e9-86bb-75f6f06d7857.png">

Reported by several users:

- Fail to retrieve public keys from bio (is this related with #74 ?)
- Need refresh after successfully retrieve keys

Potential fix:

- [ ] Add a 'Maskbook public key added to keystore ✔' in the bio as well 
- [x] Decrypt with newly retrieved keys wo refresh (?)

**Comment by Tedko** [comment]
What's the status for this issue? Let's Add a 'Maskbook public key added to keystore ✔' in the bio as well

For `Decrypt with newly retrieved keys wo refresh (?)` -- is that fixed already?

**Comment by SunriseFox** [comment]
same as #327
