### ISSUE TITLE
[Task] Simplify the usage of dialogs (in codebase)?

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1201]

**Comment by neruthes** [comment]
Are there specific examples for the alleged abusing?

**Comment by Jack-Works** [comment]
> Are there specific examples for the alleged abusing?

I mean in the codebase. Not UI/UX related.

**Comment by neruthes** [comment]
Ok

**Comment by Jack-Works** [comment]
possible candidates:

https://github.com/chunkai1312/muibox

https://github.com/mpontus/react-modal-hook

which one is better? (or both?) @septs @guanbinrui

**Comment by septs** [comment]
@Jack-Works `react-modal-hook` > `muibox`

**Comment by Jack-Works** [comment]
Bump
