### ISSUE TITLE
[Bug] Auto paste for twitter doesnt work on Firefox

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1208]

**Comment by Tedko** [comment]
confirmed. not working

**Comment by Tedko** [comment]
Any update for this one?

**Comment by neruthes** [comment]
Any update?

**Comment by Jack-Works** [comment]
I found a way to work around, will investigate later.

**Comment by Tedko** [comment]
> I found a way to work around, will investigate later.

ok

**Comment by Jack-Works** [comment]
Note: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Using_eval_in_content_scripts a Firefox-only feature may help

**Comment by jk234ert** [comment]
The current solution leads to multiple auto pasting of Twitter on Firefox. Waiting to be fixed

**Comment by Tedko** [comment]
Fixed.

But autopaste for image payload on twitter @ FF is still broken
