### ISSUE TITLE
Better hinting color for URLs in Encrypted post 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1210]
# Bug Report

![image](https://user-images.githubusercontent.com/6687437/84528965-37c71800-ad13-11ea-826a-9522b177b664.png)
![image](https://user-images.githubusercontent.com/6687437/84528977-3b5a9f00-ad13-11ea-8170-865a8380e52b.png)

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Yes the font-size can be slightly larger when the text is short enough. It is a good practice employed by Facebook. And each SNS may have its predefined colors for links. We may want to have a site-specific strategy for managing these behaviors.

**Comment by Tedko** [comment]
note that the current link hinting dont contain underscore

**Comment by Jack-Works** [comment]
> when the text is short enough

How many chars are considered as "short"?

**Comment by neruthes** [comment]
> > when the text is short enough
> 
> How many chars are considered as "short"?

0 ≤ x ≤ 85

**Comment by Tedko** [comment]
@zhouhanseng can you fix this? should be a quick fix
