### ISSUE TITLE
[Bug] When both `Follower` & `Following` of Persona is selected, `Friends` should be auto selected 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1216]
# Bug Report

![image](https://user-images.githubusercontent.com/6687437/84587878-95fc1400-ae55-11ea-9367-0a16c771d2dd.png)

 When both `Follower` & `Following` of Persona (on Twitter) is selected, `Friends` should be auto selected (since it's included). This is easier to understand. Feedbacks are welcomed.

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Set Theory is tricky. We will consider this for some long time.

**Comment by neruthes** [comment]
Currently, the upcoming revamp will make recipient options single-choice. If we do not migrate back to the multi-choice version, this problem will automatically disappear.

**Comment by Tedko** [comment]
good

**Comment by Tedko** [comment]
But if it’s single-choice it’s against several existing product design of
main stream products. Will make user more confusing

**Comment by neruthes** [comment]
I share the doubt, too. This can introduce another confusion when removing one confusion. Probably @OiCkilL may have opinions to discuss on this matter.

**Comment by Jack-Works** [comment]
these two options has been hided
