### ISSUE TITLE
[Bug] Gitcoin donation bugs

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1248]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

+ approve estimate error (cannot do donate with USDT )
+ lower nonce error

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
@owocki not sure if this is a bug of gitcoin?

**Comment by guanbinrui** [comment]
> gitcoin

These bugs all come from the Maskbook code and reasons were found will be fixing in the next release.

**Comment by guanbinrui** [comment]
> @owocki not sure if this is a bug of gitcoin?

These bugs all come from the Maskbook code and will be fixing in the next release.

**Comment by Tedko** [comment]
> > @owocki not sure if this is a bug of gitcoin?
> 
> These bugs all come from the Maskbook code and will be fixing in the next release.

ok!

**Comment by Tedko** [comment]
Tested https://app.circleci.com/pipelines/github/DimensionDev/Maskbook/4519/workflows/efed6bf8-0236-4381-a6f9-9a678c55f351/jobs/14614/artifacts -- fixed already
