### ISSUE TITLE
[Demand] Payload format naming revamp for human-friendly reading

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1249]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

On the UI display level, we will rename the payload formats according to this conversion table:

Terminology | Name (en-US) | Name (zh-Hant)
--- | --- | ---
Limbo Payload Type | Encoding Format | 編碼方案
Base64 | Alphanumerical | 字母與數字
Base1024Emoji | Emojii | 繪文字
MagicURL | Magic Link | 魔術鏈接
Image-Based Payload | Magic Image | 魔術圖案

### Before

- Payload: Base1024Emoji
- Payload: Image-Based Payload

### After

- Encoding Format: Emoji
- Encoding Format: Magic Image
- 編碼方案: 繪文字
- 編碼方案: 魔術鏈接

## Notes

- None.

**Comment by Tedko** [comment]
繪文字 and 奇妙 is 🆒

**Comment by neruthes** [comment]
Considering the most literal expressing "魔術". Discussions for translations are welcomed.

**Comment by Tedko** [comment]
奇妙 is better imo

**Comment by Tedko** [comment]
編碼方案 — is 加密方案 better？

**Comment by neruthes** [comment]
> 
> 
> 編碼方案 — is 加密方案 better？

This will mess up with encryption methods. But this way of thinking can be continued. "密文样式" can be a good choice.
