### ISSUE TITLE
[Task] Bug issue template revamp

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1251]
## Metadata

Field | Value
--- | ---
Parent Task/Demand | N/A
Expected Delivery Date | 2020-W??-5

## Content

The issue template for "Bug" has been there for some months and the utilization of the predefined fields remains low. It appears that the template needs a revamp recently.

Here we will discuss what a better template should look like and we will have a pull request after reaching consensus.

Community opinions are also welcomed.

**Comment by Tedko** [comment]
The currently template for Twidere is not bad
