### ISSUE TITLE
[Demand] Error Handling for Importing Wallet

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1252]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

We are going to have a comprehensive error handling strategy when importing wallets. Many of these designs can be reused in Persona importing, while importing Persona is considered less often.

### List of Validations

- Payload Format
- Private Key Curve Point
- Payload Content Integrity

### Payload Format Validation

The payload format should conform to the definition of relative Ethereum standards. If not, the user shall see an error message telling "This is not a keystore file".

### Private Key Curve Point Validation

The curve point should be in the valid range. Each curve has its own private key valid range. SECP256K1, the curve selected by Ethereum, has a smaller valid range than Curve25519. We will need to validate the curve point.

If the curve point is not in the private key valid range of SECP256K1, the user shall see an error message telling "Invalid private key".

### Payload Content Integrity

It is possible that certain field is incorrect in the keystore file. Maskbook shall see whether are these fields conform to each other. For example, if the private key can not produce the indicated public key, at least one between the private key and the public key must be incorrect.

If content integrity fails, the user shall see an error message telling "Input is modified".

### List of Validations

- Payload format
- Private Key Curve Point
- Checksum (?)

### Payload format

The input shall be exactly 12 words (trimmed; case-insensitive; duplicate emptyspaces should be considered 1 emptyspace). The 12 words must appear in the predefined dictionary of 2048 words. 

If words count is not 12 or there is any unaccapted character (e.g. `$`), the user shall see an error message telling "There should be 12 words".

If any invalid word is found, the user shall see an error message telling "Invalid words found: ${ invalidWords.join(" ") }".

### Private Key Curve Point

Same as above.

### Checksum (?)

It is known that 12 words (2048 choices) produce 132 bits and the last 4 bits are used for checksum.

This checksum should be calculated when importing. If the indicated checksum does not match the previous 128 bits, the user shall see an error message telling "Some words are incorrect".

## Notes

- None.

**Comment by Tedko** [comment]
did we finish this?
