### ISSUE TITLE
[Bug] Incomplete removal of the "Found in Maskbook database" banner in twitter

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1255]
# Bug Report

### Maskbook

- Maskbook Version: 1.11.*

### Expected Behavior
This banner should have been completely removed.

### Actual Behavior

This banner sometimes appears under the profile header area of Twitter.

### How To Reproduce

Unknown

**Comment by Jack-Works** [comment]
> This banner should have been completely removed.

When?

**Comment by Tedko** [comment]
> > This banner should have been completely removed.
> 
> When?

Just tested on chrome v 1.11.3 seems like this is fixed already?

**Comment by Tedko** [comment]
not fixed 
<img width="1464" alt="Screen Shot 2020-06-19 at 02 31 15" src="https://user-images.githubusercontent.com/6687437/85058660-02b83b00-b1d5-11ea-935a-c0ffbdd1bdcc.png">

cc @guanbinrui

**Comment by Jack-Works** [comment]
Let me do it
