### ISSUE TITLE
[Demand] Remove username consistency requirement for users

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1258]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

It is previously implemented that the current username of the publisher is involved in determining the PostKey during decryption. This would require users that they must never change their username, or their previous posts will be doomed.

We will need to change this behavior.

## Source Verification Notice

When composing a Post, the username of the currently using Profile shall be added to the Post.

When viewing a Post, the username should match the indicated username. If not matching, Maskbook adds a small line of notice below the content of the decrypted post, which is similar to how Twitter shows the original uploader of videos when videos are being tweeted by a different account.

## Notes

- None.

**Comment by Jack-Works** [comment]
> This would require users that they must never change their username, or their previous posts will be doomed.

We're relying on the user identifier. It has to be consistent and public access. For example, they may store each user as a UUID, that UUID cannot be changed but username/nickname can. Since there is no way to know the internal ID so this is a requirement.

There is another possible way to identify the user by their key fingerprint but that requires user never change their public key.

**Comment by septs** [comment]
provide a lookup table system

from `username` get an `platform specific user-id`.

**Comment by Jack-Works** [comment]
> lookup table system

that's not decentralized

**Comment by neruthes** [comment]
> 
> 
> provide a lookup table system
> 
> from `username` get an `platform specific user-id`.

This is beyond the scope of this issue and I suspect whether it should be employed in other components.

**Comment by neruthes** [comment]
I would like to mention that an Image-Based Payload on Twitter might be pasted on Facebook (even under the same username). In this case, the notice should be slightly different.

For example, if the notice reads as "Originally posted by username" when someone on Twitter published it on Twitter, it should read as "Originally posted by twitter.com/username" when seen on Facebook.

**Comment by Jack-Works** [comment]
🤦‍♂️

**Comment by Tedko** [comment]
> I would like to mention that an Image-Based Payload on Twitter might be pasted on Facebook (even under the same username). In this case, the notice should be slightly different.
> 
> 
> 
> For example, if the notice reads as "Originally posted by username" when someone on Twitter published it on Twitter, it should read as "Originally posted by twitter.com/username" when seen on Facebook.

Too early to consider this

**Comment by neruthes** [comment]
## Discussion Summary

Postponed indefinitely. Will consider resuming this in Jan 2021.

**Comment by Jack-Works** [comment]
> ## Discussion Summary
> Postponed indefinitely. Will consider resuming this in Jan 2021.

Explain?

**Comment by neruthes** [comment]
> > ## Discussion Summary
> 
> > Postponed indefinitely. Will consider resuming this in Jan 2021.
> 
> 
> 
> Explain?

Due to the request from Suji.
