### ISSUE TITLE
[Bug] Renaming the donate button when API not ready

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1268]
# Bug Report

<img width="501" alt="donation_dialog" src="https://user-images.githubusercontent.com/52657989/85247515-99f4eb00-b480-11ea-9deb-21f190e032d2.png">

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by Tedko** [comment]
We can keep this button open. No worry for now. Just don’t official promote it

**Comment by guanbinrui** [comment]
> We can keep this button open. No worry for now. Just don’t official promote it

OK, Let's change its name to "open" cause it will open grant page when API not ready.

**Comment by neruthes** [comment]
> 
> 
> > We can keep this button open. No worry for now. Just don’t official promote it
> 
> OK, Let's change its name to "View on Gitcoin" cause it will open the home page of Grant when API not ready.

Good

**Comment by Tedko** [comment]
Will keep the current one until the API is ready

**Comment by yisiliu** [comment]
stalled by https://github.com/gitcoinco/web/pull/6633
