### ISSUE TITLE
[Demand] Support Safari on macOS and iOS 15

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1271]
MDN data: https://github.com/mdn/browser-compat-data/pull/6320
Apple document: https://developer.apple.com/documentation/safariservices/safari_web_extensions

**Comment by Jack-Works** [comment]
Bump

**Comment by yisiliu** [comment]
@Jack-Works are we still going to support safari 14? If not, I'd suggest we close this issue first.

**Comment by Jack-Works** [comment]
We can leave it thou no plan on supporting it currently.

**Comment by yisiliu** [comment]
let's close it then.

**Comment by Jack-Works** [comment]
Re-open this since it is not resolved. We may want to revisit this in the future since iOS 15 just supported Web Extension yet.

**Comment by qqqzhch** [comment]
I'm still new to this project, I'll look into this
It is true that a number of users use the Apple browser

**Comment by qqqzhch** [comment]
some info  https://developer.apple.com/forums/thread/710876

Safari 15.4 introduced support for manifest version 3. Safari 16 continues to support both manifest version 2 and version 3. Manifest version 3 brings new and improved APIs for developers but if you have an existing mv2 extension, it will continue to work in Safari 16.

**Comment by Jack-Works** [comment]
Our extension has Chrome Manifest V3 support, but I didn't test for Firefox and Safari (for V3). Since I got a new mac device, I may be able to start to investigate support for Safari.

**Comment by qqqzhch** [comment]
> Our extension has Chrome Manifest V3 support, but I didn't test for Firefox and Safari (for V3). Since I got a new mac device, I may be able to start to investigate support for Safari.

I will gather information about the project as I learn about it and try to see what needs to be modified to make the migration successful.

**Comment by qqqzhch** [comment]
@Jack-Works  
Chrome Manifest V3 support is not yet complete, I think, I tried to build the Chrome MV3, can not open the pop page in Chrome ，
 which has a number of errors

i use npm run build:mv3

**Comment by qqqzhch** [comment]
npm  run  start:mv3  is working fine

 npm run build:mv3
<img width="1127" alt="WX20230320-195124@2x" src="https://user-images.githubusercontent.com/3917994/226332339-f9c623c9-14f7-47d1-80d4-6b6ba4caec38.png">
I will first do some tests with the code from the development environment

**Comment by Jack-Works** [comment]
@qqqzhch Hi, it used to run on Chrome MV3 but we lack a test of it so it gets regression. I believe those issues are easy to fix.

**Comment by qqqzhch** [comment]
@Jack-Works
Okay, I know, I'm not very familiar with the project, I'll learn something about the project in the process of finding out what went wrong.

**Comment by qqqzhch** [comment]
@Jack-Works  I've got the latest code to build mv3 to work in Google Chrome

**Comment by qqqzhch** [comment]
I've been working on this for the past few days, as much of the information on the internet is rather outdated and can only be used as a reference, but in practice need to create your own projects

1  need to create the project yourself in xcode, the information on the internet is rather outdated
2  need to upgrade  browser to the latest v16 because
Cannot import script to service worker with `self.importScripts`
https://developer.apple.com/forums/thread/711341
3 Debugging method The debugging method is a little different from the Google Chrome plugin
https://developer.apple.com/documentation/safariservices/safari_web_extensions/troubleshooting_your_safari_web_extension
4  Add a try catch to view the backend error log, because after an error, the installation will not see the error
```
try {
    importScripts(
        './worker_env.js',
        './gun.js',
        './polyfill/browser-polyfill.js',
        './sandboxed-modules/mv3-preload.js',
        './js/background.js',
    )
}
catch(error){
    console.log(error)
    
}
```
I can already see the error message, but I can't pinpoint the exact error yet
<img width="952" alt="image" src="https://user-images.githubusercontent.com/3917994/227754222-b4918045-a665-45e8-8f97-af3246ecda15.png">

**Comment by Jack-Works** [comment]
about the `Unexpected token '{'`, maybe you can try to downgrade the syntax target. Currently we're targeting ES2022 syntax and that may be unsupported by Safari.

**Comment by qqqzhch** [comment]
@Jack-Works  Okay, I'll try it.

**Comment by qqqzhch** [comment]
I have tried to modify the
b/packages/mask/.webpack/config.ts

target: ['web', 'es5']
Then it is packaged and put into the browser plug-in, but the error remains the same.
Are there other configuration files that need to be changed as well?

**Comment by Jack-Works** [comment]
ok I'll investigate this

**Comment by Jack-Works** [comment]
play around with Xcode and Safari for a while, and I found it's actually not debuggable.

https://developer.apple.com/forums/thread/720904

I maybe not investigate this these days unless I have more input.

**Comment by qqqzhch** [comment]
> play around with Xcode and Safari for a while, and I found it's actually not debuggable.
> 
> https://developer.apple.com/forums/thread/720904
> 
> I maybe not investigate this these days unless I have more input.

1 1 If the error is reported in the service worker, the debugging screen will not open in the browser.
like this
<img width="643" alt="WX20230411-092402@2x" src="https://user-images.githubusercontent.com/3917994/231031181-731b1124-a2f8-4a26-aa04-447a231141f0.png">
so

```
try {
    importScripts(
        './worker_env.js',
        './gun.js',
        './polyfill/browser-polyfill.js',
        './sandboxed-modules/mv3-preload.js',
        './js/background.js',
    )
}
catch(error){
    console.log(error)
    
}
```
2 The location of the debug menu is really difficult to find the first time

<img width="792" alt="WX20230411-092935@2x" src="https://user-images.githubusercontent.com/3917994/231031978-8ef33a9c-a58c-46b4-8526-26535de6c20a.png">
After adding trycatch to the service worker
<img width="713" alt="WX20230411-092904@2x" src="https://user-images.githubusercontent.com/3917994/231032015-bb373cea-4170-4dad-97a2-6b2a73d5ca2e.png">

**Comment by qqqzhch** [comment]
Safari version v16.3

**Comment by Jack-Works** [comment]
can you share how you configure the Xcode project for the extension?

**Comment by qqqzhch** [comment]
> can you share how you configure the Xcode project for the extension?

I'll organize the information I've seen and write it in the issues

**Comment by Jack-Works** [comment]
afaik a safari extension requires an Xcode project. maybe you can open a PR containing the Xcode project you created?

**Comment by qqqzhch** [comment]
> afaik a safari extension requires an Xcode project. maybe you can open a PR containing the Xcode project you created?

Okay, I'll write a post documenting the creation of the project that, and then create a pr
for testing

**Comment by qqqzhch** [comment]
Record the steps and things to note to create Safari browser plug-in extensions with mv3
https://docs.google.com/document/d/1SeV6-P_rXHUwvSnLHpgF8tuk9CK7-7YPnl6KrCARYC0/edit?usp=sharing

**Comment by qqqzhch** [comment]
@Jack-Works 
To create a project, i need to generate a folder under Maskbook/packages, the name of the folder is called MaskSafari better or MaskSafariExtension better?

**Comment by qqqzhch** [comment]
https://github.com/DimensionDev/Maskbook/pull/9436   @Jack-Works 
Added the xcode file for creating projects

**Comment by qqqzhch** [comment]
Before local testing is more casual, I put the whole built project in and then operate in xocde.
Now I plan to
1 first create a build folder in the resource directory, copy the built mv3 files into it.
2 write a new configuration file based on the existing configuration file and put it under the resource directory.
This will allow for better testing

**Comment by qqqzhch** [comment]
To record some information, the error message I encountered in my troubleshooting project was
<img width="924" alt="image" src="https://github.com/DimensionDev/Maskbook/assets/3917994/b2a4015d-c3c7-414c-9f80-2e8dbdbe0518">

- /build/js/npm-ns.masknet.compartment.js   A syntax error occurs when loading, which is quite puzzling, because the build has been successful.
- fetchBlob and localStorage need to be checked to see how browsers support them

**Comment by Jack-Works** [comment]
Hi I'm cleaning up our infrastructure to prepare for Safari!

**Comment by qqqzhch** [comment]
Ok received, hope I do this try, may help a little to adjust the infrastructure  @Jack-Works 
I tried today, changing webpack target: ['web'] or target: ['web', 'es5'] doesn't affect the packaged /build/js/npm-ns.masknet.compartment.js, which still returns syntax errors when loaded

**Comment by Jack-Works** [comment]
> which still returns syntax errors when loaded

@qqqzhch are you using safari 16.4 or higher?

**Comment by qqqzhch** [comment]
> > which still returns syntax errors when loaded
> 
> @qqqzhch are you using safari 16.4 or higher?

safari 16.3 @Jack-Works
