### ISSUE TITLE
[Demand] Add a search box for `Select Specific Friend`

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1311]
## Metadata

![Screen Shot 2020-07-12 at 18 43 27](https://user-images.githubusercontent.com/6687437/87244510-8251c680-c470-11ea-89e0-b02441656a13.png)

Once the friend list >=10 the current UX is not usable. Need a search box  for `Select Specific Friend`

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by OiCkilL** [comment]
figma link: https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=2047%3A0

**Comment by Jack-Works** [comment]
I think we had this UI now. Why it is not used in "Select specific friend"?

![image](https://user-images.githubusercontent.com/5390719/93222502-9a600200-f7a1-11ea-8705-e69ea18bbc68.png)

**Comment by Tedko** [comment]
Wondering too. Let’s add it. Should be super fast.

**Comment by Tedko** [comment]
@zhouhanseng wanna try this?

**Comment by Tedko** [comment]
> @zhouhanseng wanna try this?

try this start from oct8 the 1st working day>?

**Comment by zhouhanseng** [comment]
hey, I'd like to do it.

**Comment by Jack-Works** [comment]
I thought we have a ui for this maybe it's not in use

**Comment by zhouhanseng** [comment]
have ui code already been done?

**Comment by Jack-Works** [comment]
https://www.github.com/DimensionDev/Maskbook/tree/master/src%2Fcomponents%2Fshared%2FSelectPeopleAndGroups this ui support search

**Comment by zhouhanseng** [comment]
`<SelectPeopleAndGroupsUI />` is using on other place, and since `<SelectRecipientsDialogUI />` already had its own UI, so we should not import the whole ``<SelectPeopleAndGroupsUI />`` to `<SelectRecipientsDialogUI />`. I just copy the search input and its search logic with some changes.
