### ISSUE TITLE
Minified React Error

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#132]
<img width="541" alt="Screen Shot 2019-08-27 at 11 57 18" src="https://user-images.githubusercontent.com/6687437/63800082-3fbbe580-c8c2-11e9-9d79-27b4bd2880e9.png">

<img width="692" alt="Screen Shot 2019-08-27 at 12 02 09" src="https://user-images.githubusercontent.com/6687437/63800224-8a3d6200-c8c2-11e9-8c25-c9f115383cfa.png">

https://www.facebook.com/suji.yan.me?__tn__=lC-R&eid=ARAh70ql82yLrjQof--tiKTBipkssfFWPwifxL1GzXFjqRucnVR9Cxn_a2oyqsAjVPepeIxM2vmz_oTh&hc_ref=ARQWOhn_blCe0eDUCIVz9hOCThW3tSzhXJ6fBckHkoh3uR9hDHM9FevfXqrtdfEZC5c

Version: latest Chrome Store Ver
How to reproduce:

Post a check-in on fb with Maskbook turns on. Or go to checkout my fb profile page.

**Comment by Jack-Works** [comment]
Should be resolved in 1.6.0

**Comment by Jack-Works** [comment]
Not sure

**Comment by Tedko** [comment]
Will test 1.6.0 from chrome store

**Comment by Tedko** [comment]
Tested with 1.6. Fixed
