### ISSUE TITLE
[Bug] Remove URL permission alert on iOS

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1321]
# Bug Report
![IMG_7426 PNG](https://user-images.githubusercontent.com/6687437/87814853-179cf280-c897-11ea-975f-4121658ec6ec.jpeg)

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by jk234ert** [comment]
Retested on the latest Maskbook master branch, this issue could not be reproduced.
This issue should be closed in the upcoming new iOS version.
