### ISSUE TITLE
[Discussion] Switch to pnpm

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1324]
## Background

pnpm is a package manager for Node.js. https://pnpm.js.org/

## Pros

Fast, saving disk space (it is using hard link) and not error-prone.

Read https://www.kochan.io/nodejs/why-should-we-use-pnpm.html and https://pnpm.js.org/blog/2020/05/27/flat-node-modules-is-not-the-only-way

## Cons

1. pnpm is not as popular as `npm` or `yarn` (is this really a problem?)
2. ...?

## Blocking

1. We're modifying node_modules.

## Decision?

@septs @guanbinrui

We'll also move other projects to pnpm if we move Maskbook to pnpm.

**Comment by septs** [comment]
Rejected

**Comment by septs** [comment]
Move to `npm`, Thanks

**Comment by Jack-Works** [comment]
@septs please list your reason

> 1.  modules can access packages they don’t depend on

`npm` and `yarn1` both have this problem. This is a foot gun. `yarn2` doesn't have this problem but it is not compatible with most of our toolchains.

> [PNPM](https://pnpm.js.org/): A fundamentally new installation model that solves the [“phantom dependency” and “NPM doppelganger”](https://rushjs.io/pages/advanced/phantom_deps/)” problems, while cleverly making use of [symlinks](https://en.wikipedia.org/wiki/Symbolic_link) to remain 100% compatible with the NodeJS module resolution standard.

\-- https://rushjs.io/pages/maintainer/package_managers/

By the non-flatten module, any package cannot access \[phantom dependencies\](https://rushjs.io/pages/advanced/phantom_deps/) which make the software more predictable.

**Comment by Tedko** [comment]
Is this issue w/ high priority? Seems like so far stick w/ npm wont cuz too much trouble either

**Comment by Jack-Works** [comment]
No priority for this. But I want to find a better way to do.

**Comment by guanbinrui** [comment]
> We're modifying node_modules.

Do you mean `@holoflows/kit`?

**Comment by Jack-Works** [comment]
> Do you mean @holoflows/kit?

Beside that, we also modify `ts-results` in the SSR process

**Comment by zhouhanseng** [comment]
My previous company [compass.com](compass.com) uses `pnpm`. They have too many apps and packages, so `pnpm` is very suitable for them.

**Comment by zhouhanseng** [comment]
My previous company uses pnpm. It has too many apps and packages, so pnpm is very suitable for them to save disk space.

**Comment by Jack-Works** [comment]
`ts-results` now supports cjs too. We have already decided to have a try on pnpm in the future (now no enough bandwidth for this)

**Comment by septs** [comment]
i disagree, switch to pnpm

**Comment by Jack-Works** [comment]
I'll open a new issue for discussion
