### ISSUE TITLE
[Bug] Change `fb` within Image Mode to `platforms`

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1339]
# Bug Report

![EddgJeSU8AIxwUk](https://user-images.githubusercontent.com/6687437/88078952-a4092700-cbaf-11ea-995d-47990366c302.png)

@OiCkilL @guanbinrui change back to the previous text (only include `platforms` )

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
I thought we had an issue for this matter... 🤔

**Comment by guanbinrui** [comment]
Anyone who has the edit permission can change the Figma document.

https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=985%3A0

**Comment by Jack-Works** [comment]
the image has been changed on the figma by someone
