### ISSUE TITLE
[Bug] Cannot insert Image-Based Payload into Natural Post on Android

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1341]
# Bug Report

### System

- OS: Android
- OS Version: *

### Maskbook

- Maskbook Version: *
- Installation: Google Play

### Expected Behavior

When clicking "Finish", the image should be inserted into the Natural Post.

### Actual Behavior

The image is not inserted.

### How To Reproduce

Create a post with Image-Based Payload option enabled.

**Comment by Tedko** [comment]
duplicate
