### ISSUE TITLE
[Demand] Typo change

### ISSUE THREAD

**Issue by OiCkilL** [DimensionDev/Maskbook#1353]
## Metadata
![image](https://user-images.githubusercontent.com/613988/88764341-5db35980-d1a7-11ea-922e-fc8af539b947.png)

- [x] Before: Full address text
After: Shortened text

![image](https://user-images.githubusercontent.com/613988/88764539-b71b8880-d1a7-11ea-919c-d7604112b36b.png)
- [x] Before: History
After: Activity

![image](https://user-images.githubusercontent.com/613988/88764602-cf8ba300-d1a7-11ea-8b2f-24c4a8d9c406.png)

- [x] Before: "Well-know tokens" and "add your own"

After: Remove "ERC20", -> "Search" and "Custom Token"

![image](https://user-images.githubusercontent.com/613988/88765130-9ef83900-d1a8-11ea-9526-0222871f3ab7.png)
- [x]  Before: "Advanced Options"
After: "Advanced"

**Comment by Tedko** [comment]
```
 Before: "Well-know tokens" and "add your own"
After: Remove "ERC20", -> "Search" and "Custom Token"
```

fixed in `released` branch
