### ISSUE TITLE
[Bug] Multiple decryption post shown

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1354]
# Bug Report

<img width="1342" alt="Screen Shot 2020-07-29 at 16 24 01" src="https://user-images.githubusercontent.com/6687437/88776726-e981b180-d1b8-11ea-9cba-4eedf262fc37.png">
<img width="1342" alt="Screen Shot 2020-07-29 at 16 24 01" src="https://user-images.githubusercontent.com/6687437/88776733-eb4b7500-d1b8-11ea-844b-2c664423a7c7.png">

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### How To Reproduce

go to https://twitter.com/search?q=%23maskbook&src=recent_search_click&f=live

**Comment by Tedko** [comment]
reproduced by @OiCkilL as well

**Comment by neruthes** [comment]
I reproduced this yesterday.
