### ISSUE TITLE
Add polyfill for Blob.prototype.arrayBuffer

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1363]
see https://mdn.io/blob/arrayBuffer
see https://caniuse.com/#feat=mdn-api_blob_arraybuffer

_Originally posted by @septs in https://github.com/DimensionDev/Maskbook/pull/1338#discussion_r458547642_

We're also using this in #1355

**Comment by septs** [comment]
! This polyfill is limited to the Safari specific. !

**Comment by Jack-Works** [comment]
yes but we need that

**Comment by Jack-Works** [comment]
done
