### ISSUE TITLE
[Bug] Throw error: .firefox profile name cannot be resolved to a profile path

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#1389]
# Bug Report
Can't init the project, since terminal throws an error: 
```
The request "/pathtoproject/Maskbook/.firefox" profile name cannot be resolved to a profile path
```

![image](https://user-images.githubusercontent.com/63733714/89120858-20730280-d4ec-11ea-8747-480327b34577.png)

### System

- OS: macOS Catalina
- OS Version: 10.15.1

### Browser

- Browser: firefox
- Browser Version: 77.0.1

### Maskbook

Local development, master, and firefox branch with the latest commit.

### Expected Behavior

No error.
### Actual Behavior

With error
### How To Reproduce
``` 
$ yarn install 
$ yarn start:firefox 
```
Visit the http://localhost:8080/webpack-dev-server/ on firefox browser.

**Comment by Tedko** [comment]
hi

Try Create the folder manually? That will fix the problem. Thanks

**Comment by zhouhanseng** [comment]
You mean to create a folder, then clone the repository into it?

**Comment by Tedko** [comment]
Create A folder  "/pathtoproject/Maskbook/.firefox "
