### ISSUE TITLE
[Draft] [Discussion] Base-Emoji implementation

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#139]
#### Status
Current Stage:
* Draft

#### Overview and Motivation
* There is currently 1719 emojis, 169 of them are no more than 1 bytes, 1268 of them are 2, 1280 are 3, 1538 are 4, 1680 are 5, 1687 are 6, 1688 are 7, 1704 are 8, 1716 are 11, 1719 are 14.
* Some user says that our payload looks not quite pretty.
* No matter how long a emoji actually is, on Twitter it is all counted as 2 bytes.

#### Possible Implementation
* Based on base64, we map 1 base64 -> 1 one-byte emoji. Flaw: double bytes are wasted, 1-byte emojis are ugly, we can only .
* Based on base64, we map some base64 -> another some emoji, just like any 8bit -> base64, `256 ** 3 = 64 ** 4`，so that every 3 base256 could be represented by 4 base64.
* Based on original binary, we map 1 base256 -> 1 emoji. 

#### Caveats
* Emojis subset should be carefully choosen to avoid dispute or misunderstanding.
* Some emojis have different modifiers, maybe not all modifiers are supported on all platforms. If they would replace them, we lost informatons.
* Different platform may store emojis differently. Some are UTF-8, some UTF-16. Emojis with more than 4 bytes UTF-8 should be avoided.

#### All emojis here, sorted by UTF-8 length

["▫","▪","◽","◾","◻","◼","⬜","⬛","⚪","⚫","㊙","㊗","Ⓜ","ℹ","™","®","©","〰","❗","❕","❔","❓","⁉","‼","❇","✴","✳","〽","➿","➰","➗","➖","➕","❎","❌","✖","✔","☑","✅","⭕","⚜","♻","♾","⚕","♂","♀","⏏","⏺","⏹","⏸","⏬","⏫","⏮","⏪","◀","⏯","⏭","⏩","▶","⛎","♓","♒","♑","♐","♏","♎","♍","♌","♋","♊","♉","♈","☮","☪","☦","✝","☯","☸","✡","⚛","⤵","⤴","↪","↩","↔","↕","↖","⬅","↙","⬇","↘","➡","↗","⬆","☣","☢","⛔","⚠","♿","⚱","⚰","⚗","⛓","⚖","⚙","⚔","⚒","⛏","✂","✒","✏","✉","⌨","☎","⛑","♟","♣","♦","♥","♠","⛸","⛳","⚾","⚽","✨","☄","⛄","☃","❄","⚡","⛱","☔","☂","⛈","⛅","☁","⭐","☀","⏲","⏱","⏰","⌚","⏳","⌛","✈","⛴","⛵","⚓","⛽","♨","⛺","⛲","⛩","⛪","⛰","☕","☘","⛹","⛷","✍","✊","☝","✌","✋","❤","❣","☠","☹","☺","🏳","🏴","🎌","🚩","🏁","🔲","🔳","🔘","💠","🔻","🔺","🔹","🔸","🔷","🔶","🟫","🟪","🟦","🟩","🟨","🟧","🟥","🟤","🟣","🔵","🟢","🟡","🟠","🔴","🈵","🈺","🈳","🈴","🈸","🉑","🈲","🈚","🈹","🉐","🈯","🈶","🈷","🈂","🈁","🆚","🆙","🆘","🅿","🆗","🅾","🆖","🆕","🆔","🆓","🆒","🆑","🅱","🆎","🅰","🔤","🔣","🔢","🔡","🔠","🔟","🔰","📛","🔱","📴","📳","📶","🔆","🔅","🎦","🔽","🔼","🔂","🔁","🔀","🔯","🕎","🕉","🛐","🔝","🔜","🔛","🔚","🔙","🔄","🔃","🔞","📵","🚷","🚱","🚯","🚭","🚳","🚫","🚸","🛅","🛄","🛃","🛂","🚾","🚼","🚻","🚺","🚹","🚰","🚮","🏧","🗿","🚬","🛒","🧯","🧽","🧼","🧻","🧺","🧹","🧷","🧴","🪒","🛁","🚿","🚽","🪑","🛋","🛏","🚪","🩺","🩹","💊","🩸","💉","📡","🔭","🔬","🧬","🧫","🧪","🧲","🧰","🔗","🦯","🗜","🔩","🔧","🛡","🏹","🔫","🗡","🛠","🪓","🔨","🗝","🔑","🔐","🔏","🔓","🔒","🗑","🗄","🗃","📐","📏","🖇","📎","📍","📌","📋","📊","📉","📈","📇","🗓","🗒","📆","📅","🗂","📂","📁","💼","📝","🖍","🖌","🖊","🖋","🗳","📮","📭","📬","📪","📫","📦","📥","📤","📩","📨","📧","💲","💱","💹","🧾","💳","💸","💷","💶","💵","💴","💰","🏷","🔖","📑","🗞","📰","📄","📜","📃","📒","📓","📚","📙","📘","📗","📖","📕","📔","🪔","🏮","🔦","💡","🕯","🔎","🔍","📼","📹","📸","📷","📺","🎬","📽","🎞","🎥","🧮","📀","💿","💾","💽","🖲","🖱","🖨","🖥","💻","🔌","🔋","📠","📟","📞","📲","📱","🥁","🪕","🎻","🎺","🎹","🎸","🎷","📻","🎧","🎤","🎛","🎚","🎙","🎶","🎵","🎼","🔕","🔔","📯","📣","📢","🔊","🔉","🔈","🔇","💎","💍","💄","📿","🧢","🎓","🎩","👒","👑","👢","🩰","👡","👠","🥿","🥾","👟","👞","🎒","🛍","👝","👜","👛","👚","👙","🩳","🩲","🩱","🥻","👘","👗","🧦","🧥","🧤","🧣","👖","👕","👔","🦺","🥼","🥽","🕶","👓","🧶","🧵","🎨","🖼","🎭","🎴","🀄","🃏","🧸","🧩","🎲","🎰","🕹","🎮","🧿","🔮","🎱","🪁","🪀","🎯","🥌","🛷","🎿","🎽","🤿","🎣","🥅","🥋","🥊","🏸","🏓","🥍","🏒","🏑","🏏","🎳","🥏","🎾","🏉","🏈","🏐","🏀","🥎","🥉","🥈","🥇","🏅","🏆","🎖","🎫","🎟","🎗","🎁","🎀","🧧","🎑","🎐","🎏","🎎","🎍","🎋","🎊","🎉","🎈","🧨","🎇","🎆","🎄","🎃","🌊","💧","🔥","🌂","🌈","🌀","🌬","🌫","🌪","🌩","🌨","🌧","🌦","🌥","🌤","🌌","🌠","🌟","🪐","🌞","🌝","🌡","🌜","🌛","🌚","🌙","🌘","🌗","🌖","🌕","🌔","🌓","🌒","🌑","🕦","🕚","🕥","🕙","🕤","🕘","🕣","🕗","🕢","🕖","🕡","🕕","🕠","🕔","🕟","🕓","🕞","🕒","🕝","🕑","🕜","🕐","🕧","🕛","🕰","🧳","🛎","🛸","🚀","🛰","🚡","🚠","🚟","🚁","💺","🪂","🛬","🛫","🛩","🚢","🛥","🛳","🚤","🛶","🚧","🛑","🚦","🚥","🚨","🛢","🛤","🛣","🚏","🛹","🛴","🚲","🛺","🦼","🦽","🛵","🏍","🏎","🚜","🚛","🚚","🚙","🚘","🚗","🚖","🚕","🚔","🚓","🚒","🚑","🚐","🚎","🚍","🚌","🚋","🚞","🚝","🚊","🚉","🚈","🚇","🚆","🚅","🚄","🚃","🚂","🎪","💈","🎢","🎡","🎠","🌉","🌇","🌆","🌅","🌄","🏙","🌃","🌁","🕋","🕍","🛕","🕌","🗽","🗼","💒","🏰","🏯","🏭","🏬","🏫","🏪","🏩","🏨","🏦","🏥","🏤","🏣","🏢","🏡","🏠","🏚","🏘","🧱","🏗","🏛","🏟","🏞","🏝","🏜","🏖","🏕","🗻","🌋","🏔","🧭","🗾","🗺","🌐","🌏","🌎","🌍","🏺","🔪","🥄","🍴","🍽","🥢","🧊","🧉","🧃","🥤","🥃","🥂","🍻","🍺","🍹","🍸","🍷","🍾","🍶","🍵","🥛","🍼","🍯","🍮","🍭","🍬","🍫","🥧","🧁","🍰","🎂","🍪","🍩","🍨","🍧","🍦","🦪","🦑","🦐","🦞","🦀","🥡","🥠","🥟","🍡","🥮","🍥","🍤","🍣","🍢","🍠","🍝","🍜","🍛","🍚","🍙","🍘","🍱","🥫","🧂","🧈","🍿","🥗","🥣","🍲","🥘","🍳","🥚","🧆","🥙","🌯","🌮","🥪","🌭","🍕","🍟","🍔","🥓","🥩","🍗","🍖","🧀","🧇","🥞","🥯","🥨","🥖","🥐","🍞","🌰","🥜","🍄","🧅","🧄","🥦","🥬","🥒","🌶","🌽","🥕","🥔","🍆","🥑","🥥","🍅","🥝","🍓","🍒","🍑","🍐","🍏","🍎","🥭","🍍","🍌","🍋","🍊","🍉","🍈","🍇","🍃","🍂","🍁","🍀","🌿","🌾","🌵","🌴","🌳","🌲","🌱","🌷","🌼","🌻","🌺","🥀","🌹","🏵","💮","🌸","💐","🦠","🦟","🦂","🕸","🕷","🦗","🐞","🐝","🐜","🐛","🦋","🐌","🐚","🐙","🦈","🐡","🐠","🐟","🐬","🐋","🐳","🦖","🦕","🐉","🐲","🐍","🦎","🐢","🐊","🐸","🦜","🦚","🦩","🦉","🦢","🦆","🦅","🕊","🐧","🐦","🐥","🐤","🐣","🐓","🐔","🦃","🐾","🦡","🦘","🦨","🦦","🦥","🐼","🐨","🐻","🦇","🦔","🐿","🐇","🐰","🐹","🐀","🐁","🐭","🦛","🦏","🐘","🦒","🦙","🐫","🐪","🐐","🐑","🐏","🐽","🐗","🐖","🐷","🐄","🐃","🐂","🐮","🦌","🦓","🦄","🐎","🐴","🐆","🐅","🐯","🦁","🐈","🐱","🦝","🦊","🐺","🐩","🦮","🐕","🐶","🦧","🦍","🐒","🐵","🦲","🦳","🦱","🦰","👣","👥","👤","🗣","👪","💑","💏","👬","👫","👭","🛌","🛀","🧘","🤹","🤾","🤽","🤼","🤸","🚵","🚴","🏋","🏊","🚣","🏄","🏌","🏂","🏇","🤺","🧗","🧖","👯","🕴","🕺","💃","🏃","🧎","🧍","🚶","💇","💆","🧟","🧞","🧝","🧜","🧛","🧚","🧙","🦹","🦸","🤶","🎅","👼","🤱","🤰","👰","🤵","🧕","👲","👳","👸","🤴","👷","💂","🕵","👮","🤷","🤦","🙇","🧏","🙋","💁","🙆","🙅","🙎","🙍","👵","👴","🧓","👩","🧔","👨","👱","🧑","👧","👦","🧒","👶","👄","👅","👁","👀","🦴","🦷","🧠","👃","🦻","👂","🦶","🦵","🦿","🦾","💪","🤳","💅","🙏","🤝","🤲","👐","🙌","👏","🤜","🤛","👊","👎","👍","👇","🖕","👆","👉","👈","🤙","🤘","🤟","🤞","🤏","👌","🖖","🖐","🤚","👋","💤","💭","🗯","🗨","💬","💣","🕳","💨","💦","💫","💥","💢","💯","🤍","🖤","🤎","💜","💙","💚","💛","🧡","💔","💟","💕","💞","💓","💗","💖","💝","💘","💌","💋","🙊","🙉","🙈","😾","😿","🙀","😽","😼","😻","😹","😸","😺","🤖","👾","👽","👻","👺","👹","🤡","💩","💀","👿","😈","🤬","😠","😡","😤","🥱","😫","😩","😓","😞","😣","😖","😱","😭","😢","😥","😰","😨","😧","😦","🥺","😳","😲","😯","😮","🙁","😟","😕","🧐","🤓","😎","🥳","🤠","🤯","😵","🥴","🥶","🥵","🤧","🤮","🤢","🤕","🤒","😷","😴","🤤","😪","😔","😌","🤥","😬","🙄","😒","😏","😶","😑","😐","🤨","🤐","🤔","🤫","🤭","🤗","🤑","😝","🤪","😜","😛","😋","😙","😚","😗","😘","🤩","😍","🥰","😇","😊","😉","🙃","🙂","😂","🤣","😅","😆","😁","😄","😃","😀","9️⃣","8️⃣","7️⃣","6️⃣","5️⃣","4️⃣","3️⃣","2️⃣","1️⃣","0️⃣","*️⃣","#️⃣","🇿🇼","🇿🇲","🇿🇦","🇾🇹","🇾🇪","🇽🇰","🇼🇸","🇼🇫","🇻🇺","🇻🇳","🇻🇮","🇻🇬","🇻🇪","🇻🇨","🇻🇦","🇺🇿","🇺🇾","🇺🇸","🇺🇳","🇺🇲","🇺🇬","🇺🇦","🇹🇿","🇹🇼","🇹🇻","🇹🇹","🇹🇷","🇹🇴","🇹🇳","🇹🇲","🇹🇱","🇹🇰","🇹🇯","🇹🇭","🇹🇬","🇹🇫","🇹🇩","🇹🇨","🇹🇦","🇸🇿","🇸🇾","🇸🇽","🇸🇻","🇸🇹","🇸🇸","🇸🇷","🇸🇴","🇸🇳","🇸🇲","🇸🇱","🇸🇰","🇸🇯","🇸🇮","🇸🇭","🇸🇬","🇸🇪","🇸🇩","🇸🇨","🇸🇧","🇸🇦","🇷🇼","🇷🇺","🇷🇸","🇷🇴","🇷🇪","🇶🇦","🇵🇾","🇵🇼","🇵🇹","🇵🇸","🇵🇷","🇵🇳","🇵🇲","🇵🇱","🇵🇰","🇵🇭","🇵🇬","🇵🇫","🇵🇪","🇵🇦","🇴🇲","🇳🇿","🇳🇺","🇳🇷","🇳🇵","🇳🇴","🇳🇱","🇳🇮","🇳🇬","🇳🇫","🇳🇪","🇳🇨","🇳🇦","🇲🇿","🇲🇾","🇲🇽","🇲🇼","🇲🇻","🇲🇺","🇲🇹","🇲🇸","🇲🇷","🇲🇶","🇲🇵","🇲🇴","🇲🇳","🇲🇲","🇲🇱","🇲🇰","🇲🇭","🇲🇬","🇲🇫","🇲🇪","🇲🇩","🇲🇨","🇲🇦","🇱🇾","🇱🇻","🇱🇺","🇱🇹","🇱🇸","🇱🇷","🇱🇰","🇱🇮","🇱🇨","🇱🇧","🇱🇦","🇰🇿","🇰🇾","🇰🇼","🇰🇷","🇰🇵","🇰🇳","🇰🇲","🇰🇮","🇰🇭","🇰🇬","🇰🇪","🇯🇵","🇯🇴","🇯🇲","🇯🇪","🇮🇹","🇮🇸","🇮🇷","🇮🇶","🇮🇴","🇮🇳","🇮🇲","🇮🇱","🇮🇪","🇮🇩","🇮🇨","🇭🇺","🇭🇹","🇭🇷","🇭🇳","🇭🇲","🇭🇰","🇬🇾","🇬🇼","🇬🇺","🇬🇹","🇬🇸","🇬🇷","🇬🇶","🇬🇵","🇬🇳","🇬🇲","🇬🇱","🇬🇮","🇬🇭","🇬🇬","🇬🇫","🇬🇪","🇬🇩","🇬🇧","🇬🇦","🇫🇷","🇫🇴","🇫🇲","🇫🇰","🇫🇯","🇫🇮","🇪🇺","🇪🇹","🇪🇸","🇪🇷","🇪🇭","🇪🇬","🇪🇪","🇪🇨","🇪🇦","🇩🇿","🇩🇴","🇩🇲","🇩🇰","🇩🇯","🇩🇬","🇩🇪","🇨🇿","🇨🇾","🇨🇽","🇨🇼","🇨🇻","🇨🇺","🇨🇷","🇨🇵","🇨🇴","🇨🇳","🇨🇲","🇨🇱","🇨🇰","🇨🇮","🇨🇭","🇨🇬","🇨🇫","🇨🇩","🇨🇨","🇨🇦","🇧🇿","🇧🇾","🇧🇼","🇧🇻","🇧🇹","🇧🇸","🇧🇷","🇧🇶","🇧🇴","🇧🇳","🇧🇲","🇧🇱","🇧🇯","🇧🇮","🇧🇭","🇧🇬","🇧🇫","🇧🇪","🇧🇩","🇧🇧","🇧🇦","🇦🇿","🇦🇽","🇦🇼","🇦🇺","🇦🇹","🇦🇸","🇦🇷","🇦🇶","🇦🇴","🇦🇲","🇦🇱","🇦🇮","🇦🇬","🇦🇫","🇦🇪","🇦🇩","🇦🇨","🏴‍☠️","🐕‍🦺","👩‍👧","👩‍👦","👨‍👧","👨‍👦","🧘‍♀️","🧘‍♂️","🤹‍♀️","🤹‍♂️","🤾‍♀️","🤾‍♂️","🤽‍♀️","🤽‍♂️","🤼‍♀️","🤼‍♂️","🤸‍♀️","🤸‍♂️","🚵‍♀️","🚵‍♂️","🚴‍♀️","🚴‍♂️","⛹️‍♀️","⛹️‍♂️","🏊‍♀️","🏊‍♂️","🚣‍♀️","🚣‍♂️","🏄‍♀️","🏄‍♂️","🧗‍♀️","🧗‍♂️","🧖‍♀️","🧖‍♂️","👯‍♀️","👯‍♂️","🏃‍♀️","🏃‍♂️","👩‍🦽","👨‍🦽","👩‍🦼","👨‍🦼","👩‍🦯","👨‍🦯","🧎‍♀️","🧎‍♂️","🧍‍♀️","🧍‍♂️","🚶‍♀️","🚶‍♂️","💇‍♀️","💇‍♂️","💆‍♀️","💆‍♂️","🧟‍♀️","🧟‍♂️","🧞‍♀️","🧞‍♂️","🧝‍♀️","🧝‍♂️","🧜‍♀️","🧜‍♂️","🧛‍♀️","🧛‍♂️","🧚‍♀️","🧚‍♂️","🧙‍♀️","🧙‍♂️","🦹‍♀️","🦹‍♂️","🦸‍♀️","🦸‍♂️","👳‍♀️","👳‍♂️","👷‍♀️","👷‍♂️","💂‍♀️","💂‍♂️","👮‍♀️","👮‍♂️","👩‍🚒","👨‍🚒","👩‍🚀","👨‍🚀","👩‍✈️","👨‍✈️","👩‍🎨","👨‍🎨","👩‍🎤","👨‍🎤","👩‍💻","👨‍💻","👩‍🔬","👨‍🔬","👩‍💼","👨‍💼","👩‍🏭","👨‍🏭","👩‍🔧","👨‍🔧","👩‍🍳","👨‍🍳","👩‍🌾","👨‍🌾","👩‍⚖️","👨‍⚖️","👩‍🏫","👨‍🏫","👩‍🎓","👨‍🎓","👩‍⚕️","👨‍⚕️","🤷‍♀️","🤷‍♂️","🤦‍♀️","🤦‍♂️","🙇‍♀️","🙇‍♂️","🧏‍♀️","🧏‍♂️","🙋‍♀️","🙋‍♂️","💁‍♀️","💁‍♂️","🙆‍♀️","🙆‍♂️","🙅‍♀️","🙅‍♂️","🙎‍♀️","🙎‍♂️","🙍‍♀️","🙍‍♂️","👩‍🦲","👩‍🦳","👩‍🦱","👩‍🦰","👱‍♀️","👨‍🦲","👨‍🦳","👨‍🦱","👨‍🦰","👱‍♂️","🏳️‍🌈","🏋️‍♀️","🏋️‍♂️","🏌️‍♀️","🏌️‍♂️","🕵️‍♀️","🕵️‍♂️","👁️‍🗨️","👩‍👧‍👧","👩‍👧‍👦","👩‍👦‍👦","👨‍👧‍👧","👨‍👧‍👦","👨‍👦‍👦","👩‍👩‍👧","👩‍👩‍👦","👨‍👨‍👧","👨‍👨‍👦","👨‍👩‍👧","👨‍👩‍👦","👩‍❤️‍👩","👨‍❤️‍👨","👩‍❤️‍👨","🧑‍🤝‍🧑","👩‍👩‍👧‍👧","👩‍👩‍👦‍👦","👩‍👩‍👧‍👦","👨‍👨‍👧‍👧","👨‍👨‍👦‍👦","👨‍👨‍👧‍👦","👨‍👩‍👧‍👧","👨‍👩‍👦‍👦","👨‍👩‍👧‍👦","👩‍❤️‍💋‍👩","👨‍❤️‍💋‍👨","👩‍❤️‍💋‍👨","🏴󠁧󠁢󠁷󠁬󠁳󠁿","🏴󠁧󠁢󠁳󠁣󠁴󠁿","🏴󠁧󠁢󠁥󠁮󠁧󠁿"]

**Comment by Artoria2e5** [comment]
> on Twitter it is all counted as 2 bytes.

that is revo-fucking-lutionary, and mastodon appears to do the same.

> Possible Implementation

none of these are good enough for the base64 efficiency. to re-iterate my point: if base64 has 1 char count for every 6 bits, our 2-char system needs to encode at least 12 bits to make it even. that is 4096 emoji at least. and what are these proposals? do you think we cannot do bitwise operations in js?

**Comment by Tedko** [comment]
Suggestion: We should avoid use flags for nations & regions.

Including:
🎌https://emojipedia.org/crossed-flags/;
&
From  "🇿🇼" to "🇦🇨"  (sorted by UTF-8 length) 
&  
**`🏴Waving Black Flag Family`** 
🏴󠁧󠁢󠁥󠁮󠁧󠁿https://emojipedia.org/flag-for-england/; `sequence of the 🏴 Waving Black Flag, 󠁧 Tag Latin Small Letter G, 󠁢 Tag Latin Small Letter B, 󠁥 Tag Latin Small Letter E, 󠁮 Tag Latin Small Letter N, 󠁧 Tag Latin Small Letter G and 󠁿 Cancel Tag emojis. `
🏴󠁧󠁢󠁳󠁣󠁴󠁿https://emojipedia.org/flag-for-scotland/ , `sequence of the 🏴 Waving Black Flag, 󠁧 Tag Latin Small Letter G, 󠁢 Tag Latin Small Letter B, 󠁳 Tag Latin Small Letter S, 󠁣 Tag Latin Small Letter C, 󠁴 Tag Latin Small Letter T and 󠁿 Cancel Tag emojis`
🏴󠁧󠁢󠁷󠁬󠁳󠁿  https://emojipedia.org/flag-for-wales/ , `sequence of the 🏴 Waving Black Flag, 󠁧 Tag Latin Small Letter G, 󠁢 Tag Latin Small Letter B, 󠁷 Tag Latin Small Letter W, 󠁬 Tag Latin Small Letter L, 󠁳 Tag Latin Small Letter S and 󠁿 Cancel Tag emojis`
US-TX https://emojipedia.org/flag-for-texas-ustx/  `sequence of the 🏴 Waving Black Flag, 󠁵 Tag Latin Small Letter U, 󠁳 Tag Latin Small Letter S, 󠁴 Tag Latin Small Letter T, 󠁸 Tag Latin Small Letter X and 󠁿 Cancel Tag emojis.` (not been Recommended For General Interchange (RGI) by Unicode)

**Comment by Tedko** [comment]
Also I want to remind folks here @SunriseFox @Artoria2e5 

There are many unicodes are widely as symbols and are not selected as part of the Emoji based on very random reason, such as Mahjong Titles [Wiki](https://en.wikipedia.org/wiki/Mahjong_Tiles_(Unicode_block) )

**Comment by plantvsbirds** [comment]
>  do you think we cannot do bitwise operations in js?

No need for this rhetoric. @Artoria2e5

**Comment by neruthes** [comment]
Hope the standard can be finalized quickly. Also, I recommend using names like "Base65536Hanzi" and "Base4096Hangul". For this case, it would be "Base256Emoji".

**Comment by Tedko** [comment]
Why not base 1024Emoji

**Comment by neruthes** [comment]
> Why not base 1024Emoji
> […](#)

It will be good if we have more than 1024 options for the emojibet. In that case, call "Base1024Emoji".

**Comment by Tedko** [comment]
> Also I want to remind folks here @SunriseFox @Artoria2e5
> 
> There are many unicodes are widely used as symbols and are not selected as part of the Emoji based on very random reason, such as Mahjong Titles [Wiki](https://en.wikipedia.org/wiki/Mahjong_Tiles_(Unicode_block)); U+1F000..U+1F02F
> (48 code points) -- Surprise, only one of these is in Emoji;
> If we consider these Unicode Block, we will find lot more Emoji-like Unicode, and are supported widely in various platforms, such as [Modifier Tone Letters](https://en.wikipedia.org/wiki/Modifier_Tone_Letters) & [Enclosed Alphanumeric Supplement](https://en.wikipedia.org/wiki/Enclosed_Alphanumeric_Supplement) etc.
> 
> You may find all Unicode Symbols here: [Wiki](https://en.wikipedia.org/wiki/Unicode_symbols) -- I think most of these will be add into Emoji later as well. If we count these in (most of them are one-bit), we will double or triple the code for encoding.

@neruthes  We have more than Emoji.

**Comment by Artoria2e5** [comment]
I think I listed a bunch of ranges two months ago:

```
possible ranges :/
2700	27BF
2600	26FF
1F30D	1F5FA
1F90F	1F9DD
1F680	1F6D5
1F6E0	1F6EC
1F6F0	1F6FA
FE30	FE4F
AC00	D7A3 // precomposed hangul, so no
3200	321E // boxed..
3220	32FF
2460	24FF
1F100	1F10C
1F110	1F16C
1F170	1F1AC // ^ boxed
```

**Comment by Tedko** [comment]
BTW, we're not limiting Base-Emoji to Maskbook on Twitter. we can use it for Tessercube or on fb as well.

**Comment by neruthes** [comment]
Sure, it should be a stand-alone project. It will be good if these documents may be drafted at <https://github.com/cyberparliament/parentless-documents>.

**Comment by neruthes** [comment]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/2139261/70234900-9f474e00-1759-11ea-861a-41bfdeb249da.png">

🤔

**Comment by Jack-Works** [comment]
what to do if the platform bans some emoji?

**Comment by Tedko** [comment]
> what to do if the platform bans some emoji?

I don't think they will do so...

**Comment by Tedko** [comment]
> <img alt="image" width="322" src="https://user-images.githubusercontent.com/2139261/70234900-9f474e00-1759-11ea-861a-41bfdeb249da.png">
> 
> 🤔

Interesting...

**Comment by neruthes** [comment]
> what to do if the platform bans some emoji?



> <img alt="image" width="322" src="https://user-images.githubusercontent.com/2139261/70234900-9f474e00-1759-11ea-861a-41bfdeb249da.png">
> 
> 🤔

```
[
0x1F30D-0x1F5FA,
0x1F90F-0x1F9DD,
0x1F680-0x1F6D5,
0x1F6E0-0x1F6EC,
0x1F6F0-0x1F6FA
]
```

This range includes 1062 code points.

**Comment by neruthes** [comment]
> what to do if the platform bans some emoji?

Then fallback to another encoding.

Base16777216Emoji can be equivalent to Base4096Hangul in terms of efficiency as long as each emoji is considered 2 characters on Facebook and Twitter.

If bio with a Base16777216Emoji string cannot be saved, then fallback to Base4096Hangul; then Base64; finanlly Hex.

**Comment by Jack-Works** [comment]
> > what to do if the platform bans some emoji?
> 
> Then fallback to another encoding.
> 

So how do you know they _will_ ban this encoding?

**Comment by neruthes** [comment]
> So how do you know they will ban this encoding?

Save event error...?

**Comment by Tedko** [comment]
Again, I don’t think they will ban emoji this early.

**Comment by Jack-Works** [comment]
> > So how do you know they will ban this encoding?
> 
> Save event error...?

They will not send us a JS level _event_. We're not calling the API to post words

**Comment by OiCkilL** [comment]
I think `CJK chars` is better than `Base-emoji` in reading. Like `佛论禅` in Chinese.
Emoji in some OS Platform, Color will be attracted focus.

**Comment by neruthes** [comment]
> I think `CJK chars` is better than `Base-emoji` in reading. Like `佛论禅` in Chinese.
> Emoji in some OS platform, color will be attracted focus.
> And some website, Can't recognize emoji is very common.

You may be interested in https://github.com/DimensionDev/Tessercube2-Meta-RFC/issues/5

**Comment by OiCkilL** [comment]
> > I think `CJK chars` is better than `Base-emoji` in reading. Like `佛论禅` in Chinese.
> > Emoji in some OS platform, color will be attracted focus.
> > And some website, Can't recognize emoji is very common.
> 
> You may be interested in [DimensionDev/Tessercube2-Meta-RFC#5](https://github.com/DimensionDev/Tessercube2-Meta-RFC/issues/5)

Cool, looks interesting.

**Comment by clearloop** [comment]
What about encoding the `payload` into images(like QRcode)? And this is unlimited art.

**Comment by Tedko** [comment]
Image based payload is already delivered. Click on the extension icon you
will see ‘enable image based payload’

**Comment by clearloop** [comment]
## base1024

```
2^24 = 2^6^4 = 2^8^3 = 2^12^2
```

**Comment by septs** [comment]
Replaced by #1139
