### ISSUE TITLE
[Bug] Twitter post sent from Firefox failed to decrypt on Chrome

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#1391]
# Bug Report
Twitter post sent from Firefox failed to decrypt on Chrome

### System

- OS: macOS Catalina
- OS Version: 10.15.1 

### Browser

- Browser: chrome 84.0.4147.10, firefox 79.0

### Maskbook

- Maskbook Version: 1.13.1 for both chrome and firefox
- Installation: Browser extension

### Expected Behavior

/* Write the expected behavior here. */
Decrypted on both browser

### Actual Behavior

/* Write the actual behavior here. */
Only Decrypted on firefox, but not on Chrome
### How To Reproduce

/* Specify how it may be produced here. */

1. Prepare two twitter accounts to follow each other, account A on chrome, account B on firefox.
2. Compose the post with 'Followers of CurrentAccount'

![image](https://user-images.githubusercontent.com/63733714/89123852-0eea2480-d505-11ea-8b24-eddb62ed8bbe.png)
![image](https://user-images.githubusercontent.com/63733714/89123865-245f4e80-d505-11ea-9761-a016f2e76495.png)

3. Verify the result:

![image](https://user-images.githubusercontent.com/63733714/89123883-4bb61b80-d505-11ea-8a5e-28a1e52fd6aa.png)
![image](https://user-images.githubusercontent.com/63733714/89123890-5e305500-d505-11ea-9ca9-615298cd62d6.png)

**Comment by zhouhanseng** [comment]
Not sure is this caused by the 'hanchengtest' is newly registered, and twitter noticed me that some functionality may be limited.

**Comment by zhouhanseng** [comment]
Not sure if this caused by the account 'hanchengtest' is newly registered, and twitter noticed me that some functionality may be limited.

**Comment by jk234ert** [comment]
This issue **could be reproduced** even under following setup:
1. Same maskbook persona with the same Twitter account connected
2. Same bio
3. Composing messages with recipient set to only "Myself"

**Comment by neruthes** [comment]
Really strange. Thanks for reporting. 🤔

**Comment by Tedko** [comment]
@zhouhanseng can you still reproduce?

**Comment by Tedko** [comment]
@zhouhanseng can you still reproduce?

**Comment by zhouhanseng** [comment]
Unable to develop on Firefox, I had reported this issue to jack.

**Comment by zhouhanseng** [comment]
@Tedko I can still reproduce this.

**Comment by Tedko** [comment]
@Jack-Works any idea?

**Comment by Jack-Works** [comment]
I'll fix firefox version later

**Comment by Tedko** [comment]
@zhouhanseng @Jack-Works  can we still reproduce?

**Comment by zhouhanseng** [comment]
Still can reproduce when select specific contacts in 1.19.6, neither firefox => chrome nor chrome => firefox failed.

The fingerprint is wrong, and can't get it right through reinstall or reconnect.

firefox:

![image](https://user-images.githubusercontent.com/63733714/100609872-b3f8fa80-3349-11eb-94ec-53fc1671ff2a.png)


chrome:

![image](https://user-images.githubusercontent.com/63733714/100609903-c2dfad00-3349-11eb-8276-e9abefd57662.png)

**Comment by Tedko** [comment]
@Jack-Works @septs  take a look. seems bug on ourside

**Comment by Tedko** [comment]
@zhouhanseng try this?

 firefox => ios(webview)
 firefox => android (gecko which is also ff)

**Comment by zhouhanseng** [comment]
All failed (install maskbook from App Store and google play store)

Suji Yan <notifications@github.com> 于2020年12月3日周四 上午1:17写道：

**Comment by Tedko** [comment]
@Jack-Works @zhouhanseng @guanbinrui  this's a priority0 task. Expect to fix in early days of this week

**Comment by Jack-Works** [comment]
failed to reproduce.

![image](https://user-images.githubusercontent.com/5390719/102181805-37881f00-3ee6-11eb-9f5a-825fdf015c1a.png)

**Comment by zhouhanseng** [comment]
failed to reproduce.

<img src="https://user-images.githubusercontent.com/63733714/102313657-0114d780-3fac-11eb-9dde-f16ba163af3e.png" width=600 />
<img src="https://user-images.githubusercontent.com/63733714/102313680-0d993000-3fac-11eb-9933-3268e4ca44b1.png" width=600 />
