### ISSUE TITLE
[Demand] Plugin: Trader

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1399]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

A user can trade immediately under a Post.

## Prototype Overview

![image](https://user-images.githubusercontent.com/2139261/90384502-2e3e9100-e071-11ea-9f84-2600f79e3eb9.png)

![image](https://user-images.githubusercontent.com/2139261/90384658-7067d280-e071-11ea-9de9-06bf825594bc.png)

## Composition (Suspended)

This Plugin creates posts with its custom type.

The user must select a target token.

The user can optionally provide a suggested input amount.

## Post Text Template (Suspended)

```
Install ${some_url} to buy ${token_name}.
```

## View Snippet (Suspended)

The user can see a Snippet below the post.

## Post Text Markup Link

This Plugin matches `\$[A-Z]{3,4}` substrings and replaces them with an anchor.

By clicking the anchor, the Plugin Screen Modal (PSM) will be opened.

## Post Text Hover Card

When hovering the link, a floating card will appear next to it, in order to offer a preview. For cursorless screens, tapping the link should invoke this card. There should be an entry to invoke the PSM in this card for compatibility purposes.

In the card, the content includes:

- Price History Graph Section
  - Vendor selection tabs
  - Graph display area
  - Base currency selection dropdown menu
  - Time scope selection tabs (1D, 1W, 1M, 3M)

- Trading Section
  - List of platforms
    - Platform icon
    - Platform name
    - Platform price
    - Button to trade (Postponed to Stage 2)

## Non-User View

For users who are not Maskbook users, they will see a URL starting with a special search string.

### View Price History (K-Graph)

The K-Graph of the trading pair is shown.

### Change Base Currency

The user may change the base currency. This is made persistent in the database.

### Trade (Postponed to Stage 2)

The viewing user can trade within the Plugin Screen Modal.

- Bob selects a trading platform (if not selected in the hovercard).
- Bob sets an amount.
- Bob clicks the "Trade Now" button.
- The Plugin asks Bob to select a Wallet.
- Bob selects a Wallet and clicks "Use This Wallet".
- The Plugin generates a Smart Contract Invocation Signing Request.
- Maskbook asks Bob if he wants to authorize the request.
- Bob authorizes the request.
- Maskbook completes the invocation.
- Bob waits processing time.
- Maskbook notifies the Plugin upon success.
- The Plugin notifies Bob that the trade is successful in the Snippet.
- The Plugin sends Bob a Notification. (When we have Notification Center someday in future.)

## Dependencies

- #1415
- https://confluence.dimension.chat/x/nIEf 

## Notes

- None.

**Comment by tzhan28** [comment]
WIll provide a more detailed proposal in a few days, cheers

**Comment by Tedko** [comment]
These might be helpful:
- https://uniswap.org/blog/ipfs-uniswap-interface/
- https://twitter.com/UniswapProtocol/status/1108241985977094145 Done by https://twitter.com/androolloyd

**Comment by Tedko** [comment]
Also we can try make this into a bounty for our community

**Comment by yisiliu** [comment]
We will use https://www.coingecko.com/en/api and https://pro.coinmarketcap.com/ as our trading platform providers.

**Comment by guanbinrui** [comment]
> helpful

More widget:

+ https://www.coingecko.com/en/widgets
+ https://coinmarketcap.com/widget/
+ https://coinlib.io/widgets?w_single_coin_id=859&w_single_pref_coin_id=1505&w_single_width=250&w_all_theme=Dark#w_single
+ https://coinstats.app/en/widgets
+ https://www.coinlore.com/crypto-widgets
+ https://www.tradingview.com/widget/crypto-mkt-screener/
+ https://co-in.io/crypto-price-widget/

**Comment by jk234ert** [comment]
Close this issue since the trader plugin is already published
