### ISSUE TITLE
[Feasibility Check] Cooperative friendship discovery mechanism

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#14]
I wish that we can have un thorough and in-depth review on the proposed [cooperative friendship discovery mechanism](https://github.com/project-maskbook/Maskbook/wiki/Cooperative-friendship-discovery-mechanism) before @jack-works coding it into reality. Commentaries from @yisiliu and @mindey are especially expected.

Thanks all.

**Comment by yisiliu** [comment]
In ```Bob sends the signed certificate payload (E.pub + ECDH_Enc(Cert, E.pri, A.pub)) to a cache node.``` , there is an integrity issue since only ```Cert``` has been signed but not the entire message.

**Comment by yisiliu** [comment]
By ephemeral-static ECDH, we cannot ensure forward secrecy. Also, we cannot thereby prevent the middle-man attack.
