### ISSUE TITLE
[Demand] Feedback in Dashboard

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1400]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=356%3A713
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

A user should be able to submit feedback in Dashboard.

### Template

```
From: "Maskbook Support" <support@maskbook.com>
To: "%NAME%" <%EMAILADDR%>
Bcc: {some_internal_maillist_address}
Subject: Your feedback is received


Hi %NAME%,

Your feedback is received. We appreciate your patience and will be responding quickly.

Your original message is attached below. If there is any information to add, you may reply this mail.

------

> %NAME% (%EMAILADDR%) wrote on %DATETIMEUTC%:
> %MESSAGE%
```

### Variables

Variable | Example | Description
--- | --- | ---
DATETIMEUTC | 1984-01-24 09:41 (UTC) | The time of reception. The precision level is minute. Use UTC timezone.

## Subtasks

Task | Assignee | Completed?
--- | --- | ---
Feedback Privacy Policy | @neruthes |

## Notes

- None.

**Comment by septs** [comment]
i want to solve this problem.

**Comment by septs** [comment]
@neruthes i think `Name` field are not needed

**Comment by septs** [comment]
![SequenceDiagram1](https://user-images.githubusercontent.com/3842474/90093874-21632a00-dd5f-11ea-8ec0-c791213821fe.png)

first draft (sequence diagram)

**Comment by septs** [comment]
@neruthes design a receipt mail template.
tell users that we have received

the feedback interface maybe need a `Upload Debug Info` button.

**Comment by Tedko** [comment]
The easiest way for now @septs 
ignore the UX. use a mailto link ; fix this issue later-

mailto info@dimension.im

**Comment by Tedko** [comment]
for next ver - mailto info@dimension.im
for next next ver or later. use https://github.com/DimensionDev/Maskbook/issues/1400#issuecomment-673245507

**Comment by Tedko** [comment]
@septs @zhouhanseng 
We cant leave a buggy feedback there!
options:
1. just  mailto info@dimension.im
2. fix the whole feedback loop asap.

TBH lets do 1 to save some time. I will leave this to @zhouhanseng for now.

@septs Respond the [AT] msg accordingly pls

**Comment by Tedko** [comment]
tested. the `mailto:` is working
