### ISSUE TITLE
[Demand] UX minor adjustment on Extension Dropdown Menu

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1403]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=1165%3A1293
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

Minor UX adjustment.

## Components

![image](https://user-images.githubusercontent.com/2139261/89266509-87e09d80-d625-11ea-9718-e0f89f9e9c30.png)

### Title

The title is changed to "Current Persona" when there is an active Persona for the SNS.

### Clicking

There will no longer be any clicking effect when clicking the Persona summary.

## Notes

- The list of Personas is reduced to a single Persona summary item.

**Comment by Tedko** [comment]
how to deal with multiple personas on one SNS?

<img width="1364" alt="Screen Shot 2020-09-05 at 17 19 41" src="https://user-images.githubusercontent.com/6687437/92302117-14bba580-ef9c-11ea-885e-c267f590824d.png">

**Comment by neruthes** [comment]
You can switch persona when composing a post.

**Comment by Tedko** [comment]
> You can switch persona when composing a post.

should user able to decrypt a post to A even if its for B (also persona on the same browser)?

**Comment by neruthes** [comment]
> > You can switch persona when composing a post.
> 
> should user able to decrypt a post to A even if its for B (also persona on the same browser)?

Yes. If the user has both Alice and Bob in the Maskbook client, the user should be able to decrypt a Post (which is shared exclusively to Alice) when the currently logged-in profile belongs to Bob.

**Comment by Tedko** [comment]
will close for now and deal w/ ```switch persona when composing a post.``` later
