### ISSUE TITLE
[Demand] Establish presence in stores which we are yet not ready to publish on

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1404]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

We should establish the presence of the name "Maskbook" in certain software distribution platforms where name collision might happen future, as a way to avoid unnecessary disputes with other developers.

## List of Stores

- Mac App Store
- Safari Extension
- Windows Store

## Notes

- The list may need amending.
- Since we can implement mobile apps with webview/geckoview solutions, it is possible that we can do the same on Mac OS X and Windows.

**Comment by Jack-Works** [comment]
> Ubuntu APT Source / WinGet

Why would you distribute a browser extension to Linux / Windows package manager? If so, should we also add it to AUR (Arch Linux), scoop (Windows), and choco(Windows)? That makes no sense to me. Further, `npm` `cargo` `pip` `Windows PowerShell Gallery` would you like to add them all?

**Comment by neruthes** [comment]
> 
> 
> > Ubuntu APT Source / WinGet
> 
> Why would you distribute a browser extension to Linux / Windows package manager? If so, should we also add it to AUR (Arch Linux), scoop (Windows), and choco(Windows)? That makes no sense to me. Further, `npm` `cargo` `pip` `Windows PowerShell Gallery` would you like to add them all?

Good point. This is removed from the list.
