### ISSUE TITLE
[Demand] New Dashboard E2E Cases

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1410]
## Introduction

We had got many failures on the Wallets panel so we should add more test cases for Dashboard.

## New Cases

+ Create / Read / Import wallet
+ Add / Edit / Search contact

**Comment by yisiliu** [comment]
@neruthes Can you provide more user stories for testing on this part?

**Comment by neruthes** [comment]
> @neruthes Can you provide more user stories for testing on this part?

I will be working on this in upcoming days.
