### ISSUE TITLE
[Bug] Strange Persona Count

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1429]
# Bug Report 

### System

- [x] Windows
    - OS Version: Windows 10, 2004

### Platform/Browser

- [x] Firefox
  - Maskbook Version: 1.13.4
  - Browser Version: *

### Build Variant

- Where do you get Maskbook? 
  - [x] Store

### Actual Behavior

![image](https://user-images.githubusercontent.com/2139261/90121807-fb805a00-dd4b-11ea-85fb-c81984936922.png)

### Expected Behavior

The Persona count should be 1. 

![image](https://user-images.githubusercontent.com/2139261/90121980-32567000-dd4c-11ea-81aa-c6e33debefa8.png)

**Comment by Tedko** [comment]
Is 21 your contacts count?

**Comment by guanbinrui** [comment]
For now, this count accumulate by

+ the initialized personas count
+ the uninitialized personas count (It's a BUG fixed by [67919560d72f092a5fb04fbf77023a9b61c34837](https://github.com/DimensionDev/Maskbook/pull/1425/commits/67919560d72f092a5fb04fbf77023a9b61c34837))
+ others personas count (the current DB have got the private key)

**Comment by neruthes** [comment]
> 
> 
> Is 21 your contacts count?

No.

**Comment by neruthes** [comment]
> 
> 
> For now, this count accumulate by
> 
>     * the initialized personas count
> 
>     * the uninitialized personas count (It's a BUG fixed by [67919560d72f092a5fb04fbf77023a9b61c34837](https://github.com/DimensionDev/Maskbook/pull/1425/commits/67919560d72f092a5fb04fbf77023a9b61c34837))
> 
>     * others personas count (the current DB have got the private key)

Is this related to #1337?

**Comment by guanbinrui** [comment]
> > For now, this count accumulate by
> > ```
> > * the initialized personas count
> > 
> > * the uninitialized personas count (It's a BUG fixed by [67919560d72f092a5fb04fbf77023a9b61c34837](https://github.com/DimensionDev/Maskbook/pull/1425/commits/67919560d72f092a5fb04fbf77023a9b61c34837))
> > 
> > * others personas count (the current DB have got the private key)
> > ```
> 
> Is this related to #1337?

Yep, the second one is the dirty data.
