### ISSUE TITLE
[Bug] Unrelated profiles should not be recorded

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1430]
# Bug Report 

### System

- [x] Windows
    - OS Version: Windows 10, 2004

### Platform/Browser

- [x] Firefox
  - Maskbook Version: 1.13.4
  - Browser Version: *

### Build Variant

- Where do you get Maskbook? 
  - [x] Store

### Actual Behavior

Many "unrelated" profiles are recorded in the database. This will unnecessarily increase the database size.

(I suspect that this is the reason why @tedko often experience lagging and crashing.)

### Expected Behavior

A profile (Bob) should be recorded on witnessing (Alice) only if any statement is true:

- Bob is following Alice (Twitter-like SNS).
- Alice is following Bob (Twitter-like SNS).
- Alice and Bob are friends (Facebook-like SNS).

**Comment by Tedko** [comment]
Eventually #Maskbook will record all of these. (For growth and more reasons) For now not sure why we encountered the lag

**Comment by guanbinrui** [comment]
> Eventually #Maskbook will record all of these. (For growth and more reasons) For now not sure why we encountered the lag

The DB size is the main reason.

**Comment by guanbinrui** [comment]
> (I suspect that this is the reason why @Tedko often experience lagging and crashing.)

The DB size is the main reason. It happens when the UX part queries DB too frequently.

> Eventually #Maskbook will record all of these. (For growth and more reasons) For now not sure why we encountered the lag

Maybe we should hide these unrelated profiles in the contact list.

**Comment by neruthes** [comment]
> 
> 
> > (I suspect that this is the reason why @Tedko often experience lagging and crashing.)
> 
> The DB size is the main reason. It happens when the UX part queries DB too frequently.
> 
> > Eventually #Maskbook will record all of these. (For growth and more reasons) For now not sure why we encountered the lag
> 
> Maybe we should hide these unrelated profiles in the contact list.

Hiding in the UI should be good, as long as these surplus profiles do not significantly impact the performance.

Also uncount these unrelated profiles when importing and exporting the database.
