### ISSUE TITLE
[Demand] Settings page: Experimental Features

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1437]
## Catalogue

- [x] UI/UX

## Part 1: Introduction and Background

Sometimes we may want to include experimental features in public releases.

## Part 2: Problem to Solve

Some features need a global config flag to determine whether it should be enabled.

## Part 3: Expected Behavior

This boolean flag will be added as the first item in the "Advanced" section.

![image](https://user-images.githubusercontent.com/2139261/90391380-947ce100-e07c-11ea-8e78-e08dd9836fb9.png)

Field | en | zh
--- | --- | ---
Title | Experimental Features | 實驗型特性
Description | Preview experimental features before they are stable. | 在實驗性功能穩定之前先行預覽。

Each feature has its own strategy on its visibility and this boolean flag is only one parameter.

## Notes

- None.

**Comment by Tedko** [comment]
will come back later
