### ISSUE TITLE
[Bug] Compiling after saving code close firefox unexpectedly 

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#1443]
# Bug Report 
Video record: https://www.dropbox.com/s/vayt2z7kf6tf222/Screen%20Recording%202020-08-18%20at%204.57.16%20PM.mov?dl=0

### System
- [x] Mac OS X
    - OS Version: Catalina 10.15.5
### Platform/Browser
- [x] Firefox
  - Maskbook Version: 
  - Browser Version: 79.0 (64-bit)
### Build Variant

- Where do you get Maskbook? 
  - [ ] Store
  - [ ] ZIP
  - [X] Self-Compiled
    - Build Commit: master [@74ed2261](https://github.com/DimensionDev/Maskbook/tree/74ed226165db868a879e5558df8109461fce9241)

**Comment by neruthes** [comment]
Such strange... 🤔

**Comment by septs** [comment]
the project not use _hot module reload_, plz manual refresh.

**Comment by Jack-Works** [comment]
since it has crashed the browser I think you should file the bug to the Firefox issue cracker

**Comment by zhouhanseng** [comment]
Hot module works well on http://localhost:8080/webpack-dev-server/
