### ISSUE TITLE
[Talk] Export module from index.ts using asterisk wildcard

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#1445]
## Inroduction and Background

I started to read the project. In [InjectedComponents/PostDialog.tsx](https://github.com/DimensionDev/Maskbook/blob/f422b63170ce0fb97778d901de7c96c665367b89/src/components/InjectedComponents/PostDialog.tsx#L22), I tired to find where's the declaration of type `Profile`.

I checked the `database/index.ts`:
```ts
import './migrate/index'
import './tasks/index'
export * from './helpers/avatar'
export * from './helpers/group'
export * from './Persona/helpers'
export * from './Persona/types'
```
I lost myself here. I think we can export module explicitly to make the code more readable:

```ts
import './migrate/index'
import './tasks/index'
export { AvatarRecord, AvatarDBSchema, createAvatarDBAccess } from './helpers/avatar'
export { Group } from './helpers/group'
export { profileRecordToProfile } from './Persona/helpers'
export { Profile } from './Persona/types'
```

**Comment by Jack-Works** [comment]
In the editor with fully TypeScript support you can let the editor suggest what things you can import from it and use jump to definition to see where it is defined.

**Comment by septs** [comment]
plz use https://aka.ms/vscode, thanks.

**Comment by Jack-Works** [comment]
Or any other IDEs that supports language service protocol. You can get list at https://microsoft.github.io//language-server-protocol/implementors/tools/
