### ISSUE TITLE
[Bug] Strange scrollbar behavior

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1447]
# Bug Report 

### System

- [x] Windows
    - OS Version: 10, 2004

### Platform/Browser

- [x] Chrome
  - Maskbook Version: * 
  - Browser Version: *

### Build Variant

- Where do you get Maskbook? 
  - [x] CI

### Actual Behavior

In certain circumstances, the scroll bar my be flickering.

Tested in the `file-service` branch, when copying the FileKey.

**Comment by Tedko** [comment]
able to reproduce. tiny bug

**Comment by Tedko** [comment]
Another strange bug:

<img width="1421" alt="Screen Shot 2020-11-29 at 21 55 47" src="https://user-images.githubusercontent.com/6687437/100543993-e04f4100-328d-11eb-95c4-39a61719300a.png">
![Uploading Screen Shot 2020-11-29 at 21.55.39.png…]()


you will have this notif under the img payload

**Comment by septs** [comment]
Solution:
1. Redesign UI display method (Copy click before behavior).
2. Fix upstream library (Snackbar)

https://github.com/DimensionDev/Maskbook/blob/1cb97ec7383c472da31d552a23ec3566c80a3e11/packages/maskbook/src/plugins/FileService/components/Copyable.tsx#L26-L30

**Comment by septs** [comment]
CC @OiCkilL

**Comment by septs** [comment]
Move to #1975

**Comment by Tedko** [comment]
> Solution:
> 
> 1. Redesign UI display method (Click behavior). (fast)
> 2. Fix upstream library (Snackbar). (slower)
> 
> https://github.com/DimensionDev/Maskbook/blob/1cb97ec7383c472da31d552a23ec3566c80a3e11/packages/maskbook/src/plugins/FileService/components/Copyable.tsx#L26-L30

the fast way
