### ISSUE TITLE
 when `friends` is selected, specific friends in the list is not selected - causing confusion 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1448]
<img width="1432" alt="Screen Shot 2020-08-19 at 01 15 12" src="https://user-images.githubusercontent.com/6687437/90545926-f4c66c80-e1bb-11ea-82d4-464e47f663e5.png">
<img width="1432" alt="Screen Shot 2020-08-19 at 01 15 16" src="https://user-images.githubusercontent.com/6687437/90545927-f5f79980-e1bb-11ea-8b4c-252fe8f05314.png">

when `friends` is selected, specific friends in the list is not selected

### System

- [ ] Windows
    - OS Version:
- [ ] Mac OS X
    - OS Version:
- [ ] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [ ] Chrome
  - Maskbook Version: 
  - Browser Version:

- [ ] Firefox
  - Maskbook Version:
  - Browser Version:

- [ ] Android
  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook? 
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /* Optionally attach a Commit ID, if it is from an pre-release branch head */

### Actual Behavior

/* What happened? */

**Comment by neruthes** [comment]
Could you add some elaboration?

**Comment by neruthes** [comment]
I believe that changing from "Select Specific Friends" to "Extra specific users" will be good enough.

**Comment by Tedko** [comment]
Why not 'specific contacts' ?

**Comment by neruthes** [comment]
> 
> 
> Why not 'specific contacts' ?

Good.
