### ISSUE TITLE
[Demand] Component: WholePostView

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1450]
## Catalogue

- [x] UI/UX

## Part 1: Introduction and Background

#1360 

#1415

## Part 3: Expected Behavior

https://confluence.dimension.chat/x/nIEf

## Notes

- None.

**Comment by Jack-Works** [comment]
I'll start to explore the prototype of whole post view.

**Comment by guanbinrui** [comment]
close by #1458.
