### ISSUE TITLE
[Task] change image payload default text 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1460]
## Inroduction and Background
/* Describe the background of this task */

change it to 
```
This image is encrypted with #Maskbook (@realMaskbook) on {DATE}. 📪🔑

Install maskbook.com to decrypt it. 
```

## Content

/* Actual content here... */

**Comment by Tedko** [comment]
right now - https://github.com/DimensionDev/Maskbook/blob/master/src/_locales/en/messages.json

**Comment by Jack-Works** [comment]
> The serialization of DATE is defined as:
> 
> `yyyy-MM-DD hh:mm:ss`
> 
> For example:
> 
> `2020-08-22 09:41:00`

Please do not specify the date format. Use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString can make things easier since the time format isn't the important things to notice here.
