### ISSUE TITLE
[Demand] Switch to `npm`

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1466]
`yarn` package manager

`yarn` compare to `npm`, less functions

- `npm audit fix` (missing)
   https://classic.yarnpkg.com/en/docs/cli/audit/
   see https://github.com/yarnpkg/yarn/issues/7075
- `npm update` (no equivalent function)
   https://classic.yarnpkg.com/en/docs/cli/upgrade/
- npm dedupe (missing)
- npm prune (missing)

References: #696 #1324

**Comment by Jack-Works** [comment]
pnpm has those functions too. we have made a consensus about give pnpm a change before.

**Comment by septs** [comment]
`yarn` and `pnpm`, i think it is a community workaround.

**npm** official and did not it as **optional alternative solution** to **end user**.

**Comment by Jack-Works** [comment]
we **have made a consensus** to test if pnpm works well on other pkgs when we **have the bandwidth** for this.

not for now.

**Comment by Tedko** [comment]
not for now
