### ISSUE TITLE
Brand new "About" article

### ISSUE THREAD

**Issue by OiCkilL** [DimensionDev/Maskbook#1469]
## Inroduction and Background
Replace the old "About" article.
## Content
The new "About" article is here:
> Maskbook is a portal to the new, open internet. With Maskbook, you can send encrypted posts to your friends, participate in cryptocurrency lucky-draws, and share encrypted files on the platforms you are already using.

**Comment by Tedko** [comment]
We need other language version as well. 
For Japanese @blank71 @mizphses would you like to help us?  we will create a bounty program soon as well :)

**Comment by mizphses** [comment]
Here is the new translation file.
