### ISSUE TITLE
Refactor out the 'facebook.com' string literal

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#148]

**Comment by Tedko** [comment]
Abstraction will be helpful. After you guys have some discussion let's do it.

**Comment by Tedko** [comment]
Any update on this?

**Comment by neruthes** [comment]
Explain?

**Comment by SunriseFox** [comment]
I think it is ok as it does neither affect the user experience nor the development efficiency. So let's close this. If any updates, feel free to reopen it.
