### ISSUE TITLE
[Bug] Multiple payload pasted when composing encrypted post

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1483]
# Bug Report 

As the title. easy to reproduce 
<img width="1229" alt="Screen Shot 2020-08-28 at 01 00 53" src="https://user-images.githubusercontent.com/6687437/91472602-482a7000-e8ca-11ea-9e6d-77222b9974a5.png">

### System

- [x] Windows
    - OS Version:
- [x] Mac OS X
    - OS Version:
- [x] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [x] Chrome
  - Maskbook Version: 
  - Browser Version:

- [x] Firefox
  - Maskbook Version:
  - Browser Version:

- [ ] Android
  - Maskbook Version:
  - Android Version:

### Build Variant

- Where do you get Maskbook? 
  - [ ] Store

### Actual Behavior

/* What happened? */

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/91810905-48779200-ec61-11ea-801f-34b26aac35ff.png)

Cannot reproduce on 0159f2f4
