### ISSUE TITLE
[Demand] Red Packet minor text update

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1488]
## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background

![image](https://user-images.githubusercontent.com/2139261/91548560-14286c80-e915-11ea-852d-f205414afa88.png)

https://t.me/maskbook_group/10031

## Part 2: Problem to Solve

Reduce confusion.

## Part 3: Expected Behavior

Update the text template to "Expired" when the user fails to claim any share because the remaining share is 0.

## Notes

- Other ideas on the text template are welcomed.

**Comment by hging** [comment]
I want to claim the task.
I will submit some changes about this page.

**Comment by Tedko** [comment]
Thx @hging . Will review once u submit
