### ISSUE TITLE
[Discussion] embedded facebook pages handling logic

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#153]
Founded:

+ Clicking view-more link opens a new page instead of showing the full post. Workaround: if a new page is to be opend by an automated task, don't do that.

**Comment by Tedko** [comment]
suggestion: For now don't do that.
In future, figure out a new way to handle it. Hope we don't need to open up new tabs soon...

**Comment by SunriseFox** [comment]
Temporary solution: fix regex and prevent default behavior of its parent `<a>` tag.
