### ISSUE TITLE
[Bug] Display the failed text of setupGuide button incorrectly

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#1538]
# Bug Report 
![image](https://user-images.githubusercontent.com/63733714/92345650-c245ca80-f0fc-11ea-923b-96ff161e8087.png)

### System

- [ ] Windows
    - OS Version:
- [X] Mac OS X
    - OS Version:
- [ ] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [X] Chrome
  - Maskbook Version: 
  - Browser Version:

- [ ] Firefox
  - Maskbook Version:
  - Browser Version:

- [ ] Android
  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook? 
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /* Optionally attach a Commit ID, if it is from an pre-release branch head */

### Actual Behavior

/* What happened? */

**Comment by jk234ert** [comment]
@Jack-Works How about simply reducing the line-height of the text inside the button?

**Comment by Jack-Works** [comment]
Or maybe reduce the string length

**Comment by Tedko** [comment]
@zhouhanseng go ahead and try reduce the string leng

**Comment by neruthes** [comment]
It will be good if the error message can be moved away from the button text, e.g. a text label below the button. 🤔 

cc @OiCkilL

**Comment by zhouhanseng** [comment]
@Tedko The max length of english text is 23 to fit in one line. So how about 'Failed Please try again'

![image](https://user-images.githubusercontent.com/63733714/92879676-d0b71d80-f43f-11ea-82ee-579c332da7e9.png)

**Comment by jk234ert** [comment]
How about a "Failed icon"(maybe a `!`) on the left of the button, and simple "Retry" on the right?

**Comment by neruthes** [comment]
However, I do wonder why this operation might fail. It is a dialogue for the user to confirm whether the automatically detected username is correct and thereby giving the user a chance to correct the value. By confirming, the database will be updated.

In the process, I do not find a place for errors to occur. Can someone enlighten me on this?

**Comment by zhouhanseng** [comment]
@neruthes Don't worry, this error is only happened in my dev process, I deleted the database manually for some purpose.

**Comment by neruthes** [comment]
> 
> 
> @neruthes Don't worry, this error is only happened in my dev process, I deleted the database manually for some purpose.

In this case, I believe that the error message can be given through `window.alert` since users will not see this error.

**Comment by zhouhanseng** [comment]
@neruthes But user may see this error in other situations.

**Comment by neruthes** [comment]
> 
> 
> @neruthes But user may see this error in other situations.

For example?

**Comment by zhouhanseng** [comment]
@neruthes I don't know。。。

**Comment by neruthes** [comment]
> 
> 
> @neruthes I don't know。。。

Ok. We will be revising this decision when we find any example.
