### ISSUE TITLE
[Demand] Migrate to Ethers.js

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1545]
## Catalogue

- [ ] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background

```bash
> curl https://cdn.ethers.io/lib/ethers-5.0.umd.min.js -o ethers.min.js
> curl https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js -o web3.min.js

> ll -h

-rw-r--r--   1 xxx  staff   443K Sep  8 14:17 ethers.min.js
-rw-r--r--   1 xxx  staff   1.1M Sep  8 14:16 web3.min.js
```

## Part 2: Problem to Solve
https://github.com/ethers-io/ethers.js/

**Comment by guanbinrui** [comment]
The build size problem is huge released after we switched to ES modules (#372). I'm closing this issue because we may not resolve this in the short term.

**Comment by Jack-Works** [comment]
but we didn't switch to #372 based solution. maybe you mean #1644?

**Comment by guanbinrui** [comment]
Reopen if we need it in the future.
