### ISSUE TITLE
[Task] Multi-blockchain wallet support research

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1547]
## Inroduction and Background

We are planning to improve the Wallets system to provider better  coverage for some blockchains other than Ethereum.

## Content

- Macro logics
- Interaction Design Prototype

**Comment by Tedko** [comment]
#1722 will do a bounty with $SOL team

**Comment by aahutsal** [comment]
Why not use the `WalletConnect` protocol as the base?

**Comment by Tedko** [comment]
Will close this issue for now
