### ISSUE TITLE
[Bug] Fail to send Red packet on Maskbook mobile apps

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1549]
# Bug Report 

### System

- [ ] Windows
    - OS Version:
- [ ] Mac OS X
    - OS Version:
- [ ] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [ ] Chrome
  - Maskbook Version: 
  - Browser Version:

- [ ] Firefox
  - Maskbook Version:
  - Browser Version:

- [x] Android
  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook? 
  - [ ] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: 461bfdcc6f3202816850c899e06a22434440b34f

## Bug Info
Env: Rinkeby
When sending a new red packet, encounter error of `Failed to execute 'getAll' on 'IDBIndex': The transaction is inactive or finished.` 
Please refer to the detailed screenshots below:
<img width="1455" alt="Snipaste_2020-09-10_15-47-08" src="https://user-images.githubusercontent.com/7972003/92696795-f7f8e680-f37c-11ea-95ba-62392112875a.png">
<img width="1642" alt="Snipaste_2020-09-10_15-47-37" src="https://user-images.githubusercontent.com/7972003/92696800-faf3d700-f37c-11ea-9765-c1bc3a73d80d.png">
<img width="391" alt="Snipaste_2020-09-10_15-48-09" src="https://user-images.githubusercontent.com/7972003/92696833-08a95c80-f37d-11ea-9c83-80e8cf0cee3d.png">

### Actual Behavior

/* What happened? */

**Comment by Tedko** [comment]
i can reproduce on  mainnet --

![IMG_7948](https://user-images.githubusercontent.com/6687437/93301065-785e9200-f82a-11ea-97e1-cc1e2e5abdb5.PNG)

**Comment by Tedko** [comment]
@jk234ert any update here?

**Comment by jk234ert** [comment]
I think the latest version 1.16.3 has fixed this issue

**Comment by Tedko** [comment]
> I think the latest version 1.16.3 has fixed this issue

Seem like on iOS its still 1.15.4 now. waiting for store review?

**Comment by Tedko** [comment]
![photo_2020-11-03_02-06-33](https://user-images.githubusercontent.com/6687437/97903023-6359a600-1d79-11eb-882d-1abd03b69201.jpg)

**Comment by Tedko** [comment]
try to send 0.01eth Red packet. the tx went through but got this problem    (   https://github.com/DimensionDev/Maskbook/issues/1549#issuecomment-720636565 ).
ps tx: https://etherscan.io/tx/0xe3f4140269e61754f1553cbbc18a034608cdc68ce1dd330d0433cfb3cf339fab

**Comment by Tedko** [comment]
Tried 0.01 eth Redpack and went through. (ios latest testflight)
