### ISSUE TITLE
[Demand] Recipient selection feature simplification

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1570]
## Catalogue

- [ ] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background

The reliability of recipient selection feature has always been in difficulty. We will hide unreliable recipient options till they become reliable.

## Part 2: Expected Behavior

Only the following options will be available:

- Everyone
- Only Me
- Specific Users

This applies to both Facebook and Twitter.

## Notes

- This will postpone Cooperative Friendship Discovery Mechanism.
- This will postpone Saturation Key Retrieval Mechanism.

**Comment by Jack-Works** [comment]
Where is select specific friends?

**Comment by Tedko** [comment]
add back ```specific friends```

**Comment by neruthes** [comment]
> Where is select specific friends?

Missed it when writing. Included now.
