### ISSUE TITLE
[Bug] File-Service is buggy on Maskbook Mobile

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1574]
# Bug Report 

### System

- [ ] Windows
    - OS Version:
- [ ] Mac OS X
    - OS Version:
- [ ] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [ ] Chrome
  - Maskbook Version: 
  - Browser Version:

- [ ] Firefox
  - Maskbook Version:
  - Browser Version:

- [x] Android
  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version: 1.15.3
  - iOS Version: 1.15.3

### Build Variant

- Where do you get Maskbook? 
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /* Optionally attach a Commit ID, if it is from an pre-release branch head */

### iOS issues
- File View
  - [x] User cannot exit Arweave Preview page due to lack of a back button or gesture
  _**Fixed**_. By adding handling function to check if the destinated URL is inside our "external website list". If yes, present a SFSafariViewController to load the URL,  it comes with a built-in back button and has access to the system safari cookies & configuration.
  - [x] On Arweave Preview page, after clicking "Preview", only several file formats supported due to restriction of system WebView. After clicking "Save", users could not save anything to their local storage.
   _**Fixed**_. Similiar to the previous solution, the SFSafariViewController comes with a "share" button, which provides entry for user to share the file through system sharing feature.

- Compose File
  - [x] Nothing happens after picking files/images, the user could not send file-service payload message.
  - [x] "Not Supported" toast appears after clicking "Show More" button

**Comment by Tedko** [comment]
Tested on iOS. working well

**Comment by Tedko** [comment]
will close for now
