### ISSUE TITLE
Rationalise localization

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#158]
Some users reports say that Maskbook is being used in Hong Kong too. Looks like we can't just settle with a single `zh`: we need to add some subdivisions. While we are at it, we should also rationalize our localisation system.

- [ ] Use a proper library that has:
  - [ ] Plurals
  - [ ] Grammatical Gender
- [ ] Put it on a platform with Git hooks

* * *

I recommend Gettext/Jed if we want to put the thing on some translation platform immediately; i18next is sort of decent at that too. If we want something really good and powerful, however, I strongly recommend using [MessageFormat](https://messageformat.github.io/). Few platforms support it for now, but Weblate (WeblateOrg/weblate#2967) might do soon. There's some precedence of its adoption in the JS community by Angular folks, so we aren't doing anything crazy here.

I don't really care about what platform we use, although again I am strongly leaning Weblate. If we are using Crowdin, however, be sure to review everything and don't let these damned stale votes decide what strings to use.

PS: don't change the spelling mix

**Comment by neruthes** [comment]
Looks like we will do this in 2020 Q2.

**Comment by Artoria2e5** [comment]
Could be earlier if I ingest enough nootropics and plumb through the translate-toolkit stuff. I mean, I can do a non-weblate thing first...

**Comment by Jack-Works** [comment]
hey what about this lib @Artoria2e5 https://github.com/skolmer/es2015-i18n-tag
