### ISSUE TITLE
[Bug] Unable to locate MagicURL payload

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1584]
# Bug Report 

How to reproduce:
1. Post MagicURL like _

<img width="1332" alt="Screen Shot 2020-09-18 at 23 43 38" src="https://user-images.githubusercontent.com/6687437/93622321-80c3f200-fa0f-11ea-91b4-24a051e8e98b.png">

2.
<img width="1332" alt="Screen Shot 2020-09-18 at 23 43 50" src="https://user-images.githubusercontent.com/6687437/93622327-83bee280-fa0f-11ea-98d1-6eb3627fd848.png">

### System

- [ ] Windows
    - OS Version:
- [ ] Mac OS X
    - OS Version:
- [ ] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [ ] Chrome
  - Maskbook Version: 
  - Browser Version:

- [ ] Firefox
  - Maskbook Version:
  - Browser Version:

- [ ] Android
  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook? 
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /* Optionally attach a Commit ID, if it is from an pre-release branch head */

### Actual Behavior

/* What happened? */

**Comment by Tedko** [comment]
should be a quick fix @Jack-Works ?

**Comment by Tedko** [comment]
@zhouhanseng

**Comment by zhouhanseng** [comment]
I'd like to try it tomorrow since I'm solving a similar problem.

**Comment by zhouhanseng** [comment]
I turn off maskbook, try type ``` hhh \n Install google.com```, then `google.com ` does not display as well. So this is not our bug.

**Comment by Tedko** [comment]
This is our bug. We need to decrypt the content regardless how Twitter render it

**Comment by zhouhanseng** [comment]
The last words 'to decrypt it.' are deleted manually, yes?
