### ISSUE TITLE
[Bug] Multi tweet content showed, bug due to trading-view plugin

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1586]
# Bug Report 

https://twitter.com/defidude/status/1307874197583147008/photo/1
<img width="1423" alt="Screen Shot 2020-09-21 at 11 03 13" src="https://user-images.githubusercontent.com/6687437/93730176-0f946280-fbfa-11ea-89a8-923f2d608a44.png">

### System

- [ ] Windows
    - OS Version:
- [ ] Mac OS X
    - OS Version:
- [ ] Linux
    - Linux Distribution:
    - OS Version:

### Platform/Browser

- [ ] Chrome
  - Maskbook Version: 
  - Browser Version:

- [ ] Firefox
  - Maskbook Version:
  - Browser Version:

- [ ] Android
  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook? 
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /* Optionally attach a Commit ID, if it is from an pre-release branch head */

### Actual Behavior

/* What happened? */

**Comment by guanbinrui** [comment]
It looks like the original post didn't hide in yours. But I reproduce it in another way. The replacement post was injected twice if refresh the page while the photo was opening.

<img width="949" alt="reproduce" src="https://user-images.githubusercontent.com/52657989/94981692-d697ae80-0566-11eb-963a-8fb654232685.png">

**Comment by Tedko** [comment]
try fix? @zhouhanseng

**Comment by zhouhanseng** [comment]
@Tedko 
@guanbinrui and I can't reproduce it now.

**Comment by Tedko** [comment]
cant reproduce. Should be fixed already
