### ISSUE TITLE
UX bug for 'View / add recipients'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#159]
Version: Latest Chrome Store Ver.

How to reproduce:

Post sth, use 'View / add recipients' functionality and add some recipient.
- The recipient will show up twice during the 'sharing' (following 1st pic)
- The search box UX error - Can't search (2nd pic)

<img width="1440" alt="Screen Shot 2019-09-04 at 22 21 56" src="https://user-images.githubusercontent.com/6687437/64271733-6f2cbb00-cf70-11e9-97ca-dc0eca8a3427.png">
<img width="793" alt="Screen Shot 2019-09-04 at 22 16 38" src="https://user-images.githubusercontent.com/6687437/64271737-705de800-cf70-11e9-8d70-828401f8ebff.png">

**Comment by Tedko** [comment]
BTW is this component 'Compose Box'?

**Comment by SunriseFox** [comment]
While trying to fix this issue, another issue found:

+ the search input reveals event to facebook so triggers their shortcut
