### ISSUE TITLE
[Demand] Persona Backup UX Adjustment

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1618]
## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background

Some users have reported that they confused exporting Personas with creating database backups.

We will adjust the UX to address this challenge.

## Part 2: Expected Behavior

// TODO

## Notes

- None.

**Comment by Tedko** [comment]
will intro a quick fix first
