### ISSUE TITLE
[Demand] Generate Git info file in firefox store build

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1647]
see https://github.com/DimensionDev/Maskbook/pull/1644#pullrequestreview-499214848

**Comment by Jack-Works** [comment]
oh wait. maybe it is impossible. the build step requires build definitely same files, which is impossible when reviewer don't have a .git folder but CI have. @septs

**Comment by septs** [comment]
> oh wait. maybe it is impossible. the build step requires build definitely same files, which is impossible when reviewer don't have a .git folder but CI have. @septs

no, no, no

release bot, update version and update `git-info.json`

but the file only firefox build use it.

(this file can also tell us firefox build time)
