### ISSUE TITLE
[Bug] iOS bugs

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1668]
# Bug Report

- [x]  permission

![IMG_8295](https://user-images.githubusercontent.com/6687437/95021922-7f005c80-06a6-11eb-945c-a3c7a8ab2689.PNG)

require permission on mobile (which should not needed on iOS)

- [x] strange hinting color on compose box (not sure how to reproduce):

![IMG_8294](https://user-images.githubusercontent.com/6687437/95022039-37c69b80-06a7-11eb-9a48-2ee8e8e71962.PNG)

- [x]  strange hinting color on encrypted posts

![IMG_8293](https://user-images.githubusercontent.com/6687437/95022107-b4f21080-06a7-11eb-9346-c85742f03fd5.PNG)

cant read link/url or @ content due to strange hinting color.

- [x] rm the poll plugin or hide it since its still in beta

@jk234ert

**Comment by Tedko** [comment]
5. Auto paste still failed on iOS.

cc @jk234ert

**Comment by jk234ert** [comment]
@zhouhanseng 
Plz try to fix the issues listed above.
Remember to test on the desktop after modification to avoid the unexpected appearance.
