### ISSUE TITLE
[Bug] For the append recipient - should we able to add `everyone` ?

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1680]
# Bug Report

<img width="1391" alt="Screen Shot 2020-10-08 at 23 58 04" src="https://user-images.githubusercontent.com/6687437/95485568-82f0ef00-09c4-11eb-8a5d-de1998edea82.png">

```Add Eveyone in the {append recipient } part```

its technically doable. I guess we should do so as well. Take the reference from Wechat Moments --

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Jack-Works** [comment]
What do you mean by "Everyone"? Everyone in the group or literally "everyone" that installs Maskbook? AFAIK the latter one is not possible in the current mechanism

**Comment by Tedko** [comment]
> literally "everyone" that installs Maskbook?

```literally "everyone" that installs Maskbook?```

why? cant just add that AES key?

**Comment by Jack-Works** [comment]
> why? cant just add that AES key?

Share to someone and everyone have a significant difference in the payload.

**Comment by Tedko** [comment]
> > why? cant just add that AES key?
> 
> 
> 
> Share to someone and everyone have a significant difference in the payload.

Ok. Will need to upgrade later.
