### ISSUE TITLE
[Demand] Disable gundb related functions

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1698]
## Catalogue

- [ ] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Notes

Current gundb service stopped.

**Comment by septs** [comment]
see https://github.com/amark/gun/issues/1015

**Comment by Tedko** [comment]
> see [amark/gun#1015](https://github.com/amark/gun/issues/1015)

:( wait for his ver bump script?

**Comment by septs** [comment]
@Tedko flag-based hidden gundb related function on until gundb available again?

CC @yisiliu

**Comment by Tedko** [comment]
> @Tedko flag-based hidden gundb related function on until gundb available again?
> 
> 
> 
> CC @yisiliu 

Let's keep the server running.
