### ISSUE TITLE
[Bug] Tap "Close" button in dashboard leads to blank screen

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1699]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version: 1.16.5
  - iOS Version: 1.16.5

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
Step to reproduce:
1. Close & kill Mask Network iOS app if it is running.
2. Open Mask Network iOS app
3. Tap "Close" button in the top left corner
![Simulator Screen Shot - iPhone 11 - 2020-10-12 at 15 55 38](https://user-images.githubusercontent.com/7972003/95720411-c9d03480-0ca3-11eb-8deb-390c43799e45.png)

### Actual Behavior
A blank screen, users have to kill & re-open the app to continue.
![Simulator Screen Shot - iPhone 11 - 2020-10-12 at 15 55 48](https://user-images.githubusercontent.com/7972003/95720512-eb312080-0ca3-11eb-9877-1d8052fda990.png)

/_What happened?_/

**Comment by jk234ert** [comment]
@zhouhanseng The root cause of this issue is, when the app launched, the dashboard is the FIRST and ONLY "tab". The "close" button simply calls `window.close` to close the dashboard "tab", then there is only a blank view left.

A temp solution could be, when the user closes the dashboard, use "browser.tab.query" to check whether there is a fb/twitter tab left, if not, use "brower.tab.create" to create a FB(or twitter?) tab.

**Comment by zhouhanseng** [comment]
How about hiding the close button when there's no tab left?

**Comment by Tedko** [comment]
any update on this?

**Comment by jk234ert** [comment]
We moved back to the old implementation: Open FB website when you close the only dashboard tab.
This is still confusing, we are developing a new mobile UX (similar to friendly app) to completely fix all these weird UX
