### ISSUE TITLE
[Bug] The "Find your username" dialog in mobile apps need re-designed

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1703]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [x] Android

  - Maskbook Version: 1.16.5
  - Android Version: 1.16.5

- [x] iOS
  - Maskbook Version: 1.16.5
  - iOS Version: 1.16.5

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
Currently, the "Find your username" dialog appears when users navigate to the login page of Twitter/Facebook. This implementation has the following issues:
1. It blocks the login page, users could hardly do login with the dialog displays in front.
2. The description text in the dialog is confusing. It should be some hint text to lead users to finish the login steps.
3. Users could even input text into the dialog, and proceed without login any account. This would cause unexpected errors.

### Actual Behavior
![Simulator Screen Shot - iPhone 11 - 2020-10-12 at 15 56 47](https://user-images.githubusercontent.com/7972003/95721818-b6be6400-0ca5-11eb-985c-cb643079029b.png)

### Solution
@OiCkilL @xiazhiming 
We need to re-design the behavior & appearance.

**Comment by guanbinrui** [comment]
@OiCkilL has designed it before. Here it is [Mobile](https://www.figma.com/file/qsKvUPU1xQ9GmeVjEd0IGY/UIkit---Mobile?node-id=65%3A8265).

**Comment by jk234ert** [comment]
Let's divide this issue into the following modification requests:
- [ ] Make the username input field disabled before Maskbook could properly retrieve the logged-in username value.
- [ ] Change the title and hint text as following (all these text below are DRAFT version, list here as a sample ) :
   - [ ] Before username retrieved: 
           1. Title: "Looking for your username"
           2. Hint: "Maskbook needs the username ......, please sign in to connect your Profile to Maskbook Persona"
   - [ ] After username retrieved:
           1. Title: "Customize your username"
           2. Hint: "Please confirm your username, Maskbook will use this username to connect your Profile to Persona"

**Comment by Jack-Works** [comment]
In older version it can be folded
