### ISSUE TITLE
[Task] Split into multiple isolated packages and become monorepo?

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1710]
According to the discussion yesterday, splitting codebase into multiple isolated packages may help it easier to port maskbook core into other software, or improve the robustness of the software like what @septs did for the file service.

Should we do this in the future?

A question, which one to use?

1.  [yarn workspace](https://yarnpkg.com/features/workspaces) (+ [lerna](https://github.com/lerna/lerna)?)
2.  [pnpm workspace](https://pnpm.js.org/en/workspace) (+ [rush](https://github.com/microsoft/rushstack)?)

**Comment by septs** [comment]
i want to be a two subrepo, wallet + post transceiver.

**Comment by guanbinrui** [comment]
Vote yes for this. 

We should make some rules for those pkgs like a fixed prefix (maybe `@deimensiondev/mask-`) should be used in every pkg's name and what should have in each pkg (`docs/` `locales/` `src/` `test/` `README.md` etc).

Here is a simple list of pkgs I caught:

+ mask core pkgs
+ service pkgs (a service run in the background page)
+ helper pkgs
+ plugin pkg (a mask compatible plugin)
+ contract pkg (the pkg for ts typing declaration which could be generated by tools)

**Comment by septs** [comment]
@guanbinrui Can be turned into a shell application (Dependency inversion principle)

```
plugin/wallet
plugin/post-transceiver
plugin/...
```

**Comment by Jack-Works** [comment]
> I want to be a multi repo

Multiple repos are hard to use if you want to sync them.

> We should make some rules for those pkgs like a fixed prefix

I'm not mean by we _should_ publish those packages to some registry or something, it is used to "isolate" the unrelated parts in our program.

I'm also not suggesting we should move _everything_ into the monorepo (if they are really independent or unrelated to Maskbook).

**Comment by guanbinrui** [comment]
> Multiple repos are hard to use if you want to sync them.

`lerna` or `rush` ?

> I'm not mean by we should publish those packages to some registry or something, it is used to "isolate" the unrelated parts in our program.

Register free is OK. I think it's important to make some rules that every pkg adheres to.

> I'm also not suggesting we should move everything into the monorepo (if they are really independent or unrelated to Maskbook).

That makes sense.

**Comment by Jack-Works** [comment]
> `lerna` or `rush` ?

IIRC they both need all packages in the same repo
