### ISSUE TITLE
[Task] Publish unstable edition to Chrome Store (unlisted)

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1711]
Pre-work:
1. Modify release bot, add release to unstable branch function
2. Release first unstable edition to Chrome Store
3. Publish a Maskbook News, about the idea.

TODO:
1. unstable branch name need meet or vote.
2. release branch focus on "cumulative updates"?
3. unstable branch focus on "beta channel"?

**Comment by guanbinrui** [comment]
FYI: I have added a `build` field into the CI progress which could be `'stable' | 'beta' | 'insider'`.

**Comment by septs** [comment]
https://github.com/DimensionDev/browser-extension-action

**Comment by septs** [comment]
- [ ] Auto Build and Publish nightly edition maskbook at daily (UTC+0 00:00, UTC+8 08:00)
- [ ] Extension Name modify to `Maskbook (Nightly)`
- [ ] Maskbook Popup and Dashboard use nightly edition special logo (like Firefox nightly edition)
- [ ] Nightly edition, need legal document (may be)

**Comment by Tedko** [comment]
do u need admin account to do sth from my side?

**Comment by Tedko** [comment]
@OiCkilL need an icon etc for this

**Comment by OiCkilL** [comment]
![MB--Logo--Geo--ForceCircle--Nightly](https://user-images.githubusercontent.com/613988/98066855-37cade80-1e93-11eb-8881-2961f4aa682a.png)

[MB--Logo--Geo--ForceCircle--Nightly.zip](https://github.com/DimensionDev/Maskbook/files/5485388/MB--Logo--Geo--ForceCircle--Nightly.zip)

**Comment by septs** [comment]
Wait for OAuth Verification passed.
