### ISSUE TITLE
[Bounty] Subscan Improvement

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1724]
## Introduction and Background

Maskbook now supports a trader plugin where token market info would display when a user hover their mouse on a token hashtag starting with "$" on Twitter. It shows the price, trending, supporting exchanges and a Uniswap interface if there exists a swapping pair. [Subscan](https://polkadot.subscan.io/) is a block explorer in Polkadot network that work like Etherscan in Ethereum. In addition, Subscan supports multiple Parachains in Polkadot network so the UI differs a little bit than Etherscan. We believe it'll provide our users more info about Polkadot projects.

### Subscan API integration

Query Subscan API to get relevant information about a Polkadot project.

### Extra UI in Trader Plugin

Add the support to show extra information(TBD) in the trader view when detecting if it's a Polkadot project. This would further help users get richer information about a project and the entire Polkadot ecosystem. We believe this would also bring more incentives to the users to talk about Polkadot on Twitter.

## Deadlines

TBD.

**Comment by clearloop** [comment]
Mark

**Comment by yisiliu** [comment]
@clearloop interested?
