### ISSUE TITLE
[Demand] Link back to CMC

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1726]
## Catalogue

<img width="1416" alt="Screen Shot 2020-10-16 at 01 49 48" src="https://user-images.githubusercontent.com/6687437/96167427-f610dd00-0f51-11eb-974e-413a000b328d.png">

discussed with CMC, and would want to add:
click the line chart part -> jump to the CMC link of the token *(here $FIL )

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Tedko** [comment]
@zhouhanseng

**Comment by zhouhanseng** [comment]
kk

Suji Yan <notifications@github.com> 于2020年10月16日周五 下午9:42写道：

**Comment by guanbinrui** [comment]
@zhouhanseng CoinGecko should not able to jump.
