### ISSUE TITLE
[Demand] Uniswap Share Link

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1727]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Tedko** [comment]
any update?

**Comment by Tedko** [comment]
@guanbinrui @Jack-Works @septs update?

**Comment by guanbinrui** [comment]
Closed by #1772.
