### ISSUE TITLE
Transfer webpack web ext plugin to DimensionDev orgnization?

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#173]
@Tedko @neruthes

**Comment by Jack-Works** [comment]
@SunriseFox would you like to transfer the project to DimensionDev org or we make a fork in the DimensionDev?

**Comment by SunriseFox** [comment]
I think making a fork is better... to prevent unwanted updates or something

**Comment by Jack-Works** [comment]
Will use https://github.com/DimensionDev/webpack-web-ext-plugin as upstream later.

**Comment by Jack-Works** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/163/commits/803a0a44a55c2d53c9aa7c10d5a60693e1ad32bb
