### ISSUE TITLE
[Bug] Cannot encrypt post when chose only specific recipient

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1733]
# Bug Report

- [ ] Part1: Webcrypto bug #1734 

- [x] Part2: GunDB up again

- [ ] Part3: GunDB fix (upgrade to v2020 or bug fix from Mark side )

/_What happened?_/
<img width="356" alt="Screen Shot 2020-10-16 at 21 27 11" src="https://user-images.githubusercontent.com/6687437/96264118-70933880-0ff6-11eb-8fca-42410a7c16a4.png">

Can not encrypt post when chose only specific recipient. Can reproduce on the latest ver of FF & Chrome.

PS:
Should we cover this in our CI or QA process? @jk234ert 

### Platform/Browser

- [x] Chrome

  - Maskbook Version: 1.17.0
  - Browser Version:

- [x] Firefox

  - Maskbook Version: 1.17.2
  - Browser Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store

**Comment by Tedko** [comment]
related w/ #1698?

**Comment by Jack-Works** [comment]
> related w/ #1698?

Yeah of course

**Comment by Tedko** [comment]
> > related w/ #1698?
> 
> Yeah of course

<img width="490" alt="Screen Shot 2020-10-17 at 01 56 22" src="https://user-images.githubusercontent.com/6687437/96292533-f8d80480-101b-11eb-89a1-e95ac15d9b9a.png">

@septs @Jack-Works

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/blob/ce1126e3728b2830fe8fd469f269a669dd9b48d3/src/_background_loader.0.ts#L4-L4

but we're loading that lib, strange

**Comment by Tedko** [comment]
> https://github.com/DimensionDev/Maskbook/blob/ce1126e3728b2830fe8fd469f269a669dd9b48d3/src/_background_loader.0.ts#L4-L4
> 
> 
> 
> but we're loading that lib, strange

So part1 is ok and the only problem is gun?

**Comment by Jack-Works** [comment]
maybe we have both problem

**Comment by Tedko** [comment]
keep me posted for the fixing process

**Comment by Tedko** [comment]
any update? P1 issues need immediate fix

**Comment by Tedko** [comment]
tested on v1.18.2 on chrome and v 1.17.2 on iOS seems this is fixed already. Will close this and reopen if reproduced
