### ISSUE TITLE
[Bug] Cannot implement EC mechanism on Compose Recipient to specific people.

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1734]
![image](https://user-images.githubusercontent.com/3842474/96282601-84966480-100d-11eb-8aa3-e822c6ecab91.png)

**Comment by Jack-Works** [comment]
I will investigate this later.

**Comment by Tedko** [comment]
keep me posted

**Comment by Jack-Works** [comment]
fixed by #1753
