### ISSUE TITLE
[Bug] Mount point bug when composing on Fb

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1735]
# Bug Report

<img width="1331" alt="Screen Shot 2020-10-17 at 03 11 27" src="https://user-images.githubusercontent.com/6687437/96299591-e1eadf80-1026-11eb-91ac-bcbd3b867b03.png">
<img width="1331" alt="Screen Shot 2020-10-17 at 03 11 32" src="https://user-images.githubusercontent.com/6687437/96299595-e2837600-1026-11eb-8c5e-a5dabab2bbf6.png">

Once you have sth in the compose box the mount point of Mask compose box will disappear.

### Platform/Browser

- [x] Chrome

  - Maskbook Version: store
  - Browser Version:

- [x] Firefox

  - Maskbook Version: store
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Jack-Works** [comment]
I thought it is a feature?

**Comment by Tedko** [comment]
> I thought it is a feature?
umm I don't think so umm
