### ISSUE TITLE
[Demand] No need for `Default Wallet` any more?

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1736]
https://github.com/DimensionDev/Maskbook/issues/1090

With the current implementation seems no need for `Default Wallet` ?

## Catalogue

- [x] UI/UX

**Comment by xiazhiming** [comment]
的确没有默认这个需求。

**Comment by guanbinrui** [comment]
> 的确没有默认这个需求。

I'm removing this from UI.
