### ISSUE TITLE
[Bug] Import DB json file not working on Android Mask.io (blocked by Gecko)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1737]
# Bug Report

https://dimension.chat/group/maskbook-mobile?msg=KycCgrFZmzPLvDTdF

in short the android ver cannot import /restore json db properly 

video https://mega.nz/file/7wgCWKAA#LnLdyE-vYf7dKK6sH3mh4PxAtBDkIBZo0Tnpxre8jsA

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by jk234ert** [comment]
Strange behavior in importing backup files on Android geckoview. Need further investigation.

**Comment by Tedko** [comment]
@jk234ert any update?

**Comment by Tedko** [comment]
@jk234ert

**Comment by jk234ert** [comment]
> @jk234ert

It's caused by the new version of Android GeckoView, we are still working on it

**Comment by Tedko** [comment]
ok😂

**Comment by Tedko** [comment]
> > @jk234ert
> 
> It's caused by the new version of Android GeckoView, we are still working on it

can we downgrade or stay at a stable ver?

**Comment by Jack-Works** [comment]
> It's caused by the new version of Android GeckoView

Curious the reason

**Comment by jk234ert** [comment]
Sadly file Import & Export inside a browser extension has been buggy in GeckoView for a long duration.
On older version @Tlaster have developed a patch to resolve, we need to update the patch for the new GeckoView version.

**Comment by Tedko** [comment]
is upstream from Firefox accepting PRs 😂?

**Comment by Jack-Works** [comment]
looks like solved via patching
