### ISSUE TITLE
[Bug] iOS Mask Twitter hinting color bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1749]
# Bug Report

<img width="325" alt="Screen Shot 2020-10-20 at 00 40 26" src="https://user-images.githubusercontent.com/6687437/96480486-de489a00-126c-11eb-9823-54786e69daec.png">

The hinting color is buggy 

### System

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
assign to @zhouhanseng

**Comment by Tedko** [comment]
#1668

**Comment by zhouhanseng** [comment]
@Tedko  

@jk234ert and I still can't find the reason.

**Comment by Jack-Works** [comment]
@zhouhanseng maybe related to auto-theme detection (it might think current page is in the dark mode)

**Comment by zhouhanseng** [comment]
No, the normal color of text in dark mode is different from this color.

**Comment by Jack-Works** [comment]
Maybe you can print out the theme actually used to figure out why

**Comment by Tedko** [comment]
> @Tedko
> 
> @jk234ert and I still can't find the reason.

can u reproduce

**Comment by zhouhanseng** [comment]
> can u reproduce

no

**Comment by Tedko** [comment]
> > can u reproduce
> 
> 
> 
> no

On real iOS or simulator

**Comment by zhouhanseng** [comment]
simulator

**Comment by Tedko** [comment]
try real iOS

**Comment by Tedko** [comment]
@zhouhanseng

**Comment by Jack-Works** [comment]
Is the color overwritten by a Twitter CSS? Maybe we should try to open the ShadowRoot mode on iOS again
