### ISSUE TITLE
[Demand] When clicked copy wallet addr button, pop up `wallet addr copied` instead of `Done!`

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1750]
## Catalogue

The current one is not clear enough.

<img width="1549" alt="Screen Shot 2020-10-20 at 00 45 36" src="https://user-images.githubusercontent.com/6687437/96485735-3da7a980-126f-11eb-9491-645acff807c0.png">

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Tedko** [comment]
a good example

<img width="881" alt="96503439-d77a5100-1285-11eb-9178-71365243d4fb" src="https://user-images.githubusercontent.com/6687437/96503488-ec56e480-1285-11eb-83b1-5f0172df87d6.png">

**Comment by zhouhanseng** [comment]
assign to @zhouhanseng
