### ISSUE TITLE
[Bug] Need a `Copy` button when auto paste fail (especially for mobile maskbook)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1751]
# Bug Report
<img width="560" alt="Screen Shot 2020-10-20 at 00 43 12" src="https://user-images.githubusercontent.com/6687437/96488418-8b70e180-1270-11eb-803a-b5aad1f2ed94.png">

No way to copy it on mobile .

In the previous ver, iOS did create a popup can click `Copy` just 1-click 

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
A good example

<img width="881" alt="Screen Shot 2020-10-20 at 03 01 15" src="https://user-images.githubusercontent.com/6687437/96503439-d77a5100-1285-11eb-9178-71365243d4fb.png">

**Comment by zhouhanseng** [comment]
Assign to @zhouhanseng

**Comment by jk234ert** [comment]
@zhouhanseng 
1. Plz check why the dialog popup not correctly centered on mobile.
2. Consider adding a "Copy" action button?

**Comment by zhouhanseng** [comment]
done yesterday :  https://github.com/DimensionDev/Maskbook/pull/1757

BradGao <notifications@github.com> 于2020年10月21日周三 上午10:53写道：

**Comment by Tedko** [comment]
Merged and closed.

One question: the copy paste will not work for img payload right?

**Comment by zhouhanseng** [comment]
I will do some research.

Suji Yan <notifications@github.com> 于2020年10月21日周三 上午11:09写道：

**Comment by zhouhanseng** [comment]
Well, I find that we can copy the image just like the text, and will make a
PR next.

周汉成 <z308114274@gmail.com> 于2020年10月21日周三 上午11:12写道：

**Comment by zhouhanseng** [comment]
https://github.com/DimensionDev/Maskbook/pull/1763
