### ISSUE TITLE
[Bug] Fb `Red Packet` image payload is gray (blocked by Stego-JS)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1752]
# Bug Report
<img width="1549" alt="Screen Shot 2020-10-20 at 01 10 34" src="https://user-images.githubusercontent.com/6687437/96489801-814fe280-1272-11eb-80c3-01b1c7f6d21e.png">

Any specific reason?

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
any reason behind? @guanbinrui

**Comment by Jack-Works** [comment]
It deliberated hard-coded on Facebook but I'm not clear why. @guanbinrui left a comment in the code says:

> // ! the color image cannot compression resistance in Facebook

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/blob/7390500ffe0c5de9beb04f8f9cf3e67841558554/packages/maskbook/src/social-network-provider/facebook.com/tasks/uploadToPostBox.ts#L24-L24

**Comment by guanbinrui** [comment]
Wait for the new version of Stego-JS.
