### ISSUE TITLE
[Bug] Can't create Red Packet with Tether

### ISSUE THREAD

**Issue by moxis** [DimensionDev/Maskbook#1759]
# Bug Report

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [X] Firefox

  - Maskbook Version: 1.17.2
  - Browser Version: 81.0.2

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [X] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
I can't create a red packet that contains tether USDT. 

### Actual Behavior

|![image](https://user-images.githubusercontent.com/20289403/96626127-fbca4200-1306-11eb-9a3b-d0b7789ee085.png)|![image](https://user-images.githubusercontent.com/20289403/96626095-f0771680-1306-11eb-8513-a08a476e6c47.png)|
|---|---|

I'm not sure if this is related, but this is the error I am getting when I click send.
![image](https://user-images.githubusercontent.com/20289403/96627176-616afe00-1308-11eb-82e0-05c24de1ac53.png)

**Comment by jk234ert** [comment]
Thanks for your detailed issue information.
@guanbinrui

**Comment by Tedko** [comment]
@yisiliu

**Comment by guanbinrui** [comment]
Learn more [Tether contract source code](https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code).

**Comment by Tedko** [comment]
any update? @guanbinrui

**Comment by Tedko** [comment]
is this fixed? @guanbinrui

**Comment by Tedko** [comment]
Tested w/ MM wallet and internal wallet, seems this is not fixed:

<img width="1421" alt="Screen Shot 2020-11-01 at 03 50 27" src="https://user-images.githubusercontent.com/6687437/97788711-cc181580-1bf5-11eb-8dbe-2af76ce92b06.png">
<img width="1432" alt="Screen Shot 2020-11-01 at 03 52 59" src="https://user-images.githubusercontent.com/6687437/97788712-ccb0ac00-1bf5-11eb-8c7d-1d7e3d1b063b.png">

**Comment by Tedko** [comment]
should be bug from @yisiliu 's side

**Comment by Tedko** [comment]
@yisiliu @guanbinrui

**Comment by Tedko** [comment]
will have a speedy fix and upgrade on contract

**Comment by Tedko** [comment]
@yisiliu

**Comment by yisiliu** [comment]
@guanbinrui @septs

**Comment by Tedko** [comment]
tested again. not working. need a speedy fix @guanbinrui @jk234ert @septs @yisiliu 
<img width="1264" alt="Screen Shot 2021-01-17 at 16 49 22" src="https://user-images.githubusercontent.com/6687437/104835809-0c795c80-58e4-11eb-9042-c0b4fd83b63d.png">
