### ISSUE TITLE
Finish Firefox-Android Test by Sep 16

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#177]

**Comment by Jack-Works** [comment]
@Tlaster Any problem with Android version?

**Comment by Misaka-0x447f** [comment]
by Sep12？

**Comment by Misaka-0x447f** [comment]
This cannot be done by myself since I have no android device or enough memory to run Android Studio.

**Comment by Tedko** [comment]
> by Sep12？

Then by next Monday.
@asonmine will give you an extra Android device.

**Comment by Misaka-0x447f** [comment]
ok, ASAP, move to top of task list.

**Comment by Misaka-0x447f** [comment]
@Artoria2e5 So what is it?
