### ISSUE TITLE
[Bug] Add WalletConnect connection status

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1770]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info

<img width="1713" alt="Screen Shot 2020-10-22 at 21 42 33" src="https://user-images.githubusercontent.com/52657989/96953203-1aa52000-1523-11eb-89e9-0389ba2bee97.png">

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
Also MetaMask or should we do separate?

**Comment by Tedko** [comment]
lets prioritized this one @guanbinrui
