### ISSUE TITLE
[Demand] WalletConnet Mobile Linking

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1777]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Notes

Learn more https://docs.walletconnect.org/mobile-linking

**Comment by jk234ert** [comment]
A link generated by WalletConnect **without** a specific wallet looks like:
`wc:683A78D3-95A5-40F8-89CC-00387F0BE2F8@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=1be88ff699e2b32f97dbf7168ba47485dfc515712273a5d936cb99467eeefca3`

A link generated by WalletConnect that specified to connect to MetaMask looks like:
`https://metamask.app.link/wc?uri=wc%3Ac0535a0d-e54e-491a-90ac-93594c997eb9%401%3Fbridge%3Dhttps%253A%252F%252Fbridge.walletconnect.org%26key%3Dec3586d7c4793901617031c635347e5581df2eb0190cda49c300a2bdbb070fa3` 

JS side simply generates the URLs and call open(URL), then leaving the rest to mobile app native to handle.

https://docs.walletconnect.org/mobile-linking#wallet-support

**Comment by Tedko** [comment]
update? @septs @jk234ert

**Comment by jk234ert** [comment]
Please add the following wallet apps support in the next version @septs :
1. Rainbow
2. MetaMask
3. Trust
4. imToken

Because only the above four apps successfully connected on iOS in my test

**Comment by jk234ert** [comment]
Progress:
iOS:
- [x] Connet with other wallet apps
- [ ] Send tx to other wallet apps

Android:
- [ ] Connet with other wallet apps
- [ ] Send tx to other wallet apps

**Comment by septs** [comment]
@Jack-Works native code is un-done.
