### ISSUE TITLE
[Bug] Wrong theme color in light mode.

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1782]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

![theme](https://user-images.githubusercontent.com/52657989/97130727-2724b500-177d-11eb-8c3f-97da1a7be354.png)

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/blob/7fb6dd5b2c74c3627dafb9b4e37cff39818c3f9d/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx#L33-L33

Because you're using this

**Comment by Jack-Works** [comment]
The default table in the light theme should look like

![](https://user-images.githubusercontent.com/5390719/97135252-be443980-178a-11eb-92d7-97b7a9d099bd.png)
