### ISSUE TITLE
[Demand] A separate menu bar on mobile app

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1784]
## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
The current Mask Network mobile app is comprised of a bunch of WebViews. The app works as a mobile runtime of our JavaScript code, leaving all features implemented by the JavaScript code.

## Part 2: Problem to Solve
Our implementation has several limits:
1. Difficult and confusing for users to navigate between Twitter/Facebook/Mask Network Dashboard. Since there is no such kind of navigation on our plugin side, it's better to have a separate menu bar to help users quickly switch to the desired location.
2. We need a remedy to refresh or goback the WebViews when the JavaScript code encountered by a fatal error.
2. [iOS only] When opening an external page without a back button, we still need a separate back button for users to go back in some condition.

## Part 3: Expected Behavior
A simple menu bar at the top of app, on the top of other views. With the following items:
Left: A back button; A home button to back to the home page of the current website (Twitter, FB, our dashboard, etc...)
Center: A Label indicating the current location (Twitter/FB/Dashboard, etc..), click the label to open a dialog with all the supported websites to switch to (Twitter/FB)
Right: A setting button to open the separate dashboard page.

**Comment by guanbinrui** [comment]
We can use [Drawer](https://material-ui.com/components/drawers/#responsive-drawer) on both side.

**Comment by zhouhanseng** [comment]
Can we use [floating-action-button](https://material.io/components/buttons-floating-action-button)?

**Comment by Jack-Works** [comment]
We have that in our UI lib https://material-ui.com/components/floating-action-button/

**Comment by zhouhanseng** [comment]
https://github.com/DimensionDev/Maskbook/issues/1896

**Comment by jk234ert** [comment]
Close this issue since detailed changes are listed in #1897
