### ISSUE TITLE
[Bug] Fail to download encrypted image payload in new "Manually Copy" dialog

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1786]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:1.18.0
  - iOS Version:1.18.0

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
1. Compose any text using image payload on iOS.
2. Open the "Paste manually" dialog.
![Simulator Screen Shot - iphone11 ios-13 3 - 2020-10-26 at 14 05 50](https://user-images.githubusercontent.com/7972003/97140022-c4401780-1796-11eb-9cd1-555003150641.png)

3. Click "Download" button
### Actual Behavior
![Simulator Screen Shot - iphone11 ios-13 3 - 2020-10-26 at 14 08 47](https://user-images.githubusercontent.com/7972003/97140033-c86c3500-1796-11eb-9c0c-19a1bf95364e.png)

The URL of the image on iOS should be in the pattern:
"holoflows-blob://" + extensionID + "/" + blobStorage.uuid

/_What happened?_/

**Comment by Tedko** [comment]
this ux actually is very strange. Download is for pasting it (upload) to the twitter/fb?

**Comment by jk234ert** [comment]
> this ux actually is very strange. Download is for pasting it (upload) to the twitter/fb?

It's part of the "Manually Paste" feature, which means to provide an alternative solution for users when our auto-paste broken.

Auto-paste is good for sure, but easy to break. Image auto-paste is more fragile, so we could have the image copy(Download in specific platforms) for user to manually copy(download) the image, then use Twitter/fb's official way to upload.

**Comment by Jack-Works** [comment]
Oh, strange... IDK if it a bug of Safari...

**Comment by Tedko** [comment]
followup in #2091
