### ISSUE TITLE
[Demand] UX  [Poll] rename into [Poll(beta)]

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1810]
<img width="667" alt="Screen Shot 2020-10-31 at 23 11 32" src="https://user-images.githubusercontent.com/6687437/97782862-f86c6b80-1bce-11eb-858a-b52ac7f8548a.png">

We should tell our user if a func is in beta or not.

## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Tedko** [comment]
@zhouhanseng

**Comment by septs** [comment]
This effect may be better

> 🗳︎ Pull <sup>(Beta)</sup>

Code:

```html
🗳︎ Pull <sup>(Beta)</sup>
```

**Comment by Tedko** [comment]
Agree with Septs

**Comment by septs** [comment]
> Plugin <sup>(Experimental)</sup>

```html
Plugin <sup>(Experimental)</sup>
```

section title of plugin, such may be better.

**Comment by Jack-Works** [comment]
Don't use html because the api doesn't support proving html. Maybe use a "beta: true" when registering plugin

**Comment by septs** [comment]
> Maybe use a "beta: true" when registering plugin

add idea, add a `PluginStage` enum.

```ts
stage: PluginStage.Development
stage: PluginStage.Internal
stage: PluginStage.Production
stage: PluginStage.ClosedBeta
```
