### ISSUE TITLE
[Bug] `Wake up` locked MetaMask when using wallet func (red packet, trade etc)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1812]
# Bug Report

How to reproduce:

Lock the MM or wait to make it locked (looks like below)

<img width="364" alt="Screen Shot 2020-10-31 at 23 27 32" src="https://user-images.githubusercontent.com/6687437/97783799-f5747980-1bd4-11eb-8033-e7cc5fc405ff.png">

Then try use the MM wallet to do sth require wallet (send/receive red packet etc)

Then it looks like this:
<img width="1421" alt="Screen Shot 2020-10-31 at 23 38 18" src="https://user-images.githubusercontent.com/6687437/97783891-9f540600-1bd5-11eb-89d5-4dd4f9a7adad.png">

![359631604157202_ pic_hd](https://user-images.githubusercontent.com/6687437/97783895-a24ef680-1bd5-11eb-810a-0c5bda6caed2.jpg)

### Platform/Browser

- [x] Chrome

  - Maskbook Version: latest store ver
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store

### Actual Behavior

/_What happened?_/

**Comment by zhouhanseng** [comment]
2 things to confirm: Can we detect if MM has locked? Can we open the MM popup through code?

**Comment by zhouhanseng** [comment]
https://www.dropbox.com/s/272rf515r5xzp4h/unlock-mm.mov?dl=0

**Comment by Tedko** [comment]
> #1870 screen video: https://www.dropbox.com/s/272rf515r5xzp4h/unlock-mm.mov?dl=0

👍🏻👍🏻 cool fix

**Comment by zhouhanseng** [comment]
close by https://github.com/DimensionDev/Maskbook/pull/1883
