### ISSUE TITLE
[Bug] (Need fix on mobile) Breaking DOM change on You-Know-Where

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1813]
# Bug Report

For PC browser:

<img width="1421" alt="Screen Shot 2020-11-01 at 00 36 42" src="https://user-images.githubusercontent.com/6687437/97788370-632f9e00-1bf3-11eb-8e0c-66bca8bb6aef.png">
<img width="1424" alt="Screen Shot 2020-11-01 at 00 19 08" src="https://user-images.githubusercontent.com/6687437/97788372-64f96180-1bf3-11eb-89fa-5fda841fd040.png">

- Decryption/Detecting Failed;
- Encrypted comment failed;
- Still able to compose `Mask Post`

For Mobile:

![IMG_8586](https://user-images.githubusercontent.com/6687437/97788409-a1c55880-1bf3-11eb-9584-c8b382857bfe.PNG)

- Decrypted post: User Avatar disappeared, style broken
- Still able to compose `Mask Post`
- Auto- paste failed for Encrypted comment;

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
@jk234ert @Jack-Works @zhouhanseng

**Comment by Tedko** [comment]
#1180

**Comment by Tedko** [comment]
@septs restart #1180 yourself? this priority is higher than the image shuffle

**Comment by jk234ert** [comment]
@Tedko Chrome and FF store 1.18.3 released. This issue should be fixed on Chrome & FF.
Still testing on Mobile

**Comment by Tedko** [comment]
Fixed on PC

**Comment by Tedko** [comment]
Tested on ios tf 1.19. not fixed yet

**Comment by Tedko** [comment]
Not fixed on Android and iOS yet. @jk234ert need speed up

**Comment by Tedko** [comment]
cc @Jack-Works

**Comment by Tedko** [comment]
Also need to fix decrypt  img payload  #976

**Comment by Jack-Works** [comment]
Let me check out this

**Comment by Jack-Works** [comment]
Decryption on mobile failed with `decode image failed`, not the reason for DOM finding cc @guanbinrui .

https://scontent-hkg4-2.xx.fbcdn.net/v/t1.0-0/cp0/e15/q65/p526x395/125216073_719102385685163_2824552710096681592_o.jpg?_nc_cat=104&ccb=2&_nc_sid=8024bb&efg=eyJpIjoidCJ9&_nc_ohc=LFMYNZynJtoAX-sBUNQ&_nc_ht=scontent-hkg4-2.xx&tp=3&oh=bf05ed4be70468b30a31f59a76e788b5&oe=5FD83C25

here is an example

**Comment by Jack-Works** [comment]
![](https://user-images.githubusercontent.com/5390719/99233970-e88b9300-282e-11eb-9bdb-dc679356c859.png)
