### ISSUE TITLE
[Bug] `Auto-paste failed` alert not working accurately 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1814]
# Bug Report

Even the auto-paste is working well still the alert pop-up;

- On iOS/Android compose encrypted text msg on fb(twitter is fine):
![IMG_8590](https://user-images.githubusercontent.com/6687437/97789229-ad1b8280-1bf9-11eb-9f0b-db52abbf99d5.PNG)

- On Web, compose img payload on twitter etc
<img width="1431" alt="Screen Shot 2020-10-31 at 22 56 09" src="https://user-images.githubusercontent.com/6687437/97789230-adb41900-1bf9-11eb-8411-42edc29104bc.png">
<img width="1431" alt="Screen Shot 2020-10-31 at 22 55 49" src="https://user-images.githubusercontent.com/6687437/97789231-aee54600-1bf9-11eb-9f3e-56616738f71b.png">

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Jack-Works** [comment]
Yes, because the detect of auto-paste is also not reliable

**Comment by jk234ert** [comment]
As a fallback solution when our auto-paste not working, I suggest to re-design the "Auto-paste alert" to a "Manually paste dialog".
An example would be like:
1. Whenever a new encrypted message (Text Or Image payload) generated, Mask Network tries to auto-paste the payload into the compose dialog.
2. Do NOT check whether the auto-paste work as expected, always display the "Manually paste dialog", with the generated payload in the dialog (Or only display hint message with a button to expand the dialog)

**Comment by Tedko** [comment]
> Yes, because the detect of auto-paste is also not reliable

@Jack-Works @jk234ert 
at least we need a timeout like 15s. otherwise the dialog will be there for a long time

**Comment by Tedko** [comment]
again this UX is not usable.. will only create confusion

**Comment by Jack-Works** [comment]
draft a fix in #1838
