### ISSUE TITLE
Report the 7ef05c8 bug to upstream and remove the hack

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#182]
commit 7ef05c8

**Comment by Misaka-0x447f** [comment]
https://github.com/DimensionDev/Maskbook/blob/7ef05c8ae283d0eda0c45264b8334bd1c096453c/src/utils/jss/ShadowRootPortal.tsx#L38

**Comment by Jack-Works** [comment]
@Artoria2e5 maybe it's not a bug of the upstream, cause if the node is not connected, it's maybe right to not to append styles to it.

**Comment by SunriseFox** [comment]
This should have been solved as `construct-style-sheets-polyfill` is no longer used to handle this logic.

**Comment by Jack-Works** [comment]
we should report the performance issue to the upstream.
