### ISSUE TITLE
[Demand] How to return token from unclaimed red packet?

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1834]
1. Is the red packet history able to function and read RP history?
2. How to return token from unclaimed red packet? Is it doable? Need an FAQ @zhouhanseng wanna help write up?
3. Need an alert system or something to tell the user?

**Comment by zhouhanseng** [comment]
1. Read red packet history is **read-only call** which is fast and gas free, it is doable, I checked our current ABI, it seems like need an update to the smart contract to support history query. 
2. We can transfer token to anyone include ourselves. This had been done, after the red packet outdated we can refund. 
3. Maybe we can put the history list in dashboard, and user can refund by clicking a button at each red packets from the history list.

**Comment by Tedko** [comment]
> 1. Read red packet history is **read-only call** which is fast and gas free, it is doable, I checked our current ABI, it seems like need an update to the smart contract to support history query.
> 2. We can transfer token to anyone include ourselves. This has been done, after the red packet outdated we can refund.
> 3. Maybe we can put the history list in dashboard, and user can refund by clicking a button at each red packets from the history list.

3-> assigned to @guanbinrui

**Comment by guanbinrui** [comment]
> Maybe we can put the history list in dashboard, and user can refund by clicking a button at each red packets from the history list.

Yes, we have this feature built.

<img width="1128" alt="test" src="https://user-images.githubusercontent.com/52657989/98493714-18a6c500-2276-11eb-92e8-4d5d83639532.png">

**Comment by Tedko** [comment]
seems this is fixed.

Right now we need:

- FAQ on this feature @tsuki 
- UX improve （现在不明显） low priority
