### ISSUE TITLE
MutationObserverWatcher seems not working on twitter/ui/fetch

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#184]
https://github.com/DimensionDev/Maskbook/blob/4d7e551b03ae6dc0f4dc3cdd2753ff1da1a5cf46/src/social-network-provider/twitter.com/ui/fetch.ts#L48\

![image](https://user-images.githubusercontent.com/15797507/64845378-9a806b80-d63c-11e9-9559-42238e5cdb23.png)

The length in the image represents how many element selected by this dynamic selector at this time (via ```elevate()```). It changed from 0 to 11 but ```.forEach``` only run once.
![image](https://user-images.githubusercontent.com/15797507/64845893-e1bb2c00-d63d-11e9-8cd6-63bdeca610ef.png)

**Comment by Jack-Works** [comment]
Here is a edge case in Watcher and I don't know if that helps.

Watcher use rAF lock to run checks during each run, if a new task scheduled when the rAF lock is locked, it will be ignored. Watcher should run one more time to check if there is any change during the rAF locking (but it doesn't do it currently).

Do some DOM change and check if your problem resolved, if it runs the forEach call after you manually do a DOM change, it is the Watcher bug.

**Comment by Misaka-0x447f** [comment]
This could be my bad since I realized that in some cases in firefox exception will not visible in console. I tried to replace your's with a more simpler version this afternoon but the problem consists. Then I found that maybe some exception happened but not shown in the console.

**Comment by Misaka-0x447f** [comment]
* they are only visible if a try...catch added to the call of ```callbackFn```. Maybe same thing should be done on the @holoflow/kits.
![image](https://user-images.githubusercontent.com/15797507/64852169-6e201b80-d64b-11e9-809a-998d7a68cd87.png)
![image](https://user-images.githubusercontent.com/15797507/64852200-81cb8200-d64b-11e9-949e-a16d36184d93.png)
In this piece of code, if no try/catch, no exception.

**Comment by Misaka-0x447f** [comment]
*but you can catch it by 'pause on exception'.

**Comment by Jack-Works** [comment]
It's a Firefox bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1469304 and https://github.com/facebook/react/issues/16605
