### ISSUE TITLE
Start our matrix server as decenterialized sync tool

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#185]
See: https://github.com/matrix-org/

related #176 #76 #163 #142

**Comment by Jack-Works** [comment]
Will be used in the following components: 

- Friendship certificate distribution
- User group message exchange
- Cross device sync

**Comment by SunriseFox** [comment]
That sounds the same as using any centralized server with an encrypted protocol...

**Comment by Jack-Works** [comment]
Umm Matrix say they can p2p between servers

**Comment by SunriseFox** [comment]
But just like GUN, we will possibly never have another, community provided server. If there is not, then we are not utilizing this functionality.

**Comment by Tedko** [comment]
Related parties will initiate these servers soon.

**Comment by neruthes** [comment]
Any latest update? Is this blocking #142?

**Comment by neruthes** [comment]
Again, any latest update?

**Comment by neruthes** [comment]
Discussion summary: Suspended for low priority. Will resume when there is time.

**Comment by Jack-Works** [comment]
related works: https://github.com/Jack-Works/generate-matrix-js-sdk-type
