### ISSUE TITLE
[Bug] Append Recipients `close X` button not working 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1852]
# Bug Report

<img width="1431" alt="Screen Shot 2020-11-06 at 01 37 10" src="https://user-images.githubusercontent.com/6687437/98276293-b7aa9300-1fd0-11eb-8752-9e1160b29162.png">

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by zhouhanseng** [comment]
@Tedko how to reproduce?

**Comment by Tedko** [comment]
Send a post to 'myself' and try append recp
