### ISSUE TITLE
[Bug] version number display is missing

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1854]
latest chrome store vr: 1.19.2

<img width="1431" alt="Screen Shot 2020-11-06 at 02 00 54" src="https://user-images.githubusercontent.com/6687437/98278756-060d6100-1fd4-11eb-97ff-fbe22855db39.png">

**Comment by Tedko** [comment]
@guanbinrui any bug introed by the recent update?

**Comment by guanbinrui** [comment]
![test](https://user-images.githubusercontent.com/52657989/98328224-2bc85380-2030-11eb-877a-f0699a8b05fe.png)

Strange. It's Ok on my end.

**Comment by Tedko** [comment]
after upgrading i cant reproduce as well. will close this for now
