### ISSUE TITLE
Mobile setup QR code overlapped if multiple identities are imported

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#186]
![image](https://user-images.githubusercontent.com/3343358/64938512-be3bef80-d890-11e9-9d24-deaf284abedd.png)
It happens when you own two or more identities.

**Comment by SunriseFox** [comment]
This is a known issue... as dashboard is about to be rewritten, such fix maybe won't be applied.

**Comment by neruthes** [comment]
I suggest that implementing the cross-device synchronization is the best way to avoid this in future.

**Comment by SunriseFox** [comment]
When there are more than 1 identities the QR code becomes too large to scan. So we really need to find another way to sync between devices.

**Comment by Jack-Works** [comment]
fixed by #284
