### ISSUE TITLE
[Task] Decide write our own mm extension-provider or not

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#1860]
## Content

[extension-provider](https://github.com/MetaMask/extension-provider) has not been updated for long time. It still uses `metamask-inpage-provider@1.1.0`, which only has a few features and does not include `ethereum.request()`.

Need to confirm if we can use `ethereum.request()` to detect if metamask is locked https://github.com/DimensionDev/Maskbook/issues/1812

**Comment by Jack-Works** [comment]
if we need to write one, please move it to another repo 👀

**Comment by guanbinrui** [comment]
Why we need `ethereum.request()`?

**Comment by zhouhanseng** [comment]
Using `ethereum._metamask.isUnlocked()` to detect if mm is locked. If it is locked then calling `ethereum.request({ method: 'eth_requestAccounts', params: [] })` could popup mm dashboard. These two methods are neither supported by old extension-provider.

**Comment by Tedko** [comment]
whats the pro and con

**Comment by zhouhanseng** [comment]
@Tedko 

We have just forked a temporal [package](https://github.com/DimensionDev/extension-provider) for MetaMask/extension-provider. Before they accept our [PR](https://github.com/MetaMask/extension-provider/pull/15) we can use the forked version.

**Comment by Tedko** [comment]
Ok. I will ping MM team

**Comment by danfinlay** [comment]
We've now published the inpage-provider update as `@metamask/extension-provider@2.0.0`, thanks for the help!

**Comment by zhouhanseng** [comment]
@danfinlay Hi, so glad to see this publish is so fast! 

There's one more issue:

Currently we can call `ethereum.request()` to popup metamask dashboard to prompt user to unlock when metamask is locked. But if I have called `ethereum.request()`, then I call it again, it will throw an error: `Object: Already processing eth_requestAccounts. Please wait.(-1)`, which cause it is unable to popup again.

How about providing a special method to popup metamask dashboard?
