### ISSUE TITLE
[Bug] Fail to decode red packet payload on mobile on twitter

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1865]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
This issue is not reproducible on previous version (1.18.2)

Create a redpacket on rinkeby, then check the post, there is error message with "Maskbook has an error" as below screenshot.

1. Send redpackets from mobile app or Chrome/Firefox, on **Chrome/Firefox** everything works properly
2. Send redpackets from mobile app or Chrome/Firefox, on **mobile** the issue occurs at 100%.

So this issue should be related to the redpacket plugin view injection on the mobile app Twitter.

### Actual Behavior

/_What happened?_/
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-09 at 09 28 42](https://user-images.githubusercontent.com/7972003/98490927-2a846a00-226e-11eb-859e-e828f2e10968.png)

**Comment by Jack-Works** [comment]
@jk234ert iOS only?

**Comment by guanbinrui** [comment]
This issue caused by `eval` used in the `template` function which provided by `lodash`.
