### ISSUE TITLE
[GeckoView] Add a Homepage for a better navigation experience

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#187]
GeckoView is not a browser, at least currently not. So there are some problems:

+ Not be able to manually navigate to Maskbook's option page
+ Not be able to navigate back to facebook / twitter, etc. 

So I suggest that we add a Homepage, from where we can choose to go to Dashboard / Facebook / Twitter.  And inject a float button / hook navigate back button on every pages that not Homepage, when triggered, navigate to Homepage. By doing this we connect our features together and make them accessible everywhere through the user experience.

**Comment by Tedko** [comment]
I agree. A home page is definitely necessary.
Since you mentioned Twitter on Android — I’m not sure can we use non PWA
tech stack (native app) for this ‘3rd party’ twitter. Currently that will
create a better User experience.

**Comment by Jack-Works** [comment]
fixed by https://github.com/DimensionDev/Maskbook/pull/282
