### ISSUE TITLE
[Task] Tracking ABIs in the codebase

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1873]
## Introduction and Background

Contract ABIs are not tracking in the codebase now. We should create an `abis/` folder for keeping those files.

/_Describe the background of this task_/

## Content

+ Tracking contract ABIs in the current codebase.
+ Listing the `solcjs`  in the deps list of the project.
+ Rewrite `contract.sh` in JavaScript.

**Comment by Jack-Works** [comment]
packages/eth-abis/

**Comment by septs** [comment]
Original from https://github.com/DimensionDev/Maskbook/issues/1550
