### ISSUE TITLE
Event hijack has a race with native code

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#19]
Nothing happens.
Hard to reproduce.

**Comment by Jack-Works** [comment]
In that case, the text will be copied to the clipboard.

**Comment by yisiliu** [comment]
@Jack-Works it didn't behave that way.

**Comment by Tedko** [comment]
When User don't have key import/initiate, Need to have an introduction for 'post it'.

没有创建key或者导入key的时候点post it没反应。需要一个引导。

**Comment by Jack-Works** [comment]
Reproduced. Have a race with native code. Deal with it later

**Comment by Jack-Works** [comment]
NOT FAST ENOUGH!
