### ISSUE TITLE
[Demand] Able to send token directly within Mask Wallet

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1907]
## Catalogue

- [ ] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Now we need to enable the user to send token / NFT directly within the wallet page;
Few steps:
- Able to send token in internal wallet
- Able to send NFT in internal
- Able to send in external

**Comment by Tedko** [comment]
@guanbinrui @zhouhanseng let's prioritize this one as well?

**Comment by guanbinrui** [comment]
@xiazhiming Plz paste the Figma link into the description, thx.

**Comment by Tedko** [comment]
tested with wallet connect wallet on mask, and confirm its delivered
