### ISSUE TITLE
[Bug] Duplicate RedPacketRecord in DB

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1913]
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Expect Behavior

Should check if the red packet record exists in DB before adding it in to DB.

### Actual Behavior

![test123](https://user-images.githubusercontent.com/52657989/99229081-7a43d200-2828-11eb-8e99-5719f52b629a.png)

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/1afefcb92d03d590506dbb414844cef432280ae6/packages/maskbook/src/plugins/RedPacket/database.ts#L18-L20
