### ISSUE TITLE
[Discussion] npm, pnpm, yarn or yarn 2

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1937]
|                           | npm | pnpm | yarn 1 | yarn 2 | yarn 2 with PNP |
|---------------------------|-----|------|--------|--------|-----------------|
| Workspace                 | ✔   | ✔    | ✔      | ✔      | ✔               |
| Prevent accidental import | ❌   | ✔    | ❌      | ❌      | ✔               |
| Modify package install    | ❓   | ✔    | ❓      | ✔      | ✔               |
| Modify node_modules       | ✔   | ❌    | ✔      | ✔      | ✔               |

1. Should we use PNP?
2. Yarn 2 has a new feature called "Constraints" which is powerful. (https://yarnpkg.com/features/constraints)
3. PNPN has "pnpmfile.js" which is powerful too. (https://pnpm.js.org/en/pnpmfile)

**Comment by Jack-Works** [comment]
Please vote (via Github reaction) or comment.

🎉 = npm
🚀 = pnpm
♥ = yarn
👀 = yarn 2

**Comment by Jack-Works** [comment]
Please vote (via Github reaction) or comment and address your argument.

Should we use PNP (Plug and Play)? pnpm and yarn 2 support this feature.

Reaction with 👍 or 👎

**Comment by Jack-Works** [comment]
Please vote (via Github reaction) or comment and address your argument.

Which one to use?

🎉 = lerna (works with npm, yarn and yarn 2)
🚀 = rush (works with npm 5 and pnpm)
👀 = npm/pnpm/yarn workspace only

**Comment by Jack-Works** [comment]
@guanbinrui @zhouhanseng

**Comment by Jack-Works** [comment]
One of the problem of the dependencies hoisting is that, you're getting modules you _don't_ want in the top level. For example, this is what we get when running `yarn why @babel/core` in our project. Generally this is not a serious problem but imagine what will happen if a conflicting TypeScript definition is being hoisted. TypeScript will auto-discover `@types/` and merge those types you don't want in. cc @septs 

```
yarn why @babel/core
yarn why v1.22.5
[1/4] Why do we have the module "@babel/core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@babel/core@7.9.0"
info Has been hoisted to "@babel/core"
info Reasons this module exists
   - Hoisted from "@jest#transform#@babel#core"
   - Hoisted from "jest-esm-transformer#@babel#core"
   - Hoisted from "istanbul-lib-instrument#@babel#core"
   - Hoisted from "@storybook#addon-docs#@jest#transform#@babel#core"
   - Hoisted from "@storybook#react#@svgr#webpack#@babel#core"
   - Hoisted from "jest-environment-jsdom-fourteen#@jest#environment#@jest#transform#@babel#core"
   - Hoisted from "jest#@jest#core#jest-config#@babel#core"
   - Hoisted from "@storybook#addon-docs#vue-docgen-loader#jscodeshift#@babel#core"
   - Hoisted from "@storybook#react#@svgr#webpack#@svgr#plugin-jsx#@babel#core"
   - Hoisted from "@storybook#react#babel-plugin-react-docgen#react-docgen#@babel#core"
info Disk size without dependencies: "1.05MB"
info Disk size with unique dependencies: "11.34MB"
info Disk size with transitive dependencies: "12.53MB"
info Number of shared dependencies: 42
=> Found "@mdx-js/mdx#@babel/core@7.8.0"
info This module exists because "@storybook#addon-docs#@mdx-js#mdx" depends on it.
info Disk size without dependencies: "288KB"
info Disk size with unique dependencies: "10.52MB"
info Disk size with transitive dependencies: "11.6MB"
info Number of shared dependencies: 36
=> Found "remark-mdx#@babel/core@7.8.0"
info This module exists because "@storybook#addon-docs#@mdx-js#mdx#remark-mdx" depends on it.
info Disk size without dependencies: "288KB"
info Disk size with unique dependencies: "10.52MB"
info Disk size with transitive dependencies: "11.6MB"
info Number of shared dependencies: 36
Done in 3.83s.
```

**Comment by Jack-Works** [comment]
npm 7 (with workspace support) is still in early stage, and in npm 7 peer dependencies will be auto installed. that might break something. @septs

**Comment by Jack-Works** [comment]
> As of the writing of this post, it still hasn't reached feature parity with Lerna, pnpm or Yarn Workspaces. Technical details about how Workspaces will work are still being voted and discussed on GitHub issues.

> The toolset is still limited. There is no npm workspaces subcommand or anything equivalent. If you want to be an early adopter, you’ll need to combine it with tools like nx or Lerna for a complete monorepo workflow.

-- https://hyperfoo.io/posts/npm-7-workspaces-1

**Comment by Jack-Works** [comment]
Let's use the npm7 workspace. I'll open a new issue to track it.

**Comment by Jack-Works** [comment]
Ok, now we have a problem (or exactly, many problems) with NPM.

# Problem 1: Bad deduplicate of dependencies

In our dependency tree here is the problem:

```text
/node_modules/webpack@v5
/node_modules/some_plugin_that_support_both_webpack_4_and_5
/pakcages/theme/node_modules/webpack@4
```

And both the main project relies on the `some_plugin_that_support_both_webpack_4_and_5`. When starting webpack 4, it will find the `some_plugin_that_support_both_webpack_4_and_5` in the `/node_modules`. And when that plugin `require` webpack, it will get webpack 5.

IMHO, the way `pnpm` structure the `node_modules` would never cause this problem.

# Problem 2: Missing interactive-upgrade

yarn, yarn 2, and pnpm have this feature. The 3rd party solution for npm doesn't work well for us.

# Problem 3: NPM bugs

https://github.com/npm/cli/issues/2430


Though I strongly recommend PNPM I cannot guarantee PNPM is absolutely good. I've heard PNPM is lacking contributors (maybe?).

cc @guanbinrui @septs

**Comment by merceyz** [comment]
Hello :wave: 

Just out of curiousity what do you mean by "Modify package install"?

Yarn has [resolutions](https://yarnpkg.com/configuration/manifest#resolutions) to modify declared dependencies of your dependencies, Yarn 2 also has [packageExtensions](https://yarnpkg.com/configuration/yarnrc#packageExtensions) to add dependencies to them and a [`patch:`](https://yarnpkg.com/features/protocols#patch) protocol to modify the content of any dependency

**Comment by Jack-Works** [comment]
@merceyz cool, that's almost what I mean, I have updated the top-most table.

**Comment by lelenei** [comment]
I executed the npm ci command in a branch to solve this problem, it will appear again after switching the branch
<img width="960" alt="image" src="https://user-images.githubusercontent.com/72531217/105796415-c39f6300-5fc9-11eb-9aa2-21ddced99843.png">

**Comment by guanbinrui** [comment]
> I executed the npm ci command in a branch to solve this problem, it will appear again after switching the branch.
> This problem is recent
> 
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/72531217/105796415-c39f6300-5fc9-11eb-9aa2-21ddced99843.png">

It causes by https://github.com/DimensionDev/extension-provider/packages/584832. You should reinstall your node_modules.

**Comment by Jack-Works** [comment]
it actually the npm bug I mentioned before https://github.com/npm/cli/issues/2430 @guanbinrui

**Comment by lelenei** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/72531217/105818902-68359b00-5ff2-11eb-91bf-d72ddc3635d0.png">
