### ISSUE TITLE
[Discussion] Use `urlcat` build url?

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1938]
see https://github.com/balazsbotond/urlcat

![](https://github.com/balazsbotond/urlcat/raw/master/docs/urlcat-basic-usage.svg)

sample code:
```ts
const API_URL = 'https://api.example.com/';

function getUserPosts(id, limit, offset) {
  const requestUrl = urlcat(API_URL, '/users/:id/posts', { id, limit, offset });
  // send HTTP request
}
```

CC @guanbinrui @Jack-Works @zhouhanseng

**Comment by Jack-Works** [comment]
Are we built URL frequently?

**Comment by septs** [comment]
CC @guanbinrui @zhouhanseng

**Comment by Jack-Works** [comment]
What's your conclusion? @septs
