### ISSUE TITLE
[Bug] Recursive event loop on mobile

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1939]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
On Mask Network iOS app, after navigating to Twitter/Fb, the app could not properly retrieve the actual status of the connected persona, it even leads to a recursive event loop of "query profile/query persona" under the hood, users may found the app laggy and various kind of weird appearance.

### Actual Behavior
Including but not limited to the following appearance:
1. App becomes almost not responding after several minutes of use.
2. "Find your username" dialog does not appear when connecting profile to persona.
3. "Setup Maskbook" is always displayed and users could not compose/decrypt Maskbook payload even they already connected
4. In Maskbook dashboard, users could not find their created wallets

/_What happened?_/

**Comment by Jack-Works** [comment]
I'm sorry I have slow internet connection and sometimes outage this week

**Comment by septs** [comment]
https://github.com/DimensionDev/webextension-polyfill/commit/1bd22b9f078bcb0426202e920b3acb5b2e447375

**Comment by jk234ert** [comment]
Root caused confirmed on iOS native side.
