### ISSUE TITLE
[RFC] PersonaAutobiography v1.0.1.1

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#194]
## Metadata

Field | Value
--- | ---
Manifest | [Meta/Article-3](https://github.com/DimensionDev/Meta/blob/master/articles/3--rfc-peer-review.md)
Purpose | Data Management
Feedback deadline | 2019-12-19 12:00:00 UTC
Explicitly designated reviewers | @yisiliu @Jack-Works 

## Abstract

PersonaAutobiography is designed to provide a universal description format for every person, which should cover all scenarios and be compatible with all transportation methods.

Scenarios include persona backup, database backup, and persona export.

Transportation methods include QR, Base64 text, and JSON File.

## Background

- #225
- #195

### Generic

```json
{
    "Meta": {
        "PayloadSpec": "DeadSeaOldScroll",
        "Version": 1
    },
    "Content": {
        "_": {
            "AppLabel": "maskbook.com--persona-autobiography",
            "AppVersion": 1,
            "Time": 1569374955715,
            "Name": "Neruthes 0x5200DF38",
            "PersonaPrivateKey": null,
            "PersonaPublicKey": {
                "_": "ArxApPYD24e+RjrKyYMpG/2QemXLfxsISb+aFFbltJ1f",
                "encoding": "base-64"
            },
            "PersonaPublicKeyFingerprint": {
                "_": "BCD1FF19582A9B8D5CE9CB780E18C651318756B6",
                "hash": "SHA-1",
                "encoding": "hex"
            },
            "Profiles": {
                "facebook.com": [ "neruthes.5200DF38" ],
                "twitter.com": [ "neruthes" ]
            }
        }
    },
    "Signature": {
        "_": {
            "BaseSig": {
                "_": "WFceyl2VOyvyeaqkTodUI1XulcXQkRVQvh3U65vvMUuRq2ln9ozlECaZYLkKq9HHWKucm9sc2e52y32I1Foikg==",g
                "encoding": "base-64"
            }
        }
    }
}
```

Since there is no private key in this type, `PersonaPrivateKey` field should be `null`.

### Including Private Key

```json
{
    "Meta": {
        "PayloadSpec": "DeadSeaOldScroll",
        "Version": 1
    },
    "Content": {
        "_": {
            "AppLabel": "maskbook.com--persona-autobiography",
            "AppVersion": 1,
            "Time": 1569374955715,
            "Name": "Neruthes 0x5200DF38",
            "PersonaPrivateKey": {
                "_": "the natural law of privacy is now enforced by maskbook and tessercube",
                "encoding": "mnw"
            },
            "PersonaPublicKey": {
                "_": "ArxApPYD24e+RjrKyYMpG/2QemXLfxsISb+aFFbltJ1f",
                "encoding": "base-64"
            },
            "PersonaPublicKeyFingerprint": {
                "_": "BCD1FF19582A9B8D5CE9CB780E18C651318756B6",
                "hash": "SHA-1",
                "encoding": "hex"
            },
            "Profiles": {
                "facebook.com": [ "neruthes.5200DF38" ],
                "twitter.com": [ "neruthes" ]
            }
        }
    },
    "Signature": {
    }
}
```

### Over QR code

![image](https://user-images.githubusercontent.com/2139261/70438024-d16fed00-1a84-11ea-8018-72b62b626545.png)

**Comment by Artoria2e5** [comment]
Are we going to consider the case where one persona corresponds to multiple accounts/identifiers on a network? I mean, with the strict URL-like identifier encoding, adding a `$1` `$2` prefix will do. Just don't call it `FACEBO~2.com`.

**Comment by neruthes** [comment]
Its feasibility remains uncertain, but I do wish to have it possible in data level for now.

**Comment by Jack-Works** [comment]
I'm sorry but where will we use this?

**Comment by neruthes** [comment]
@Jack-Works This is designed for persona backup with mnemonic words, where metadata needs a storage other than the sequence of mnemonic words.

**Comment by Jack-Works** [comment]
> @Jack-Works This is designed for persona backup with mnemonic words, where metadata needs a storage other than the sequence of mnemonic words.

We're not saving mnemonic words currently. Should we do this? Does it safe enough to do?

**Comment by Tedko** [comment]
For mnemonic words: better generate some encrypted file protected by a
simple password?

**Comment by neruthes** [comment]
> > @Jack-Works This is designed for persona backup with mnemonic words, where metadata needs a storage other than the sequence of mnemonic words.
> 
> We're not saving mnemonic words currently. Should we do this? Does it safe enough to do?

We should.

Safety remains open for discussion. Maybe @yisiliu has ideas to share on this topic.

**Comment by neruthes** [comment]
> For mnemonic words: better generate some encrypted file protected by a simple password?
> […](#)

Requiring a password on persona creation is not a good idea. We may introduce "Upgrade Persona Safety" feature in a later version. Device honesty is beyond our concern at this stage; we must assume that all devices are safe enough.

**Comment by neruthes** [comment]
Update:

An optional password field has been added in the interaction design draft. A user may optionally give a password if he feels necessary.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/2139261/70026123-e1746200-1596-11ea-8e7d-592ceb51e4f3.png">

**Comment by neruthes** [comment]
Update:

Now the autobiography may optionally include persona private key or mnemonic words. This can be used as a text-based full backup of a persona, like the "Base64" option in #369.

**Comment by neruthes** [comment]
Update:

With this RFC ratified, optical transfer over QR will be possible, and it could remain.

**Comment by neruthes** [comment]
Updated:

According to discussions in #407, password is now a mandatory field.

**Comment by neruthes** [comment]
Since RFC #223 is ratified and #224 requires this RFC as a dependency, we can now work on this.

**Comment by neruthes** [comment]
This RFC relies on #225. Should ratify #225 fast.

**Comment by neruthes** [comment]
Update:

RFC #225 has been ratified.

**Comment by neruthes** [comment]
TO: @Jack-Works 

-------

You may want to introduce the latest design in RFC #223 here. Feel free to update the RFC document content.

**Comment by neruthes** [comment]
I will mark this as Ratified if there is no further discussion before today 12:00 UTC.

----

cc @yisiliu @Jack-Works @SunriseFox @guanbinrui

**Comment by Jack-Works** [comment]
Objection. This format is too verbose.

Why prefer `"Meta": {
        "PayloadSpec": "DeadSeaOldScroll",
        "Version": 1
    },`, instead of `"version": 1`? I'll draft a competitive format that is more concise but still extendable.

(By the way capitalized field name make it somewhat like the classic XML format)

**Comment by neruthes** [comment]
> Objection. This format is too verbose.
> 
> Why prefer `"Meta": { "PayloadSpec": "DeadSeaOldScroll", "Version": 1 },`, instead of `"version": 1`? I'll draft a competitive format that is more concise but still extendable.

I believe that verbosity is better than trivialization. We have a lot of JSON-based payloads. Preventing trivialization is more important than reducing verbosity. RFC #225 has been ratified already.

**Comment by Tedko** [comment]
I'm `√` for the idea of RFC and seems it's indeed necessary. 
Also love to see @Jack-Works 's opinion beside **verbose.** 

@Jack-Works @neruthes If you have time take a look of SOLID (and many w3c related) persona designs you might find them helpful. This is an issue under long debating.

`Done is better than perfect.` -- quote from someone.

**Comment by Jack-Works** [comment]
A format that so verbose is not necessary.

A shorter version

```json
{
  "meta": {
    "version": 1,
    "type": "file_type",
    "maskbookVersion": "1.8.0",
    "timestamp": 1569374955715
  },
  "datatype": [
    {
      "field1": "value1"
    }
  ]
}
```

**Comment by Tedko** [comment]
👍

**Comment by neruthes** [comment]
Feel free to introduce an alternative to #225. But be hurry.

**Comment by Jack-Works** [comment]
> Feel free to introduce an alternative to #225. But be hurry.

I have drafted a cleaner alternative. And we can even change between proposals (before we ship it to user)

**Comment by Jack-Works** [comment]
Draft based on current database structure.
```ts
interface BackupJSONFileVersion2 {
    _meta_: {
        version: 2
        type: 'maskbook-backup'
        maskbookVersion: string // e.g. "1.8.0"
        createdAt: number // Unix timestamp
    }
    personas: Array<{
        identifier: string // PersonaIdentifier.toText()
        mnemonic?: {
            word: string
            parameter: { path: string; withPassword: boolean }
        }
        publicKey: JsonWebKey
        privateKey?: JsonWebKey
        localKey?: JsonWebKey
        nickname?: string
        linkedProfiles: Record</** ProfileIdentifier.toText() */ string, LinkedProfileDetails>
        createdAt: number // Unix timestamp
        updatedAt: number // Unix timestamp
    }>
    profiles: Array<{
        identifier: string // ProfileIdentifier.toText()
        nickname?: string
        localKey?: JsonWebKey
        linkedPersona?: string // PersonaIdentifier.toText()
        createdAt: number // Unix timestamp
        updatedAt: number // Unix timestamp
    }>
    userGroups: Array<{
        groupName: string
        identifier: string // GroupIdentifier.toText()
        members: string[] // Array<ProfileIdentifier.toText()>
        banned?: string[] // Array<ProfileIdentifier.toText()>
    }>
    posts: Array<{
        postBy: string // ProfileIdentifier.toText()
        identifier: string // PostIVIdentifier.toText()
        postCryptoKey?: JsonWebKey
        recipients: Record</** ProfileIdentifier.toText() */ string, RecipientDetail>
        recipientGroups: string[] // Array<GroupIdentifier.toText()>
        foundAt: number // Unix timestamp
    }>
}
```

**Comment by neruthes** [comment]
All 225-based RFCs are now being dismissed.
