### ISSUE TITLE
[Demand] Storybook current is unavailable

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1946]
storybook current is unavailable. 

![image](https://user-images.githubusercontent.com/3842474/99938148-28f48f00-2da2-11eb-8c8a-701002a62349.png)

_Originally posted by @septs in https://github.com/DimensionDev/Maskbook/issues/1933#issuecomment-731984427_

**Comment by septs** [comment]
https://github.com/storybookjs/storybook/issues/13219

**Comment by Jack-Works** [comment]
It's not an upstream problem I guess. If you adjust ts-loader config in storybook it might be fixed
