### ISSUE TITLE
[RFC] Persona Key Export with Mnemonic Words

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#195]
## Metadata

Field | Value
--- | ---
Manifest | [Meta/Article-3](https://github.com/DimensionDev/Meta/blob/master/articles/3--rfc-peer-review.md)
Purpose | Data Management
Feedback deadline | 2019-12-19 12:00:00 UTC
Explicitly designated reviewers | @yisiliu @Jack-Works 

## Context

- #68
- #70
- #369

## Summary

It is evident that 12 mnemonic words are not enough to store the whole persona metadata. My proposal for this problem is that the metadata may be stored on GUN after a basic ECDH encryption. So that 12 mnemonic words may be enough.

## Payload Format

See RFC #194.

The location of the ECDH-encrypted payload is `SHA512('e515b2eb-c353-43f8-a1c8-db83935b7288,' + MnemonicWords.join(',')).toString('hex-uppercase')`

**Comment by Tedko** [comment]
Stored on Gun sounds like a good idea.
Will 12 -> 24 mnemonic words make a difference?

**Comment by Artoria2e5** [comment]
We already have key mnemonic from 1cefbff, using Bitcoin's bip39 12-word algorithm. Joy's idea is that personae and keys will always map one-to-one, so it would be fine to just fetch mnemonic by the key.

> Will 12 -> 24 mnemonic words make a difference?

No. The mnemonic system is designed to transform a set of random binary data, such as the seed used to generate a ECDH key. The list of soc. net profiles, on the other hand, is some variable-length data that we cannot effeciently store.

On the other hand though, it surely is easier to remember one's own username than it is to remember some binary data. Perhaps we can just suffix the mnemonic with a space-separated list of identifiers bound to it, lol.

**Comment by Tedko** [comment]
Do agree on that easy to remember part. Blockstack had the similar approach
- you can take a look (looks like < hex string >@Alice ).

**Comment by neruthes** [comment]
Latest solution: Add an additional screen in account connection procedure where the user may optionally import a specific MW seed. This will make least modification to the current UI before #68 is delivered, and will not require GUN reliability since it does not include #195.

**Comment by neruthes** [comment]
I am closing all my RFCs since [Meta/Article-3: RFC Peer Review Convention](https://github.com/DimensionDev/Meta/issues/3) has been abolished. I assume that everyone agrees that this is not worth discussing for now. Some discussions may be restarted, if necessary, after [Meta/Bill-4: DSD Peer Review Convention](https://github.com/DimensionDev/Meta/issues/4) is ratified. In the meantime, if there is any question with documentation and workflow, please consult @yisiliu. Thanks for everyone who has engaged in the discussions so long.
