### ISSUE TITLE
[Bug] Use <a> tag to trigger file downloading on mobile

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1952]
## Bug Report
We have some features that trigger file downloading when users click the corresponding button/links:

1. Backup Database. `browser.downloads.download` is used.
2. Encrypted image download in the new "Manually Image Paste" dialog. <a> tag is used with URL like "blob://xxxxxx.png"

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [x] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
On Android, GeckoView does NOT support `browser.downloads.download`, users click the "OK, Back it up" button takes no effect.
On iOS, the link is "blob:null/xxxxx", leads to an error page.

### Actual Behavior

/_What happened?_/

**Comment by zhouhanseng** [comment]
On Android, do you need to [request the permission](https://github.com/mozilla-mobile/focus-android/issues/14#issuecomment-304454973) first?

**Comment by jk234ert** [comment]
> On Android, do you need to [request the permission](https://github.com/mozilla-mobile/focus-android/issues/14#issuecomment-304454973) first?

Permission related stuff would be handled by GeckoView & system, we just use a <a> tag to trigger the event
