### ISSUE TITLE
[Task] Redesign locale kit

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1955]
@septs how to let the locale kit support this PR?

_Originally posted by @Jack-Works in https://github.com/DimensionDev/Maskbook/issues/1953#issuecomment-733500801_

**Comment by Jack-Works** [comment]
Without the new locale kit my pr cannot be merged because it will break the workflow

**Comment by septs** [comment]
Wait for #2006

**Comment by septs** [comment]
npm workspace new locale kit design (#1980)

```
packages/[package]/_locales/*.json

e.q:
packages/maskbook/_locales/*.json
packages/plugin-file-service/_locales/*.json
packages/theme/_locales/*.json
// etc
```
