### ISSUE TITLE
[Bug] fb fanpage img-payload decryption failed due to compression too much

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1956]
## Bug Report

take a look of https://www.facebook.com/masknetwork (fan page of fb) and the DOM is different than other timeline. The decryption process cannot work properly.

(The `post encrypted post` process and auto paste etc are  working fine.)

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by zhouhanseng** [comment]
@Tedko How to test the decryption process on the masknetwork page?

**Comment by Tedko** [comment]
@zhouhanseng let me post a test post

**Comment by Tedko** [comment]
@zhouhanseng take a look  https://www.facebook.com/masknetwork
<img width="1772" alt="Screen Shot 2020-11-26 at 16 19 06" src="https://user-images.githubusercontent.com/6687437/100325097-1d53d300-3003-11eb-87fb-c4b731d1d3ed.png">

**Comment by zhouhanseng** [comment]
This isn't caused by DOM mismatch. There is probably a bug during image encryption.

**Comment by zhouhanseng** [comment]
@septs Facebook compresses the image on fanpage too much which probably causes this issue.

fanpage:
![image](https://user-images.githubusercontent.com/63733714/100436406-4a26e980-30da-11eb-9f21-ace600133679.png)

normal page:
![image](https://user-images.githubusercontent.com/63733714/100436569-7e020f00-30da-11eb-8b60-e070a8e09f61.png)

**Comment by Tedko** [comment]
@guanbinrui seems problem need to be solved by new stego-js

**Comment by Tedko** [comment]
#1752  

also hows the stage of new stego js?

**Comment by zhouhanseng** [comment]
![Uploading image.png…]()

**Comment by zhouhanseng** [comment]
This issue has been fixed.
