### ISSUE TITLE
[Bug] `Comment` auto paste failed on fb red packet image payload post

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1957]
## Bug Report

https://www.facebook.com/suji.yan.me/posts/3257169381072384 example
<img width="421" alt="Screen Shot 2020-11-26 at 11 59 25" src="https://user-images.githubusercontent.com/6687437/100306743-0b603900-2fdf-11eb-9129-a1bd9d8668ee.png">

basically the post encrypted  comment will fail to auto paste (disappear)

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by zhouhanseng** [comment]
I can't reproduce it.

<img src="https://user-images.githubusercontent.com/63733714/100325679-ea5e0f00-3003-11eb-8c9c-f41616d199da.png" width=700 />

**Comment by Tedko** [comment]
comment not post

**Comment by Tedko** [comment]
@zhouhanseng try to comment on my latest img payload post to reproduce

**Comment by zhouhanseng** [comment]
reproduced

Suji Yan <notifications@github.com> 于2020年11月26日周四 下午4:37写道：
