### ISSUE TITLE
[Bug] Red Packet history need improvement

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1963]
## Bug Report

RN we are using home brew server for the query test. Which got some delay and inaccurate for RedP histroy (delay for few minutes or some redP is missing).

@guanbinrui recommand use theGraph API (such as 0x did) to have an improvement of this func

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook-RedPacket-Subgraph

**Comment by Tedko** [comment]
> https://github.com/DimensionDev/Maskbook-RedPacket-Subgraph

i assume this one's using web3 api; and thegraph have sth better? @guanbinrui

**Comment by Tedko** [comment]
Current problems:
- time lag ( not real time )

**Comment by Tedko** [comment]
> Current problems:
> 
> * time lag ( not real time )

@septs take a look

**Comment by guanbinrui** [comment]
> > https://github.com/DimensionDev/Maskbook-RedPacket-Subgraph
> 
> i assume this one's using web3 api; and thegraph have sth better? @guanbinrui

This is the thegraph solution. We will introduce it this week.

**Comment by septs** [comment]
- [x] Deploy thegraph instance
- [ ] Use thegraph replace current solution

**Comment by Tedko** [comment]
cc @septs @guanbinrui

**Comment by guanbinrui** [comment]
Fixed in [v.1.33.1](https://github.com/DimensionDev/Maskbook/releases/tag/v1.33.1).
