### ISSUE TITLE
[Task] Review and revamp the labels

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1970]
We now have 80 labels in this repo and we really need to review them to simplify and formalize the labels.

**Comment by septs** [comment]
WARNING:
But delete label no any notification.
Plz update to other label and remove the label.

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/0b5eb37e1460812c9698d870d0280ddb37521a55/.github/stale.yml#L6-L15

Redesign label system after, need update the stale bot configuration
See https://github.com/probot/stale#usage

**Comment by septs** [comment]
Integrated https://github.com/actions/labeler

**Comment by yisiliu** [comment]
@guanbinrui @jk234ert @Jack-Works
