### ISSUE TITLE
[Demand] Web-based continuous localization

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1976]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other
  - /_List it here_/

## Notes

https://weblate.org

**Comment by Tedko** [comment]
ive applied a trial account. feel free to apply urself and play around.
Note: i18n is not our priority for now
