### ISSUE TITLE
[Bug] The guide popup did not present as expected

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#1983]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

![image](https://user-images.githubusercontent.com/52657989/100722443-92584b80-33fb-11eb-8173-83429fc268e2.png)

**Comment by Jack-Works** [comment]
how is that "not expected"?

**Comment by jk234ert** [comment]
Guess here you mean the popup **does not always appear** as expected @guanbinrui ?
