### ISSUE TITLE
[Bug] gitcoin.co integrate down?

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1996]
## Bug Report

https://twitter.com/LefterisJP/status/1333828296572854274?s=20
<img width="1437" alt="Screen Shot 2020-12-02 at 06 19 05" src="https://user-images.githubusercontent.com/6687437/100803539-4bec0680-3466-11eb-86e1-2e174185382f.png">

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by guanbinrui** [comment]
![encrypt](https://user-images.githubusercontent.com/52657989/100813663-c757b300-347a-11eb-99da-6119543a600a.png)
@septs

**Comment by septs** [comment]
Note: Switch to AWS Lambda (Maintenance-less)

**Comment by septs** [comment]
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-overriding-response-header

**Comment by guanbinrui** [comment]
Wait for #1999 to be merged.

**Comment by septs** [comment]
New solution is unavailable.
