### ISSUE TITLE
[Bug] Remove the "Add your own" tab in the add token dialog

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2001]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
how to add new token then?

**Comment by Tedko** [comment]
> how to add new token then?

oh gotcha. ignore the previous comment

**Comment by Tedko** [comment]
Assign to @zhouhanseng -

I've tested on latest store ver. no need to add func, (pasting erc20 contract addr in search box; work just fine ). Just delete the "Add your own" tab in the add token dialog
