### ISSUE TITLE
[Demand] Release Android App on F-Droid

### ISSUE THREAD

**Issue by trymeouteh** [DimensionDev/Maskbook#2005]
Please release the Android app on F-Droid to allow Degoogled Android users to use Maskbook on their mobile devices.

**Comment by jk234ert** [comment]
Thanks for your interest in Mask :)
We are hard working on a brand new mobile app design, and it would be on F-Droid when it's done.

**Comment by Tedko** [comment]
I will close this issue for now for Mask/MaskX mobile. We will have apk and that's sure on our list.
