### ISSUE TITLE
[Demand] Wallet Asset ranking (use Debank's ranking method)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2032]
## Catalogue

- [ ] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature

Right now our wallet asset ranking is like:

![901607148360_ pic_hd](https://user-images.githubusercontent.com/6687437/101236452-3ef04100-370c-11eb-9559-9d973673f2d3.jpg)

For debank its like:
![891607148358_ pic_hd](https://user-images.githubusercontent.com/6687437/101236455-44e62200-370c-11eb-8b11-deab681f7a0a.jpg)

lets rank it in this way:

eth -> asset A with most usd value -> asset b xxxx

**Comment by zhouhanseng** [comment]
close by https://github.com/DimensionDev/Maskbook/pull/2038
