### ISSUE TITLE
[Task] Maskbook mobile app release 1.20 tasks

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2041]
Issues & PRs block the release of new Maskbook Android & iOS version:

iOS:
None

Android:
#1959

**Comment by septs** [comment]
Next release need include pr list: #1931 #2024 #1960

**Comment by Jack-Works** [comment]
> Next release need include pr list: #1931 #1960 #2024

All of them are merged

**Comment by Tedko** [comment]
delivered
