### ISSUE TITLE
[Bug] Mobile Mask.io `Feedback` bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2086]
## Bug Report

The `mailto: xxx` link is not working.

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Jack-Works** [comment]
Did you have an email client on your device? I tried on Chrome & Windows it works when I developed this

**Comment by Tedko** [comment]
Yes. I got multiple ones on my iPhone. Assume it’s some iOS problem. Try
test on Android?

**Comment by jk234ert** [comment]
It's a new issue introduced on iOS 14, unlike previous iOS system versions, now apps need to explicitly claim some commonly defined URL schemes(like `mailto`) to open.
This would be fixed on iOS native side.
