### ISSUE TITLE
[Bug] iOS - Try download Img Payload will crash app

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2091]
## Bug Report
https://dimension.chat/group/maskbook-mobile?msg=CxnhMDSQFFuFiufFk

Take a look of the video.
How to reproduce: compose img payload, try manual, download, -> save to album -> crash;

May caused by something on ios side

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
btw - the current img payload compose on iOS experience is not that good. Should we hide that on iOS by default and add it in the setting for some users to try as beta func? @jk234ert ? is this func quiet hard to deliver on ios side?

**Comment by jk234ert** [comment]
Crash issue fixed on iOS 1.21.3(66)
Will add the `(Beta)` along with the image payload option on iOS soon.

>  is this func quiet hard to deliver on ios side?
It needs some time debugging on safari, we will try to fix it next release

**Comment by Tedko** [comment]
fixed by iOS 1.21.3(66) TF
