### ISSUE TITLE
[Task] Automatic release to Chrome and Firefox store on CI?

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#2101]
Let's try it first on the beta version

**Comment by guanbinrui** [comment]
Auto pushing release builds to specific stores will be a big help.

**Comment by Jack-Works** [comment]
we should do it on a `tag` event on git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/issues/1711

**Comment by Tedko** [comment]
already partially delivered and the rest will be discussed internally
