### ISSUE TITLE
[Bug] Fail to auto-paste encrypted image on iOS

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2102]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version: 1.21.3
  - iOS Version: 1.21.3

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
After users select `image payload` when posting an encrypted message, Mask Network iOS app fail to auto-paste the generated encrypted image into the Twitter/FB compose dialog.

### Actual Behavior
On mobile WebView console, after the encrypted message generated, error log of `TypeError: Illegal constructor` of `new DataTransfer()` printed out.
Root cause: we are using `DataTransfer` to handle the auto-paste on iOS [here](https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/extension/injected-script/addEventListener.ts#L88), but `DataTransfer` is not supported on Safari mobile [Ref](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/DataTransfer)

**Comment by Jack-Works** [comment]
@jk234ert `new DataTransfer` failed is not the root cause because the SNS input box on the mobile doesn't support paste an image into it. It should always show `AutoPasteFailedDialog`. Did it?

**Comment by jk234ert** [comment]
You mean even we replace the usage of `DataTransfer`, we still can not paste the image into the input box?

**Comment by jk234ert** [comment]
Closed this issue since this is limited by other platforms

**Comment by Jack-Works** [comment]
@jk234ert So if `AutoPasteFailedDialog` shows, it works normally. If not, it is a bug
