### ISSUE TITLE
[Demand] Revamp the buy now button

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2110]
## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

According to [Which Cryptocurrencies does Transak support?](https://help.transak.com/en/articles/4410381-which-cryptocurrencies-does-transak-support) Transak only supports a few famous tokens. We can fetch this list from [/currencies/crypto-currencies](https://transak.stoplight.io/docs/transak-docs/1.swagger.yaml/paths/~1currencies~1crypto-currencies/get). Now the plan is we can check the existence of a specific token from that list and display a more specific UI to our user.

**Comment by alis-xia** [comment]
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=885%3A2189
![image](https://user-images.githubusercontent.com/52199365/102192191-68238500-3ef5-11eb-977f-824feedc46f9.png)

**Comment by Tedko** [comment]
@zhouhanseng fix this?

**Comment by zhouhanseng** [comment]
okay
