### ISSUE TITLE
[Bug] Hide small balance token in wallet

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2117]
## Bug Report

<img width="1899" alt="Screen Shot 2020-12-16 at 19 41 05" src="https://user-images.githubusercontent.com/6687437/102346988-b494c080-3fda-11eb-882b-b4b2fa82e8e2.png">

We can follow the design of Rainbow wallet. Hide the smaller balance token 
![IMG_8893](https://user-images.githubusercontent.com/6687437/102347575-8a8fce00-3fdb-11eb-8440-4663999b6a5a.PNG)
![IMG_8894](https://user-images.githubusercontent.com/6687437/102347580-8cf22800-3fdb-11eb-8f76-0ab03382ab89.PNG)

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
Add an `Less` button should be fine @xiazhiming @zhouhanseng 

余额＜5 USD && token数量 > 5 个 之后的 都hide？

**Comment by Tedko** [comment]
ps.

小一点的屏幕上 13inch 能不滑动显示的只有三四个


<img width="1354" alt="Screen Shot 2020-12-17 at 02 29 03" src="https://user-images.githubusercontent.com/6687437/102390704-b7f66f00-400f-11eb-9595-e94f5971b8eb.png">

**Comment by xiazhiming** [comment]
Token 列表 
1. balance 非稳定币显示小数点6位即可，USDT、USDC、DAI、CUSDT、GUSDT、等稳定币显示小数点2位即可。
2. 0 余额隐藏。
3. 按 Value 大小进行倒叙排列。
4. 小于 1 美金添加 Load More /  Show Less 文字按钮。

**Comment by Tedko** [comment]
cc @guanbinrui @zhouhanseng

**Comment by Tedko** [comment]
Also is debank api stable enough? should we add zerion as backup?

**Comment by xiazhiming** [comment]
https://debank.com/ranking/stablecoin Stable coins in the reference list。

**Comment by Tedko** [comment]
@lelenei tested on my iOS ver. Found several small bugs.-

**Comment by Tedko** [comment]
![image](https://user-images.githubusercontent.com/6687437/104834879-9a9e1480-58dd-11eb-8dc8-73e2b98e1c13.png)![image](https://user-images.githubusercontent.com/6687437/104834881-9e319b80-58dd-11eb-8023-5b8047e30a5b.png)

Don't hide ETH since if no eth no gas (so no way to send or do Transactions) 


Thoughts @xiazhiming ?

**Comment by Tedko** [comment]
@xiazhiming 以太 balance 低 也不应该隐藏。不然gas和转账没法处理。

**Comment by xiazhiming** [comment]
@lelenei lei 不管钱包有没有资产。默认第一行显示ETH，banlacer小数位精度6位。其他依照以前进行fix。

**Comment by guanbinrui** [comment]
This feature has shipped.
