### ISSUE TITLE
[Bug] Fail to display contacts in dashboard on mobile apps

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2150]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [x] Android

  - Maskbook Version: 1.22.2
  - Android Version:

- [x] iOS
  - Maskbook Version: 1.22.2
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
On Mask Network mobile apps, open dashboard -> Contacts, no contacts displayed

### Actual Behavior
Found following console logs, not sure if they are helpful in debugging:
![Snipaste_2020-12-29_09-05-57](https://user-images.githubusercontent.com/7972003/103251808-6bb71180-49b5-11eb-9be9-a7130d4e9414.png)
![Snipaste_2020-12-29_09-06-21](https://user-images.githubusercontent.com/7972003/103251810-6d80d500-49b5-11eb-80fe-2d845c9363b8.png)
![Snipaste_2020-12-29_09-07-36](https://user-images.githubusercontent.com/7972003/103251813-6f4a9880-49b5-11eb-8e42-aa4341a2ceab.png)

**Comment by Jack-Works** [comment]
that's strange

**Comment by Tedko** [comment]
any idea why?

**Comment by jk234ert** [comment]
Should be an UI issue.
Contacts list disappears when the viewport's width <= 600
