### ISSUE TITLE
backup filename should include user & network name

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#218]

**Comment by Jack-Works** [comment]
There is {"network":"facebook.com","userId":"100027562******"} in the backup file

**Comment by neruthes** [comment]
It should not. The backup file is the whole keystore. Persona-specific backup is never planned, except for persona key export with mnemonic words.

**Comment by Misaka-0x447f** [comment]
So consider a tip about ‘backup contains all your data’

**Comment by Jack-Works** [comment]
#11 

> So consider a tip about ‘backup contains all your data’
