### ISSUE TITLE
[Bug] No more inline images

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2198]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [] Chrome

  - Mask Version:
  - Browser Version:

- [x] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info

The size of the assets of some plugins is too large to compress into a fit size for the Firefox store. We need them to be reduced to a smaller size. Those plugins include ITO and Election2020.

<img width="1029" alt="test_1" src="https://user-images.githubusercontent.com/52657989/104032123-a8320b00-5208-11eb-827f-99b752d1f3ad.png">

**Comment by Jack-Works** [comment]
@guanbinrui cause we have some files that directly turn images into base64 data url

**Comment by guanbinrui** [comment]
> @guanbinrui cause we have some files that directly turn images into base64 data url

Directly inline will be turned into using [useBase64](https://github.com/DimensionDev/Maskbook/blob/090f97bde2b4e5e6033d043f8a617fab884cb405/packages/maskbook/src/utils/hooks/useBase64.ts) hook instead.

**Comment by Jack-Works** [comment]
> > @guanbinrui cause we have some files that directly turn images into base64 data url
> 
> Directly inline will be turned into using [useBase64](https://github.com/DimensionDev/Maskbook/blob/10d204195b174ed99ae7f9985b702dce9c5f6d2d/packages/maskbook/src/utils/hooks/useBase64.ts) hook instead.

That's weird. Why not use our `<Image />` element? It supports those

**Comment by guanbinrui** [comment]
> > > @guanbinrui cause we have some files that directly turn images into base64 data url
> > 
> > 
> > Directly inline will be turned into using [useBase64](https://github.com/DimensionDev/Maskbook/blob/10d204195b174ed99ae7f9985b702dce9c5f6d2d/packages/maskbook/src/utils/hooks/useBase64.ts) hook instead.
> 
> That's weird. Why not use our `<Image />` element? It supports those

We use images as CSS backgrounds here.
