### ISSUE TITLE
[UX] Error handling: What if the user tries composing with Maskbook while there is no active account-keypair combination in the local database

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#22]
Let nous think.

**Comment by yisiliu** [comment]
I think there are two options:
1. Replace the appended composing area with [Get Started] button
2. The appended composing area won't even appear if there is no key.

**Comment by neruthes** [comment]
It might be possible that the account ownership proof post and the cipher text payload can co-exist in one post...?

**Comment by yisiliu** [comment]
> It might be possible that the account ownership proof post and the cipher text payload can co-exist in one post...?

It's better to split them in practice for clearer identifiers.

**Comment by neruthes** [comment]
Now we likely have 3 options:

- Post now, prove later
- Show banner, hide panel (for now)
- Show banner, disable checkbox (next version)

I personally prefer the 2nd.

**Comment by neruthes** [comment]
What is the current behavior? cc @Jack-Works

**Comment by neruthes** [comment]
Ugh... @Jack-Works Could you explain the current behavior when you are free?

**Comment by Jack-Works** [comment]
Notify user they are not inited when decrypting but not leading them to the welcome.

**Comment by neruthes** [comment]
> Notify user they are not inited when decrypting but not leading them to the welcome.

Got it. Thank you.

**Comment by neruthes** [comment]
> Notify user they are not inited when decrypting but not leading them to the welcome.

It is for when the user cannot decrypt properly; now what for when the user tries composing?

**Comment by Jack-Works** [comment]
They cann't compose. Background will throw an error but not showing to the user.
