### ISSUE TITLE
[Bug] The result of a retweeted post run into its parent post

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2215]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

![image](https://user-images.githubusercontent.com/52657989/104297612-09eebf80-54fe-11eb-9c08-0bbfd31c38b4.png)
![image](https://user-images.githubusercontent.com/52657989/104142389-6070d680-53f6-11eb-9e31-1bd413f40806.png)

**Comment by guanbinrui** [comment]
@Jack-Works  Any ideas?

**Comment by Tedko** [comment]
@Jack-Works

**Comment by Jack-Works** [comment]
@guanbinrui please leave a URL that can reduce this bug and I'll take a look at it later

**Comment by guanbinrui** [comment]
> @guanbinrui please leave a URL that can reduce this bug and I'll take a look at it later

This bug is sneaky. Actually, I failed to reproduce it.

**Comment by Tedko** [comment]
sanshui able to reproduce again in last ITO

**Comment by Tedko** [comment]
maybe this issue is only related w/ ITO related content cc @zhouhanseng

**Comment by Tedko** [comment]
Any feedback? Not crucial but worry it will affect Ito
