### ISSUE TITLE
[RFC] Sisterhood Membership Certificate (SSMC) v1.0.0.0 [Draft]

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#222]
# Background

- #76
- #225

# Basic Idea

Include entire trust chain of the inviter.

Comprehensive certificate from D03 to D04 should include the trust chain of D03 and the simple certificate for D04.

When inviting D05, D04 may simply stack up 2 simple certificates (D02 to D03, D03 to D04) as its InviterTrustChain, and grant the simple certificate from D04 to D05; this should be enough to form a comprehensive certificate.

# Metadata

| Key | Value |
| --- | --- |
| AppLabel | Maskwork--SisterhoodMembershipCertificate |

# Content Structure

## Simple Certificate

- MisakanetID
- InviterPublicKey
- InviteeAutobiography

## Comprehensive Certificate

- MisakanetID
- InviterPublicKey
- InviteeAutobiography
- TrustChain

## InviterTreeTrustChain

If the inviter is a root, the value of `InviterTrustChain` should be string `"I AM YOUR FATHER"`.

If it is not, its value should be a list of `Maskwork--ImoutoTrustChainSection`:

```
{
    "...": "... // Other nodes",
    "InviterTrustChain": [
        {
            "Meta": {
                "PayloadSpec": "DeadSeaOldScroll",
                "Version": 1
            },
            "Content": {
                "_": {
                    "AppLabel": "Maskwork--SisterhoodMembershipCertificate-Simple",
                    "AppVersion": 1,
                    "Time": 1569374955715,
                    "MisakanetID": "...",
                    "InviterPublicKey": { ... },
                    "InviterPublicKeyFingerprint": { ... },
                    "InviteeAutobiography": { ... }
                }
            },
            "Signature": {
                "_": {
                    "BaseSig": "..."
                }
            }
        }
    ]
}
```

# DeviceAutobiography node

## Example

```
{
    "Meta": {
        "PayloadSpec": "DeadSeaOldScroll",
        "Version": 1
    },
    "Content": {
        "_": {
            "AppLabel": "Maskwork--DeviceAutobiography",
            "AppVersion": 1,
            "Time": 1569374955715,
            "PublicKeyFingerprint": {
                "_": "BCD1FF19582A9B8D5CE9CB780E18C651318756B6",
                "hash": "SHA-1",
                "encoding": "hex"
            },
            "PublicKey": {
                "_": "ArxApPYD24e+RjrKyYMpG/2QemXLfxsISb+aFFbltJ1f",
                "encoding": "base-64"
            },
            "DeviceName": "Nietzsche"
        }
    },
    "Signature": {
        "_": {
            "BaseSig": {
                "_": "WFceyl2VOyvyeaqkTodUI1XulcXQkRVQvh3U65vvMUuRq2ln9ozlECaZYLkKq9HHWKucm9sc2e52y32I1Foikg==",
                "encoding": "base-64"
            }
        }
    }
}
```

**Comment by Tedko** [comment]
looks cool. Need more feedbacks from our Devs

**Comment by neruthes** [comment]
All 225-based RFCs are now being dismissed.
