### ISSUE TITLE
[Bug] ITO card refund eth less than zero 

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#2224]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info

<img src="https://user-images.githubusercontent.com/63733714/104183366-d1db7400-544c-11eb-9d86-706b427dd427.png" width=600 />

### Actual Behavior

/_What happened?_/

**Comment by guanbinrui** [comment]
A subgraph bug?

**Comment by zhouhanseng** [comment]
yes, amount - amount_sold < 0

![image](https://user-images.githubusercontent.com/63733714/104263542-c166e000-54c4-11eb-8f61-0066aa82d354.png)

**Comment by guanbinrui** [comment]
> yes, amount_sold is wrong, it should equal to '40000000'
> 
> ![image](https://user-images.githubusercontent.com/63733714/104263542-c166e000-54c4-11eb-8f61-0066aa82d354.png)

Could you paste the pid and network too?

**Comment by yisiliu** [comment]
In this case, what's `amount_sold` and what is `amount_bought`? ETH vs MSKA

**Comment by zhouhanseng** [comment]
@guanbinrui 0x0ad9a012939929bc2b6d2ea17d33840827bd2264550701c772a7d3a6bb703668 ropsten

@yisiliu amount_sold is ETH, amount_bought is MSKA

**Comment by yisiliu** [comment]
So basically you set ETH:MSKA to 100000000:1 and you swapped twice with 0.00000000006 each. I don't think this is a problem at all. Where is that 40000000000000000000000?

**Comment by yisiliu** [comment]
And I saw `exchanged_tokens = 400000000000000060000000`.

weird

**Comment by yisiliu** [comment]
Can you try this in the test? @zhouhanseng

**Comment by zhouhanseng** [comment]
@yisiliu I set ETH:MSKA to 1:100000000, 40000000000000000000000 is wrong.

**Comment by yisiliu** [comment]
Alright I see. This is a bug in the contract - let me fix it.
ref: https://github.com/DimensionDev/InitialTwitterOffering/blob/master/contracts/ito.sol#L162 and https://github.com/DimensionDev/InitialTwitterOffering/blob/master/contracts/ito.sol#L159

**Comment by zhouhanseng** [comment]
@yisiliu I'd like to add the test.

**Comment by yisiliu** [comment]
@zhouhanseng please do so. Thank you!

**Comment by yisiliu** [comment]
@zhouhanseng can you rebase to this branch: https://github.com/DimensionDev/InitialTwitterOffering/pull/9?

**Comment by zhouhanseng** [comment]
ok

**Comment by zhouhanseng** [comment]
close by https://github.com/DimensionDev/InitialTwitterOffering/pull/9

<img src="https://user-images.githubusercontent.com/63733714/104672724-4e0adb80-571b-11eb-90b9-5b490dbae10a.png" width=700 />
