### ISSUE TITLE
[Bug]  ITO Card swap active state

### ISSUE THREAD

**Issue by xiazhiming** [DimensionDev/Maskbook#2225]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:11.0.1 (20B29)

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version: 1.22.3
  - Browser Version: 87.0.4280.88 (Official Build) (x86_64)

- [x] Firefox

  - Mask Version: 1.22.3
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
Ito card display
1. fix the active state
- 1. Nor Started  2. Ongoing /Out of Stock 3. Expired.
 2. fix the Swapped display.
See Figma Question 47-53.
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=2797%3A14425
### Actual Behavior

/_What happened?_/

**Comment by guanbinrui** [comment]
close by #2227.
