### ISSUE TITLE
[Demand] Integrate dextools.io for dex *such as uni/sushi/dex price

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2226]
## Catalogue

> 说起来，想给Mask提产品小建议，是不是考虑推特上接入dextools.io，gecko和cmc对degen们来说报价延时太高了[LetMeSee]

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Users suggest (in chinese above) we should integrate dextool for low latency (cmc/gecko have high latency on price).

Dextool is a cool tool/price feed provider of token price on dexs.

## Part 2: Problem to Solve

cmc/gecko have high latency on price.

## Part 3: Expected Behavior

User can switch the default price provider to dextool if they want

**Comment by yisiliu** [comment]
@Tedko You have to fill in the template when creating the issue, or, what's the point of the template? This is a **public community** project so everyone needs to follow the rules including all the team members.

**Comment by Tedko** [comment]
> @Tedko You have to fill in the template when creating the issue, or, what's the point of the template? This is a **public community** project so everyone needs to follow the rules including all the team members.

added
