### ISSUE TITLE
[RFC] Database Backup Specification v1.0.0.0

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#224]
## Metadata

Field | Value
--- | ---
Manifest | [Meta/Article-3](https://github.com/DimensionDev/Meta/blob/master/articles/3--rfc-peer-review.md)
Purpose | Documentation
Feedback deadline | 2019-12-19 12:00:00 UTC
Explicitly designated reviewers | ...

## Background

- #218

## See Also

- #194
- #195
- #225

## Database Tables for Backup

Refer to #223.

### File Name

The file name of a backup should be `Maskbook-Database-Backup-YYYY-MM-DD.bin`.

### Structure

The total structure of the file should be a JSON with UTF-8 encoding.

```json
{
    "Meta": {
        "PayloadSpec": "DeadSeaOldScroll",
        "Version": 1
    },
    "Content": {
        "_": {
            "AppLabel": "maskbook.com--database-backup",
            "AppVersion": 1,
            "Time": 1569374955715,
            "db": {
                "table1": [
                    {
                        "col1": "value 1",
                        "col2": "value 2"
                    }
                ]
            }
        }
    },
    "Signature": {
    }
}
```

### Handling Custom Types

// TODO

**Comment by Jack-Works** [comment]
We already have a backup format.

**Comment by neruthes** [comment]
> We already have a backup format.

Have we put that into documentation? If not, I hope this is a good time to have it done :)

**Comment by Artoria2e5** [comment]
Basically this if I am not mistaken. https://github.com/DimensionDev/Maskbook/blob/65108836a64a1e2d02ef5c0583a3303f2be40230/src/utils/type-transform/BackupFile.ts#L51-L73

**Comment by Artoria2e5** [comment]
Besides the 232 thing about only storing `d` there's also the concern about many profiles having the same key. We might as well end up with:

```TypeScript
export type keyNamedRef = string
export type JsonKey = JsonWebKey | keyNamedRef
export interface BackupJSONFile {
    maskbookVersion: string
    version: 42
    personae: Array<{
        privateKey: JsonKey
        localKey: JsonKey
        profiles: Array<{
            network: string
            userId: string
            previousIdentifiers?: { network: string; userId: string }[]
            nickname?: string
        }>
    }>
    people?: Array<{
        network: string
        userId: string
        publicKey: JsonKey
        previousIdentifiers?: { network: string; userId: string }[]
        nickname?: string
        groups?: { network: string; groupID: string; virtualGroupOwner: string | null }[]
    }>
    namedKeys?: {
        // keyNamedRef
        [ref: string]: JsonWebKey
    }
    grantedHostPermissions: string[]
}
```

**Comment by neruthes** [comment]
Since #223 is ratified, we can now work on this RFC.

**Comment by Jack-Works** [comment]
Question 1: Why use an extname like `.bin` instead of `.json`?

Question 2: Doesn't this better?
```json
{
  "version": 1,
  "type": "maskbook-database-backup",
  "content": {
    "maskbookVersion": "1.8.4",
    "timestamp": 1569374955715,
    "databaseName": [
      {
        "col1": "value 1",
        "col2": "value 2"
      }
    ]
  }
}
```

**Comment by neruthes** [comment]
All 225-based RFCs are now being dismissed.
