### ISSUE TITLE
[Demand] add zerion for wallet/token info “backup”

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2252]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

For now we're using debank for fetching info on wallet/token (portfolio);
We may wanna use Zerion as another solution for backup or combine the data from the 2 sources

## Part 2: Problem to Solve
As mentioned above.
## Part 3: Expected Behavior
May need to add a Wallet info source 'debank'. But we can actually ignore that for now. 
## Notes

**Comment by Tedko** [comment]
P.S.: rainbow wallet is using zerion api etc. pls check and learn

**Comment by Tedko** [comment]
Also. There're several cases when debank is not updating the price /info of new token (vice versa for zerion); eg:
https://debank.com/portfolio/0x934b510d4c9103e6a87aef13b816fb080286d649
![image](https://user-images.githubusercontent.com/6687437/104854824-e97e9500-5943-11eb-82d1-3e66be4301f3.png)



While onzerion/ rainbow ![image](https://user-images.githubusercontent.com/6687437/104854851-fe5b2880-5943-11eb-8cdd-a8ee9bac704a.jpeg)

We need to merge these token info so we can have the most updated ones. Need some way to work around. Not top priority to have this merge func ready

**Comment by Tedko** [comment]
@lelenei let me know the progress so far

**Comment by lelenei** [comment]
> @lelenei let me know the progress so far

I have done some functions in pr#2237, and after the merge, I will submit the next part of the code

**Comment by guanbinrui** [comment]
Replaced by #2578.
