### ISSUE TITLE
[Bug] Add loading indicator and "empty assets" messages to Dashboard Wallet page while fetching wallet assets

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2261]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
In Mask Network dashboard wallet page, since we need to request the wallet assets information by network requests, this page should display a loading indicator before network requests finish. We also need messages like "No collectibles/No Assets Found" when the current wallet is empty.

### Actual Behavior
The wallet page just presents a blank view before network requests finish.
<img width="1099" alt="Snipaste_2021-01-20_09-33-34" src="https://user-images.githubusercontent.com/7972003/105114795-97d03900-5b02-11eb-98e3-c3dbfc153800.png">

The wallet page only displays a blank view when there are no collectibles in the wallet.
<img width="1113" alt="Snipaste_2021-01-20_09-34-33" src="https://user-images.githubusercontent.com/7972003/105114907-cfd77c00-5b02-11eb-86e5-afc7e80f9f0d.png">

### Expected Behavior
1. Display "Loading..." before network requests finish on the wallet page, for both "Token" and "Collectibles" tabs. Please refer to the style in the "Add Token" dialog.
2. Display "No Data" when there are no assets/collectibles found in the wallet. Please refer to the style in the "Activity" dialog.

**Comment by Tedko** [comment]
https://github.com/DimensionDev/Maskbook/issues/2117

Better not use `empty assets`

on layer 1 of eth we should better always display eth since that the gas of any tx etc. Maybe add DAI as a default currency (stable coin) even if the balance is 0

**Comment by Tedko** [comment]
cc @jk234ert

**Comment by nuanyang233** [comment]
@jk234ert There are two album in collectibles.So we need show duplicate indicator and empty assets?

**Comment by nuanyang233** [comment]
@lelenei I added the loading indicator for collectibles
