### ISSUE TITLE
[Demand] Add mask's domain to replace `https://arweave.net` in file service 

### ISSUE THREAD

**Issue by haihongS** [DimensionDev/Maskbook#2262]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
The endpoint of file service is `https://arweave.net`, but generally we should use domain managed from Mask e.g. `fs.mask.io` instead and configure CNAME or other redirect strategy to suit future feature.

With the help of CDN, we can then configure the visit from China Mainland CNAME to meson service, and keep others to official endpoint.

## Part 2: Problem to Solve
As mentioned above.

## Part 3: Expected Behavior
- File Service Endpoint: `https://xxx.mask.io`
- Default CNAME to `https://arweave.net`
- Visit from China Mainland CNAME to Meson: `https://coldcdn.com`

**Comment by septs** [comment]
plz set a title on this issue

**Comment by yisiliu** [comment]
FYI this is the conclusion of what @haihongS and I discussed yesterday.
