### ISSUE TITLE
[Bug] File Service bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2268]
## Bug Report

AR File Sevice is down(?)

<img width="1552" alt="Screen Shot 2021-01-21 at 09 07 59" src="https://user-images.githubusercontent.com/6687437/105260178-4a1e0400-5bc8-11eb-8c5e-5e2a4c7b2d24.png">

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by septs** [comment]
Wait for next release.
