### ISSUE TITLE
[Demand] Refresh trending data from CMC intimately

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2276]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

The price data from the widget API is slow updating. The WebSocket price API (wss://stream.coinmarketcap.com/price/latest)  can subscribe the price of specific coin.

<img width="945" alt="test" src="https://user-images.githubusercontent.com/52657989/105564578-c564ee80-5d5d-11eb-91b6-a7a745869bfd.png">

**Comment by Tedko** [comment]
We will close this for now. For stage ver we're using paid CoinGecko service provider fyi.
