### ISSUE TITLE
[UX] Account ownership verification process consolidation [draft]

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#23]
# Background

It can be hard to ensure that the automatic verification posting mechanism can work, so we need some saturation measures to ensure that the public key is posted, in bio or in post.

# Some basic change on setup

<img width="696" alt="Screen Shot 2019-04-24 at 12 09 59" src="https://user-images.githubusercontent.com/2139261/56658417-1ed05300-668a-11e9-901f-2910138a0633.png">

<img width="725" alt="Screen Shot 2019-04-22 at 06 27 43" src="https://user-images.githubusercontent.com/2139261/56486630-c6515800-64c7-11e9-9fb9-e65603ca4004.png">
 
# Measure 1: Just-in-time Self-checking

As soon as the setup is completed (proof(s) automatically added), the extension shall immediately check if the proof is really added to bio and really posted on timeline. If no proof is online, the user will receive alert message like "automatic proof failed, please add manually", and will be guided to post the public key.

Error handling: User bio may have no enough space for the public key. This will lead to failure of bio update and the other method of proof is the only possible way. In the best case, we can detect the available space in user bio so we can ban the option when it is not possible.

# Measure 2: Continued Self-checking

The extension shall periodically check the proofs of claimed accounts of the user to see if they are validly connected.

If the proof is no longer available, the user will receive alert message like "proof broken, please re-add". This alert should appear only when the user is logged in as the Facebook account.

**Comment by yisiliu** [comment]
1. Editable after posting? What's the point of creating such a post instead of adding to some random database if the proof post is not considered the "PROOF POST" that can be accessed for future reference?

2. If the user chooses both, how do you guide them? We have two different payloads for two methods. How do you solve this?

----- My suggestion:
Instead of insisting on your saturation family, we should stay the same options for posting the public proof for users to choose. Make this process an easy and concise one.

**Comment by neruthes** [comment]
1. What "editable"?
2. The user can choose both when and only when the user is at Automatic Mode. If the user chooses Manual Mode, the user will be directed to bio. (Why prioritize bio? Because it is more efficient than proof post.)

**Comment by neruthes** [comment]
I see. The "editable" appeared in the second option box in Automatic Mode.

I may adjust the wording.

**Comment by yisiliu** [comment]
> 2. The user can choose both when and only when the user is at Automatic Mode. If the user chooses Manual Mode, the user will be directed to bio. (Why prioritize bio? Because it is more efficient than proof post.)

Automatic mode may not be accepted by users since it will create a post without the user's permission

**Comment by yisiliu** [comment]
👍Let's keep this design for now
