### ISSUE TITLE
Feature Request: Regenerate Key

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#230]
Contributed by @nyartsgnaw

Related to #70 

For now, if power user go options - Setup - Setup and download his json key-files, he will only get the old key pairs instead of `re-generate and download the new key`.

For now there will be some problems for:
- If the users want to use a different key (such as an ETH key pair)
- If the users want to generate a new Maskwork key pair

Let's ask @nyartsgnaw for more feedbacks.

**Comment by neruthes** [comment]
This is part of #70, indeed.

**Comment by Jack-Works** [comment]
closed by #242
