### ISSUE TITLE
[Bug] File service down on v1.25.0 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2305]
## Bug Report
Cannot use file service. Cant upload files.
PS: we need to add the test streamline of these plugins

<img width="1479" alt="Screen Shot 2021-01-29 at 02 42 34" src="https://user-images.githubusercontent.com/6687437/106183831-bc4fa380-61db-11eb-9d89-37509f5bbd11.png">

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [x] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/pull/2283#issuecomment-766708329

**Comment by guanbinrui** [comment]
> #2283 (comment)

@septs Could please you test those links? I think they already online now.

**Comment by septs** [comment]
![Uploading image.png…]()
