### ISSUE TITLE
[Demand] Define how many decimals to show for some famous token

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#2309]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

For example, Metamask shows amount respectively when click max button for transferring token, it display only 6 decimals for ETH and all decimals for MASKA that leads a trim, although they are both 18 decimals.

<img src="https://user-images.githubusercontent.com/63733714/106229086-ca2b1600-6227-11eb-80b1-ecc53ede686b.png" width=500 />

<img src="https://user-images.githubusercontent.com/63733714/106229314-4c1b3f00-6228-11eb-8bf8-626cff391be6.png" width=500 />

**Comment by Tedko** [comment]
IMO we can just follow metamask; on mobile we can learn from rainbow wallet
