### ISSUE TITLE
[Bug] inject failed

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#2319]
# Bug Report

![image](https://user-images.githubusercontent.com/3842474/106414817-87b44400-6488-11eb-8158-d490a27d540a.png)

## Environment

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
Version: v1.23.3-113-g81cd5786-dirty
Tag Name: v1.26.0
Build Date: 2021-02-01T04:16:05.027Z
Commit Hash: 81cd5786
Commit Date: 2021-02-01T04:11:58.000Z
Remote URL: git@github.com:DimensionDev/Maskbook.git
Branch Name: feature/integrate-stego-js-v2

### Actual Behavior

/* What happened? */

**Comment by Jack-Works** [comment]
I believe your problem is a build failure but I'm still adjusted the way how inject works
