### ISSUE TITLE
Mobile QR is not efficient enough

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#232]
https://github.com/DimensionDev/Maskbook/issues/186#issuecomment-533059735:
> When there are more than 1 identities the QR code becomes too large to scan. So we really need to find another way to sync between devices.

Our current QR encoding scheme is woefully inefficient: we put a json with long key names and base64-ed data through QR's 8-bit "byte" encoding, and get a huge image back. 

### The JSON level

The problems with `JsonWebKey` noted here should be handled by #224.

<details>
<summary>A big ol' backup (636b minimized)</summary>

```JSON
{
    "version": 1,
    "whoami": [
        {
            "network": "facebook.com",
            "userId": "100034588593645",
            "previousIdentifiers": [],
            "localKey": {
                "alg": "A256GCM",
                "ext": true,
                "k": "REDACTEDREDACTEDREDACTEDREDACTEDREDACTED***",
                "key_ops": [
                    "encrypt",
                    "decrypt"
                ],
                "kty": "oct"
            },
            "publicKey": {
                "crv": "K-256",
                "ext": true,
                "x": "7seqxT72nd8UhC8tIWKqux0LWT-de7sDVSYqO4vLJnI",
                "y": "oNRjB320h3p4TUbjZmHk5iZByPp0Q6aT4MX9BpA2mmM",
                "key_ops": [
                    "deriveKey"
                ],
                "kty": "EC"
            },
            "privateKey": {
                "crv": "K-256",
                "ext": true,
                "d": "REDACTEDREDACTEDREDACTEDREDACTEDREDACTED***",
                "x": "7seqxT72nd8UhC8tIWKqux0LWT-de7sDVSYqO4vLJnI",
                "y": "oNRjB320h3p4TUbjZmHk5iZByPp0Q6aT4MX9BpA2mmM",
                "key_ops": [
                    "deriveKey"
                ],
                "kty": "EC"
            }
        }
    ]
}
```
</details>

What problems are we seeing here?

* We are saving both the public and the private key when they have the exact same `x` and `y`. Of course they do; they are the same effing key.
 * The maths say that we can get `y` from `x`, and we actually use that for importing the key.
 * This ain't the worst part: the maths also say we can get the public `x` and `y` from the private `d`. We are needlessly wasting five times the space for all these.

Let's yank down the useless parts and try again. Boom! 364b minimized.

### Other corners
There are some small overheads that can be reduced by:
* JSON: binary formats. Pick one, pack it.
* Base64: compression. Using json already forces us onto the less-efficient byte (as compared to `alphanumerical`) encoding of QR with the special characters it uses, so why don't we push it further? Even `zlib` can effectively revert the damage base64 does to the data size.

**Comment by Tedko** [comment]
#195 How will this help? *(195 already told us the 12 words won't be enough)

**Comment by neruthes** [comment]
Any update? If no further question, this will be dismissed since it is nonexistent after we deliver #70 and #195.

**Comment by Tedko** [comment]
> Any update? If no further question, this will be dismissed since it will be nonexistent after we deliver #70 and #195.

>This ain't the worst part: the maths also say we can get the public x and y from the private d. We are needlessly wasting five times the space for all these.

@neruthes yes the above part also specified in #70 #195 so we can maybe combine **Other corners** in this issue to #195 maybe?

**Comment by yisiliu** [comment]
QR code is never a problem with Maskbook. The debate regarding QR code originated from what we had with TesserPG, whose keystore payload is way too long to store. Maskbook never has this problem since we would only store an encrypted private key and would never store the entire keystore in it.

**Comment by Jack-Works** [comment]
shoud be closed by https://github.com/DimensionDev/Maskbook/pull/284
