### ISSUE TITLE
[Demand] Image payload customization display

### ISSUE THREAD

**Issue by xiazhiming** [DimensionDev/Maskbook#2324]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
image payload customization and  Distinguish between permission display.
## Part 2: Problem to Solve
Add image payload custom upload
[figma design  ](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=2581%3A0)
[Documents ](https://xiazhiming.github.io/MaskPM/Forestage/h08ImagePayload.html#%E6%96%87%E5%AD%97%E9%9A%90%E5%86%99)

**Comment by Jack-Works** [comment]
please give this issue a title thanks
