### ISSUE TITLE
[Demand] Remove COTM and Election2020 from the composition dialog

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2336]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Jack-Works** [comment]
we can remove the send-side but not the receive-side. is it?

**Comment by guanbinrui** [comment]
> we can remove the send-side but not the receive-side. is it?

Can be totally removed now.

**Comment by guanbinrui** [comment]
Oh, those flags already off. So I'm closing this issue.
