### ISSUE TITLE
[Bug] metamask lock/unlock event or correspond listener not works

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#2354]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by zhouhanseng** [comment]
https://github.com/MetaMask/metamask-extension/issues/10368

**Comment by guanbinrui** [comment]
Does MetaMask able to emit a corresponding unlock event? We can request accounts again when we receive that event. Actually, no need to emit account changed event after unlocking MetaMask.

**Comment by zhouhanseng** [comment]
close by https://github.com/DimensionDev/Maskbook/pull/2404
