### ISSUE TITLE
[Bug] 0x swap calculate amount mistake

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#2394]
## Bug Report 
Using 0x, DAI -> MUSE, when input DAI, the calculating amount is always the same.

<img src="https://user-images.githubusercontent.com/63733714/107869560-762c5c80-6eca-11eb-95b6-88bb7cc2a935.png" width=500 /> 

<img src="https://user-images.githubusercontent.com/63733714/107869565-847a7880-6eca-11eb-8f83-2077c2680f98.png" width=500 /> 

But when input the same MUSE amount: the DAI would change, and is different:

<img src="https://user-images.githubusercontent.com/63733714/107870916-df669c80-6ed7-11eb-87f1-50f537955dbe.png" width=500 /> 

I think this is the bug of 0x api since uniswap works well.

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment]
Also cc @guanbinrui

**Comment by Tedko** [comment]
any update on this?

**Comment by guanbinrui** [comment]
closed by #2398
