### ISSUE TITLE
Turn dependabot off

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#240]
dependabot is giving us a lot of upgrade requests for dependencies. The problem is that it creates a branch for each update, resulting in a lot of bloat in the list of branches.

I am fairly sure that we will be fine with manual `yarn install --upgrade` commands, as long as the dependency security alert is enabled.

**Comment by Tedko** [comment]
Sure. Do it with the best way possible.

**Comment by Misaka-0x447f** [comment]
Some dependencies may work for this project while some are not. It could be important to merge only one dependent on each test. It may work as intend once CI test part is ready.

**Comment by Jack-Works** [comment]
objection. manually upgrade is very likely to forget.

**Comment by Artoria2e5** [comment]
Try npm-check:

```
yarn global add npm-check
npm-check
```

**Comment by Tedko** [comment]
If no further discussion i will close this issue.
