### ISSUE TITLE
[Demand] Snapshot DB before each side-effect operation

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2442]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Jack-Works** [comment]
only for wallet db?

**Comment by guanbinrui** [comment]
> only for wallet db?

Yes, wallet DB is the priority, and we should audit the wallet.ts. All side-effect operations should be verified or rewrite in another no side-effect way if possible.
