### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#25]
Current Status: Available
- ✔ Background Service
- ✔ Options Page
- ✔ Content Script
- ✔ Injected Script

Components:
- ✔ Encryption
- ✔ Decryption
- ✔ Welcome from the webpage
- ✔ Welcome from the options page
- ✔ Auto verify post
- ✔ Auto verify bio
------------------------------------------------------------------------
- [x] Web Extension #13
- [x] Custom events registered many times
- [x] Inject error Error: "document.documentElement is null"
- [x] Error: conflictAction prompt not yet implemented in Backup
- [x] Error: Permission denied to access property Symbol.iterator (addEventListener.ts:40)
------------------------------------------------------------------------
- [ ] Publish on Firefox

**Comment by Jack-Works** [comment]
mention for who are interested in Firefox supports in https://www.reddit.com/r/crypto/comments/bevx1s/maskbook_surrender_no_privacy_to_youknowwho/

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/commit/4072b3cfb773a78c44c3a9b42bb2cccc9f65edb6

**Comment by Jack-Works** [comment]
Related https://github.com/facebook/react/issues/15759

**Comment by yisiliu** [comment]
assigned @guanbinrui

**Comment by Tedko** [comment]
@guanbinrui  expectation?

**Comment by guanbinrui** [comment]
@yisiliu @Tedko @Jack-Works Firefox is fully supported waiting for merge the [PR](https://github.com/DimensionDev/Maskbook/pull/83) and release.

**Comment by Jack-Works** [comment]
Will test later

**Comment by Jack-Works** [comment]
closed by 0298aa93e8b99187f1c26a9b064100826962e61a
