### ISSUE TITLE
[Draft] A simple message exchanging server

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#2520]
cc @iamzubin @yisiliu 

For the use case of #2363 (unlock protocol), there must have a way to notify the author that someone has subscribed with a certain ETH address. (Therefore the author can verify and share the post key to the author).

This use case is like what we have for the friendship verification mechanism. Originally we choose to use matrix, but the matrix is too heavy and might cause too much network traffic even it is not in use.

Thus I want to propose a simpler version of it for machine-readable message exchange.

It must meet the following requirement:

- Have none or very low network traffic when there is no message for this client wants.
- Opt-in Subscribe to certain message types (e.g. `plugin/unlock/key_hash_partition_x`).
- Privacy concerns, no meaning info leak to it.

It would be better if it meets the following requirement:

- Decentralized like matrix (multiple servers) can connect with each other
- Can store and replay the messages for a certain time in case the client wants to receive the event when it is offline.

Question:

How to avoid DOS? An attacker can send a widely-wanted message type in a high frequency and this server will distribute the message to all listeners.

**Comment by iamzubin** [comment]
I guess to deal with ddos we can set a limit. (50-100 requests/second )
