### ISSUE TITLE
[Bug] Cannot connect to MetaMask on Edge

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2547]
# Bug Report

### System

- [x] Windows

  - OS Version: 10

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome
- [x] Firefox

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior
Mask doesn't recognize the metamask on Microsoft Edge. We need to manually add Metamask extension id on Edge, and probably on Brave #2421.

**Comment by Tedko** [comment]
is this a bug related with MM side or Brave/Edge side?

**Comment by AinuX** [comment]
Checked with latest Microsoft Edge Version 92.0.902.55 (Official build) and Mask build commit
08ae9d9, worked OK.

**Comment by AinuX** [comment]
Checked again with same Edge and Mask build version, but Metamask with version 9.8+, it did not work.

**Comment by guanbinrui** [comment]
The injected provider is now available by #4656.
