### ISSUE TITLE
[Bug] The polls plugin is down

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2566]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

Unable to create a poll on twitter. Stop on the loading page and "Method not found" error was found on the background page.

![test](https://user-images.githubusercontent.com/52657989/110884580-42edb980-8320-11eb-867c-47717c68adc5.png)
![test](https://user-images.githubusercontent.com/52657989/110884654-63b60f00-8320-11eb-8a9d-882b0a37a85b.png)

**Comment by yisiliu** [comment]
We probably need to re-design this feature

**Comment by Tedko** [comment]
which part is down?

**Comment by Tedko** [comment]
sup . should we make this into a bounty?

**Comment by guanbinrui** [comment]
> which part is down?

Unable to send the poll. It stops at the sending phase.
