### ISSUE TITLE
[Demand] Integration Zerion API

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2578]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

The API documentation link: https://docs.zerion.io/zerion-api

What do those APIs can be built into Mask?

+ subscribe assets list
+ subscribe  transaction list

## Part 2: Problem to Solve

Add another Defi data source besides debank.

**Comment by Tedko** [comment]
will talk to zerion team about api integration
