### ISSUE TITLE
[Bug] Setup Guide dialog cannot be dismissed on mobile

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2583]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [x] Android

  - Mask Version: 1.29.8
  - Android Version: 1.29.8

- [x] iOS
  - Mask Version: 1.29.8
  - iOS Version: 1.29.8

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
On mobile (Both Android & iOS), when users tap the "close" button, or "Done" button after being successfully connected to Twitter/Facebook, the setup guide does not dismiss.

This issue is introduced by this [commit](https://github.com/DimensionDev/Maskbook/commit/f62e947ace89af4fd04408eec8c8dcc63adb734c)
@Jack-Works

**Comment by Jack-Works** [comment]
ACK. I'll revisit this change

**Comment by Jack-Works** [comment]
Emm I have to say this is very strange. I didn't make any significant change in the commit you mentioned and there is nothing related to the mobile.

**Comment by Jack-Works** [comment]
Is this still exists? 🤔
