### ISSUE TITLE
[Bug] Fail to backup database on Android

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2589]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [x] Android

  - Mask Version: 1.29.8
  - Android Version: 1.29.8

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
On Android, after backup database, the exported JSON file is empty with size 0.
This issue does not occur on iOS & Web

**Comment by Jack-Works** [comment]
this is strange. is it possible to be a geckoview bug?

**Comment by jk234ert** [comment]
Should be an Android side bug that fails to save the backup-ed payload into device's local storage

**Comment by jk234ert** [comment]
Fixed on Android side
