### ISSUE TITLE
[Bug] Election NFT plugin down?

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2627]
## Bug Report

<img width="1217" alt="Screen Shot 2021-03-20 at 01 06 21" src="https://user-images.githubusercontent.com/6687437/111817624-2ef61900-8919-11eb-846b-97fc5d84e904.png">

https://twitter.com/realmaskbook/status/1328162010366840832

**Make sure to add this into the test routine next time**

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by guanbinrui** [comment]
It was removed.

**Comment by Tedko** [comment]
ok

**Comment by Tedko** [comment]
will put back by binrui soon

**Comment by guanbinrui** [comment]
It has been recovered.
