### ISSUE TITLE
[Bug] Duplicate banners when first opening page on Twitter

### ISSUE THREAD

**Issue by mimikun** [DimensionDev/Maskbook#2629]
### System

- [x] Windows

  - OS Version: Windows 10 [Version 10.0.19041.867]

### Platform/Browser

- [x] Vivaldi(Chromium based browser)

  - Mask Version: v1.29.12
  - Browser Version: 3.7.2218.45 (Stable channel) (64-bit)

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info

Duplicate banners when first opening page on Twitter.

this: 

![image](https://user-images.githubusercontent.com/13450321/111870537-af278780-89c8-11eb-804d-4a0baa5562ab.png)

### Actual Behavior

1. download chrome extension
2. open https://twitter.com
3. check maskbook banner.

**Comment by guanbinrui** [comment]
Replaced by #2909.
