### ISSUE TITLE
[Bug] Fail to restore the DB backup

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2630]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

![image](https://user-images.githubusercontent.com/52657989/111926336-6c100600-8ae7-11eb-8cfb-ab810b0e3976.jpeg)

**Comment by Jack-Works** [comment]
is this still reproducible?

**Comment by Jack-Works** [comment]
cannot reproduce
