### ISSUE TITLE
[Bug] Duplicate processes of creating a wallet.

### ISSUE THREAD

**Issue by StellaCODING** [DimensionDev/Maskbook#2643]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:Mask Network (Beta)
1.29.13
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/
I already created a wallet, but then it asked me to create my wallet again. 
![1](https://user-images.githubusercontent.com/61523201/112088558-0301be80-8bcb-11eb-923a-4053e7a09e6d.png)
![2](https://user-images.githubusercontent.com/61523201/112088568-0ac16300-8bcb-11eb-9218-c5744adcddfd.png)
![3](https://user-images.githubusercontent.com/61523201/112088578-0f861700-8bcb-11eb-8119-790d813668ae.png)
![4](https://user-images.githubusercontent.com/61523201/112088589-13199e00-8bcb-11eb-81af-83d12918ee2e.png)

**Comment by guanbinrui** [comment]
They are not duplicate but serve different purposes.
