### ISSUE TITLE
[Demand] Non-blocking transaction dialog

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2648]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 3: Expected Behavior

+ Store and retrieve transactions from the local DB.
+ Present a in blocking dialog if any transaction is going to be mined.
+ Bind a specific payload with a transaction and able to draft post if the transaction mined successfully.
+ Present all on-going transactions in the transactions list on the dashboard page.

## Notes

**Comment by Jack-Works** [comment]
Yes, we need a transaction queue on the background page. It should be a per-wallet address queue. Is it possible to make this kind of queue for external wallet like MetaMask?
