### ISSUE TITLE
[Demand] Add pagination for transaction list

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2650]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 3: Expected Behavior

+ Add pagination if transactions more than one page.
+ List all page numbers if the total count of transactions is available. Otherwise, just provider previous and next buttons.
+ The current page number should reflect in the dashboard URL in case of the user refresh the dashboard page.

## Notes

+ [MUI Pagination Component](https://material-ui.com/components/pagination/)

**Comment by Jack-Works** [comment]
The correct URL is https://next.material-ui.com/components/pagination/

**Comment by guanbinrui** [comment]
closed by #2802.
