### ISSUE TITLE
[Demand] Introduce Collectible Plugin

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2651]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

For now, the NFT plugin supports recognize NFT assets by parsing an OpenSea link. We may extend this feature to support various links from different platforms like Rarible and SuperRare. Also, we may provide the user to share those NFT assets listed in the collectible list as a post with a specific version of payload.  

If the plugin detected an NTF asset.

For an NFT asset owned by others. It may let the user
  + view the NFT asset info (price, traits, trade history, etc.) from some backend data sources.
  + buy an NFT asset with an Ethereum wallet to be connected.
  + offer price under an NFT asset.
  + accept the offers created by other users.

For an owned NFT asset. It may let the user
  + transfer it to another address.
  + sell it by creating an auction or bidding.

## Notes

+ [UI](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=8896:0)
+ [OpenSea JS SDK](https://github.com/ProjectOpenSea/opensea-js)
+ [Demo Project](https://ships-log.herokuapp.com/)

**Comment by yisiliu** [comment]
@sounak98 hey we want to ship #2608 asap and would like to sync with you if you have started. If not, we will take over that bounty or we can collaborate on this feature together. Let me know! Thanks

**Comment by sounak98** [comment]
Hey, sorry for the late reply. I had started some initial work but I had to pause the work as something urgent came up. I will be able to resume working on it by this weekend. Let me know if that sounds good.

**Comment by Tedko** [comment]
> Hey @yisiliu sorry for the late reply. I had started some initial work but I had to pause the work as something urgent came up. I will be able to resume working on it by this weekend. Let me know if that sounds good.

cc @yisiliu

**Comment by Tedko** [comment]
Hi guys @yisiliu @guanbinrui @sounak98 one more thing.

For now if I send a link within `mask post` (aka cyber test or image-payload) we can render the opensea NFT and also play around with it 
https://twitter.com/suji_yan/status/1375167910633644032?s=20

However in most case ppl will just send the link of opensea/rarible right? like this  https://twitter.com/suji_yan/status/1375167961724424193?s=20 

we should parse that link and render that `NFT plugin` as well! make more sense to me .
cc @xiazhiming

**Comment by guanbinrui** [comment]
> Hi guys @yisiliu @guanbinrui @sounak98 one more thing.
> 
> 
> 
> For now if I send a link within `mask post` (aka cyber test or image-payload) we can render the opensea NFT and also play around with it 
> 
> https://twitter.com/suji_yan/status/1375167910633644032?s=20
> 
> 
> 
> However in most case ppl will just send the link of opensea/rarible right? like this  https://twitter.com/suji_yan/status/1375167961724424193?s=20 
> 
> 
> 
> we should parse that link and render that `NFT plugin` as well! make more sense to me .
> 
> cc @xiazhiming 

Yes, We can do the same thing as the Gitcoin plugin.

**Comment by yisiliu** [comment]
> Hi guys @yisiliu @guanbinrui @sounak98 one more thing.
> 
> For now if I send a link within `mask post` (aka cyber test or image-payload) we can render the opensea NFT and also play around with it
> https://twitter.com/suji_yan/status/1375167910633644032?s=20
> 
> However in most case ppl will just send the link of opensea/rarible right? like this https://twitter.com/suji_yan/status/1375167961724424193?s=20
> 
> we should parse that link and render that `NFT plugin` as well! make more sense to me .
> cc @xiazhiming

this is one of the two goals in #2608

**Comment by yisiliu** [comment]
> Hey @yisiliu sorry for the late reply. I had started some initial work but I had to pause the work as something urgent came up. I will be able to resume working on it by this weekend. Let me know if that sounds good.

I think that matches our timeline but you should definitely check the status with @guanbinrui when starting working on this bounty. cheers 🍻 !

**Comment by sounak98** [comment]
Hey @guanbinrui, what's the status of this issue? I was going to start working on this, so thought of confirming with you once. I have checked out the Opensea SDK and that seems to have all the necessary functions to bid/sell/transfer an asset. Also, your latest PR has the UI updates, so can I pick it up from there?

**Comment by guanbinrui** [comment]
> Hey @guanbinrui, what's the status of this issue? I was going to start working on this, so thought of confirming with you once. I have checked out the Opensea SDK and that seems to have all the necessary functions to bid/sell/transfer an asset. Also, your latest PR has the UI updates, so can I pick it up from there or are you already working on it?

I plan to create a new plugin for this: Collectible. And I have created the scaffolding of the plugin, features are divided into small issues for each tab. May be you can help us to build one of those tabs?

**Comment by sounak98** [comment]
> Maybe you can help us to build one of those tabs?

Yeah sure! It looks like the `Offers` & `Auction` tabs will interact with the Opensea SDK and facilitate bidding/selling, so I can work on those tabs.

**Comment by yisiliu** [comment]
@sounak98 thanks! feel free to pick up #2685, #2686, #2687 or #2689
