### ISSUE TITLE
[Demand]  Backup wallet as JSON key store file

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2662]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Notes

+ [keythereum](https://github.com/ethereumjs/keythereum)

**Comment by septs** [comment]
Rationale: No mainstream wallet implementation
