### ISSUE TITLE
[Bug] Improve toolbox on Twitter

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2671]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

+ Rename the injected menu item to "Mask Network".
+ The gap above the injected menu item does not follow the original ones.
+ The height of the injected menu item is a litter bigger than the original ones.
+ The popper over should follow the original style (font, box-shadow, etc.).
+ The smiley face logo is smaller than other icons in the menu list.

![image](https://user-images.githubusercontent.com/52657989/112596514-e5408d80-8e46-11eb-916a-96258a3507f1.png)

Here is the injected toolbox popper over:

![image](https://user-images.githubusercontent.com/52657989/112596384-b32f2b80-8e46-11eb-9ce3-2f2d4bdaef6d.png)

Here is the original popper over:

![image](https://user-images.githubusercontent.com/52657989/112597679-664c5480-8e48-11eb-8b29-971a19f2122e.png)

**Comment by Tedko** [comment]
niubi
