### ISSUE TITLE
[Demand] Add plugins management page on the dashboard

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2674]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

For now, Mask Network has got many plugins built-in. All plugins were enabled by default. We need a dashboard page for plugins which installed. Some features will be nice to have:

+ Listing all installed plugins one by one with plugin name, description, version, and other metadata to be presented.
+ Enable or disable a specific plugin.
+ Enable or disable a specific feature on the plugin (That plugin will provide settings on its definition class).

### Plugins will not be listed

For fundamental plugins should not let the user disable them, and we should not list them at all. So we need to extend the definition of the plugin to add a trait like `visible`.

### Offical Plugins

For official plugins provide by the Mask Network team. Should add a label for them.

## Part 3: Expected Behavior

Here is the chrome extension management page.

![image](https://user-images.githubusercontent.com/52657989/112599722-45d1c980-8e4b-11eb-825c-df91e0c7e7b6.png)

The entrance may look like this.

![image](https://user-images.githubusercontent.com/52657989/112600678-7a925080-8e4c-11eb-857d-9c74d6535dd7.png)

**Comment by Jack-Works** [comment]
@guanbinrui Hi please don't be too hurry on this. I'm working on third-party plugin now.

**Comment by guanbinrui** [comment]
closed by #2783.
