### ISSUE TITLE
[Bug] Unable to open a plugin's composition dialog

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2715]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: 328c495

### Actual Behavior

+ Open the post-composition dialog.
+ Open the file service plugin's composition dialog then close it.
+ Try to open the file service plugin's composition dialog again, but failed.
+ Close the post-composition dialog and click the smiley face icon to open it again, but failed.

**Comment by zhouhanseng** [comment]
Hi @Jack-Works 7feceda9 cause this bug.

**Comment by Jack-Works** [comment]
ACK I'll take this
