### ISSUE TITLE
[Bug] Wrong account link in the transaction list

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2718]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

Account Address: 0x66b57885E8E9D84742faBda0cE6E3496055b012d

For now, it's `https://etherscan.io/tx/0xba50933c268f567bdc86e1ac131be072c6b0b71a`. Actually, it should be `https://etherscan.io/address/0xba50933c268f567bdc86e1ac131be072c6b0b71a`

![image](https://user-images.githubusercontent.com/52657989/113104033-9f167000-9232-11eb-8de7-f09b6b6570cb.png)

**Comment by septs** [comment]
https://etherscan.io/tx/0xba50933c268f567bdc86e1ac131be072c6b0b71a the link is invalid.
