### ISSUE TITLE
[Bug] Use NFT's token id as transaction amount

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2719]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

Account Address: 0x66b57885E8E9D84742faBda0cE6E3496055b012d
Tx ID: 0xe4a2e47fc372d69eae45a1f8f41c14f85e5f94c245d411300cfb526958f9a2cd

![image](https://user-images.githubusercontent.com/52657989/113104474-2cf25b00-9233-11eb-8735-15bab2dc72db.png)

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/113293797-cc454a00-9328-11eb-81b5-db7548d7ff85.png)

from provide zerion
