### ISSUE TITLE
[Demand] ERC721 Token List

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2724]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Data Source: https://etherscan.io/tokens-nft

**Comment by lelenei** [comment]
ERC712, tokens list
[tokens.json.zip](https://github.com/DimensionDev/Maskbook/files/6240297/tokens.json.zip)

**Comment by septs** [comment]
@lelenei plz update to https://github.com/DimensionDev/Mask-Token-List

**Comment by lelenei** [comment]
> @lelenei plz update to https://github.com/DimensionDev/Mask-Token-List
already given to binrui

**Comment by lelenei** [comment]
#close
