### ISSUE TITLE
[Bug] flag emoji broken in Twitter Mask post

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2753]
## Bug Report
![image](https://user-images.githubusercontent.com/6687437/113499062-6255bc00-9545-11eb-8bd7-3356e5d8e16b.png)
## Environment

Haven't reproduced. Please try reproduce. 

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by tiaramoe** [comment]
Windows 10 built-in emoji problem
![2021-04-04 2.13.28.png](https://i.loli.net/2021/04/04/AeWLpjXNYOQJxuC.png)

**Comment by Tedko** [comment]
duplicate #2754
