### ISSUE TITLE
[Demand] Implement plugin card (Plugin Management)

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2756]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

A card to present information of a specific built-in plugin which contains:

+ An emoji character as its avatar.
+ A primary text field to present its name.
+ A secondary text field to present its version no (semver).
+ A secondary text field to present its one-line description.
+ A toggle box to enable/disable this plugin. Disabling a plugin will totally remove its all functions from the Mask Network.
+ A `Details` button which will open a Plugin Detailed Dialog by clicking it.

## Part 3: Expected Behavior

![card](https://user-images.githubusercontent.com/52657989/112599722-45d1c980-8e4b-11eb-825c-df91e0c7e7b6.png)

## Learn More

#2727

**Comment by Jack-Works** [comment]
The switch on-off feature requires #2691. Please cc me if you need it.
