### ISSUE TITLE
[Bug] backup - Output mnemonic in plain text

### ISSUE THREAD

**Issue by tiaramoe** [DimensionDev/Maskbook#2760]
## Bug Report
Backup Database - Output mnemonic in plain text
### System

- [x] Windows

  - OS Version: 

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

1.29.13

![2021-04-06 11.25.32.png](https://i.loli.net/2021/04/06/7cONqSBz3R1W6mi.png)

**Comment by Jack-Works** [comment]
what are you expected? 🤔

**Comment by tiaramoe** [comment]
> what are you expected? 🤔

The mnemonic phrase is output in encrypted form.

**Comment by Jack-Works** [comment]
cc @guanbinrui

**Comment by guanbinrui** [comment]
> > what are you expected? 🤔
> 
> 
> 
> The mnemonic phrase is output in encrypted form.

It hasn't been encrypted. You can restore the wallet from the words directly.

**Comment by septs** [comment]
We are redesign next generation backup and restore modal and new backup file format.

CC @yisiliu
