### ISSUE TITLE
[Demand] Pages with no other information contained in trusted links are decoded.

### ISSUE THREAD

**Issue by tiaramoe** [DimensionDev/Maskbook#2761]
## Catalogue

- [x] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

![2021-04-06 11.37.04.png](https://i.loli.net/2021/04/06/Ru2LkIjGw31xAOD.png)

## Part 2: Problem to Solve
how can we tweet something without always having this message, saying "This tweet is encrypted with...etc" ?
## Part 3: Expected Behavior
Pages with no other information contained in trusted links are decoded.

**Comment by guanbinrui** [comment]
This issue is caused by #2717.
