### ISSUE TITLE
[Demand] Add hooks for Geoblocking

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2772]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Introduce a react hook for resolving the user's IP address to a country code for geoblocking purposes. Can found country codes in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) and two open API hosters will be used for this hook:

| Hoster | API | 
| -------| ----|
| https://ip-api.com/ | http://ip-api.com/json/?fields=status,countryCode |
| https://ipgeolocationapi.com/ | https://api.ipgeolocationapi.com/geolocate | 

## Part 2: Problem to Solve

The signature of the hook may like this:

```typescript
// listing all available country codes in the ISO document
enum CountryCode {
    US,
    EN,
}

function useCountryCode(): AsyncResult<CountryCode> {
    // implement the async logic
}
```

## Part 3: Expected Behavior

+ Emit both the two requests in a race and resolve the early returned one.

**Comment by Jack-Works** [comment]
what? why need this?
