### ISSUE TITLE
[Demand] Post-Modern Mask Login

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2789]
## Catalogue

- [x] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
WIP

**Comment by Jack-Works** [comment]
I'll investigate if we can do the job of Web Auth API does.

**Comment by yisiliu** [comment]
@Jack-Works I happened to find out that one of the authors/collaborators on the webauthn standards is my friend. I think maybe we can consult with him but he is always busy though.
