### ISSUE TITLE
Provide a stable extension id for users that install from source and for development

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#28]

**Comment by yisiliu** [comment]
> users that want install

https://github.com/SujiTech/BetterLife/issues/5

**Comment by neruthes** [comment]
> > users that want install
> 
> [SujiTech/BetterLife#5](https://github.com/SujiTech/BetterLife/issues/5)

233333333

**Comment by Jack-Works** [comment]
Not resolved yet

**Comment by Jack-Works** [comment]
The dist folder seems to be the only factor that affects the extension id.

**Comment by yisiliu** [comment]
https://stackoverflow.com/questions/23873623/obtaining-chrome-extension-id-for-development
https://stackoverflow.com/questions/21497781/how-to-change-chrome-packaged-app-id-or-why-do-we-need-key-field-in-the-manifest

**Comment by Misaka-0x447f** [comment]
Requested speedy close due to not active.

**Comment by Jack-Works** [comment]
This issue should stay open until someone solve this

**Comment by neruthes** [comment]
Seemingly impossible? Maybe we can just leave this piece of thought forsaken.

**Comment by Jack-Works** [comment]
Seemingly impossible. and if you keep install it in the same directory, the extension id will not change.
