### ISSUE TITLE
[Bug] Mask icon missing in Twitter Compose Dialog

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#2800]
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:1.29.13
  - Browser Version:

- [x] Firefox

  - Mask Version:1.29.13
  - Browser Version:

- [x] Android

  - Mask Version:1.29.13
  - Android Version:

- [x] iOS
  - Mask Version:1.29.13
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
The injected mask button is missing in Twitter's compose dialog. This makes users not able to reply using Mask on desktop, and cannot send anything on mobile since mobile Mask apps depend on this injected button to send Mask encrypted post.

### Actual Behavior

/_What happened?_/
![image](https://user-images.githubusercontent.com/7972003/114154742-527a1580-9953-11eb-8c17-524e763a645f.png)

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/114988435-e8b8b900-9ec8-11eb-96ed-1bae808f9ab5.png)

PC

![image](https://user-images.githubusercontent.com/5390719/114988488-f66e3e80-9ec8-11eb-9e73-93d8b4ed3902.png)

Mobile

Cannot reproduce
