### ISSUE TITLE
[Bug]  Unable to decrypted new posts with image payload

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2807]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

The current selected identity is an empty string that causes this problem on Twitter.

![image](https://user-images.githubusercontent.com/52657989/114299689-42973880-9aef-11eb-8e56-92e459ab6a4e.png)

**Comment by Jack-Works** [comment]
I think we should avoid to rely on this in the future version
