### ISSUE TITLE
[Bug] Wrong color in dark mode

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2809]
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

![image](https://user-images.githubusercontent.com/52657989/114351400-205bf400-9b9d-11eb-99d6-5fd6c1226e6c.png)

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/114359196-4b971100-9ba6-11eb-824a-4144a64801a3.png)

Can not reproduce in the master branch

**Comment by guanbinrui** [comment]
Actually, It's not a color problem. Our breakpoint settings are different from Twitter's.

**Comment by Jack-Works** [comment]
so a new interesting problem. maybe we should try to match the breakpoints on the SNS but that will make things harder
