### ISSUE TITLE
[Demand] Guide the user to create a new Wallet

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2863]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Open the create wallet dialog instead of the error dialog if no wallet was created before.

![testess](https://user-images.githubusercontent.com/52657989/114901113-10ffd380-9e47-11eb-8756-78dcd7764026.png)

**Comment by xiazhiming** [comment]
Click red pecket to bring up the wallet selection 
![image](https://user-images.githubusercontent.com/29635388/115048407-1c690280-9f0c-11eb-9f3c-b8bd643bdcf1.png)
