### ISSUE TITLE
Button navigation looks bad (contrast, emphasis)

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#288]
This is PR #282 issue. It's not going to be blocking, so let's put it here for later.
* * *
Compare https://material-ui.com/components/bottom-navigation/ and...
![](https://user-images.githubusercontent.com/5390719/66796204-8e3c4680-ef39-11e9-97a4-3fc1f343b9ec.png)

See the difference?
* Selected element has bad contrast
* No font weight difference on selected vs other

**Comment by Artoria2e5** [comment]
The colors are defined at
https://github.com/mui-org/material-ui/blob/83521f74872fc41682fe7715bd82d82dc75ca0ca/packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js#L24
https://github.com/mui-org/material-ui/blob/2b1bad30e582459c912d47ee7ced724147902d9e/packages/material-ui/src/BottomNavigation/BottomNavigation.js#L12,
For us, primary is indigo400.


The size difference seems to be there. The font-weight issue is a mis-spot.

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/pull/282#discussion_r335539701

**Comment by SunriseFox** [comment]
this shall be solved when we switch to our new dashboard.
