### ISSUE TITLE
[Bug] The Zerion service is not available

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2883]
### How to reproduce?

1. 
2.
3.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
The WebSocket server has down
