### ISSUE TITLE
[Bug] Remove loading indicator on non-Mask user's tweets

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2885]
### How to reproduce?

![image](https://user-images.githubusercontent.com/52657989/115099096-523ad500-9f66-11eb-9dba-cc0f3a6bd989.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
closed by 77baac46d2db34051142d5426038ed4b9e975a8a
