### ISSUE TITLE
Adding Maskbook to PRISM Break

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#289]
As is suggested by one of our users, we can probably add Maskbook to [PRISM Break](https://prism-break.org/), where projects that help users opt-out of the current surveillance systems are listed. Let's file a pull request following their [guideline](https://gitlab.com/prism-break/prism-break/blob/master/CONTRIBUTING.md). 

DDL - Oct 28

**Comment by neruthes** [comment]
Good idea. I will take care of this matter.

**Comment by Tedko** [comment]
Great

**Comment by Tedko** [comment]
Also dont forget Tssercube :D

**Comment by Tedko** [comment]
@neruthes Let's finish this by next Monday for better PR etc

**Comment by neruthes** [comment]
🎉 https://gitlab.com/prism-break/prism-break/merge_requests/2087 🎉
