### ISSUE TITLE
[Demand] A rule-based web requests interception solution

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2896]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

### Learn more

+ https://developer.chrome.com/docs/extensions/reference/webRequest/
+ https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

**Comment by Jack-Works** [comment]
Modify requests needs `webRequestBlocking` instead of `webRequest` permission and that API is going to be removed in Manifest V3.
That permission also needs user approval otherwise it will block the auto-update of the extension.

**Comment by Jack-Works** [comment]
IMO if the only problem is CORS to `https://example.com`, then request permission on that domain dynamically can resolve the CORS problem. There is no need to use the `webRequestBlocking` permission.

**Comment by guanbinrui** [comment]
We need more refined control on domain permissions.

**Comment by Jack-Works** [comment]
> We need more refined control on domain permissions.

Can you explain the detail? The domain permissions are _not_ a thing that we can control well.

**Comment by guanbinrui** [comment]
> > We need more refined control on domain permissions.
> 
> Can you explain the detail? The domain permissions are _not_ a thing that we can control well.

I mean we should tell the user the domain name to be visited in the permission notifications card. For now, it's only an abstract description. 

We'd better do not reveal the API level domains to the user. The domain of dynamically requested permission may not know to the user.

**Comment by Jack-Works** [comment]
> We'd better do not reveal the API level domains to the user. 

The browser will do whatever.

**Comment by Jack-Works** [comment]
We should not use this if we want to support iOS 15 Web Extensions in the future. I'll close this.
