### ISSUE TITLE
[Bug] Flash of blank board before popup is fully loaded

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2910]
### How to reproduce?

1. Go to twitter.com.
2. Click the Mask icon on the pinned extension list. 
3. You will get a blank board before the popup is fully loaded.

![image](https://user-images.githubusercontent.com/52657989/115230069-6d643b00-a146-11eb-8ddf-03cb252f0eff.png)
![image](https://user-images.githubusercontent.com/52657989/115230286-b6b48a80-a146-11eb-91e4-5b98e8b9ddf2.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
We should hand-write some static HTML & CSS to make it render in no time. The UI is too dynamic so there is no meaning to use SSR.

**Comment by AinuX** [comment]
Any update? @guanbinrui @Jack-Works

**Comment by Tedko** [comment]
assume this is fixed? @Jack-Works @guanbinrui @AinuX 
if so pls close
