### ISSUE TITLE
[Bug] MacOS “NFT” emoji display problem

### ISSUE THREAD

**Issue by tiaramoe** [DimensionDev/Maskbook#2915]
## Bug Info
![2021-04-20 12.04.44.png](https://i.loli.net/2021/04/20/tFfAqSg2iw4xCW5.png)
### How to reproduce?

1.plugins pages
2.
3.

### What happened?
🖼  ( “NFT” emoji )Not displayed correctly
## Environment
NFT emoji display problem on MacOS
### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash:
/tree/ade0d025 Version 1.30.5-beta-ade0d025
(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by tiaramoe** [comment]
cc 🖼  that in 
https://ip.sb/emoji/

**Comment by yisiliu** [comment]
I don't think is a bug, like, why?

**Comment by tiaramoe** [comment]
> I don't think is a bug, like, why?

It seems that this is not a bug, but a different way of displaying it. :D
