### ISSUE TITLE
[Demand] Replace BigNumber.js with @ethersproject/bignumber

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2919]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other
  - /_List it here_/

## Part 1: Introduction and Background

Clean the barrier before we switch to Ethers.

+ [BigNumber.js](https://mikemcl.github.io/bignumber.js/)
+ [@ethersproject/bignumber](https://www.npmjs.com/package/@ethersproject/bignumber)

**Comment by septs** [comment]
@Jack-Works create a dummy library?
