### ISSUE TITLE
[Bug] Page stop responding after Delete Friend record in 'developer options'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#292]
How to reproduce:
- Go to Options - Developer Options
- Del some friend's record
- Buggy behavior

**Comment by guanbinrui** [comment]
Fail to reproduce the bug with v1.7.0 with below steps:

1. Open "Options page" - "Developer Options"
2. Click user record
3. Click "Delete" button
4. Do step 2-3 many times

UI still functional. Tell me if i'm wrong.

**Comment by Tedko** [comment]
@guanbinrui 
There's another each to reproduce UI bug. go to "Options page" - "Developer Options", then some UI error.

**Comment by Tedko** [comment]
@guanbinrui 

I suspect we have some localDB problem with the friend's record.

Here's another bug I can reproduce:

- go to "Options page" - "Developer Options"
- Quit Chrome
- Restart

![Screen Shot 2019-10-18 at 07 36 30](https://user-images.githubusercontent.com/6687437/67055385-891a0a00-f17a-11e9-8e89-d8cd46f82ec1.png)

FYI: I have more than 250+ friend records.

**Comment by Jack-Works** [comment]
@Tedko Do you open the options page immediately after the Chrome restarts? because the background page is not ready yet, so all the requests are ignored by the background page

**Comment by Tedko** [comment]
@Jack-Works yes..so the 'Nothing' is not a bug?

**Comment by Jack-Works** [comment]
In general, user will open Facebook or options page after some seconds. At that point, background page is ready. (Background page need hundreds milliseconds to bootstrap).
It is not a common case that user manually restart the browser so the background page is not ready when the Facebook loads

**Comment by Tedko** [comment]
@Jack-Works Ok.

Also I think after we fix #293 I will test this bug again.

**Comment by guanbinrui** [comment]
@Tedko 
+ The refresh UI error is fixed in #293. I test it in night mode only before PR. It's a bit different with your screenshot.
+ I will add more user records hope that can help to reproduce the issue.

**Comment by yisiliu** [comment]
Since #293 is fixed, can we close this too?

**Comment by Tedko** [comment]
Hard to reproduce on my side as well.

But for https://github.com/DimensionDev/Maskbook/issues/292#issuecomment-543410397 — we may need to open a separate issue for it. @yisiliu
