### ISSUE TITLE
[Demand] Add Site Access Workflow into Plugin System

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2927]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Jack-Works** [comment]
if you're mean by what we talked about in the last meeting, it is not a plugin but a plugin system feature

**Comment by guanbinrui** [comment]
> if you're mean by what we talked about in the last meeting, it is not a plugin but a plugin system feature

Have renamed the issue title.
