### ISSUE TITLE
[Bug] Legacy ITO tweets are broken

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2960]
### How to reproduce?

https://twitter.com/TheYisiLiu/status/1347470169711407106

![image](https://user-images.githubusercontent.com/52657989/115700479-4baec200-a399-11eb-80c3-9097e6805e5a.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [x] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
fixed by https://github.com/DimensionDev/ITO-Subgraph/pull/5
