### ISSUE TITLE
[Demand] No more tracking on blocknumber

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2970]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

To reduce RPC requests.

**Comment by guanbinrui** [comment]
cc @yisiliu

**Comment by yisiliu** [comment]
It should become an on-demand operation when the user creates any transactions. This would largely reduce our traffic with our Ethereum rpcs.

**Comment by zhouhanseng** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/3511
