### ISSUE TITLE
Discussion: Gun devtools?

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#299]
https://github.com/amark/gun/pull/793

**Comment by Tedko** [comment]
@amark What's ur opinion? 

For now I don’t think we have enough man power on this. Not sure if we're (Jack) familiar with Gun's code base enough. But a viewer will be super cool.

**Comment by neruthes** [comment]
```
      MANPOWER SHORTAGE...
+------------------------------+
|                              |
|                              |
|                              |
|                              |
|                              |
|                              |
|                              |
+------------------------------+
  MANPOWER SHORTAGE EVERYWHERE
```

**Comment by amark** [comment]
I dream of one!

is @Dletta's https://github.com/Dletta/visualGraph useful here?

**Comment by Dletta** [comment]
@tedko Let me know if you need instructions or support

**Comment by neruthes** [comment]
Discussion resolution: We will look into this matter some weeks later.
