### ISSUE TITLE
Scroll on iOS device

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#302]
See: https://stackoverflow.com/questions/47244002/make-wkwebview-real-fullscreen-on-iphone-x-remove-safe-area-from-wkwebview

related #301

**Comment by Tedko** [comment]
Assign to @MainasuK  but the priority of this is not high

**Comment by MainasuK** [comment]
@Jack-Works Need modify the native layout constraint?

**Comment by Jack-Works** [comment]
> @Jack-Works Need modify the native layout constraint?

no need.

**Comment by Tedko** [comment]
Let's prioritise this one @MainasuK

**Comment by MainasuK** [comment]
@Jack-Works Need modify the native layout constraint or something?

**Comment by MainasuK** [comment]
> Let's prioritise this one @MainasuK

Properly I can't do anything about that.

**Comment by Tedko** [comment]
This problem needs to be fixed on front end side?

**Comment by MainasuK** [comment]
I'm guess it is a CSS issue. @Jack-Works not request the native side change.
@Jack-Works please post your comment.

**Comment by Jack-Works** [comment]
Sorry I forgot what excatly the problem is. Is there a screenshot for that?

**Comment by Tedko** [comment]
> Sorry I forgot what excatly the problem is. Is there a screenshot for that?

I dont remember either..
Maybe just dismiss this issue.

**Comment by Tedko** [comment]
I will close this issue since @Jack-Works dont really remember what’s the problem is, and seems like we haven’t encountered it recently.
