### ISSUE TITLE
[Demand] Hide media card of decrypted tweet

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3029]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

![image](https://user-images.githubusercontent.com/52657989/116078298-00fab600-a6c9-11eb-9a94-21ab06caf1b6.png)
![image](https://user-images.githubusercontent.com/52657989/116078366-166fe000-a6c9-11eb-922c-035b2c29459b.png)

**Comment by Tedko** [comment]
media card => mask.io link right?

**Comment by guanbinrui** [comment]
> media card => mask.io link right?

Yes! Only those tweets that have encrypted payload will be hidden.

![image](https://user-images.githubusercontent.com/52657989/116351349-176a5400-a826-11eb-843e-f0af3a68e2f4.png)
