### ISSUE TITLE
[Bug] Unsolovable Math Problem

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3030]
### How to reproduce?

Some cases have been reported that the math problem cannot be resolved even if the result is definitively right.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [x] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [x] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
the case is reproduced by sanshui -
after testing ourself - likely the problem is : when the ito is finished (on chain) you might still stuck in the math problem, and you will got the wrong err msg for math problem. (should return ```ito finished``` )

**Comment by AinuX** [comment]
With latest build:1.31.9, can't reproduce the issue.

**Comment by zhouhanseng** [comment]
Math problem had been removed from ITO.
