### ISSUE TITLE
[RFC] Steganographic Payload Behavior on Facebook and Twitter [Draft]

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#304]
## Abstract

This issue defines the Phase 1 behavior of steganographic payload publishing on Facebook and Twitter.

## Base Image

At Phase 1, we only support one image, <Steg-Example-001.png>.

![Steg-Example-001](https://user-images.githubusercontent.com/2139261/67277327-18465b00-f4b6-11e9-8b6e-3d57fe752382.png)

## Block Matrix

According to the specifications which are available elsewhere, a base image will be split to a matrix of 8px*8px blocks.

In this version, the dimension of base image is always 1024px X 1240px, therefore containing 128 blocks per row and 155 blocks per column, totally 59520 bits can be encoded.

## Filling Text

As the binary payload is put in the image, the text content of the post will be something else.

### Facebook

```
This post is shared to my friends but not Facebook.com itself. You may install Maskbook to decrypt the content from the image. ([I:b])
```

### Twitter

```
Use @ProjectMaskbook to decrypt this tweet. ([I:b])
```

## Publishing

When the user completes composing and chooses to publish, the payload will be embedded into the image and will be uploaded to the social network through their respective web upload interfaces.

## Relations With Existing Behaviors

This feature does not change how the composing box is displayed and interacted.

**Comment by neruthes** [comment]
Need review by @yisiliu @guanbinrui

**Comment by yisiliu** [comment]
What about replacing Facebook with Facebook.com?

**Comment by guanbinrui** [comment]
Here is a example which encoding 'hello world' into base image:

![fb_compressed](https://user-images.githubusercontent.com/52657989/67279496-b4e01b80-f4fd-11e9-83b1-d05ae660d36b.jpg)

**Comment by neruthes** [comment]
@guanbinrui Sorry I forgot that the image is expected to be grayscale. Now I have a more prepared version and I wish it will work better for this case.

![Steg-Example-001](https://user-images.githubusercontent.com/2139261/67282040-4e88d800-f4c0-11e9-91fb-3449f452e157.png)

**Comment by guanbinrui** [comment]
@neruthes Maybe we can create something like "mask layer" in Photoshop.

Use a built-in mask image whose white part will be encoded and black part will leave it untouch. So we can use colorful maskbook logo in the base image.

**Comment by yisiliu** [comment]
@guanbinrui good point we can actually deliberately ignore the "mask zone" when hiding information

**Comment by guanbinrui** [comment]
@yisiliu OK I will implement it after we support posting stego image in facebook.com.

**Comment by neruthes** [comment]
Nice idea ([I:b])
