### ISSUE TITLE
[Bug] PostDialog can't display when click the icon

### ISSUE THREAD

**Issue by nuanyang233** [DimensionDev/Maskbook#3041]
### What happened?
The postdilaog can't display when click the icon and encrypted message button.
maybe cause by [this](https://github.com/DimensionDev/Maskbook/blob/9d537251fe15ece77ff3ca5cebc0b6566a393a8c/packages/maskbook/src/components/InjectedComponents/PostDialog.tsx#L104)

### Snapshot
![image](https://user-images.githubusercontent.com/28348152/116238430-ea6d6100-a793-11eb-8278-cad3e506da58.png)

### What should happen?

The postdialog need display

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
dup with #3040

**Comment by septs** [comment]
Duplicate of #3040
