### ISSUE TITLE
[Bug] Incorrect style provider in storybook

### ISSUE THREAD

**Issue by nuanyang233** [DimensionDev/Maskbook#3057]
### `useStyles` can't override MaterialUI style

![Clipboard - 2021年4月29日下午3点16分](https://user-images.githubusercontent.com/28348152/116523430-cda66a00-a908-11eb-89d7-abededd2e73f.png)
![Clipboard - 2021年4月29日下午3点16分](https://user-images.githubusercontent.com/28348152/116523525-e7e04800-a908-11eb-9f40-2bb34e9f7735.png)

### Incorrect hover style with `Button`

![image](https://user-images.githubusercontent.com/28348152/116523736-21b14e80-a909-11eb-98d1-cb3a862b7702.png)
![image](https://user-images.githubusercontent.com/28348152/116523690-13633280-a909-11eb-8bf9-99f350e96e1f.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
is this fixed? @nuanyang233
