### ISSUE TITLE
[Demand] Action Artifacts Previewer

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3062]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

An electron-based app to fetch artifacts list and load an extension to preview, all automatically.

This issue introduces a desktop app powered by Electron to fetch and list all available CI builds. Let the user be able to select one of each build and kit to run in that App. We suppose it will be useful for someone who needs to switch and review CI builds quickly.

## Part 2: Problem to Solve

+ To find out a kind of API that will help fetch all of those CI builds of PRs on GitHub.

## Notes

+ https://www.electronjs.org/docs/api/extensions

**Comment by UncleBill** [comment]
electron doesn't support all chrome extensions API, see https://www.electronjs.org/docs/latest/api/extensions/. We might use puppeteer instead.
