### ISSUE TITLE
[Bug] It should throw a timeout error if the public key cannot find

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3063]
### How to reproduce?

![image](https://user-images.githubusercontent.com/52657989/116650748-6a721180-a9b4-11eb-8b69-62a8e9783fc0.png)

https://twitter.com/antgeorge6/status/1387232503228813312

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [x] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
No, this step is not finding the public key. It's finding the E2E encrypted key on the gun.
