### ISSUE TITLE
[Demand] Store name and picture

### ISSUE THREAD

**Issue by tiaramoe** [DimensionDev/Maskbook#3077]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
- Store shelves
## Part 1: Introduction and Background
![2021-05-03 9.14.51.png](https://i.loli.net/2021/05/03/Mawo9WFDxVGKuH6.png)
https://addons.mozilla.org/en-US/firefox/addon/maskbook/
https://addons.opera.com/zh-cn/extensions/details/maskbook/
## Part 2: Problem to Solve
The screenshots of the old version and  "Maskbook" name  are still used in the Firefox and Opera stores.
Maybe need  update to the pictures like Chrome Store and name of "Mask Network"?
https://chrome.google.com/webstore/detail/mask-network/jkoeaghipilijlahjplgbfiocjhldnap?utm_source=chrome-ntp-icon

**Comment by Tedko** [comment]
yes please update in both store @septs @Jack-Works

**Comment by tiaramoe** [comment]
Hi, everyone.
I updated a set of content packages for Opera and Firefox browser store
[Google Driver Link](https://drive.google.com/drive/folders/1KS7eY8YOmjVEmqFFy9NaHmZqva6h5ANM?usp=sharing)
If you need other information, please feel free to tell me, I will write and update.

**Comment by Tedko** [comment]
> Hi, everyone.
> 
> I updated a set of content packages for Opera and Firefox browser store
> 
> [Google Driver Link](https://drive.google.com/drive/folders/1KS7eY8YOmjVEmqFFy9NaHmZqva6h5ANM?usp=sharing)
> 
> If you need other information, please feel free to tell me, I will write and update. 

Cc @septs pls
UpdAtes these

**Comment by Tedko** [comment]
cc @Jack-Works

**Comment by Jack-Works** [comment]
I found there is no place to change name and picture in the Opera store. Firefox account has two-step verification which I don't have access to.

**Comment by yisiliu** [comment]
@Jack-Works hmm Firefox store version can be fixed by @guanbinrui but we probably need to contact with opera to change it there.

**Comment by Jack-Works** [comment]
I don't know if it possible to change those info when uploading a new version on Opera

**Comment by guanbinrui** [comment]
FF has been updated.

**Comment by Tedko** [comment]
> I don't know if it possible to change those info when uploading a new version on Opera

ok lets update a new ver @Jack-Works
