### ISSUE TITLE
[Demand] Use HTML5 Date Picker

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3082]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 2: Problem to Solve

Use the HTML5 native date picker to replace the MUI date picker component.

**Comment by lelenei** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/72531217/117256135-dd7bfc00-ae7c-11eb-8a05-01604364d2d1.png">

**Comment by zhouhanseng** [comment]
How about replacing all MUI date picker component?

**Comment by lelenei** [comment]
> How about replacing all MUI date picker component?

type='datetime-local'

**Comment by zhouhanseng** [comment]
@lelenei @guanbinrui I mean replace MobileDateTimePicker for all other plugins.
