### ISSUE TITLE
[Demand] Investigation of the cause of slow loading of ITO

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3083]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

![image](https://user-images.githubusercontent.com/52657989/117006888-8f031c00-ad1b-11eb-8ed6-a17bac211457.png)

**Comment by zhouhanseng** [comment]
The loading of ITO no longer depended on graph service.
