### ISSUE TITLE
[Bug] Incorrect Input UI

### ISSUE THREAD

**Issue by nuanyang233** [DimensionDev/Maskbook#3090]
### How to reproduce?
1. click the add personas in dashboard
2. Enter any name
### What happened?

![image](https://user-images.githubusercontent.com/28348152/117259209-66e0fd80-ae80-11eb-8eed-0f180143ebe4.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS Big Sur
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
https://github.com/mui-org/material-ui/pull/25156/files#r627216511

After this change, the problem appears. I have requested help from the maintainer
