### ISSUE TITLE
[Bug] Weird Popup position on short screen

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#3097]
### How to reproduce?

1. Open Twitter.com in Chrome using a laptop
2. Click the injected Mask button at the bottom left corner
3. Check the position of the Mask popup

### What happened?
The last item of the Mask popup is outside of Chrome's bottom boundary.
<img width="1420" alt="Snipaste_2021-05-07_11-21-44" src="https://user-images.githubusercontent.com/7972003/117393853-972fa700-af27-11eb-8d76-0424b8879a93.png">

### What should happen?
The popup's bottom border should be positioned above Chrome's bottom boundary, all the popup's items should be visible.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: 1.31.9)
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Reopen.

**Comment by wenluomask** [comment]
Fixed.
