### ISSUE TITLE
[Placeholder][Draft] Extending Friendship Certificate Design

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#31]
I have been thinking about a feasible implementation and extension of this mechanism. The following lied in my considerations:
- [ ] BitTorrent trackers or  implementing a DHT (distributed hash table) for tracking requests
- [ ] "Buses" in CPU architecture, in which different types of data go through them with corresponding privileges. We can potentially build different "buses" based on GunDB with different functionalities and privileges. E.g., address bus for tracking, signal/control bus for transmitting operations and data bus for holding temporary friendship certificate issuing/renewing requests. This is an efficient design, and I would like to explore more on a distributed implementation of this.
- [ ] Using FB's graph API to get a user's friend list directly?
- [ ] Zero knowledge in certificates
- [ ] To be continued

**Comment by neruthes** [comment]
Are there updates after the introduction of #34?

**Comment by Jack-Works** [comment]
> Are there updates after the introduction of #34?

Nope

**Comment by yisiliu** [comment]
This might take longer than expected I guess

**Comment by Jack-Works** [comment]
close for housekeeping
