### ISSUE TITLE
[Bug]Mask无法唤起使用手动解压加载的V9.4.0版本Metamask

### ISSUE THREAD

**Issue by Ha1o** [DimensionDev/Maskbook#3144]
### How to reproduce?

1.在Chrome上手动安装V9.4.0版本的Metamask（加载已解压的扩展程序方式），插件是从Metamask官方github上下载的zip文件
2.使用Mask连接钱包的时候无法唤起Metamask，其他网站应用可以唤起并成功连接

### What happened?

Metamask最新版为V9.5.0，但是目前存在bug（#11033），所以手动安装了上一个版本。

## Environment

PC、Chrome-90.0.4430.212（正式版本） （64 位）

### Mask Version:

1.32.0

![1620717236(1)](https://user-images.githubusercontent.com/9363544/117779772-96717a80-b271-11eb-80c1-6738218d0e38.jpg)

**Comment by Tedko** [comment]
One solution is to make our dashboard page not a chrome-ext:// but a local-host (like ipfs companion)
