### ISSUE TITLE
[Bug] Performance issue - infinite tryRender invokes by setTimeout

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#3152]
### How to reproduce?

1. open https://twitter.com/differui
2. wait for UI and network stable
3. open chrome devtools, try `pause script execution`

![image](https://user-images.githubusercontent.com/1141198/117930140-35f54280-b330-11eb-8c2f-774762928c0e.png)

### What happened?

![image](https://user-images.githubusercontent.com/1141198/117930010-0e05df00-b330-11eb-9004-9f1362c63d8c.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: 1.32.0)
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Himself65** [comment]
https://github.com/DimensionDev/Maskbook/blob/1398a55ea49c69b0178bac97f8698020fb06af52/packages/shared/src/ShadowRoot/createReactRootShadowed.tsx#L49

Would it be better if we use a queue to poll rendering? @Jack-Works

**Comment by Himself65** [comment]
![image](https://user-images.githubusercontent.com/14026360/119466880-9d22e600-bd77-11eb-8a70-34a193cbb437.png)

**Comment by Jack-Works** [comment]
let me investigate this

**Comment by Jack-Works** [comment]
what about change `setTimeout(tryRender, 20)` to `setTimeout(tryRender, 200)`?
