### ISSUE TITLE
[Bug] Unable to import wallet via "Private Key"

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3174]
### How to reproduce?

1. Create wallet in Mask Dashboard
2.Input needed info at "Private Key" tab
![image](https://user-images.githubusercontent.com/2582974/118115116-1c7cf500-b41b-11eb-87e7-94ceacb94fac.png)

### What happened?
Unable to click "Import" button

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Is your private key available on other wallets?

**Comment by Tedko** [comment]
fixed https://github.com/DimensionDev/Maskbook/pull/3404
