### ISSUE TITLE
[Bug] Can't restore wallet from keystore with non-json format content

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3175]
### How to reproduce?

![screenshot_35](https://user-images.githubusercontent.com/2582974/118119293-b98e5c80-b420-11eb-971b-91b4cbd6c6f1.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
#2799

**Comment by Jack-Works** [comment]
This is expected. Why you'd expect it can accept invalid JSON content?

**Comment by AinuX** [comment]
> This is expected. Why you'd expect it can accept invalid JSON content?

Tried with other wallet, like TokenPocket, can import keystore with non-json format.

It's better to pop a user friendly error message if we don't support non-json format keystore, rather than displaying "Error: Unexpected token ' in JSON at position 1" .
