### ISSUE TITLE
[Bug] The style of drop-down box is inconsistent in red packet plugin.

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3193]
### How to reproduce?
![image](https://user-images.githubusercontent.com/2582974/118470258-1ea3c400-b739-11eb-8644-37cd40ad9107.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
Fixed by https://github.com/DimensionDev/Maskbook/pull/2374

![image](https://user-images.githubusercontent.com/63733714/119926965-0b9bba00-bfab-11eb-938b-3948e9d9f67c.png)

**Comment by zhouhanseng** [comment]
fixed by https://github.com/DimensionDev/Maskbook/commit/af46719168e59fe4e70283f07ed219c67b5a19f4#diff-132dab787ac96d48965f7e2bae75964692d36df6012b26d9015f3f6be235359cR261
