### ISSUE TITLE
[Bug] Auto-paste has stopped working on the latest master branch

### ISSUE THREAD

**Issue by manishoo** [DimensionDev/Maskbook#3200]
## Bug Info

Auto-paste has stopped working on the latest master branch

### How to reproduce?

1. checkout master
2. create an encrypted post with raw content or with image payload

### What happened?

text or images don't get pasted

### What should happen?

text and images should get pasted

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by manishoo** [comment]
I was working on my branch, then I pulled the master, and the auto paste wasn't working anymore. I confirmed this by checking out master. I haven't investigated why this is the case

**Comment by septs** [comment]
@AinuX plz test

**Comment by AinuX** [comment]
Tested with latest build from master branch, the auto paste function stoped working.

**Comment by manishoo** [comment]
@Jack-Works do you have any idea what might have caused this issue?

**Comment by Jack-Works** [comment]
I will investigate this tomorrow
