### ISSUE TITLE
[Demand] More clearly identify the unlock status of tokens when participating in ITO

### ISSUE THREAD

**Issue by cryptocatdog** [DimensionDev/Maskbook#3213]
## Catalogue

-☑UI/UX

**## Part 1: Introduction and Background**
When I participate in ITO, I cannot confirm whether I have unlocked the corresponding tokens; when I unlock successfully, I still cannot determine whether the unlocking is successful through the front-end interface, which may cause repeated calls to the unlocking method.

**## Part 2: Problem to Solve**
After successfully unlocking the token, the ito interface will give a striking prompt

**Here are my thoughts**
![捕获](https://user-images.githubusercontent.com/49095419/119114247-908d4d80-ba58-11eb-8b20-16806fe938d2.PNG)

**Comment by zhouhanseng** [comment]
@cryptocatdog when the input is empty, it shows how much token has been approved on the button.

![image](https://user-images.githubusercontent.com/63733714/119830608-07ca5200-bf2f-11eb-9176-624d80036709.png)
