### ISSUE TITLE
[Demand] Implement Token Panel on the Dashboard

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3222]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Migrate ITO composition dialog onto the token panel of the new Dashboard.

![image](https://user-images.githubusercontent.com/52657989/119334330-93d54300-bcbd-11eb-95e7-623f0801821a.png)

**Comment by septs** [comment]
keep alive

**Comment by UncleBill** [comment]
This feature has been cancelled.

cc @guanbinrui @xiazhiming
