### ISSUE TITLE
[Bug] "Finish" button overlapped in red pack page if zoom out browser window

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3229]
### How to reproduce?

![Screen Shot 2021-05-25 at 18 05 32](https://user-images.githubusercontent.com/2582974/119481270-16750580-bd85-11eb-9b78-b6dd605ab602.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
fixed!
