### ISSUE TITLE
Unify maskbook tip style

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#323]
![image](https://user-images.githubusercontent.com/15797507/67562570-8d818c80-f751-11e9-8585-065b4b9c8c13.png)
for now, not all tip component using the same generation of style as the image shows.
maybe discuss with @neruthes first.

**Comment by neruthes** [comment]
Will take into consideration into further periodic UI improvements.

**Comment by Tedko** [comment]
Is this still a problem now?

**Comment by Tedko** [comment]
@neruthes

**Comment by neruthes** [comment]
Could plan a reassessment in this week 🤔

**Comment by Tedko** [comment]
> Could plan a reassessment in this week 🤔

update? Seems we can close this issue now

**Comment by neruthes** [comment]
Investigation needs much effort. I doubt would those efforts yield well. We will keep this in mind and fix inconsistencies when we notice them.
