### ISSUE TITLE
[Bug] "From" info is incorrect in red packet

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3230]
### How to reproduce?

![Screen Shot 2021-05-25 at 19 00 52](https://user-images.githubusercontent.com/2582974/119487199-a8800c80-bd8b-11eb-963f-3029cf41d335.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
This is old red packet.
