### ISSUE TITLE
[Bug] 'Extra Specific Contacts' should be an independent option to choose

### ISSUE THREAD

**Issue by StellaCODING** [DimensionDev/Maskbook#3237]
## Bug Info

'Extra Specific Contacts' is not an independent option to choose. 

### How to reproduce?

1.
2.
3.

### Mask Version: 1.32.3

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)

![Screen Shot 2021-05-26 at 5 02 11 PM](https://user-images.githubusercontent.com/61523201/119637769-96b06f00-be48-11eb-870a-58825783f149.png)

https://user-images.githubusercontent.com/61523201/119637813-a0d26d80-be48-11eb-9fc2-1aeb22292fe7.mov

- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
@AinuX plz re-check the bug

**Comment by wenluomask** [comment]
I have checked with mingming, it is necessary to be fix.
