### ISSUE TITLE
[Bug] Chain will not update if change wallet between different wallet type 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3238]
### How to reproduce?

1. Connect wallet A (metamask, Ropsten).
2. Then change to wallet B (maskwallet, Mainnet).

### What happened?
Wallet was changed as expected, but the chain still keep in previous chain (Ropsten).

### What should happen?
The wallet and chain should be updated as expected.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Fixed in v1.33.0.
