### ISSUE TITLE
[Bug] Trending view will hang if search some token in unsupported chain

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3260]
### How to reproduce?

1. Connect to metamask wallet with unsupported chain, like HECO
2. Search some token to view the trending info, like $pond
![Screen Shot 2021-05-28 at 18 23 07](https://user-images.githubusercontent.com/2582974/119970700-a2d03400-bfe2-11eb-9d86-d20d901bfddd.png)

### What happened?
The trending view will hang,

### What should happen?
Should display correct info.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
we need fix this b4 bsc/mattic integration

**Comment by zhouhanseng** [comment]
This bug will be solved in the new release, since `useChainId()` has already always returned `mainnet` in production.
