### ISSUE TITLE
Add a Maskbook tip for public key on bio 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#327]
As the title.

For now we only have hint/tip for proof post.

**Comment by SunriseFox** [comment]
Preview: 

Desktop:
![image](https://user-images.githubusercontent.com/14029711/68008932-6c71ec00-fcbb-11e9-8198-a39d0c8d83e6.png)

Mobile:
![image](https://user-images.githubusercontent.com/14029711/68008983-93c8b900-fcbb-11e9-9be8-6deee453cab4.png)

However it is not checking the bio but checking our database if it HAS been stored. This hint won't show if you just view someone's profile without any encrypted post observed.

**Comment by Tedko** [comment]
> Preview:
> 
> Desktop:
> ![image](https://user-images.githubusercontent.com/14029711/68008932-6c71ec00-fcbb-11e9-8198-a39d0c8d83e6.png)
> 
> Mobile:
> ![image](https://user-images.githubusercontent.com/14029711/68008983-93c8b900-fcbb-11e9-9be8-6deee453cab4.png)
> 
> However it is not checking the bio but checking our database if it HAS been stored. This hint won't show if you just view someone's profile without any encrypted post observed.

Great!

**Comment by neruthes** [comment]
Nice
