### ISSUE TITLE
[Bug] Image payload doesn't work on Facebook

### ISSUE THREAD

**Issue by manishoo** [DimensionDev/Maskbook#3284]
## Bug Info

Image payload doesn't work on Facebook

### How to reproduce?

1. Install the extension from Chrome Store or checkout master
2. Try to create an image payload

### What happened?

Image payload will not be decrypted

## Environment

I tested it on Chrome

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
Cc @Jack-Works

**Comment by Jack-Works** [comment]
ACK, thanks for your report. I'll investigate this.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/120443940-b9e39d00-c3b9-11eb-9e48-b85cb6576ff9.png)

Hi @manishoo it works on my machine. I'm using the master branch build

**Comment by manishoo** [comment]
I now tested it on Brave and Chrome with a clean install it can't decrypt the image payload

![Untitled](https://user-images.githubusercontent.com/16239413/120449156-70d51e00-c3a4-11eb-9a2e-ab7d5d1d7168.png)

I'll test again with master and confirm

**Comment by manishoo** [comment]
It's not working on master either. It may have something to do with my environment. I wonder what it could be

**Comment by Jack-Works** [comment]
Can anyone else help to reproduce this?

**Comment by AinuX** [comment]
> Can anyone else help to reproduce this?

I will try to reproduce with latest official build and master branch build.

**Comment by AinuX** [comment]
Image payload doesn't work with build 1.34 on Facebook. @Jack-Works
