### ISSUE TITLE
[Bug] Cannot send ITO

### ISSUE THREAD

**Issue by manishoo** [DimensionDev/Maskbook#3285]
## Bug Info

When I click the Send button from the "Past" tab of the ITO Composition Dialog, nothing will happen. The console logs are as follows:

![image](https://user-images.githubusercontent.com/16239413/120318427-1630b900-c2f5-11eb-8ce3-e0b28755bbce.png)

## Environment

Tested on Facebook and Twitter

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by manishoo** [comment]
This happens with a clean install of mask and in the case where I haven't signed anything with MetaMask

**Comment by Tedko** [comment]
cc @zhouhanseng @guanbinrui
