### ISSUE TITLE
[Bug] Can't connect to Social Network on Android

### ISSUE THREAD

**Issue by manishoo** [DimensionDev/Maskbook#3287]
## Bug Info

I've already added my Persona in the Android app and have connected to Twitter, but when I try to connect to Facebook the app crashes.

<img src="https://user-images.githubusercontent.com/16239413/120479949-c4a32f80-c3c3-11eb-812d-a893450f5fa2.gif" alt="output" width="250px">

### How to reproduce?

1. Instal app from Play store
2. Try to connect to Facebook

## Environment

Galaxy A51 android 11

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [x] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [x] Android 11
- [ ] iOS 14

**Comment by manishoo** [comment]
I cleaned app data and tried again. This time I can't connect to Twitter either. I tried reinstalling the app, but the same thing happened

**Comment by Jack-Works** [comment]
Is that a geckoview bug? 🤔 cc @jk234ert
