### ISSUE TITLE
[Demand] remove ancient post comp mode

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3302]
## Catalogue

<img width="1068" alt="Screen Shot 2021-06-05 at 16 50 40" src="https://user-images.githubusercontent.com/6687437/120885976-3aa2d300-c61e-11eb-921c-334efbc4d337.png">

No need for this func any more. we can just remove this option ux etc

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by Jack-Works** [comment]
Should we do it?

**Comment by Tedko** [comment]
> Should we do it?

@Jack-Works yeah do it when free
