### ISSUE TITLE
[Demand] Track upstream fix about "(tag.text || "").trim is not a function"

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#3307]
> TypeError: (tag.text || "").trim is not a function

IMO @Himself65 know how to fix this right?

**Comment by Himself65** [comment]
Related: https://github.com/DimensionDev/Maskbook/issues/3256

**Comment by Jack-Works** [comment]
cc @Himself65 undo this when a new version that contains https://github.com/styleguidist/react-docgen-typescript/pull/360 has released

**Comment by Jack-Works** [comment]
https://github.com/styleguidist/react-docgen-typescript/releases/tag/v2.0.0

has published cc @Himself65

**Comment by Himself65** [comment]
yeah, the `v2` has published however we use `react-docgen-typescript-loader` which is the upstream of it, and haven't publish the correct version

**Comment by Himself65** [comment]
what's more, it seems like the `react-docgen-typescript-loader` has deprecated yet. 🤔

https://github.com/strothj/react-docgen-typescript-loader

**Comment by Himself65** [comment]
Blocking because of https://github.com/storybookjs/storybook/issues/15067

**Comment by Himself65** [comment]
https://github.com/storybookjs/storybook/issues/15067#issuecomment-861348973
