### ISSUE TITLE
Auto add friend on twitter, stage 2

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#331]
stage 1: #330 
finally we need to support all four status on twitter: follower, following, both, none.
awaiting special group definition on network profile.

**Comment by Jack-Works** [comment]
This should be automatic if @Misaka-0x447f implements the logic of detecting friends

**Comment by Misaka-0x447f** [comment]
logic of detecting friend done, but no special group for follower/following

**Comment by Tedko** [comment]
@Jack-Works are you working on this issue?

**Comment by Jack-Works** [comment]
nope I'm working on persona database

Suji Yan <notifications@github.com> 于 2019年11月11日周一 下午10:38写道：

**Comment by Tedko** [comment]
Assign to @guanbinrui

**Comment by Tedko** [comment]
let me know who's handle this for now

**Comment by guanbinrui** [comment]
> let me know who's handle this for now
I will do this.

**Comment by guanbinrui** [comment]
Implemented in #414.
