### ISSUE TITLE
[Task] Move `useSnackbarCallback()` to a shared folder

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#3340]
## Introduction and Background

`useSnackbarCallback()` is defined inside `extension/options-page` but also being used by `plugins`.

https://grep.app/search?q=useSnackbarCallback&filter[path][0]=packages/maskbook/src/plugins/

## Content

Move it into `@dimensiondev/maskbook-shared`

**Comment by nuanyang233** [comment]
It has been moved to theme package

**Comment by UncleBill** [comment]
close in favor of #3290
