### ISSUE TITLE
[Bug] Fix CN-i18n typo

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3345]
## Bug Info

<img width="701" alt="Screen Shot 2021-06-14 at 13 31 55" src="https://user-images.githubusercontent.com/6687437/121843990-d4047000-cd15-11eb-90f2-70af5cef4a60.png">

not `咧文` but `貼文`

### How to reproduce?

1.
2.
3.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [x] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [x] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
parent issue #3263
CC @touhonoob
