### ISSUE TITLE
[Bug] Use polygonscan.com for polygon explorer

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3349]
## Bug Info

The current one will out of date soon
<img width="1408" alt="Screen Shot 2021-06-15 at 00 50 38" src="https://user-images.githubusercontent.com/6687437/121930645-30e34300-cd75-11eb-911c-232d6f7760d4.png">

### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Closed by https://github.com/DimensionDev/Maskbook/commit/8496913ac9f83a3d6293731be825f602b8e9c5ef.
