### ISSUE TITLE
[Bug] Some bugs on https://dimensiondev.github.io/Maskbook-VI/

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3354]
1.
## Bug Info
Some UI bugs on https://dimensiondev.github.io/Maskbook-VI/

### How to reproduce?

1.Enter webpage https://dimensiondev.github.io/Maskbook-VI/;
2.Find the Introduction section and third section Combinations.

### What happened?
1. In the introduction section, the “Webpage” links to nothing;
2. In the third section Combinations, UI error happened.

### What should happen?
1. It should be deleted or links to somewhere;
2. The third logo should be placed before text.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
<img width="761" alt="1 The third logo should be placed before text " src="https://user-images.githubusercontent.com/85149605/121988059-4b94d680-cdcc-11eb-92a3-baceb21bf5ed.png">

**Comment by septs** [comment]
@wenluomask plz contact @xiazhiming re-design entire mask network visual identity documentation
