### ISSUE TITLE
[Bug] Can not back up by Mnemonic Words or QR code on get started page

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3355]
### How to reproduce?

1.Back up persona from dashboard;
2.Download QR code;
3.Go the get started page -> Restore From Backup;
4.Click Advance… to the advanced page, and try QR code backup.

### What happened?
QR code is uploaded but import button is enable to click. 

### What should happen?
Data should be back up successfully by QR code.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
<img width="688" alt="2  QR code is uploaded but import button is enable to click" src="https://user-images.githubusercontent.com/85149605/121988037-3d46ba80-cdcc-11eb-8a3d-00ee81a30c41.png">

**Comment by nuanyang233** [comment]
Hi, I restored successfully by mnemonic Words, can't be reproduced the bug

**Comment by wenluomask** [comment]
> Hi, I restored successfully by mnemonic Words, can't be reproduced the bug

I tried again, but the twitter account connected to persona can not be restored successfully.

**Comment by wenluomask** [comment]
![截屏2021-06-15 下午2 01 58](https://user-images.githubusercontent.com/85149605/122001038-4b073a80-cde2-11eb-88c4-132c8f7a8889.png)

**Comment by Jack-Works** [comment]
Can reproduce via QRCode

**Comment by wenluomask** [comment]
Bug Fixed. I Verified.
