### ISSUE TITLE
[Bug] Restricted contacts can claim the red packet.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3356]
### How to reproduce?

1.Send a red packet type tweet on twitter;
2.Select only one specific contact by clicking “+Extra Specific Contacts”  ;
3.Let someone else except for the specific contact to claim the red packet.

### What happened?
The contact who is not selected on specific contact list can claim the red packet.

### What should happen?
Only the contacts who are selected on specific contact list can claim the red packet.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
It's by design. The Red Packet payload is always shared publicly.
