### ISSUE TITLE
[Demand] The history tab of ITO on BSC and Polygon

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3359]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ https://thegraph.com/explorer/subgraph/dimensiondev/mask-ito-bsc-mainnet
+ https://thegraph.com/explorer/subgraph/dimensiondev/mask-ito-bsc-chapel
+ https://thegraph.com/explorer/subgraph/dimensiondev/mask-ito-polygon
+ https://thegraph.com/explorer/subgraph/dimensiondev/mask-ito-mumbai

**Comment by zhouhanseng** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/3421
