### ISSUE TITLE
[Bug] Token icon display incorrect after expanding token list 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3360]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/121990037-b562af80-cdcf-11eb-8579-13d59463efd8.mov

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
update? @NikoManiac

**Comment by AinuX** [comment]
Can't reproduce with 1.34 build.
