### ISSUE TITLE
[Bug] dHEDGE miss icon in plugin page 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3365]
### How to reproduce?

![Screen Shot 2021-06-15 at 13 32 14](https://user-images.githubusercontent.com/2582974/121998316-4476c400-cdde-11eb-8076-a6498348848a.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
#2678
