### ISSUE TITLE
[Bug] TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3367]
### How to reproduce?

https://twitter.com/realmaskbook/status/1397993871980654594

1. go to progress tab
2. click the votes section

![Screen Shot 2021-06-15 at 13 47 07](https://user-images.githubusercontent.com/2582974/121999715-3de94c00-cde0-11eb-8ada-cc380f5dacbb.png)

### What happened?

npm.react-dom.js:304 TypeError: Cannot read property 'toUpperCase' of undefined
    at 7508.js:25199
    at Array.map (<anonymous>)
    at VotesCard_Content (7508.js:25192)
    at Oh (npm.react-dom.js:236)
    at sk (npm.react-dom.js:360)
    at rk (npm.react-dom.js:348)
    at qk (npm.react-dom.js:347)
    at hk (npm.react-dom.js:347)
    at bk (npm.react-dom.js:336)
    at J (7993.js:7868)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/753fa5086ab27dbda67738d046bfcd45b52d85f1/packages/maskbook/src/plugins/Snapshot/UI/VotesCard.tsx#L84
