### ISSUE TITLE
[Demand] Red packet confirm dialog

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#3368]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=4312%3A216588

Open confirm dialog before send the red packet.

![image](https://user-images.githubusercontent.com/63733714/122000545-953bec00-cde1-11eb-86ae-f56f9f60bd48.png)

**Comment by wenluomask** [comment]
For the random type red packet, Amount per Share should be deleted.
![截屏2021-06-18 下午5 54 28](https://user-images.githubusercontent.com/85149605/122543999-edcbed00-d05e-11eb-97c4-6d5e5394f666.png)

**Comment by wenluomask** [comment]
In addition, "Amount Totals" change to "Amount Total"

**Comment by wenluomask** [comment]
Checked.
