### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3389]
### How to reproduce?

1.Post Poll1 tweet in Twitter;
2.Try to select multiple times of different answers;
2.After Poll1 finish, post Poll2 tweet;

### What happened?
1. User can choose different answers by multiple times;
2. Since post Poll2, tweet shows Poll1's information.

### What should happen?
1. User should only can choose one of the answers and only click once;
2. Since post Poll2, it should show Poll2's information.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
<img width="628" alt="截屏2021-06-16 下午5 08 21" src="https://user-images.githubusercontent.com/85149605/122191620-7c0c6b80-cec5-11eb-9599-95725b8965c5.png">

**Comment by Tedko** [comment]
this is known bug. poll is delivered by 3rd party

**Comment by wenluomask** [comment]
Closed
