### ISSUE TITLE
[Bug] Incorrect numeric format in tradeview 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3392]
### How to reproduce?
![Screen Shot 2021-06-16 at 19 46 09](https://user-images.githubusercontent.com/2582974/122213939-15467c80-cedc-11eb-8756-1f10b51c3391.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
fixed
