### ISSUE TITLE
[Bug] Token icon not found in transaction page

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3393]
### How to reproduce?

![Screen Shot 2021-06-16 at 20 10 20](https://user-images.githubusercontent.com/2582974/122216571-20e77280-cedf-11eb-8381-5d0ffe399d41.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
@guanbinrui @NikoManiac 

should we just store ETH/matic these common icons to save network traffic?

**Comment by Tedko** [comment]
created another issue for `icon not found` problem and closed this one
