### ISSUE TITLE
[Demand] Add Transaction Snackbar

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3397]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by UncleBill** [comment]
Already updated the UI following figma in https://github.com/DimensionDev/Maskbook/pull/3718/files
