### ISSUE TITLE
[Bug] Status of red packet can not convert in time

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3398]
### How to reproduce?

1.Post a red packet tweet;
2.Claim it and share;
3.Check the status of red packet.

### What happened?
After claimed the red packet, the status of red packet is still unclaimed(showing claim button).

### What should happen?
After claimed the red packet, the status of red packet should be "claiming" and enable to click.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
https://user-images.githubusercontent.com/85149605/122338073-c4816300-cf71-11eb-8d0e-fbe7275d7e19.mov

**Comment by zhouhanseng** [comment]
Let me add bug description: After claimed the red packet, the status of red packet in current twitter will become "claiming", but the shared one which is within another twitter is unclaimed.

We need a mechanism to track on-going transaction.
