### ISSUE TITLE
Implement UserGroup Abstraction Model in group membership management

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#34]
Documentation: https://github.com/DimensionDev/Maskbook/wiki/UserGroup-Abstraction-Model

**Comment by neruthes** [comment]
Any update? @jack-works

**Comment by neruthes** [comment]
Any update? @Jack-Works

**Comment by Jack-Works** [comment]
> Any update? @Jack-Works

Nope

**Comment by Jack-Works** [comment]
We do have a user group system now. does it enough? Note: I think `Virtual Group | Friends of friends Alice` is not possible

**Comment by neruthes** [comment]
> We do have a user group system now. does it enough? Note: I think `Virtual Group | Friends of friends Alice` is not possible

Selective implementation is ok. I will introduce a partial implantation plan.
