### ISSUE TITLE
[Bug] The Uniswap Info is down

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3401]
### How to reproduce?

1. Goto https://twitter.com/search?q=%24MASK&src=typed_query
2. Switch the trade provider to `Uniswap Info`.
3. Got a syntax error

![image](https://user-images.githubusercontent.com/52657989/122351317-9c4d3080-cf80-11eb-89c9-c9f230b7c07c.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by nuanyang233** [comment]
I can't reproduce this issue.

**Comment by Tedko** [comment]
<img width="1370" alt="Screen Shot 2021-06-19 at 01 37 38" src="https://user-images.githubusercontent.com/6687437/122598132-ff34e980-d09e-11eb-86be-970183c46f08.png">


@nuanyang233 i can reproduce

**Comment by Tedko** [comment]
> I can't reproduce this issue. @guanbinrui

mine - installed from chrome. latest v1.33.1

**Comment by nuanyang233** [comment]
Ok, I reproduce it in matic network.  The `PluginTraderRPC.getCoinTrendingByKeyword` cause the error. It looks like appears to be related to the Message handler. @Jack-Works 

```ts
// packages/maskbook/src/plugins/Trader/trending/useTrending.ts
export function useTrendingByKeyword(tagType: TagType, keyword: string, dataProvider: DataProvider) {
    const currencyAsyncResult = useCurrentCurrency(dataProvider)
    const trendingAsyncResult = useAsync(async () => {
        if (!keyword) return null
        if (!currencyAsyncResult.value) return null
        console.log(keyword, tagType, currencyAsyncResult.value, dataProvider)
        return PluginTraderRPC.getCoinTrendingByKeyword(keyword, tagType, currencyAsyncResult.value, dataProvider)
    }, [dataProvider, currencyAsyncResult.value, keyword])
    return {
        value: {
            currency: currencyAsyncResult.value,
            trending: trendingAsyncResult.value,
        },
        loading: currencyAsyncResult.loading || trendingAsyncResult.loading,
        error: currencyAsyncResult.error || trendingAsyncResult.error,
    }
}
```

![image](https://user-images.githubusercontent.com/28348152/122720499-20b1f300-d2a2-11eb-90fb-e83a1cb79a88.png)

**Comment by nuanyang233** [comment]
The reason is that uniswap's graph does not support other chains (like matic, bsc), and we need to determine the option to hide the DataProvider switch when the user is these network.
