### ISSUE TITLE
[Bug] Inconsistent data in tradeview

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3403]
### How to reproduce?

1.Enter Twitter's Explore page and search #btc to display tradeview;
2.Since bitcoin's data display, choose CoinMarketCap for data source;
3.Check the percentage of increase or decrease;
4.Check Market Cap and Volume (24h) in CoinMarketCap and CoinGecko.

### What happened?
1.The percentage of increase or decrease is different from the data in CoinMarketCap;
2.Number data of Market Cap and Volume (24h) use both "$" and "USD" to represent US dollar.

### What should happen?
1. Data should be identical;
2. Delete "$" since "USD" is more accurate.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
![价格的升降百分比不一致](https://user-images.githubusercontent.com/85149605/122360755-39ac6280-cf89-11eb-9e07-933540ef1e0f.png)

**Comment by guanbinrui** [comment]
Ref to https://github.com/DimensionDev/Maskbook/issues/2276.
