### ISSUE TITLE
[Bug] ITO configured data will not be cleared after close ITO dialog

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3406]
### How to reproduce?

1.  Open ITO plugin
2. Config some data
3. Close ITO dialog
4. Re-Open ITO plugin

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Verified.
