### ISSUE TITLE
refactor: isSameAddress in curring version

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3409]
maybe can provide currying `isSameAddress` function

```ts
const MatchAddress = (a: string) => (b: string) => isSameAddress(a, b)

exclude.find(MatchAddress(address))
```

_Originally posted by @septs in https://github.com/DimensionDev/Maskbook/pull/3290#discussion_r654115537_

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/122501885-1f759180-d028-11eb-8048-7935f973ae8c.png)
