### ISSUE TITLE
[Bug] Red packet w/ image payload wrong text info(tweet)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3424]
## Bug Info

<img width="1370" alt="Screen Shot 2021-06-19 at 01 40 57" src="https://user-images.githubusercontent.com/6687437/122607693-8b4e0d80-d0ad-11eb-8eb3-8c7cd26f399a.png">
<img width="1370" alt="Screen Shot 2021-06-19 at 01 41 14" src="https://user-images.githubusercontent.com/6687437/122607698-8db06780-d0ad-11eb-9dc4-ac546fb8446f.png">

Should be like the 2nd pic (text payload) 
`Claim this Red Packet with xxxx`

PS - should we add network here? Claim this @polygon network with xxx? 

### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
I can't reproduce it.

https://twitter.com/chsss3/status/1405943449065385985

<img src="https://user-images.githubusercontent.com/63733714/122713050-aa0ff800-d297-11eb-878e-048e77c6b5af.png" width=600 />


> PS - should we add network here? Claim this @polygon network with xxx?

@xiazhiming

**Comment by polygon** [comment]
Please stop mentioning me in this issue, thank you.

**Comment by Tedko** [comment]
@zhouhanseng  i mean - 
chance the text info to `Claim this Red Packet with xxxx` if thats a image payload red packet

**Comment by zhouhanseng** [comment]
@Tedko you mean the text on the steganography redpacket image?

**Comment by Tedko** [comment]
> @Tedko you mean add text on the steganography redpacket image?

yes @zhouhanseng

**Comment by zhouhanseng** [comment]
This issue is waiting for https://github.com/DimensionDev/Maskbook/issues/3066 to be done.

**Comment by Tedko** [comment]
> @Tedko you mean add text on the steganography redpacket image?

@zhouhanseng no. replied you in rocket chat. 这里推特文字部分应该是领红包

**Comment by Tedko** [comment]
@zhouhanseng

**Comment by AinuX** [comment]
#3066
