### ISSUE TITLE
[Task] Dummy SNS website for better developer experience

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3425]
## Introduction and Background

The current development progress is highly bound with Twitter.com. It brings bad developer experience. We can do nothing if Twitter.com is not available. To get rid of the SNS websites. We can host a dumb website on GH pages that provides basic DOM nodes for mounting by the Mask extension.

## Content

/_Actual content here..._/

**Comment by Jack-Works** [comment]
I'm working on this. This is basically the same idea as #3037
