### ISSUE TITLE
[Bug] Duplicate tokens in wallet assets table

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3433]
### How to reproduce?

Use `0x11DCb909e26be914d2d3d02C51D356bF1DfB7631` to load the assets.

![image](https://user-images.githubusercontent.com/52657989/122666886-82128d00-d1e2-11eb-92e7-75659bae7e70.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
zerion or debank?

**Comment by Tedko** [comment]
after testing - this will only appear when using zerion; same as #3346
