### ISSUE TITLE
Cooperation with Unlock Protocol

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#344]
[Unlock Protocol](https://unlock-protocol.com/) enables creators to monetize their content by injecting their code into different platforms. We can realize the same function using our extension. 

This was discussed in an earlier meeting today and we would like to explore if we can try to help them build a demo on top of [Medium](https://medium.com) by next weekend. 

All we need to do is to enable all Maskbook extension users to encrypt and decrypt the content on Medium. This can be done by directly synchronizing the aes key among the complete Maskbook GUNDB network.

What's you guys' thoughts?

**Comment by Tedko** [comment]
Not that hard and definitely worth trying.

**Comment by Tedko** [comment]
Let me know who will handle and how to work on this issue by today @yisiliu @neruthes

**Comment by yisiliu** [comment]
@Jack-Works is willing to help

**Comment by yisiliu** [comment]
wanna tell us more what you want?  @julien51

**Comment by julien51** [comment]
Sorry for the delay here! Let me check things today!

**Comment by Tedko** [comment]
👍

**Comment by yisiliu** [comment]
Closed until further messages from @julien51
