### ISSUE TITLE
[Bug] Auto-detect first language function broken

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#3446]
### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
fixed by #3957

**Comment by AinuX** [comment]
Change Chrome's lanauge and then check  Mask welcome page.

| Chrome setting language | Mask display language |
| :--- | :--- |
| English | English |
| Chinese (Traditional) | Chinese (Traditional) |
| Korean | English |
| Japanese | English |
