### ISSUE TITLE
[Bug] Typing mistake in Snapshot plugin

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3453]
### How to reproduce?
![截屏2021-06-21 下午5 13 03](https://user-images.githubusercontent.com/85149605/122737856-0aad2e00-d2b4-11eb-81a3-1d6959574528.png)

1.https://twitter.com/realmaskbook/status/1397993871980654594
2. Check the "close" tag on the right of "[Community Choice ITO 5 ] —— Shield"

### What happened?
The tag looks like a close button.
 
### What should happen?
"close" changes to "closed" will be better.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash:1.33.2

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
fixed by https://github.com/DimensionDev/Maskbook/pull/3458
