### ISSUE TITLE
fetchPostContent + fetchProfile is not fully implemented on twitter

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#346]
Fetch content by http request from legacy twitter seems not possible since we cannot got the same result that from the browser, so for now we only use the fallback method (delegate to foreground).
This problem can be resolve later.

**Comment by yisiliu** [comment]
Can you show us some sample requests to try?

**Comment by Misaka-0x447f** [comment]
## How to reproduce
Select 'disable JavaScript' in developer tools;
go to this example url:
```
https://twitter.com/Twitter/status/1184189961278513155
```
twitter will show a prompt page to let you go legacy twitter by using <form>, so we click 'yes', then it should goes:
```
https://mobile.twitter.com/i/nojs_router?path=/?prefetchTimestamp=1572336385770
```
*the source url was encoded.
but we cannot get this url on RESTClient, which returns:
```
https://mobile.twitter.com/i/nojs_router?path=/Twitter/status/1184189961278513155
```
and cannot be used.

**Comment by yisiliu** [comment]
can't you directly query https://mobile.twitter.com/Twitter/status/1184189961278513155 ?

**Comment by Misaka-0x447f** [comment]
> 
> 
> can't you directly query https://mobile.twitter.com/Twitter/status/1184189961278513155 ?

This returns the 'do you want to switch to legacy twitter' page

**Comment by yisiliu** [comment]
ok let me try it in a browser

**Comment by SunriseFox** [comment]
removing `<noscript>` tag should reveal the page

**Comment by Tedko** [comment]
@SunriseFox  how's this issue

**Comment by guanbinrui** [comment]
Legacy twitter is supported in #414
