### ISSUE TITLE
[Bug] Message is encrypted for mask users after editing payload picture.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3468]
### How to reproduce?

1.Post an encrypted message in Twitter;
2.Choose image payload and click "edit" on the left bottom of picture;
3.Change size of picture and post it.

### What happened?
The message is encrypted for mask users.
![截屏2021-06-22 下午4 40 29](https://user-images.githubusercontent.com/85149605/122893236-b9b33d80-d378-11eb-88fe-ca2a0e28fe4a.png)

### What should happen?
The message should be showed.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: 1.33.2

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by nuanyang233** [comment]
Plz add the title

**Comment by Tedko** [comment]
@wenluomask this wont fix since the data is encrypted within the image payload. changing /clip it will break the msg
