### ISSUE TITLE
[Bug] TypeError: Cannot destructure property 'date' of 'bisect(...)' as it is undefined.

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3479]
### How to reproduce?

1. Search any token, and enter tradeview 
2. Hover on the price line

### What happened?

61564.js:17127 Uncaught TypeError: Cannot destructure property 'date' of 'bisect(...)' as it is undefined.
    at SVGSVGElement.<anonymous> (1564.js:17127)
    at SVGSVGElement.<anonymous> (chunk.2213.js:2369)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/51563cb515e5fd447efadbe9c638ea6c8f4a7b94/packages/maskbook/src/plugins/Trader/graphs/usePriceLineChart.ts#L121-L128
