### ISSUE TITLE
Issues observed 

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#348]
+ [ ] (iOS) always shows `Maskbook is identifying how to setup your account...` just after login to facebook (Likely will be fixed by 222d04bdc7311f12a26ffe042ed59a5d1bdf50b0)
+ [ ] (iOS) sometimes Maskbook's code does not load -- High Priority
+ [ ] (iOS) cannot view images from news feed
+ [x] (all) ResponsiveDialog event goes to facebook first

**Comment by Tedko** [comment]
Another one: cannot type/search in 'view recipient' popup

**Comment by SunriseFox** [comment]
It is because event goes to facebook first and processed by them.
