### ISSUE TITLE
[Demand] Popup 2.0

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3481]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

https://www.figma.com/file/meVupGL2NoyjoDjc1DzZMM/Mask-Wallet?node-id=9448%3A74

**Comment by Jack-Works** [comment]
What is this?

**Comment by guanbinrui** [comment]
> What is this?

Revamp the Popup page to be able to do wallet and persona management.
