### ISSUE TITLE
[Bug] Cannot restore persona successfully from Mnemonic Words

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3493]
### How to reproduce?

https://user-images.githubusercontent.com/85149605/123219393-6cada380-d4ff-11eb-9fdb-03c579e574b0.mov

1.Back up persona from dashboard and remember the Mnemonic words ;
2.delete the persona and then go the get started page -> Restore From Backup; 
4.Click Advance… to the advanced page, and try Mnemonic words backup.
(Or dashboard-> persona -> import->Mnemonic words backup)

### What happened?
After backup, user need to reconnect social network.

### What should happen?
Data should be back up successfully by Mnemonic words, especially the social network connected.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: Hotfix-1.33.2

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
IMO This is working intended right? @yisiliu 

Mnemonic words only contain the private key, therefore there is no place to store extra information like connected SNS.

**Comment by guanbinrui** [comment]
> IMO This is working intended right? @yisiliu
> 
> Mnemonic words only contain the private key, therefore there is no place to store extra information like connected SNS.

That's right.

**Comment by yisiliu** [comment]
Yes you'd better learn more about how hd wallet works
