### ISSUE TITLE
[Bug] "Originally posted by xxx" info is incorrect when using multiple persona 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3494]
### How to reproduce?

1. Create persona P1, and connect with twitter account T1
2. Create person P2, and connect with twitter account T2
3. Switch current twitter account to T2, and send ITO or RedPacket.

### What happened?

Posted by in ITO card showed persona P1 info

### What should happen?
When switch twitter account to T2, then the persona also should be switched to P2, so the "posted by xx" or "From: xx" info should be changed accordingly.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
🤔 That requires detection of the current identity.
