### ISSUE TITLE
[Bug]There is a chance that two mask icons occur after send an encrypt text message.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3504]
## Bug Info

**How to reproduce?**

https://user-images.githubusercontent.com/85149605/123362362-214cd100-d5a3-11eb-8f7c-b4a2d89a0bfc.mov

1. Post some encrypted text messages;

2. Check the icon besides the name.

**What happened?**

![截屏2021-06-24 下午5 46 40](https://user-images.githubusercontent.com/85149605/123362401-30338380-d5a3-11eb-8fed-b19689d55273.png)
Sometimes there are two icons beside the name. Once I refresh the page, it disappears.

**What should happen?**

Only one mask icon should be there.  

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: Hotfix-1.33.2

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
maybe due to racing issue
