### ISSUE TITLE
Improve the language/UX for on boarding multi social networks

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#356]
<img width="1470" alt="Screen Shot 2019-11-04 at 22 02 20" src="https://user-images.githubusercontent.com/6687437/68127190-57fa5180-ff50-11e9-9c70-65517fadb175.png">

For example for here: 

- Just say 'Switch your Maskbook Account' is better. (should we use the term 'Account'?)

- Also be carefully with the terminology.  @neruthes  Should we use the term 'accounts'? I assume we may use term like 'identity' ?

- For 'Connect Other Accounts'  -- It's better if we can have _suji.yan.me @ facebook.com_   or _sujiyan @ twitter.com_

**Comment by Tedko** [comment]
<img width="1470" alt="Screen Shot 2019-11-04 at 22 03 37" src="https://user-images.githubusercontent.com/6687437/68128366-8c6f0d00-ff52-11e9-9106-a2a0701736e9.png">


Also for here: 

better to have suji_yan @ twitter.com (the one connecting)

**Comment by yisiliu** [comment]
We haven't finished the multi-network identity management design yet. This involves the universal DID/CID design. We will try to finish it soon but this also requires the design of Tessercube PKI. I will create an issue on this.

**Comment by neruthes** [comment]
Within #70.
