### ISSUE TITLE
[Demand] Codegen for @masknet/icons package

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#3563]
Generate TSX files from SVG

- Derive from the file name
- Run by demand? (Like codegen for ETH contrats)
- Generate random ID

**Comment by UncleBill** [comment]
What about using svg as image file or convert them into a font instead of embedding it into DOM?

Moving svg out from JS can reduce both JS file size and runtime memory consumption as well.

**Comment by Jack-Works** [comment]
> What about using svg as image file or convert them into a font instead of embedding it into DOM?

Does anyone know how to handle colorful fonts? Some SVG should bring it's own color information and some SVG should be able to twist the color by CSS>
