### ISSUE TITLE
[Bug] Only Dhedge in plugin list page

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3567]
### How to reproduce?
![Screen Shot 2021-07-02 at 16 46 31](https://user-images.githubusercontent.com/2582974/124248074-11aa2b00-db55-11eb-89cb-80bf6af11213.png)
### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
Oh, this is because all of our plugins are migrated to the new infra and this page doesn't read from the new plugin infra list.
