### ISSUE TITLE
Cannot view/add recipient on Twitter test ver

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#358]
<img width="1470" alt="Screen Shot 2019-11-04 at 22 28 30" src="https://user-images.githubusercontent.com/6687437/68178552-66378480-ffc7-11e9-9dc3-6b2aac049f8c.png">
<img width="1470" alt="Screen Shot 2019-11-04 at 22 07 31" src="https://user-images.githubusercontent.com/6687437/68178557-6a63a200-ffc7-11e9-9923-e81bda0f54d4.png">

How to reproduce:

Post some encrypted msg, try add/view recipients.

**Comment by Jack-Works** [comment]
let me check out this

**Comment by Jack-Works** [comment]
fixed
