### ISSUE TITLE
[Bug] Infinite loop during import JS as 'file' on iOS

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#3603]
### What happened?
On Mask Network iOS app, while decoding image format Mask encoded format payload, js files stuck on `resolveSocialNetworkWorker`, making image payloads can not be decoded.

The root cause seems to be that, during importing chunk js files, inside 'WebExtension-Shim`, `RunInProtocolScope` function has 
```
if (code.type === 'file')
    script.src = code.path;
```
This triggers the setter bound to `src` element. Inside the hooked setter, it invokes `RunInProtocolScope` again, leads to the infinite call loop.
![Clipboard2](https://user-images.githubusercontent.com/7972003/124719888-31b56200-df3a-11eb-82f1-da6360cdfb4a.png)
![Clipboard](https://user-images.githubusercontent.com/7972003/124719902-337f2580-df3a-11eb-8d87-8034cdc43e96.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [x] iOS 14

**Comment by Jack-Works** [comment]
@jk234ert please try https://github.com/DimensionDev/webextension-polyfill/commit/57a254d0d7c7e531a76959e1fd565e836bc05e32
