### ISSUE TITLE
[Demand] Add useTokensDetailed() hook

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#3605]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
There's an `useTokenDetailed()` hook to fetch token information by passing the token address in our codebase now.

## Part 2: Problem to Solve
Add an `useTokensDetailed()` hook which accept a token address list to fetch bunch of token informations.

**Comment by guanbinrui** [comment]
`useTokensDetailed`
