### ISSUE TITLE
[Bug] Duplicate native token records

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3606]
### How to reproduce?

The original address is 0x66b57885E8E9D84742faBda0cE6E3496055b012d.

Those native token records fetched by `useAssetsFromChain` should be removed. 

![image](https://user-images.githubusercontent.com/52657989/124726845-b6a37a00-df40-11eb-878e-b30dba195aa4.png)
![image](https://user-images.githubusercontent.com/52657989/124726960-d5a20c00-df40-11eb-9796-bba8dc3b9d4b.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
Using the '0x66b57885E8E9D84742faBda0cE6E3496055b012d' test, the problem cannot be reproduced

**Comment by Tedko** [comment]
> Using the '0x66b57885E8E9D84742faBda0cE6E3496055b012d' test, the problem cannot be reproduced

switch the data source to zerion

**Comment by Tedko** [comment]
@lelenei

**Comment by lelenei** [comment]
matric
<img width="904" alt="image" src="https://user-images.githubusercontent.com/72531217/125713629-9231a451-9326-4f4c-ab44-8a4e4505b84f.png">
<img width="881" alt="image" src="https://user-images.githubusercontent.com/72531217/125713647-b977530f-2f42-466f-9fd2-20508151b2f2.png">
bsc:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/72531217/125713693-190e6f59-8f39-470d-a4bb-ae09e0029768.png">
<img width="881" alt="image" src="https://user-images.githubusercontent.com/72531217/125713712-2b4a52fe-2b72-4350-bb3a-43c427cf5f48.png">
eth:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/72531217/125713756-71cfc8ff-0e50-4b02-93fa-97b6373dba54.png">
<img width="915" alt="image" src="https://user-images.githubusercontent.com/72531217/125713784-20d972f8-b1ca-409f-8e00-f14517c68465.png">

**Comment by guanbinrui** [comment]
Fixed in [PR hotfix/1.34.1](https://github.com/DimensionDev/Maskbook/tree/hotfix/1.34.1) by 01fd81e1e9b5b01d44d2be8d91a834de0b132c13.
