### ISSUE TITLE
[Bug] "Account" dialog should be auto closed after changing wallet connection

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3627]
### How to reproduce?

1. Click "Account" on left side menu. 
2. Click "Change" to change wallet connection.

### What happened?
Wallet connection is changed, but the "Account" dialog is still alive.

### What should happen?
After wallet connection changed, the "Account" dialog should be closed automatically.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Failed to reproduce.
