### ISSUE TITLE
[Feature] Encrypted tweets that just view for myself should display different message to other mask users.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3635]
### How to reproduce?

1. Send any encrypted tweets that just view for myself;
2.Change to a different twitter account which installs mask(personas are not stay together);
3.Check the encrypted tweet posted before.

### What happened?
The encrypted tweet displays a loading icon and message "Mask is retrieving the post key to decrypt this post." 
![截屏2021-07-09 上午11 45 17](https://user-images.githubusercontent.com/85149605/125020298-2afa2c80-e0ab-11eb-83ff-17e0112d1993.png)

### What should happen?
The encrypted tweet displays "You are not authorized to view it, please ask the owner for authorization."
![截屏2021-07-09 上午11 23 59](https://user-images.githubusercontent.com/85149605/125020285-259ce200-e0ab-11eb-960d-01e0ce9d4672.png)
Please fix it in 1.34.1

### Mask Version:

- [x] (Browser) Installed from the extension store (version:1.34 )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
I'll change this to a feature request. IIRC encrypted to myself still allows appending the encryption key in the future and there is no way to distinguish from a normal encrypted post in the payload level.

**Comment by Tedko** [comment]
is that technically doable in an easy way? um

**Comment by Jack-Works** [comment]
> is that technically doable in an easy way? um

We should not do it even if we can. It's a privacy leak.

**Comment by yisiliu** [comment]
exactly

this meta info should never be leaked to anyone but the sender.

**Comment by Tedko** [comment]
add 'will not fix'
