### ISSUE TITLE
[Crash] RangeError: Invalid time value

### ISSUE THREAD

**Issue by BlueManGroup1735** [DimensionDev/Maskbook#3644]
I was *looking at a post on twitter for spaceshibas*, then Mask report an error.

> Invalid time value

Error stack:

<pre>format@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/chunk.npm.date-fns.js:1999:11
Collectible@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/chunk.1452.js:2493:56
Ch@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:232:137
si@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:259:255
gk@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:356:346
fk@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:343:24
ek@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:342:371
Vj@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:342:229
Pj@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/npm.react-dom.js:331:476
J@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/5133.js:16253:204
R@moz-extension://548b68eb-ff08-4b13-9b37-5e246ea5ab46/js/5133.js:16254:123
</pre>

## Build info
- Version: 1.34.0
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- firefoxVariant: fennec
- resolution: desktop
- BUILD_DATE: 1970-01-01T00:00:00.000Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A) on tag "N/A"
N/A

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/69df9490a2720d496e3e15906e3476fdcbe8d0e7/packages/maskbook/src/plugins/Collectible/SNSAdaptor/Collectible.tsx#L303-L311
