### ISSUE TITLE
Notes on Google's Manifest V3

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#365]
## Development experience regression

- [ ] [Issue 1159293: Unable to use "unsafe-eval" as CSP of Web Extension manifest V3](https://bugs.chromium.org/p/chromium/issues/detail?id=1159293) even in development (sideload) mode
- [ ] fixed [Issue 1159283: Cannot refresh via F5 in the background service worker of Web Extension Manifest V3](https://bugs.chromium.org/p/chromium/issues/detail?id=1159283)

## Chunk splitting

- [ ] [Issue 1159286: Cannot use importScripts after init in Web Extension manifest v3 background service worker](https://bugs.chromium.org/p/chromium/issues/detail?id=1159286)
- [ ] [Issue 1198822: Allow dynamic import() and postponed importScripts() in extension service worker](https://bugs.chromium.org/p/chromium/issues/detail?id=1198822)

## Usability

- [ ] [Issue 1152255: ServiceWorker is shut down every 5 minutes for manifest V3 extension](https://bugs.chromium.org/p/chromium/issues/detail?id=1152255)
- [ ] No longer need ~~[Issue 1137396: Manifest V3: Scripts injected into pages by an extension content script no longer bypass the page's CSP](https://bugs.chromium.org/p/chromium/issues/detail?id=1137396)~~
- [ ] No longer need ~~[Issue 1051597: Extension Manifest V3 support for SingleFileZ and similar extensions](https://bugs.chromium.org/p/chromium/issues/detail?id=1051597) **Manifest V3 cannot use DOMParser in the background, make some DOM parsing feature dies**~~
- [ ] No longer need ~~[Issue 1252645: Cannot use Worker in MV3 background worker](https://bugs.chromium.org/p/chromium/issues/detail?id=1252645)~~
- [x] [Issue 1173354: wasm does not work in extensions manifest v3](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354)

**Comment by Tedko** [comment]
I feel this will largely affect adblock? @Jack-Works  and when will google do the next step?

**Comment by Jack-Works** [comment]
I have no idea about how manifest v3 is going on now

**Comment by Jack-Works** [comment]
https://blog.chromium.org/2020/12/manifest-v3-now-available-on-m88-beta.html

**Comment by Jack-Works** [comment]
I'll write about the problems I found here. Maybe report to the Chrome team later.

1. New CSP policy does not allow `unsave-eval` which is important for development mode sourcemapping.
2. New property `host_permissions` doesn't distinguish if it is optional or not.
3. ...

**Comment by Jack-Works** [comment]
new blocker: WebAssembly does not work in MV3

https://bugs.chromium.org/p/chromium/issues/detail?id=1173354

**Comment by Jack-Works** [comment]
Manifest V3 support is in the mainline.

**Comment by Jack-Works** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1271154
