### ISSUE TITLE
Plan a reliability test for GUN

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#367]
## Purpose

Test the reliability of GUN.

## Scale

Within 1 hour, 1000 users publish posts (uniform distribution), each post being shared to 1 user group, each user group consisting of 4 non-self recipients. Facebook only.

We do not actually publish things on Facebook.

## Modes

The traditional mode and #168 mode should be tested separately.

## Environment

2 nodes, including Heroku and Linode.

## Metrics

How long does it take for an entry to be accessible at the other server.

## Measurement

After a post is published on one node, it tries to get the post key from the other node, interval 30 sec (reduced to 60 sec since 5 min, and to 120 sec since 10 min).

**Comment by Jack-Works** [comment]
It's better not to pollute the data on the main gun network

**Comment by yisiliu** [comment]
https://github.com/amark/gun/tree/master/test/panic could help us run some tests on our server.

**Comment by Tedko** [comment]
close for now. will re evaluate later
