### ISSUE TITLE
[Bug] The link for viewing pair analytics in swap dialog link to a broken page.

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#3671]
### How to reproduce?

1. open swap dialog
2. checkout the link for viewing pair analytics

### What happened?

https://info.uniswap.org/pair/0x4d5f135691f13f7f5949ab3343ac7dc6bd7df80b link to a broken page.

![image](https://user-images.githubusercontent.com/1141198/125585482-daef3010-a29f-4d25-ae45-d415d8708c95.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
The V2 Analysis has been removed its host from [info.uniswap.info] to [v2.info.uniswap.info].
