### ISSUE TITLE
[DX problem] webpack keeps compiling repeatedly without file changes

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#3672]
Start it from my terminal without any editor open.

![image](https://user-images.githubusercontent.com/1141198/125588662-25f4ed19-7a37-487d-a462-394357a641b8.png)

~~I guess its' because the `tsc` process is running, and it compiles `ts` into `js`, then triggers webpack to recompile.~~

**Comment by Jack-Works** [comment]
Yes, this problem exists but I don't know why.

> I guess its' because the tsc process is running, and it compiles ts into js, then triggers webpack to recompile.

This is not true because we're actually not using `.js` file emitted from the `tsc`.
