### ISSUE TITLE
[Bug] walletconnect icon ux issue on IOS

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3677]
### How to reproduce?

![IMG_0760](https://user-images.githubusercontent.com/2582974/125609516-9aa784b0-1c1d-496c-a3a6-8d3471f72c95.PNG)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [x] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [x] iOS 14

**Comment by Tedko** [comment]
can you guys reproduce? fail to reproduce on my end

**Comment by Tedko** [comment]
cannot reproduce
