### ISSUE TITLE
[Demand] add rpc param to useContract()

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#3689]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
The RPC for contract is equal to the current one of wallet provider.

## Part 2: Problem to Solve
Now we want to read contract data from any chain no matter which chain you are on.

## Part 3: Expected Behavior
E.g. Metamask is on eth-mainnet, BSC ITO card is still visible.

**Comment by guanbinrui** [comment]
I've added a parameter for RPC overrides to the INTERNAL_Send in #3664.
