### ISSUE TITLE
Dashboard Revamp (Stage 2)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#369]
## Metadata

Field | Value
--- | ---
Previous Stage | #70 
Figma Link | [figma.com/...](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=1%3A2)
Expected UX prototype due | 2019-11-12
Actual UX prototype release | 2019-11-13
Expected engineering due | 2019-12-15

## Catalogue

- Dashboard internal navigation structure minor adjustment
- Create Persona UX adjustment
- Connect Profile UX adjustment
- Delete Persona UX adjustment
- Disconnect Profile UX adjustment

### Left For Future Stages

- Database Backup
- Backup Persona UX adjustment
- Import Persona UX adjustment
- Debug Tool UX adjustment
- Misakanet UX initialization

### Desktop Browser Extension

Generally, Dashboard is opened in a new tab. In such scenario, we do not need a way to exit Dashboard.

### Stand-Alone App, Big Screen

Min-width: 1024.

In addition to the case of Desktop Browser Extension, we need a way to exit Dashboard. Simply add an AppBar above at the top left position, within the pseudo-drawer.

### Stand-Alone App, Small Screen

Max-width: 1023.

In this case, we need an AppBar which has a close button at the top-right corner for exiting. Also, in the sense that we cannot use a drawer button to invoke the drawer, the items in the drawer will be shown as tabs below the AppBar.

## Dashboard Home

- Multiple sections:
  - My Personas
  - Add Persona
  - Database

<img width="336" alt="Screen Shot 2019-11-12 at 10 09 31" src="https://user-images.githubusercontent.com/2139261/68662361-908fc180-0534-11ea-95d0-541c1ab02638.png">

##### Component: Profile Row

- Vacant Mode
  - Show a blue text button to connect a profile
- Filled Mode
  - Show a black text label to display the username with a leader `@` regardless of site-specific conventional representation of usernames.

##### Modes

- Standard Mode
  - Hover Persona Card to show "Edit Name" button
  - Hover Profile Row to show "Disconnect" button
- Name Edit Mode
  - "Save" button never hides
  - Other operations do not interrupt name edit mode

## Create Persona

- Step 1: Set name
- Step 2: See success screen, be suggested to connect a profile
- Step 3a: Quit
- Step 3b: Connect a profile

<img width="901" alt="Screen Shot 2019-11-13 at 07 48 16" src="https://user-images.githubusercontent.com/2139261/68743272-fab66e00-05e9-11ea-80b8-eb6f9f482258.png">

## Backup Persona

<img width="586" alt="Screen Shot 2019-11-13 at 07 50 02" src="https://user-images.githubusercontent.com/2139261/68743380-3e10dc80-05ea-11ea-8c25-b7f2266beef7.png">

## Import Persona

<img width="442" alt="image" src="https://user-images.githubusercontent.com/2139261/68743496-85976880-05ea-11ea-8e46-845d6c92ba0b.png">

## Delete Persona

<img width="892" alt="Screen Shot 2019-11-13 at 07 48 49" src="https://user-images.githubusercontent.com/2139261/68743301-0b66e400-05ea-11ea-9f9d-8444cd18620d.png">

## Connect Profile

<img width="892" alt="Screen Shot 2019-11-13 at 07 47 16" src="https://user-images.githubusercontent.com/2139261/68743226-e1152680-05e9-11ea-8794-0c8a773921a6.png">

## Disconnect Profile

<img width="663" alt="image" src="https://user-images.githubusercontent.com/2139261/68743700-ed4db380-05ea-11ea-88cf-1f04fe038f57.png">

## Database Backup

<img width="646" alt="image" src="https://user-images.githubusercontent.com/2139261/68743579-ae1f6280-05ea-11ea-8bfd-284a70bce816.png">

## Database Restore

<img width="878" alt="image" src="https://user-images.githubusercontent.com/2139261/68743566-a5c72780-05ea-11ea-9c3c-8b03dae181a4.png">

**Comment by SunriseFox** [comment]
I sometimes think the configuration is too complex and confusing, more after memo words were implemented and will be even more after this if implemented. We should think as a user with only a basic level about using social media and crypto, not a designer that designs a too complicated masterpiece with limited user experience.

**Comment by yisiliu** [comment]
> I sometimes think the configuration is too complex and confusing, more after memo words were implemented and will be even more after this if implemented. We should think as a user with only a basic level about using social media and crypto, not a designer that designs a too complicated masterpiece with limited user experience.

good point - let's show this to a "real" user

**Comment by neruthes** [comment]
Good point, but also note that Dashboard Revamp Stage 3 will include Initialization procedure.

**Comment by neruthes** [comment]
Also, if we really wanted to avoid exceeding the level where "real" users feel difficult to understand, we should not have started supporting multiple networks and multiple personas. It is always a science of balance.

**Comment by neruthes** [comment]
Note:

"Connect Profile" procedures may be subject to changes according to the arrangement of #409. 

https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=196%3A1474

It may be good to deliver #409 and #369 in the same release.

**Comment by SunriseFox** [comment]
This seems not at all like what I could finish within this month... It contains lots of work apart from the UI aspect. Some more days may be required.

**Comment by Jack-Works** [comment]
why do we need a "base64" mode?

**Comment by neruthes** [comment]
@Jack-Works There are alternative backup methods. I just leave Base64 as a placeholder. Other ways should employ the same interaction design. Options remain open for discussion.

**Comment by neruthes** [comment]
Update:

We may pass the #194 (with private key) payload into Base64 encoding as the result of Base64 persona backup payload.

**Comment by SunriseFox** [comment]
![image](https://user-images.githubusercontent.com/14029711/69592975-ade38600-1032-11ea-973e-5516e924cbac.png)
Filename and save place cannot be enforced. So displaying such information is not possible.

**Comment by neruthes** [comment]
> ![image](https://user-images.githubusercontent.com/14029711/69592975-ade38600-1032-11ea-973e-5516e924cbac.png)
> Filename and save place cannot be enforced. So displaying such information is not possible.

So we may skip this step. When the user clicks "Backup" button in the Database section, the user will get the native download prompt.

**Comment by SunriseFox** [comment]
:gai_hui_qu_le:

**Comment by neruthes** [comment]
Update:

According to the discussions in #407, the persona creation modal will include a mandatory password field.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/2139261/70225835-b67d4000-1747-11ea-9832-8cc04380227e.png">

**Comment by Tedko** [comment]
Request a QR code identity tsf functionality within the same milestone. We should not ship any stable ver without the QR code identity tsf functionality.

**Comment by neruthes** [comment]
> @neruthes Request a QR code identity tsf functionality within the same milestone. We should not ship any stable ver without the QR code identity tsf functionality.

Will be added in Stage 3. Consider releasing Stage 3 together.

**Comment by neruthes** [comment]
Backup alert is removed. No need to implement it in this stage.

**Comment by neruthes** [comment]
Update:

Changed this line of text.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/2139261/70593575-77cb0800-1bd5-11ea-9db7-ed1c3892bddf.png">

**Comment by neruthes** [comment]
Note:

We later agreed that the connecting component (Figure 1) may be embedded in the webpage, and may be delivered before #409.

--------

- Figure 1:
  - <img width="321" alt="image" src="https://user-images.githubusercontent.com/2139261/71609993-17e8d100-2b85-11ea-801c-ea92db55549d.png">
