### ISSUE TITLE
[Bug] Switch to xx network not work - occasional problems

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3693]
### How to reproduce?
MetaMask: 9.7.1

1. Switch network in plugin card

### What happened?
Sometime, it's not work as expected.

https://user-images.githubusercontent.com/2582974/125799570-add8aa84-35ab-486e-a6ef-a1364e66fd2d.mp4

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
Any thoughts?

**Comment by guanbinrui** [comment]
May be fixed by #3664.
