### ISSUE TITLE
[Feature] Add entries for «Import Keystore» and «Publish Public Key» in decryption error messages

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#37]
For example, for this situation:
![Screen Shot 2019-05-21 at 16 29 40](https://user-images.githubusercontent.com/6687437/58080356-a788d300-7be5-11e9-8e8f-ca5a6835f15a.png)

We should remind the user that the private key is not imported or generated.

**Comment by neruthes** [comment]
Possible error message:

```
Seems that you do not have your private key. You may <a>import your existing keystore</a> or <a>reset and start from scratch</a> if you have totally lost your keystore.
```

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/60434989-04db5f80-9c3b-11e9-9831-25ad656de1ee.png)
