### ISSUE TITLE
[Bug] Transactions list and assets value does not work with Zerion under EVM compatible chain (BSC & Polygon)

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3700]
### How to reproduce?

1. Change data source to "Zerion"
2. Check assets value and transactions list under BSC or Polygon

### What happened?
Assets value alway shows 0 and transactions list is empty.

### What should happen?
The data should be displayed correctly. 

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Zerion does not support BSC and Polygon. What about hiding the transaction tab if Zerion was selected.

**Comment by AinuX** [comment]
> Zerion does not support BSC and Polygon. What about hiding the transaction tab if Zerion was selected.

Should be confirmed with @xiazhiming

**Comment by guanbinrui** [comment]
I'm sure that Zerion is supporting BSC and Polygon. This bug will be solved in the next ver.

**Comment by guanbinrui** [comment]
> I'm sure that Zerion is supporting BSC and Polygon. This bug will be solved in the next ver.

Ops, only assets are supported.

**Comment by guanbinrui** [comment]
The ZERION API now is supporting BSC and Polygon.

+ https://docs.zerion.io/websockets/namespaces/address#bsc-assets
+ https://docs.zerion.io/websockets/namespaces/address#polygon-assets
