### ISSUE TITLE
[Bug] Fail to get MASK's price in Wallet page of Dashboard

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3702]
### How to reproduce?

1.Connect a wallet that has MASK in both BSC and ETH;
2.Go to Wallet page of Dashboard, and add MASK token in both BSC and ETH if you didn't do so;
3.Check the price and value for both MASK token.

### What happened?
BSC's MASK token doesn't have price and 0 value.
![截屏2021-07-16 下午4 34 21](https://user-images.githubusercontent.com/85149605/125920058-ead8f35b-c1ea-4e39-83e4-15558d68e7d2.png)
![截屏2021-07-16 下午4 34 45](https://user-images.githubusercontent.com/85149605/125920030-b23b9e2a-5538-4fa2-8f88-933c9797dd7c.png)

### What should happen?
Both token should show the information from Debank.
### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash:1.34.1

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
"Mask" and "MASK" are not the same token.
It is recommended to delete "Mask"!

**Comment by wenluomask** [comment]
> "Mask" and "MASK" are not the same token.
> It is recommended to delete "Mask"!

The Mask didn't show price is the MASK token in BSC network. It is necessary to display in Wallet.

**Comment by lelenei** [comment]
> > "Mask" and "MASK" are not the same token.
> > It is recommended to delete "Mask"!
> 
> The Mask didn't show price is the MASK token in BSC network. It is necessary to display in Wallet.

There is no 'Mask' token in the data returned by debank, so the Mask didn't show price and usd

**Comment by wenluomask** [comment]
Checked.
