### ISSUE TITLE
[Demand] Migrate `react-use` to `react-hookz`

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#3705]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other
  - /_List it here_/

## Notes

plz @Jack-Works provide a migration guide.

reference: https://github.com/react-hookz/web/pull/209

**Comment by Jack-Works** [comment]
Let's wait for a while
