### ISSUE TITLE
[Bug] Fail to load avatar image in dHEDGE plugin

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3708]
### How to reproduce?

1. Check avatar in dHEDGE plugin card.

![image](https://user-images.githubusercontent.com/2582974/126139930-02b790d4-f499-4506-898f-aa3363f04f70.png)

![image](https://user-images.githubusercontent.com/2582974/126139839-5500e932-714e-4f25-be75-de1216f1e144.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
Is this fixed? @lelenei

**Comment by Tedko** [comment]
Is this fixed

**Comment by lelenei** [comment]
avatar image load from twitter, need twitter sdk
