### ISSUE TITLE
[Bug] Mask Wallet information still exists after delete operation.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3722]
### How to reproduce?

1.Import wallet via mask wallet;
2.delete wallet in Dashboard's Wallet page;
3.Check Dashboard's Wallet page and Twitter's left menu bar.

### What happened?
Wallet address is showed on Dashboard's Wallet page and Twitter's left menu bar.
![截屏2021-07-21 上午11 46 08](https://user-images.githubusercontent.com/85149605/126427937-9859ec7e-3ddb-4555-876e-9b26ec4dd6f4.png)
![截屏2021-07-21 上午11 46 20](https://user-images.githubusercontent.com/85149605/126427942-547b11c7-1f85-43ca-b4ac-55090e29f45d.png)

### What should happen?
Wallet address shouldn't be showed and "Connect Wallet" should be showed.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: ) 
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:fix/wallet-dialog

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
The current wallet address did not clean.

**Comment by UncleBill** [comment]
@guanbinrui I can handle this issue. And I would submit a PR later.

**Comment by wenluomask** [comment]
Checked.
