### ISSUE TITLE
[RFC] Maskbook Twitter payload specification

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#373]
## Metadata

Field | Value
--- | ---
Manifest | [Meta/Article-3](https://github.com/DimensionDev/Meta/blob/master/articles/3--rfc-peer-review.md)
Purpose | Support posting on Twitter
Feedback deadline | 2019-11-15 12:00:00 UTC
Explicitly designated reviewers | @yisiliu @Jack-Works @SunriseFox 

## Dependencies

- #198 
- #329 

## Glossary

Phrase | Definition
--- | ---
mock_url | The URL-like payload, as specified in #198, which represents a payload which is specified in #329.
non-user | A person who is not a Maskbook user, or has not installed/enabled Maskbook on the current device.

## Principles

- Be shorter than max length of tweets.
- Clearly tells non-users how to decrypt.
- Has fun memes.
- Hides mock_url as invisible as possible.

### Base

```
#InMaskweBook ([I:b])

Decrypt this tweet with @ProjectMaskbook

—§— /* {mock_url} */
```

### Alternatives

```
#InMaskWeBook ([I:b]) Decrypt this tweet with @ProjectMaskbook

—§— /* {mock_url} */
```

```
#Maskbook_com ([I:b]) Decrypt this tweet with @ProjectMaskbook

—§— /* {mock_url} */
```

```
([I:b]) Decrypt this tweet with @ProjectMaskbook

—§— /* {mock_url} */
```

```
([I:b]) Decrypt this tweet with @ProjectMaskbook #Maskbook_com

—§— /* {mock_url} */
```

```
([I:b]) Decrypt this tweet with #Maskbook_com

—§— /* {mock_url} */
```

## The Choice: ☯️

While #Maskbook is the hashtag we ultimately want to advocate for, #InMaskWeBook is an irresistibly nice meme. We will use both, randomly selecting one upon posting.

```
#InMaskweBook ([I:b])

Decrypt this tweet with <https://maskbook.com> (Twitter: @ProjectMaskbook)

—§— /* {mock_url} */
```

```
#Maskbook ([I:b])

Decrypt this tweet with <https://maskbook.com> (Twitter: @ProjectMaskbook)

—§— /* {mock_url} */
```

## Notes

- On Twitter we can mute "Decrypt this tweet with" keyword in notifications to prevent being unable to distinguish the tweets which seek to start a conversation with us.

**Comment by Tedko** [comment]
I do like #InMaskWeBook but this meme is not good.. We might use #Maskbook_com  or #Maskbookcom

**Comment by Tedko** [comment]
Got some great feed back from Cole
```
Decrypt this tweet with @ProjectMaskbook!

Download here:
```

>You need the call to action - Which is download

Still, using URL is sensitive

**Comment by Tedko** [comment]
Also what if we just use #Maskbook ?

**Comment by Tedko** [comment]
I dont have any strong preference -- so lets consider just use #Maskbook and go ahead

**Comment by Tedko** [comment]
The time is passed - recommend lets put the URL back:

 ```
#Maskbook ([I:b])

Decrypt this tweet with maskbook.com @ProjectMaskbook

—§— /* {mock_url} */
```

Is prob the best for now

**Comment by neruthes** [comment]
We may replicate the way employed by Blizzard for Lenassa and Zer'atai.

**Comment by neruthes** [comment]
This RFC should go into finalization when #397 needs.

**Comment by Tedko** [comment]
I need this to be delivered b4 #397 and by this Friday. 

The only thing we need is `#Maskbook`  or `with maskbook.com @ProjectMaskbook`

@neruthes @guanbinrui

**Comment by neruthes** [comment]
> I need this to be delivered b4 #397 and by this Friday.
> 
> The only thing we need is `#Maskbook` or `with maskbook.com @ProjectMaskbook`
> 
> @neruthes @guanbinrui

Your advice should have been satisfied in the Conclusion section.
