### ISSUE TITLE
[Bug] Lost original tweet info while sharing after depositing token in PoolTogether

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3771]
### How to reproduce?

1. Deposit token in pooltogether
2. Share the info after depositing tx was send 
3. Check the shared tweet 

![image](https://user-images.githubusercontent.com/2582974/127117696-18e10d8b-6a7c-44b1-af00-6037fb4ce88d.png)

### What happened?
There is no original pooltogether info.

### What should happen?
The original pooltogether info should be associated. 

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
As disused in prev calls and eco group chat we should close this issue

**Comment by Tedko** [comment]
@AinuX i will close this fyi
