### ISSUE TITLE
[Bug] The value of balance in past ITO tab is incorrect

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3773]
### How to reproduce?

1. Send ITO 
2. Check the value of balance in past ITO tab

### What happened?
The value is incorrect, seems that it's a variable reference error.
![image](https://user-images.githubusercontent.com/2582974/127132523-b4d956dd-8302-49ac-a640-aa4e208aa4c9.png)

![image](https://user-images.githubusercontent.com/2582974/127132631-ce2c4287-b2ec-4fae-8664-315de10604c9.png)

Cake decimal 18
Alice decimal 6

0xbtc decimal 8
Matic decimal 18

The root cause of the issue maybe,
![image](https://user-images.githubusercontent.com/2582974/127133402-15e510fc-4fa0-42cb-a2f4-142f16b3347a.png)
 

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Checked.
