### ISSUE TITLE
[Bug] Unable to switch Network automatically in Metamask since user is connecting different chain wallet

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3774]
### How to reproduce?

1.Set the Metamask wallet in BSC network;
2.Connect Eth Metamask wallet;
3.Check what will be happened.

### What happened?
Fail to connect wallet because Metamask didn't switch Network automatically.

https://user-images.githubusercontent.com/85149605/127135057-3aa26077-bb6f-49f6-90e4-555c8d8dece2.mov

### What should happen?
Metamask should switch to Eth Network automatically and then connect the wallet.
### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Fixed by #3586.

**Comment by wenluomask** [comment]
It doesn't work in the latest develop.

**Comment by wenluomask** [comment]
Checked.
