### ISSUE TITLE
[Bug] Switch network does not work with walletconnect 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3778]
### How to reproduce?

1. Connect wallet via wallet connect
2. View some tweets contain plugin with unsupported chain  
3. Try to switch network in plugin card

### What happened?

https://user-images.githubusercontent.com/2582974/127137539-773cf98a-9a19-4b39-977c-80d52998c3c7.mp4

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
is this a bug /limitation of Wallet connect itself? 
@yisiliu lets connect with Wallet Connect team and donate them for stability if possible
