### ISSUE TITLE
[Crash] TypeError: null is not an object (evaluating 'parentEle.querySelector')

### ISSUE THREAD

**Issue by llorillee** [DimensionDev/Maskbook#3818]
I was *omg! This is all over my Facebook page. I can’t read anyone’s post*then Mask report an error.

> null is not an object (evaluating 'parentEle.querySelector')

Error stack:

<pre>zipPostLinkPreview
zipPost
PostInspector
Ch
gk
fk
ek
Vj
Pj
Pj@[native code]
J
R</pre>

## Build info
- Version: 1.34.0
- NODE_ENV: production
- target: safari
- build: stable
- architecture: app
- firefoxVariant: false
- resolution: mobile
- BUILD_DATE: 2021-07-13T07:57:40.890Z
- VERSION: v1.29.12-593-gbc6604a26

## Git (*):

bc6604a26 (HEAD) on tag "v1.29.12"
https://github.com/DimensionDev/Maskbook

**Comment by Jack-Works** [comment]
hi, thanks for your report. we have already fixed this but the new version is still in review.
