### ISSUE TITLE
[Bug] 1.34.1 was rejected by Firefox

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3819]
### How to reproduce?

```
This version contains obfuscated code or logic, which is not permitted by our policies. Please re-submit with the code without obfuscation. Further instructions are available at https://extensionworkshop.com/documentation/publish/source-code-submission/#use-of-obfuscated-code. Here are some examples of obfuscated code we have found:
- js\npm.bn.js.js
```

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
@Jack-Works

**Comment by Jack-Works** [comment]
Nothing we can do, we're not compressing the code

**Comment by guanbinrui** [comment]
It was rejected by the bot. Has been confirmed by a human reviewer.
