### ISSUE TITLE
[Bug] WalletConnect doesn't work in Mask Extension

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3822]
## Bug Info
Same problem as #3801 
### How to reproduce?

1.Connect wallet by using WalletConnect.

### What happened?
Metamask, huobi and imtoken are all unresponsive.

### What should happen?
Connect successfully by using Wallet Connect.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment]
@wenluomask This issue should be fixed by #3821

**Comment by wenluomask** [comment]
Checked.
