### ISSUE TITLE
[Bug] Red packet plugin didn't show the information.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3830]
### How to reproduce?

1.Check any red packet tweet, like https://twitter.com/WEN6666661/status/1422100805461504000.

### What happened?
Red packet plugin card didn't show the information.
<img width="583" alt="Screen Shot 2021-08-02 at 3 49 22 PM" src="https://user-images.githubusercontent.com/85149605/127830125-f04aea0d-eb6b-43c2-abd3-c8d1c81bae62.png">

### What should happen?
Red packet plugin card should show the information.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash:develop

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
This is due to use new red-packet on old version mask within our testing stage. 

It would happen on production version.
