### ISSUE TITLE
[Bug] “Fail to check for transaction receipt” error occurs when doing swap and rep packet by using imtokn wallet(WalletConnect)

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3832]
### How to reproduce?

1.Connect imtoken wallet by using WalletConnect;
2.Swap token or send a red packet.

### What happened?
“Fail to check for transaction receipt” error occurs;
 Swap successfully;
Red packet is unlock token unsuccessfully.
<img width="1378" alt="Screen Shot 2021-08-02 at 4 00 02 PM" src="https://user-images.githubusercontent.com/85149605/127833714-55085bd0-73b2-45e8-a1fd-5a2a2b22cbdc.png">
<img width="1423" alt="Screen Shot 2021-08-02 at 4 03 43 PM" src="https://user-images.githubusercontent.com/85149605/127833722-68ba65c1-a0a2-49ee-a33c-eef50a0c7373.png">

https://user-images.githubusercontent.com/85149605/127833726-cfbaf9f7-d659-481a-803a-e1b480e6abcd.mov

### What should happen?
Swap or send red packet successfully.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash:develop

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
bug from walley connect likely

**Comment by wenluomask** [comment]
Can not reproduce.
