### ISSUE TITLE
Create a twitter account for testing all kinds of tweet

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#3836]
## Introduction and Background

To test all kinds of tweet more easily, we can create a twitter account which will post every kind of tweet to cover our test cases.

## Content

Test cases including:

- [ ] text only, not crypto text
- [ ] link only, 
- [ ] crypto text
- [ ] image payload
- [ ] other kinds of tweet

**Comment by UncleBill** [comment]
@DimensionDev/qa Could you help to create one?

**Comment by wenluomask** [comment]
Okay.

**Comment by wenluomask** [comment]
Please follow WenLuo04001516 to check the tweets for testing.

https://twitter.com/WenLuo04001516
