### ISSUE TITLE
[Bug] The decrypted text box in timeline is unclickable to enter tweet's detail page.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3838]
### How to reproduce?

1.Post an encrypted tweet;
2.Click the decrypted text in the tweet.

### What happened?
Unresponsive after clicking the decrypted text box.
<img width="937" alt="Screen Shot 2021-08-03 at 5 06 09 PM" src="https://user-images.githubusercontent.com/85149605/127989511-5ad2b51e-9c70-4eb0-a447-e2c890f95c20.png">

### What should happen?
Enter tweet's detail page after clicking the decrypted text box.

### Mask Version:

- [x] (Browser) Installed from the extension store (version:1.35 )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
Is your expected behavior is to open the tweet on the full page?

**Comment by wenluomask** [comment]
> Is your expected behavior is to open the tweet on the full page?

Yes.

**Comment by Jack-Works** [comment]
> > Is your expected behavior is to open the tweet on the full page?
> 
> Yes.

It's a hard problem because we have to reject all events like this to be sent across the boundary we create.

![image](https://user-images.githubusercontent.com/5390719/128001437-8ed6f0ea-b76c-4dbd-8499-9f4491b669af.png)

So this is expected
