### ISSUE TITLE
[Bug] GoodGhosting link tweet was showing "Something went wrong" in plugin card.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3858]
### How to reproduce?

1.Check the tweet with GoodGhosting link: https://twitter.com/WEN6666661/status/1423156243108044800

### What happened?
"Something went wrong" was showing in plugin card.

### What should happen?
Pool's information should be showed.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash:develop

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment]
Looks like the data struct of `https://raw.githubusercontent.com/Good-Ghosting/mask-plugin-integration/master/games.json` got changed.

![image](https://user-images.githubusercontent.com/1141198/128305068-d30f9604-8a8c-4573-b0a0-ac43525e1285.png)

**Comment by UncleBill** [comment]
Since https://github.com/Good-Ghosting/mask-plugin-integration/commit/420282450ff1d4b4f7c2bc1667dfd45adcae7017

**Comment by wenluomask** [comment]
Checked.

**Comment by UncleBill** [comment]
Fixed by #3815
