### ISSUE TITLE
[Bug] Mask threw error on promoted tweets

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3878]
### How to reproduce?

![image](https://user-images.githubusercontent.com/52657989/128451609-9c81cb8d-f676-49a8-8a4d-3d87b90aaa03.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
This warning only shows in development mode. It means Mask Network can't find out the author of the current post.

**Comment by guanbinrui** [comment]
> This warning only shows in development mode. It means Mask Network can't find out the author of the current post.

Yes, so it's not boring our users.
