### ISSUE TITLE
[Bug] Error: [ethjs-query] while formatting outputs from RPC - occasional problems

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3890]
### How to reproduce?

1. Send tx during interact with mask
2. Check the response of the tx

### What happened?

```
Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"changes":[],"path":"/content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html","location":"/content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html","parentLocation":"/content/adt7/en_US/v3","error":{"class":"javax.jcr.nodetype.ConstraintViolationException","message":"No default node type available for /content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html"},"status.code":500,"status.message":"javax.jcr.nodetype.ConstraintViolationException: No default node type available for /content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html","title":"Error while processing /content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html","referer":""}}}'
```

<img width="943" alt="截屏2021-08-06 19 41 41" src="https://user-images.githubusercontent.com/2582974/128505367-5cc4ed84-a184-45e4-8fe4-c4931ed48688.png">
<img width="939" alt="截屏2021-08-06 19 42 17" src="https://user-images.githubusercontent.com/2582974/128505440-2ff314e4-89cd-4e52-b68d-03ff75e9c880.png">

### What should happen?
Maybe it's due to the unstable RPC network, but it's better to show a user friendly error message to end user.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by septs** [comment]
```json
{
  "value": {
    "code": -32603,
    "data": {
      "changes": [],
      "path": "/content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html",
      "location": "/content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html",
      "parentLocation": "/content/adt7/en_US/v3",
      "error": {
        "class": "javax.jcr.nodetype.ConstraintViolationException",
        "message": "No default node type available for /content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html"
      },
      "status.code": 500,
      "status.message": "javax.jcr.nodetype.ConstraintViolationException: No default node type available for /content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html",
      "title": "Error while processing /content/adt7/en_US/v3/295cce92179b4be498665b1b16dfee34.html",
      "referer": ""
    }
  }
}
```

**Comment by septs** [comment]
@DimensionDev/qa we need contact the api provider fix the bug.

**Comment by AinuX** [comment]
RPC URL: https://rpc-mainnet.matic.network
Chain ID: 137

**Comment by zhouhanseng** [comment]
The error comes from user determined RPC, which is uncontrollable. The only thing we can do now is beautify the error output, hide the unnecessary error detail.
