### ISSUE TITLE
[Feature][UX] Remind user to post pub-key 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#39]
Situation:

Alice installed Maskbook and posted the pub-key;
Bob installed Maskbook and added Alice's pub-key into cached. He post a encrypted post to Alice before post his pub-key in bio/post.

Currently Alice will see error message:

```
 's public key is not xxx ... 
```

We should change error message:
- let it make more sense
- let Alice remind Bob to post his pub-key in bio/post (maybe?)

**Also we need a better entry point for 1st time user to post pub-key**

**Comment by neruthes** [comment]
Duplicate #37
