### ISSUE TITLE
[Demand]  Let the token picker loads tokens from DB

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3931]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Wallet)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

If the user have added a custom token on the dashboard side. The token picker should be able to list it.

## Notes

**Comment by AinuX** [comment]
Checked
