### ISSUE TITLE
[Locale] Farsi

### ISSUE THREAD

**Issue by mehdiag** [DimensionDev/Maskbook#3933]
# Add a locale request

1. Locale name: Fa

2. Can it be maintained for a long term? Yes

**Comment by tzhan28** [comment]
Yes, we will accept all the locale request including Farsi, French, Spanish, Italian and Russian.

**Comment by septs** [comment]
We are configuring <https://crowdin.com>, please wait a moment (ETA: may be 10 working days)

Thanks you for contribution

**Comment by septs** [comment]
closes #5004
