### ISSUE TITLE
[Bug] Unable to decrypt...

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#394]
# Bug Report

### System

- OS: macOS
- OS Version: ?

### Browser

- Browser: Chrome
- Browser Version: ?

### Maskbook

- Maskbook Version: 1.7.1
- Installation: Store
- Build Commit: ?

### System

- OS: macOS
- OS Version: ?

### Browser

- Browser: Chrome
- Browser Version: Chromium: 78.0.3904.97 (Official Build) (64-bit)

No problem found on iOS ver and Firefox ver

### Maskbook

- Maskbook Version: 1.7.1
- Installation: Store
- Build Commit: ?

### Expected Behavior

Should decrypt the content.

### Actual Behavior

![IMAGE 2019-11-13 08:57:34](https://user-images.githubusercontent.com/2139261/68748437-571e8b00-05f4-11ea-9090-42b9dc6235e6.jpg)

### How To Reproduce

Written by @guruhenry, received by @suji.yan.me.

**Comment by Tedko** [comment]
Very strange that I can decrypt this on my iOS ver Maskbook (latest internal testflight).

**Comment by SunriseFox** [comment]
Please turn on the Debug Mode on iOS (from Facebook Settings Tab -> *Maskbook Settings*, then *go to the bottom*, click *Developer Settings* and turn the first switch on), and check if the magic codes of this post are the same.

If they are not the same, it might be a fixed known issue since the previous release. If they are, it may be related to network conditions.

Or you can always download the latest dev release and load to chrome (currently tagged as 1577) from here: [https://1577-178806582-gh.circle-artifacts.com/0/Maskbook.chromium.zip](https://1577-178806582-gh.circle-artifacts.com/0/Maskbook.chromium.zip). **Removal of the stock version of this extension before loading may be required.**

**Comment by Tedko** [comment]
> Please turn on the Debug Mode on iOS (from Facebook Settings Tab -> _Maskbook Settings_, then _go to the bottom_, click _Developer Settings_ and turn the first switch on), and check if the magic codes of this post are the same.
> 
> If they are not the same, it might be a fixed known issue since the previous release. If they are, it may be related to network conditions.
> 
> Or you can always download the latest dev release and load to chrome (currently tagged as 1577) from here: https://1577-178806582-gh.circle-artifacts.com/0/Maskbook.chromium.zip. **Removal of the stock version of this extension before loading may be required.**

I can decrypt on iOS but not Chrome. -- 
>'If they are, it may be related to network conditions.'

I'm using same wifi for both iOS and PC and the PC Chrome ver cannot decrypt. The FF ver and iOS ver can decrypt

**Comment by Jack-Works** [comment]
Does it working on the master branch?

**Comment by Tedko** [comment]
> Please turn on the Debug Mode on iOS (from Facebook Settings Tab -> _Maskbook Settings_, then _go to the bottom_, click _Developer Settings_ and turn the first switch on), and check if the magic codes of this post are the same.
> 
> If they are not the same, it might be a fixed known issue since the previous release. If they are, it may be related to network conditions.
> 
> Or you can always download the latest dev release and load to chrome (currently tagged as 1577) from here: https://1577-178806582-gh.circle-artifacts.com/0/Maskbook.chromium.zip. **Removal of the stock version of this extension before loading may be required.**

@Jack-Works @SunriseFox This 1577 ver can decrypt the msg. Problem fixed.



BTW find this css error:

<img width="1409" alt="Screen Shot 2019-11-14 at 13 59 45" src="https://user-images.githubusercontent.com/6687437/68830705-57e41980-06e7-11ea-8d99-65eb10e4931f.png">

**Comment by Tedko** [comment]
@Jack-Works @SunriseFox strange behavior - when re-install the store ver of Maskbook I can decrypt the post again.
