### ISSUE TITLE
Discussion: Better posting experience for twitter 

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#396]
At this time user can posting tweets in two manner:

+ edit the tweet box in timeline for wide screen;
+ eidt the tweet box in popup for small screen;

Maskbook twitter impl always inject posting box at the init stage since the box always seen by user in timeline which looks like this:

![image](https://user-images.githubusercontent.com/52657989/68944966-315ad700-07ea-11ea-94a8-41ad2ae81c1c.png)

It's better posting experience if only inject the box when original tweet box is focused. But only few node attributes changed when tweet box focus/blur. It's easy to know when to inject the box (focus) but hard to know when to remove it in our **selector -> mutation -> inject** model.

I recommend for adding a button into the tweet box in timeline. Click it will open the popup for posting private tweets with Maskbook and the tweet box in timeline only for public ones.

**Comment by Tedko** [comment]
Vote for YES. Let's do it.

Also FYI we will have some biz coop etc in end of Nov or early Dec. So we really need to hurry up on twitter.

**Comment by neruthes** [comment]
A long-term way to improve composing experience: https://github.com/DimensionDev/Maskbook-Talks/issues/9
