### ISSUE TITLE
[Demand] Post Composition UI - Temporary Consolidation

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#397]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](https://www.figma.com/file/nDyLQp036eHgcgUXeFmNA1/Post-Composition-v1?node-id=12%3A183)
Expected UX prototype due | 2019-11-18
Actual UX prototype release | 2019-11-18
Expected engineering due | 2019-11-22

## Abstract

Before the real consolidation of post composition UI may be introduced, we need a framework to describe UI behaviors. This is especially useful since multiple-network support is coming into reality.

### Definitions of Classes

The composing state ephemerality may fall in 3 classes:

Class | Flag 1: Manual Invocation Required & Must Exit Composing State Before Doing Whatever Else | Flag 2: Automatically Exiting On Textarea Blur Event
--- | --- | ---
Static | False | N/A
Hybrid | True | False
Ephemeral | True | True

Notes:

- Pseudo-content mock boxes are considered Hybrid.
- Generally, no network should choose Ephemeral. But this case should be included in the list.

### Known Behavior

Network | Class
--- | ---
Facebook (Desktop Web) | Hybrid
Twitter (Desktop Web) | Static + Hybrid

### Behavior Consistency (Deprecated)

The invocation and the dismissal of Maskbook post composition UI should align to the behavior of the composition UI at the place where the native post composition UI is displayed.

If the native post composition UI is Hybrid, Maskbook post composition UI should be dismissed as soon as the native post composition UI is dismissed. However, if the native post composition UI is Static, Maskbook post composition UI should be manually invoked upon focusing, and there should be no way to dismiss Maskbook post composition UI there. If such persistence becomes a problem, we will provide a way to dismiss Maskbook post composition UI for Static scenarios.

### Handling Hybrid Composing Areas

The invocation of Maskbook composing modal is automatic upon the invocation event of native composing box. When exiting Maskbook composing modal, the native composing area is automatically focused, in order to prevent cyclical invocation of Maskbook composing modal.

In other words, Maskbook composing modal will be automatically invoked again only if the user exit native composing state and re-enter native composing state.

### Handling Static Composing Areas

It will be a bit tricky to deal with Static native composing areas.

When a static composing area is focused by the user, we will check its `data-maskbook-composing-box-already-invoked` attribute. If the value is `false`, Maskbook composing modal will be prompted and the attribute will be set to be `true`; else, nothing will happen. So that one Static composing area can only automatically trigger prompting Maskbook composing modal once.

### Reentry to Maskbook Composing Modal

We will add network-specific elements for the user to manually open Maskbook composing modal. This is for both cases.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/2139261/69135059-6435f100-0ab0-11ea-92e7-77c276d945da.png">

Styling should be place-specific. Network-specific styling is not enough.

## UI Elements

Now we have to display a stand-alone composing box besides the original one instead of displaying it over the original one.

### Figma Preview

<img width="734" alt="image" src="https://user-images.githubusercontent.com/2139261/69130111-dfdf7000-0aa7-11ea-846a-6131fc8da0e6.png">

### Composing Box

A generic `textarea` element.

### Recipients Selection Bar

Each network, according to its friendship model, has different default options.

These options should be displayed with [Filter Chips](https://material.io/components/chips/#filter-chips) according to Material Design specifications.

Facebook:

Place | Options
--- | ---
My News Feed | Global, All Friends
Friend Timeline | Global, All Friends, This Friend
Real Group | Global, Group Members
Brand Page Manager | Global, Followers

Twitter:

Place | Options
--- | ---
Timeline | Global, Followers, Following, Following Each Other
Reply | Global, Followers, Following, Following Each Other

When replying, OP and mentioned users are always automatically and implicitly added.

#### Notes

- Global, Group Members, and Following Each Other do not have to be implemented for now. They are only being documented for future references.

### Advanced Recipients Selection (Debug Mode Only)

<img width="686" alt="image" src="https://user-images.githubusercontent.com/2139261/69130415-64ca8980-0aa8-11ea-9c69-7ce80ed8d78b.png">

One more option in recipients options.

The text should be `Specific Friends (${specificRecipients.length} selected)`. By clicking the option, another modal, Specific Recipients Selection Modal, is displayed over the current modal.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/2139261/69130475-7f046780-0aa8-11ea-952f-b4e594c3c946.png">

In the Specific Recipients Selection Modal, the user may toggle the checkboxes besides the friends. Click "Done" button to close the modal.

(But which Material Design component should we use?)

### Finish Button

A button showing "Finish".

## Matching Network-Specific Styles (Suspended)

// This part can be delayed to a future stage

Font-family, font-size, line-height, letter-spacing, and color should match the current network. The Finish button should also look like the Post/Tweet button.

Styling parameters should be customizable with a simple CSS configuration.

## Editing

For networks which support editing existing posts, we should provide that compatibility. IV and post key should remain unchanged, as long as IV is 128-bit long and is used as an equivalent to UUIDv4 for post-identifying purposes.

**Comment by Jack-Works** [comment]
Share with friends has problem with detecting friends. Should not hide the select box so quick

**Comment by neruthes** [comment]
> Share with friends has problem with detecting friends. Should not hide the select box so quick

UserGroup membership discovery problem should be solved independently. Also, a user can always enable debug mode to access advanced recipient selection feature.

**Comment by guanbinrui** [comment]
> If such persistence becomes a problem, we will provide a way to dismiss Maskbook post composition UI for Static scenarios.

It's hard to know when we should hide the composition box in twitter timeline. I think we should add a way to close it.

**Comment by neruthes** [comment]
> > If such persistence becomes a problem, we will provide a way to dismiss Maskbook post composition UI for Static scenarios.
> 
> It's hard to know when we should hide the composition box in twitter timeline. I think we should add a way to close it.
> 
> #396

If we are going to do it now, Maskbook composing area may be closed upon `click` events which are bubbled to `<body>`. Also notice that we should add event handlers so that Maskbook composing area and Twitter composing area always prevent `click` events from bubbling.

**Comment by neruthes** [comment]
#373 will be finalized when we need payload specification here.

**Comment by neruthes** [comment]
[Idea] What if we display a whole-screen modal instead of a box next to the original box?

Benefits:

- Reduced UI trivialization
  - Greater portability of composing experience among networks
  - Unified branding visual identity
  - Less network-specific coding
  - Greater robustness when websites change their UI
  - Less confusion on which box to use
- Reduced scrolling
- Easier positioning
- Easier exiting

Drawback:

- More intra-network UI inconsistency
- More difficult to rely on native post visibility options on social networks which provide this feature

**Comment by neruthes** [comment]
Discussion summary: Good idea.

----

Content updated accordingly.

**Comment by neruthes** [comment]
Per the advice from @Jack-Works, recipients options will be moved to a separate RFC, since it should be decoupled with GUI.

**Comment by neruthes** [comment]
Note:

Already delivered for Twitter but no clue for Facebook. Expedition requested.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/2139261/72243955-17205800-35e5-11ea-851c-56f0646dba72.png">

**Comment by neruthes** [comment]
When will this be available on Facebook? cc @guanbinrui

**Comment by guanbinrui** [comment]
> When will this be available on Facebook? cc @guanbinrui

After we finished red packet.

**Comment by Jack-Works** [comment]
In what state this issue can be done?

**Comment by guanbinrui** [comment]
> In what state this issue can be treated as done?

Until we implement this in facebook?

**Comment by Tedko** [comment]
Do we have plan for this on Facebook? Within this month?
