### ISSUE TITLE
[Demand] search token input UI

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#3986]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
![image](https://user-images.githubusercontent.com/63733714/129529487-6b051712-04a3-4ed2-bd7f-c15fd8d6c8fe.png)

to

![image](https://user-images.githubusercontent.com/63733714/129529604-731d316f-4a0e-4f51-9425-0c39a0be3b92.png)

https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=4393%3A212674

**Comment by wenluomask** [comment]
Please change to "Search Token Name or Contract Address" in input box. In addition, check the token list from dashboard's add token to make sure text can be displayed fully there. 
![Screen Shot 2021-08-17 at 5 01 23 PM](https://user-images.githubusercontent.com/85149605/129698026-786e446f-923a-4624-a383-6f063f64b620.png)

**Comment by wenluomask** [comment]
Checked.
