### ISSUE TITLE
[Bug] Token will not show up if search a manually added token no matter via token name or contract

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4001]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/129659758-4666ebcd-c23b-4c8b-88f2-dfabae7feb99.mp4

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by NikoManiac** [comment]
Why should show up added token when use token list in dashboard wallet?

**Comment by AinuX** [comment]
> Why should show up added token when use token list in dashboard wallet?

Think about that, I have a long token list, and forget some token(s) have already been added, then I try to add again, but there is no reminder that the token have already existed in token list.

**Comment by NikoManiac** [comment]
The current token list is supported show trusted token in token list.
