### ISSUE TITLE
[Demand] Export wallet by JSON file

### ISSUE THREAD

**Issue by nuanyang233** [DimensionDev/Maskbook#4006]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Wallet)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

In the new wallet, we need to support the user to export that via JSON file.

**Comment by guanbinrui** [comment]
https://github.com/ethereumjs/keythereum/blob/master/index.js

**Comment by septs** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55336

**Comment by guanbinrui** [comment]
Already fixed in 2.0
