### ISSUE TITLE
[Bug] Plugin card will not be rendered in twitter reply thread 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4036]
### How to reproduce?

1. UserA post a twitter x
2. UserB reply twitter x and insert a plugin card 
3. Check the plugin card in UserB's reply thread

Original twitter x: https://twitter.com/AinuxA/status/1427198799043170306
Replied twitter thread: https://twitter.com/testondemand1/status/1428254660834455559

### What happened?
Plugin card will not be rendered in UserB's reply thread.

### What should happen?
Should be rendered.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment]
Twitter changed back the DOM, This problem no longer exists.
