### ISSUE TITLE
[Bug] NFT List is not showing in my twitter but found in wallet

### ISSUE THREAD

**Issue by leeduckgo** [DimensionDev/Maskbook#4055]
### What happened?

1.https://twitter.com/0xleeduckgo
![image](https://user-images.githubusercontent.com/12784118/130306954-786cfd48-4ec0-412b-b9d7-7f03318bf201.png)

2.Wallet: 
![image](https://user-images.githubusercontent.com/12784118/130306975-790f01ba-b84d-41ee-b209-e8248eb71f1a.png)

### What should happen?
Show in my twitter.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: 1.36.2)
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment]
@leeduckgo Thanks for reporting. `.blockchain` domain would be supported soon(maybe next release), see #3978. In addition, your domain should be `leeduckgo.blockchain`, right?

**Comment by leeduckgo** [comment]
My ens is 「 leeduckgo.eth」, but i think that the nfts showing in wallet should show in twitter too(for example: the long cat.jpg)?

**Comment by AinuX** [comment]
As seen from your screenshot, your nickname is "leeduckgo", it did not match our rule to show NFT in twitter profile.
And I notice that the nickname is changed to "leeduckgo.eth" now which is a validated ens, then the NFT show up.

<img width="944" alt="截屏2021-08-21 20 40 03" src="https://user-images.githubusercontent.com/2582974/130322104-a87d808f-101f-402a-bb32-a250efabc91a.png">

**Comment by AinuX** [comment]
Close this issue due to usage error.
If you encounter error again, please feel free to reopen, thanks!

**Comment by leeduckgo** [comment]
> Close this issue due to usage error.
> If you encounter error again, please feel free to reopen, thanks!

thxs a lot!

**Comment by leeduckgo** [comment]
Change my nickname is working, but the addr that binding with my twitter is same as the addr in wallet.
 「NFT in twitter profile depends on ens in nickname or bio and eth address in bio」.
so…… if I use another nickname(not leeduckgo.eth ), the NFTs should be show normally too?
![image](https://user-images.githubusercontent.com/12784118/130346231-defded17-9770-4ca8-aaa8-1601d63f106c.png)
![image](https://user-images.githubusercontent.com/12784118/130346287-2c203158-c587-43b7-aed6-af3160ed007a.png)

**Comment by AinuX** [comment]
> Change my nickname is working, but the addr that binding with my twitter is same as the addr in wallet.
> 「NFT in twitter profile depends on ens in nickname or bio and eth address in bio」.
> so…… if I use another nickname(not leeduckgo.eth ), the NFTs should be show normally too?
> ![image](https://user-images.githubusercontent.com/12784118/130346231-defded17-9770-4ca8-aaa8-1601d63f106c.png)
> ![image](https://user-images.githubusercontent.com/12784118/130346287-2c203158-c587-43b7-aed6-af3160ed007a.png)

Yes, it's currently as design.
