### ISSUE TITLE
[Crash] RangeError: Invalid time value

### ISSUE THREAD

**Issue by burncovenant** [DimensionDev/Maskbook#4059]
I was *doing something...*, then Mask reports an error.

> Invalid time value

Error stack:

<pre>formatDistance@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/chunk.npm.date-fns.js:5328:11
formatDistanceToNow@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/chunk.npm.date-fns.js:5529:84
OrderRow@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/chunk.5348.js:2028:163
Ch@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/npm.react-dom.js:171:137
gk@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/npm.react-dom.js:294:29
fk@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/npm.react-dom.js:282:24
ek@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/npm.react-dom.js:281:371
Vj@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/npm.react-dom.js:281:229
Pj@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/npm.react-dom.js:270:476
J@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/3764.js:19025:204
R@moz-extension://db2680ff-5718-468e-bf35-a9ea29314743/js/3764.js:19026:123
</pre>

## Build info
- Version: 1.36.1
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- firefoxVariant: fennec
- resolution: desktop
- BUILD_DATE: 1970-01-01T00:00:00.000Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A) on tag "N/A"
N/A

**Comment by guanbinrui** [comment]
It's caused by the OpenSea SDK.
