### ISSUE TITLE
[Demand] Initialization Revamp

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#407]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=134%3A2)
Expected UX prototype due | 2019-11-22
Actual UX prototype release | 2019-11-21
Expected engineering due | 2019-12-15

## Catalogue

- Dashboard Logics
- Components:
  - Dashboard Pre-Initialization State
  - Dashboard Half-Initialized State

## Dashboard Logics

Dashboard has 3 states:

State Name | Condition
--- | ---
Pre-initialization state | 0 persona in database
Half-initialized state | 1 persona and 0 profile in database
Post-initialization state | otherwise

If there is no Persona currently, Dashboard will be in pre-initialization state; otherwise, Dashboard will be in post-initialization state. This selection is made every time when Dashboard is loaded.

Post-initialization state has been implemented in #369. 

## Component: Dashboard: Pre-Initialization State

In this state, Dashboard introduces Maskbook to a new user.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/2139261/69315961-b0f40600-0c2f-11ea-9e7e-5621eecd80c6.png">

By entering `S.a.2` screen after the name of the new persona is given, now this Maskbook installation comes into half-init state.

### New User

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/2139261/69318696-a50b4280-0c35-11ea-81f3-0524ffa2c861.png">

We onboard new users like this.

When clicking in-cell "Connect facebook.com" text button, the user will be prompted a [dialogue](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=107%3A0), then the user will be directed to the profile page with a Guide Bar (#409) displayed on the top of the web page.

If we deliver this without #409, in the meantime, the [original behavior](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=107%3A36) as defined in #369 will still be in use till the delivery of #409. 

### Returning User

<img width="949" alt="image" src="https://user-images.githubusercontent.com/2139261/69532113-0bad9a80-0f6d-11ea-89f3-432858fb0a4a.png">

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/2139261/69532126-1405d580-0f6d-11ea-826f-dd6a169cd2c3.png">

If the database backup file has no persona, we will ask the user to create one after a successful restoration.

Restoration failure will result in an error alert (`{title: "Restoration Failed", body: "Not a valid backup file.", buttons: {primary: "OK"}}`) without any proceeding.

Alternatively, the user may import a persona in "Import Persona" through "Advanced..." button. When the user clicks "Import Persona" button, the user will be prompted [Import Persona dialogue](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=89%3A173).

## Component: Dashboard Half-Initialized State

Go directly into `S.a.2` screen as in initialization procedure when entering Dashboard.

## Notes

- Some designs date back to <https://github.com/DimensionDev/Maskbook/wiki/Maskbook-on-Facebook>.

**Comment by Jack-Works** [comment]
Looks good to me. Do you have interest to use steppers? https://material-ui.com/components/steppers/

**Comment by neruthes** [comment]
@Jack-Works I wish I had it in my Figma UI Kit. But still, this is not a linear progress; conditional moves are complex. Therefore I would refrain from adopting it.

**Comment by SunriseFox** [comment]
![image](https://user-images.githubusercontent.com/14029711/69509266-54685200-0f73-11ea-8851-d4b7e4a65778.png)

+ `Restore Persona` and `Restore Database` may be confusing for users
+ is `Restore from text / QR code` no longer supported?
+ should the old backup files (neither persona nor database ) be treated as persona backup or database backup?
+ what if a user chooses to restore database backup and selects a persona backup file, or chooses to restore persona backup and selects a database backup file

**Comment by neruthes** [comment]
> * `Restore Persona` and `Restore Database` may be confusing for users

Good point. I will introduce adjustments.

> * is `Restore from text / QR code` no longer supported?

Text can remain supported. But probably, we should always encourage users to save the database backup as a file, instead of a text string. This question remains open for further discussions.

QR backup is a disaster. Good time to remove it.

> * should the old backup files (neither persona nor database ) be treated as persona backup or database backup?

Database.

> * what if a user chooses to restore database backup and selects a persona backup file, or chooses to restore persona backup and selects a database backup file

Invalid files cannot be imported.

**Comment by SunriseFox** [comment]
An extra confirmation is required after `MB/Dashboard/Intro/S.b.1` and before `S.b.2.a.1`, or browser may not grant us required permissions.

**Comment by neruthes** [comment]
> An extra confirmation is required after `MB/Dashboard/Intro/S.b.1` and before `S.b.2.a.1`, or browser may not grant us required permissions.

This will be requested when the user enters post-initialization state Dashboard the first time.

**Comment by neruthes** [comment]
Update: Minor adjustment on `MB/Dashboard/Intro/S.b.1` wording.

**Comment by SunriseFox** [comment]
> Update: Minor adjustment on MB/Dashboard/Intro/S.b.1 wording.

No way to confirm the file selection or text.

**Comment by neruthes** [comment]
> > Update: Minor adjustment on MB/Dashboard/Intro/S.b.1 wording.
> 
> No way to confirm the file selection or text.

Upon successful file selection, the file shall be parsed. If it is a valid backup file, the process shall proceed to `S.b.2.a.1` or `S.b.2.b.1`; else, the user will see an error alert.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/2139261/70025315-98bba980-1594-11ea-97d3-19a3fcdc6673.png">

There is no need to add an extra explicit "Restore" button.

**Comment by neruthes** [comment]
Discussion:

It is a good idea to include optional password here? Or should we do it in another issue?

<img width="920" alt="image" src="https://user-images.githubusercontent.com/2139261/70038675-8c454a00-15b0-11ea-8521-b7e5c340a971.png">

<img width="653" alt="image" src="https://user-images.githubusercontent.com/2139261/70038751-b0a12680-15b0-11ea-9387-2c447baa1cae.png">

------

cc @SunriseFox @Jack-Works

**Comment by Jack-Works** [comment]
I think password should be enforced for new users.

**Comment by neruthes** [comment]
> I think password should be enforced for new users.

I believe that this should not be mandatory. Maskbook is not a cryptocurrency wallet and should not bow down to the cryptocurrency wallet security measures.

Probably @yisiliu may have some idea on this matter.

**Comment by neruthes** [comment]
Discussion summary:

Password is now a mandatory field.

**Comment by yisiliu** [comment]
I would prefer a mandatory password.

**Comment by Jack-Works** [comment]
and also, we should warn user when they are restoring their persona by mnemonic word, if the password is not correct, maskbook can't check that and may recover a valid key but not as same as the old one.

**Comment by Tedko** [comment]
Why ‘not as same as’?

**Comment by Jack-Works** [comment]
> Why ‘not as same as’?

key = f(mnemonic word, password)

Maskbook cannot check if the given password is the original password, and the `f` will generate the corresponding key for us.

**Comment by neruthes** [comment]
Time to reconsider the thirteenth word.

**Comment by neruthes** [comment]
Idea:

Put `SHA512('38ed2d61-f85a-4f44-a109-8768c33a9a67,' + MnemonicWords.join(',') + ',' + Password).toString('hex-uppercase').slice(4, 6)` on GUN at `SHA512('db3c04d3-1cef-4511-936e-1ba369708c3b,' + MnemonicWords.join(',')).toString('hex-uppercase')`.

The user may get an error alert if the password is wrong when importing persona. The probability of considering a wrong password as the correct password is 1/256. This will reveal some partial knowledge of the password on GUN, but 1 byte of the its hash might be acceptable. Only 1/32 entropy is lost; the password is still 248-bit strong. Even if the hash is guessed correctly, the password is still salted with the 128-bit mnemonic words (really random) and the 128-bit header UUID (making rainbow table impossible).

**Comment by Jack-Works** [comment]
> Idea:
> 
> Put `SHA512('38ed2d61-f85a-4f44-a109-8768c33a9a67,' + MnemonicWords.join(',') + ',' + Password).toString('hex-uppercase').slice(4, 6)` on GUN at `SHA512('db3c04d3-1cef-4511-936e-1ba369708c3b,' + MnemonicWords.join(',')).toString('hex-uppercase')`.
> 
> The user may get an error alert if the password is wrong when importing persona. The probability of considering a wrong password as the correct password is 1/256. This will reveal some partial knowledge of the password on GUN, but 1 byte of the its hash might be acceptable. Only 1/32 entropy is lost; the password is still 248-bit strong. Even if the hash is guessed correctly, the password is still salted with the 128-bit mnemonic words (really random) and the 128-bit header UUID (making rainbow table impossible).
> 
> If the desired node on GUN is available, the user will be able to notice a potential error.
> 
> If the desired node on GUN is unavailable, the process can continue without fake error.
> 
> On the assumption that node ID must be known to write, this node ID is random enough against targeted pollution attacks.

@yisiliu What do you think about this

**Comment by neruthes** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/2139261/70800413-1c9b4000-1da4-11ea-9c13-d17bfd476957.png">

**Comment by neruthes** [comment]
Please always close Demand issues with `Close #%s` in a pull request.

**Comment by SunriseFox** [comment]
#427
