### ISSUE TITLE
[Demand] Network-Specific Guides Revamp

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#409]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=196%3A972)
Expected UX prototype due | 2019-11-22
Actual UX prototype release | 2019-11-21
Expected engineering due | 2019-12-29

### Current Stage

- Entry
- MBGuideBar Module
- Components:
  - Guides on Facebook
  - Guides on Twitter

### Left For Future Stages

- Backup Alert

## Entry

<img width="643" alt="image" src="https://user-images.githubusercontent.com/2139261/70430003-b9db3900-1a71-11ea-9553-e0979a6c4824.png">

If the user specifies his username and clicks "Next" button, the user will be directed to a 5-step guide.

If the user clicks this "I do not know my username..." button, the user will be direct to a guide which is a little different in terms of steps.

## MBGuideBar Module

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/2139261/69314756-d59aae80-0c2c-11ea-8df4-2b69bc819be9.png">

Mainly designed for wide screens. For smaller screens, minor adjustments may be necessary.

### Structure

- Header
- Content
  - Title
  - Body (usually 2 lines)
- Buttons Area
  - Right Button (Next Step / Finish)
  - Left Button (Prev Step)
- Close Button

### Connect Profile

Title: `Current task: Connect profile @%s on facebook.com`

Step | Body Line 1 | Body Line 2 | Right Button | Left Button | Close Button
--- | --- | --- | --- | --- | ---
1 | Step 1/5: Login | Login on facebook.com as @%s | Next Step | - | End Guide
2 | Step 2/5: Navigate to your profile | Visit <a>https://www.facebook.com/%s</a>. | Next Step | Prev Step | End Guide
3 | Step 3/5: Enter bio editing mode | Click button "Edit bio". | Next Step | Prev Step | End Guide
4 | Step 4/5: Add public key to profile bio | <a>Click here</a> to copy public key. Paste it to your profile bio, and save profile. | Next Step | Prev Step | End Guide
5 | Step 5/5: Verification | Please wait as Maskbook is trying to check whether the setup is successful... | Finish (%ns) (disabled) (%n is a countdown from 8) | Prev Step | End Guide
5a | Step 5/5: Verification | You have successfully connected @%s on facebook.com to persona "%s". | Finish | - | -
5b | Step 5/5: Verification | Not successful. Please go back and try again. | Finish (disabled) | Back | End Guide

### Connect Profile

Title: `Current task: Connect profile @%s on twitter.com`

Step | Body Line 1 | Body Line 2 | Right Button | Left Button | Close Button
--- | --- | --- | --- | --- | ---
1 | Step 1/5: Login | Login on twitter.com as @%s | Next Step | - | End Guide
2 | Step 2/5: Navigate to your profile | Visit <a>https://twitter.com/%s</a>. | Next Step | Prev Step | End Guide
3 | Step 3/5: Enter profile editing mode | Click button "Edit profile". | Next Step | Prev Step | End Guide
4 | Step 4/5: Add public key to profile bio | <a>Click here</a> to copy public key. Paste it to your profile bio, and save profile. | Next Step | Prev Step | End Guide
5 | Step 5/5: Verification | Please wait as Maskbook is trying to check whether the setup is successful... | Finish (%ns) (disabled) (%n is a countdown from 8) | Prev Step | End Guide
5a | Step 5/5: Verification | You have successfully connected @%s on twitter.com to persona "%s". | Finish | - | -
5b | Step 5/5: Verification | Not successful. Please go back and try again. | Finish (disabled) | Back | End Guide

## Notes

- Decide whether to skip Step 1 according to login status.
- Decide whether to skip Step 2 according to page URL.
- During profile connecting, the Guide Bar should show only if the tab is opened by the Maskbook dialogue or the website has an active *profile connection request*.
- For profile connecting, all other navigations in the Guide Bar are manual. We do not automatically turn pages.
- When the Step 5 countdown reaches 0, jump to Step 5a or Step 5b, according to the verification result. Jump earlier if the result comes earlier; 8-second countdown is only a timeout mechanism.
- Clicking "Back" button in Step 5a or Step 5b, go back to Step 4.

**Comment by Tedko** [comment]
should we implement this in holoflows?

**Comment by neruthes** [comment]
> should we implement this in holoflows?

Off-topic

**Comment by Jack-Works** [comment]
record a intro video and play it in Picture in Picture mode will be easier

https://w3c.github.io/picture-in-picture/#dom-htmlvideoelement-requestpictureinpicture

**Comment by neruthes** [comment]
@Jack-Works Possible, but matching steps and guiding eye attention might be more challenging. Also, a text-based step-by-step guide would be more inclusive for people who face difficulties with sight fidelity.

**Comment by Tedko** [comment]
Another problem just encounter by our user, who is experienced with PGP/keybase etc:

> 我忘记了，发了proof post 只有我自己可见。

**Comment by Jack-Works** [comment]
> Another problem just encounter by our user, who is experienced with PGP/keybase etc:
> 
> > 我忘记了，发了proof post 只有我自己可见。

This is somehow expected. User can post proof post to thier friends not public

**Comment by Tedko** [comment]
“只有自己可见” not friends

**Comment by Tedko** [comment]
abandoned
