### ISSUE TITLE
[Bug] Cannot get price of ARETH and Transactions in Dashboard's wallet page for Arbitrum Network

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4092]
### How to reproduce?

1.Connect to Arbitrum Network;
2.Send a red packet;
3.Check the asset and transactions in dashboard

### What happened?
Cannot get price for ARETH and Transactions is empty.
![Screen Shot 2021-08-25 at 11 37 52 AM](https://user-images.githubusercontent.com/85149605/130724042-164163ae-af81-4583-b42a-1a814cbf5942.png)

### What should happen?
ARETH can show the price and Transactions shows the history of red packet.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: lelenei/fix-3997

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
It should wait until third-party providers supported Arbitrum Network.
