### ISSUE TITLE
[Bug] Wallet Transaction status is always loading

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#4097]
## Bug Info
On develop branch. Transactions have already completed.

<img src="https://user-images.githubusercontent.com/63733714/130741675-e6bd909e-c208-423e-b1ae-ae06ef9cece8.png" width=200 />

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Checked.
