### ISSUE TITLE
[RFC] UserGroup Definition for Twitter

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#412]
## Metadata

Field | Value
--- | ---
Manifest | [Meta/Article-3](https://github.com/DimensionDev/Meta/blob/master/articles/3--rfc-peer-review.md)
Purpose | Update UserGroup Abstraction Model
Feedback deadline | 2019-11-29 12:00:00 UTC
Explicitly designated reviewers | @Jack-Works 

## Background

- https://github.com/DimensionDev/Maskbook/wiki/UserGroup-Abstraction-Model

## Abstract

When composing tweets, the user should be able to determine whose members may decrypt the tweet, by selecting a set of UserGroups. Since we have established a convention for Facebook, the Twitter version should be similar.

## Definition

Type|Description|Data-Exchange Group ID (DEGID)|Internal Group Identifier (IGI)
---|---|---|---
Virtual Group|Everyone on `twitter.com`|`twitter.com::*`
Virtual Group|Followers of Alice|`twitter.com::{ username_alice }>>>FR`|`group:twitter.com/{ username_alice }/followers`
Virtual Group|Followed by Alice|`twitter.com::{ username_alice }>>>FG`|`group:twitter.com/{ username_alice }/followings`
Virtual Group|FR∩FG|`twitter.com::{ username_alice }>>>F0`|`group:twitter.com/{ username_alice }/friends`

## Notes

- This might affect #397.

**Comment by Jack-Works** [comment]
"Everyone on twitter.com": it cannot be determinted when composing a post.
"Followers of Alice": it's hard to detect this relationship on some network
"Followed by Alice": we're using this now.

**Comment by neruthes** [comment]
> "Everyone on twitter.com": it cannot be determinted when composing a post.

Elaboration please?

> "Followers of Alice": it's hard to detect this relationship on some network

"Some"?

> "Followed by Alice": we're using this now.

Nice.

**Comment by guanbinrui** [comment]
> Everyone on `twitter.com`

All discoveried Maskbook users?

> FR

Implemented in #414

> FG

Implemented in #414

> FR & FG

Implemented in #414 as the default friend group.

**Comment by guanbinrui** [comment]
Screenshot of User Groups implemented in #414:

![image](https://user-images.githubusercontent.com/52657989/69531012-176d8100-0fae-11ea-88d3-2436a5478f17.png)

**Comment by neruthes** [comment]
> They are list as people list but not a single group yet?

I mean literally everyone on Twitter. Everyone on Twitter should be able to decrypt. Implementation method remains open for discussions.

> Screenshot of User Groups implemented in #414 

Good. Now we only wait for new compose modal UI details. ([I:b])

**Comment by neruthes** [comment]
Forgot to mark this as Ratified.
