### ISSUE TITLE
[Bug] Optimize tooltip content of NFTs binding rule 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4137]
### How to reproduce?

![Screen Shot 2021-08-27 at 16 16 55](https://user-images.githubusercontent.com/2582974/131095933-87ae5884-9b87-4a25-9ce6-6a9ef462f261.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
[Tooltip](https://mui.com/components/tooltips/) is not working. CC @Jack-Works

**Comment by Jack-Works** [comment]
@guanbinrui You should use `ShadowRootTooltip`
