### ISSUE TITLE
Maskbook Android Unexpected quit 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#415]
# Bug Report

### System

- OS: Android
- OS Version: 9

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
 Android version: Latest Google Play version
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */ Google Play
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

Quit unexpectedly 

### How To Reproduce

/* Specify how it may be produced here. */

Use Android 9 to download and open the app.

More details:
https://github.com/DimensionDev/Maskbook-Android/issues/1

**Comment by neruthes** [comment]
Please use standard bug report template

**Comment by SunriseFox** [comment]
It relates to the native parts. There's nothing much we can do.

**Comment by Tedko** [comment]
Will assign to Tlaster

**Comment by neruthes** [comment]
https://github.com/DimensionDev/Maskbook/wiki/FAQ%3A-How-to-report-a-bug

**Comment by neruthes** [comment]
Why does GitHub consider that I unassigned @tlaster... 🤔

**Comment by Tedko** [comment]
fixed by latest Google Play ver
