### ISSUE TITLE
[Bug] Miss history in collectible plugin

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4156]
### How to reproduce?
Original opensea url: https://opensea.io/assets/0x85f740958906b317de6ed79663012859067e745b/558
Twitter url: https://twitter.com/AinuxA/status/1432581086740025345

1. Chekc the "History" tab in plugin

### What happened?
![image](https://user-images.githubusercontent.com/2582974/131464661-6317e2f2-541b-405b-996d-9c3c5b47af7e.png)
![image](https://user-images.githubusercontent.com/2582974/131464758-d10d3254-c69a-46ba-a4bb-d18405f6fe0f.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
Already fixed.

![image](https://user-images.githubusercontent.com/63733714/142963162-93bb66bf-c874-4421-805d-c41a8b090881.png)
