### ISSUE TITLE
Request a standard procedure for Mobile Maskbook release

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#416]
Including:
- Basic test procedure
- (iOS) Release internally first
- All related ppl should participate in the internal release test @neruthes

**Comment by Tedko** [comment]
This should not be a RFC since it’s not a standard. All related devs should design this procedure together .

**Comment by neruthes** [comment]
Noted.

**Comment by Jack-Works** [comment]
We do have one.

iOS release:
https://github.com/DimensionDev/Maskbook/pull/259
https://github.com/DimensionDev/Maskbook/pull/260
https://github.com/DimensionDev/Maskbook/pull/301
https://github.com/DimensionDev/Maskbook/pull/364

Android release:
https://github.com/DimensionDev/Maskbook/pull/264
https://github.com/DimensionDev/Maskbook/pull/265
https://github.com/DimensionDev/Maskbook/pull/364

**Comment by Tedko** [comment]
> We do have one.
> 
> iOS release:
> #259
> #260
> #301
> #364
> 
> Android release:
> #264
> #265
> #364

It’s more about let our Android/iOS dev design a platform specific test etc. not that related to Front end

**Comment by Tedko** [comment]
Need add QR code identity transfer test  @Jack-Works

**Comment by Jack-Works** [comment]
- Checkout to `master-ios` or `master-android`
- `git rebase [the target release branch, maybe master or released]`
- test on coresponding platform

- if there is platform fix for iOS or android, merge it into master

- if two branch are divereged, remove the master-ios or master-android branch (the platform fix has been merged into master in the last step)
- checkout new master-ios or master-android branch from the target branch

**Comment by neruthes** [comment]
I think this matter has been done already. I am closing this issue now. If there is any further update, feel free to reopen.

**Comment by Tedko** [comment]
Let’s see. Mobile and front end team is working ok this.
