### ISSUE TITLE
[Bug] Failed to claim RP with error "SafeMath: subtraction overflow"

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4168]
### How to reproduce?

URL: https://twitter.com/dego_finance/status/1432955486643445760
![Clipboard - September 1, 2021 3_24 PM](https://user-images.githubusercontent.com/2582974/131651683-303a38bf-50bf-4bc5-87cd-e57b364ae30b.JPG)
![Screen Shot 2021-09-01 at 15 25 19](https://user-images.githubusercontent.com/2582974/131651695-9c51cd0e-06bc-41aa-9410-b5f07e39daac.png)

### Mask Version:

- [X] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [X] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [X] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by andy-at-mask** [comment]
从Telegram上copy过来的：
这个问题的原因大概是这样： 由于dego token存在[燃烧和奖励机制](https://github.com/dego-labs/dego-token/blob/master/contracts/token/DegoToken.sol#L246)

燃烧奖励机制的通俗解释：用户塞dego token进入红包的时候，transfer() 1000个dego币给红包合约，这1000个币会分成如下几部分：
- 一部分燃烧掉【通缩设计，转进黑洞】
- 一部分留出来，奖励给LP的提供者
- 剩下的币转到红包合约【红包合约实际收到小于1000， 可能是900个】
- 
红包合约按1000个dego token的数量发红包，结果发到最后，红包里的token不够发了
【为了容易解释：1000/900是虚构的数目】

合约这边会看看怎么解决这个问题

**Comment by andy-at-mask** [comment]
这个已经Fix了，刚才我用dego在BSC主网测试过.
稍后会更新其他链

**Comment by AinuX** [comment]
Checked
