### ISSUE TITLE
[Bug] Repeated rendering of plugin in quote tweets

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4183]
### How to reproduce?

URL: https://twitter.com/realmaskbook/status/1432871281293086724/retweets/with_comments

https://user-images.githubusercontent.com/2582974/131777755-53084135-93f5-4186-9dcf-ec99f25cac76.mp4

### Mask Version:

- [X] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [X] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [X] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
https://twitter.com/AinuxA/status/1441006631731433480/retweets/with_comments

**Comment by UncleBill** [comment]
This issue does not seem to exist anymore。
