### ISSUE TITLE
[Crash] TypeError: exchange_tokens is undefined(ITO plugin in Firefox)

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4193]
I was checking ITO plugin card in Firefox, then Mask reports an error.

> exchange_tokens is undefined

Error stack:

<pre>ITO@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/chunk.9134.js:2202:9
Ch@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:171:137
gk@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:294:29
fk@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:282:24
ek@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:281:371
Vj@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:281:229
Pj@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:270:476
J@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/70.js:19512:204
R@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/70.js:19513:123
EventHandlerNonNull*4223@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/70.js:19513:300
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
76375@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/70.js:19530:20
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
17510@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:18:86
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
24204@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-dom.js:356:20
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
11670@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm.react-transition-group.js:24:36
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
30943@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm-ns.material-ui.core.js:9367:99
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
99242@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm-ns.material-ui.core.js:15065:31
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
95702@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/npm-ns.material-ui.core.js:13397:34
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
7082@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/6816.js:1350:94
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
3078@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:703:85
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
63371@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/6364.js:935:83
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
76898@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/2871.js:55:92
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
4336@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:10:34
__webpack_require__@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:875:42
__webpack_exports__<@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:1215:462
__webpack_require__.O@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:917:23
@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:1216:53
@moz-extension://6683047c-5549-f540-981e-f546ac785e20/js/content-script.js:1218:12
</pre>

## Build info
- Version: 1.36.4
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- firefoxVariant: fennec
- resolution: desktop
- BUILD_DATE: 1970-01-01T00:00:00.000Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A) on tag "N/A"
N/A

**Comment by Tedko** [comment]
not stale

**Comment by septs** [comment]
@DimensionDev/qa plz re-verify the bug, if exists plz contact @zhouhanseng resolve the bug, thanks
