### ISSUE TITLE
[Bug] Tradeview can not work in Firefox

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4195]
### How to reproduce?

1. Search any token, like $MASK
2. Check the tradeview in search result

### What happened?
No tradeview showup.

### Mask Version:

- [X] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [X] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [X] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment]
## It's OK here

![image](https://user-images.githubusercontent.com/1141198/132617440-032c0b6b-aecd-46cc-9e46-92852b5448cb.png)

## But not here

![image](https://user-images.githubusercontent.com/1141198/132617466-c776cdfe-fa0a-440b-a90e-168b34e5cecc.png)

**Comment by Tedko** [comment]
its working well
<img width="1295" alt="Screen Shot 2022-01-17 at 00 28 21" src="https://user-images.githubusercontent.com/6687437/149668688-be1ea27e-f647-49e0-9d31-5ea0ce92adf0.png">

<img width="1295" alt="Screen Shot 2022-01-17 at 00 28 41" src="https://user-images.githubusercontent.com/6687437/149668695-b3e2184b-8eee-420d-852f-be628ed11e5e.png">
