### ISSUE TITLE
[Bug] Confusing behavior while switching SNS accounts

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4218]
### What happened?

+ `Persona A` links with `Twitter A`. `Twitter A` is currently using by the user.
+ The user has two Twitter accounts and switches his account from `Twitter A` to `Twitter B`.
+ It is still possible to send encrypted messages with the identity of `Persona A`.

### What should happen?

+ It should prompt the user to connect to a Persona since the SNS account has been changed. (If the new Twitter account hasn't been connected to any persona before.)
+ It should switch to the connected persona automatically. (If the new Twitter account has connected to a persona.)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
For the socail network accounts which didn't connect to any persona, they are supposed to not be the mask user(showing mask icon beside name) and not able to try any mask feature.

**Comment by wenluomask** [comment]
Fixed.
