### ISSUE TITLE
[Demand] Twitter address update

### ISSUE THREAD

**Issue by Tsukimoe** [DimensionDev/Maskbook#4230]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other

File list
```
/README.md
packages/dashboard/src/components/FooterLine/About.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx
```
Change the address From
`https://twitter.com/realmaskbook`
To
`https://twitter.com/realMaskNetwork`

**Comment by guanbinrui** [comment]
Updated in #4656.
