### ISSUE TITLE
[Demand] User forum address update

### ISSUE THREAD

**Issue by Tsukimoe** [DimensionDev/Maskbook#4231]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other

Now we have a brand new forum, maybe it's better to update to this address?
File list
`https://github.com/DimensionDev/Maskbook/blob/develop/README.md`
Change the address From
`https://github.com/DimensionDev/Maskbook/discussions`
To
`https://we.mask.io/`

**Comment by guanbinrui** [comment]
Updated in #4656.
