### ISSUE TITLE
[Demand] Update app store image

### ISSUE THREAD

**Issue by Tsukimoe** [DimensionDev/Maskbook#4232]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
Now Mask’s new Twitter address is updated, but the store image uses the old address
## Part 2: Problem to Solve
Update new picture
## Part 3: Expected Behavior
-
## Notes
Waiting for further collaboration

**Comment by guanbinrui** [comment]
Updated.
