### ISSUE TITLE
Maskbook tries to fetch other's profile too many times

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#424]
Edit: the reason has been identified. And it might be the main cause of failing to decrypt others' posts on mobile.

![image](https://user-images.githubusercontent.com/14029711/69691610-8f50be00-110a-11ea-8867-d66fa9ee9866.png)

...and lead to being blocked by facebook.

Possible solutions:

+ Add public key only after view profile manually, or
+ Share - verify public keys between blockchain nodes, or
+ Block next fetch before receiving response / rate-limit / cache fetch result

**Comment by neruthes** [comment]
Need a request scheduler, seemingly. 🤔

**Comment by Jack-Works** [comment]
We do have one already. It works for automated tab task. It maybe not working for fetch method 🤔

**Comment by neruthes** [comment]
BTW, you may want to use https://gist.github.com/neruthes/dd12b4fa130c32b585fc0fbd42c696b6 to open typed issues. ([I:b])c
