### ISSUE TITLE
[Bug] vCent plugin will not be rendered if it's a replying twitter

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4249]
### How to reproduce?

vCent url: https://v.cent.co/tweet/1433235034756972544
Twitter url: https://twitter.com/VitalikButerin/status/1433235034756972544
![Screen Shot 2021-09-06 at 18 49 12](https://user-images.githubusercontent.com/2582974/132206097-cfd771be-3599-4a89-8493-d410df93d004.png)
![Screen Shot 2021-09-06 at 18 49 29](https://user-images.githubusercontent.com/2582974/132206136-a939021e-6ea2-462d-a956-5430577cff42.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
After #4421, we only allow one tweet whose ID is present in the URL.

### ID in the URL

![image](https://user-images.githubusercontent.com/52657989/134753453-7fb5dce1-e39e-4c10-8b87-651febba3f4d.png)

### ID not in the URL

![image](https://user-images.githubusercontent.com/52657989/134753465-cd2fdc48-87b3-433f-8357-ce7b9caa76ad.png)

**Comment by guanbinrui** [comment]
Fixed in ##4421.
