### ISSUE TITLE
[Bug] When user clicks "Connect Wallet", send a message to mobile instead of opening JS wallet dialog

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#4264]
### How to reproduce?

1.Open any tweet which contains any plugin that requires a wallet. (ITO, RedPacket, GitCoin, etc..)
2.Click the "Connect Wallet" button

### What happened?
JS side wallet dialog appears
![IMG_2740](https://user-images.githubusercontent.com/7972003/132436864-1246bfcb-134a-4e51-86fa-0cb3df3a5be9.PNG)

### What should happen?
JS should send the message ["misc_openCreateWalletView"](https://mask.atlassian.net/wiki/spaces/MASK/pages/230031526/Misc#2.2-misc_openCreateWalletView()) to mobile instead of open JS wallet dialog

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [x] iOS 14

**Comment by guanbinrui** [comment]
I will close it cause we have fixed it.
