### ISSUE TITLE
[Discussion] What are good ways to encrypt comments?

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#43]
- Use the same AES key for the post.
- Use the SHA512 of the whole post as the AES key.

Are there other options that we may consider?

**Comment by Jack-Works** [comment]
There is no shared aes key between receivers

**Comment by yisiliu** [comment]
The former.
We don’t consider the permission system in Wechat Moments here. Too complicated for this product now.

**Comment by neruthes** [comment]
We are near to the conclusion.

Any further idea?

**Comment by yisiliu** [comment]
considered finalized

btw "near the" not "near to the"

**Comment by neruthes** [comment]
Will create feature issue.
