### ISSUE TITLE
[Wallet] Using MetaMask as wallet, but useWallet().name is the name of Mask wallet

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#4306]
### How to reproduce?

![image](https://user-images.githubusercontent.com/1141198/132798097-6990f96c-aaac-4024-bc4d-971c4bdb283e.png)

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
This issue could cause by connecting to a wallet from MetaMask whose address is the same as the original Mask Wallet.
