### ISSUE TITLE
[RFC] Author Hinting as a Way to Fight Account Suspension Risks

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#431]
## Metadata

Field | Value
--- | ---
Manifest | [Meta/Article-3](https://github.com/DimensionDev/Meta/blob/master/articles/3--rfc-peer-review.md)
Purpose | Fix Facebook account suspension risk
Feedback deadline | 2019-12-06 12:00:00 UTC
Explicitly designated reviewers | @Jack-Works @SunriseFox @guanbinrui @yisiliu 

## Abstract

:facepalm:

![Clipboard - November 27, 2019 4-05 PM](https://user-images.githubusercontent.com/2139261/69705363-50f8d600-10ed-11ea-9f76-0a9ccf1e02d3.png)

## Background

- https://github.com/DimensionDev/Maskbook/wiki/Payload-of-posts-and-comments
- https://github.com/DimensionDev/Maskbook/issues/373

### Post

The old payload for posts starts with `Decrypt...`.

In the new payload, we will prepend such a string in front of the original payload:

```
[${date.YYYY}-${date.MM}-${date.DD} ${profile.displayName}]&nbsp;
```

### Comment

The old payload for comments starts with `%F0%9F%8E%BC`.

In the new payload, we will add such a string in front of the original payload:

```
[${date.YYYY}-${date.MM}-${date.DD} ${profile.displayName}]&nbsp;
```

### Tweet

Although there is no such report from Twitter, it is worth preparing for the same situation happening on Twitter. We will append this string after the original payload (as specified in #373):

```
&nbsp;— by @${profile.username} (${date.YYYY}-${date.MM}-${date.DD})
```

## Notes

- `&nbsp;` means a generic `Whitespace` character (`%20`) instead of a real NBSP character.
- `${varname}` means to replace this part with the variable.

**Comment by Jack-Works** [comment]
lgtm. maybe need to wait for persona (which includes custom persna nickname)

**Comment by neruthes** [comment]
> lgtm. maybe need to wait for persona (which includes custom persna nickname)

Could be better, but not necessarily.

**Comment by neruthes** [comment]
Added date (`YYYY-MM-DD`) as well, in order to distinguish comments which were published before 3 months ago.

**Comment by Tedko** [comment]
+1 for add date

**Comment by neruthes** [comment]
Motion: Ratify on today 10:00 UTC if no additional requests for modification.

**Comment by neruthes** [comment]
Ratified.
