### ISSUE TITLE
Avoid long waiting time for Pop-up after clicking the extension

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#433]
For now, user will encounter super long waiting time  for Pop-up after clicking the extension button

**Comment by neruthes** [comment]
+1; I also wonder why it is so slow

**Comment by SunriseFox** [comment]
How long?... Does it happen only when the first time extension loads or on specific conditions?... Is it mitigated if click it again and again?...

**Comment by Tedko** [comment]
> How long?... Does it happen only when the first time extension loads or on specific conditions?... Is it mitigated if click it again and again?...

usually >5s on my laptop
Once I have not click the pop-up for a while (eg hald hour) and then click it it will be super slow

**Comment by SunriseFox** [comment]
Possible solutions:

1. remove all style tag rendered by SSR
2. replace network image by data-uri
3. make script tag async

@Jack-Works

**Comment by neruthes** [comment]
2-2.5 s on my machine.

**Comment by Tedko** [comment]
> Possible solutions:
> 
> 1. remove all style tag rendered by SSR
> 2. replace network image by data-uri
> 3. make script tag async
> 
> @Jack-Works

2 will add 300-400ms on my laptop in avg.

**Comment by Jack-Works** [comment]
> Possible solutions:
> 
> 1. remove all style tag rendered by SSR
> 2. replace network image by data-uri
> 3. make script tag async
> 
> @Jack-Works

I thought SSR is used to speed up the popup render

**Comment by SunriseFox** [comment]
In fact it doesn't...

**Comment by Tedko** [comment]
Is this fixed by some PR? @SunriseFox @Jack-Works

**Comment by Jack-Works** [comment]
I can't reproduce this problem

**Comment by Tedko** [comment]
> I can't reproduce this problem

@Jack-Works   very easy to reproduce on my side. 

Fix these 2 first?

>replace network image by data-uri
>make script tag async

**Comment by neruthes** [comment]
Happened again on a `dashboard-st2` build.

**Comment by Jack-Works** [comment]
@SunriseFox maybe we should use `defer` instead of `async`?

**Comment by SunriseFox** [comment]
seems the same for this condition (if `script` tag is at the end of `body`)

**Comment by Jack-Works** [comment]
> > I can't reproduce this problem
> 
> @Jack-Works very easy to reproduce on my side.
> 
> Fix these 2 first?
> 
> > replace network image by data-uri
> > make script tag async

I'll include these two fixes in the this patch (1.8.5)

**Comment by Tedko** [comment]
I still have this problem with 1.8.7 @neruthes do you?
