### ISSUE TITLE
[Bug] Encrypted image will not paste automatically 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4333]
### How to reproduce?

1. Send a post with  image payload 

### What happened?
Encrypted image will not paste automatically 

### Mask Version:

- [X] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [X] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [X] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
After fresh installation, send the first post with auto paste enabled, the image will be pasted automatically, but it will not be auto pasted when you try the second time.

**Comment by Jack-Works** [comment]
Yes. I can reproduce this. Working on this/
