### ISSUE TITLE
Twitter Direct Message UX bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#434]
![Screen Shot 2019-11-28 at 10 06 59](https://user-images.githubusercontent.com/6687437/69771406-a30e2a00-11c7-11ea-899b-6d8601183176.png)

In the current version of maskbook we should not touch DM.

**Comment by Jack-Works** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/411/commits/73655c6543476d8ef28b051f7c6d0dbe2bc5dfba
