### ISSUE TITLE
[Bug] Error handling when being unable to get Twitter username

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#437]
# Bug Report

### Browser

- Browser: Chrome
- Browser Version: *

### Maskbook

- Maskbook Version: @Jack-Works 
- Installation: @Jack-Works 
- Build Commit: *

### Expected Behavior

/* Open for discussion */

#### Proposal 1

Show an input and a button to manually set the username after a 5-second timeout.

#### Proposal 2

Ask the user to navigate to his own profile page.

### Actual Behavior

Waiting forever when detecting username.

### How To Reproduce

*

**Comment by Jack-Works** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/411/commits/815931c797a99dbbda68df00fd983ffb14698a96

**Comment by guanbinrui** [comment]
Twitter changed its `STATE_DATA` failed the regexp which unable to get the correct user name. This issue can be closed after renew the regexp.
