### ISSUE TITLE
[feature request] Twitter's translation function can not work together with Mask plugin 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4379]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/133759328-27d39250-e5ff-460c-805f-fd1c4ca23f51.mp4

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
Cannot reproduce

**Comment by AinuX** [comment]
> Cannot reproduce

1. Change Twitter language setting to Chinese
2. Post a twitter via mask compose in English 
3. Use Twitter's translation function 

![image](https://user-images.githubusercontent.com/2582974/134309773-bb0987dc-890d-4111-bcd2-f451a5b1a4ac.png)

![image](https://user-images.githubusercontent.com/2582974/134309847-1d468f43-d366-43ca-b12c-c7eb84a82a4f.png)
