### ISSUE TITLE
[Bug] Image payload can't be decrypted on Facebook

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4388]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/133878025-15e3d80e-280a-43bd-a8e1-c694866b13b6.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
We should use a gray image to improve compression resistence.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/134890596-652852e7-d394-47c2-8fb1-1a6744fc9d13.png)

Unusual. It should not be possible to create a colorful image payload since it's configured to `LUMINANCE` on Facebook

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/135013428-9c0c87aa-da19-40ff-9799-896234ccc57b.png)

Cannot reproduce. I have confirmed we're using Luminance grayscale.

**Comment by AinuX** [comment]
Image payload still not work

https://user-images.githubusercontent.com/2582974/136517948-f3e77bff-b187-41c3-a9ef-776d9099f5b4.mp4

**Comment by zhouhanseng** [comment]
@Jack-Works @AinuX Image payload does not work on latest develop branch

**Comment by AinuX** [comment]
Fixed with PR: #4932
