### ISSUE TITLE
[Bug] No original post content in shared post on Facebook 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4398]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/133880615-4f60b543-ccec-44b7-90fb-6de503ace4e0.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
There‘s no post ID expose on Facebook page DOM tree.

**Comment by AinuX** [comment]
Cloese due to the limitation.
