### ISSUE TITLE
[Bug] 'Add Decrypter' Button display bug  

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#44]
<img width="598" alt="Screen Shot 2019-05-29 at 00 10 01" src="https://user-images.githubusercontent.com/6687437/58493761-39747b00-81a6-11e9-8598-dd9e93438c21.png">

Not reproduced by my side yet. Maybe caused by racing

**Comment by Jack-Works** [comment]
下一個版本就不會出現了，因爲下一版設計上無法得知誰已經被分享，所以被分享者的數據是存在本地數據庫内的

**Comment by yisiliu** [comment]
FYI: please use the term "recipient" instead of "decrypter".
