### ISSUE TITLE
[Bug] Crashed when send poll - OOM

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4400]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/133881360-3e3824ac-9c00-4880-aeb0-8c05ad9193e5.mp4

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
is `poll` still well mantained? if not pls hide it
