### ISSUE TITLE
[Bug] Unencrypted post will not trigger plugin to render

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4404]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/133884565-b0ea544a-5503-4e83-a7b7-14b11ae7d66a.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
what do you mean?
