### ISSUE TITLE
[Bug] Input box style issue in ITO dialog 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4405]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/133886279-63d3cb42-1c9d-4630-b9e4-dff337696594.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Checked.
