### ISSUE TITLE
[Bug] facebook getProfile may fail if user's profile is empty

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#442]

**Comment by neruthes** [comment]
[This link](https://maskbook.com/links/?report-bug) is your friend ([I:b])

**Comment by Tedko** [comment]
Need prioritize this one

**Comment by Tedko** [comment]
@SunriseFox @guanbinrui is this fixed?

**Comment by SunriseFox** [comment]
Can't confirm. But It seems not affecting any users.

**Comment by Tedko** [comment]
I will close this issue @SunriseFox @Jack-Works  reopen it if this affect any users
