### ISSUE TITLE
[Bug] Press enter key in token list search input box will refresh the whole web page.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4442]
### How to reproduce?

1. Open token list from swap or others;
2.Type something in search input box;
3.Press enter key to check what will happen.

### What happened?
It will refresh the whole web page.

### What should happen?
Should show the search result related to what you typed.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
@Jack-Works Can we stop the propagation of all events in the shadow root?

**Comment by Jack-Works** [comment]
Confirmed. I'm working on this.
