### ISSUE TITLE
[Crash] RangeError: Invalid time value

### ISSUE THREAD

**Issue by ab-obo** [DimensionDev/Maskbook#4445]
I switched to listing section in collectibles twitter plugin here: https://twitter.com/rariboycom/status/1352715120456167424 , then Mask reports an error.

> Invalid time value

Error stack:

<pre>formatDistance@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/chunk.npm.date-fns.js:5328:11
formatDistanceToNow@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/chunk.npm.date-fns.js:5529:84
OrderRow@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/chunk.6942.js:2007:163
Ch@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/npm.react-dom.js:171:137
gk@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/npm.react-dom.js:294:29
fk@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/npm.react-dom.js:282:24
ek@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/npm.react-dom.js:281:371
Vj@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/npm.react-dom.js:281:229
Pj@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/npm.react-dom.js:270:476
J@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/70.js:19512:204
R@moz-extension://f1a622ca-88b5-41f8-a84a-9e763c2411cd/js/70.js:19513:123
</pre>

## Build info
- Version: 1.36.5
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- firefoxVariant: fennec
- resolution: desktop
- BUILD_DATE: 1970-01-01T00:00:00.000Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A) on tag "N/A"
N/A

**Comment by AinuX** [comment]
please update mask to latest version, it should be ok, thanks!

**Comment by ab-obo** [comment]
my firefox says "no updates found". 
![image](https://user-images.githubusercontent.com/9332836/134702051-2b58416e-225c-426a-8bf6-40ed65bd0a69.png)
should i do something manually?

**Comment by guanbinrui** [comment]
> my firefox says "no updates found".
> ![image](https://user-images.githubusercontent.com/9332836/134702051-2b58416e-225c-426a-8bf6-40ed65bd0a69.png)
> should i do something manually?

The new version is still pending review by the Firefox store. :(
