### ISSUE TITLE
[Bug] Firefox addon breaks view of <nav> on twitter if width is 1280 px or 1281 px

### ISSUE THREAD

**Issue by ab-obo** [DimensionDev/Maskbook#4446]
## Bug Info
Firefox addon breaks view of '<nav>' on twitter if width is 1280 px or 1281 px

### How to reproduce?

1. Open twitter.com on latest stable Firefox with Mask addon
2. Open developer tools (f12), switch to responsive design mode
3. Set page's width to 1280 or 1281

### What happened?
![image](https://user-images.githubusercontent.com/9332836/134699924-c836c969-eccc-47a4-ba63-8aabf2af2c70.png)

### What should happen?
![image](https://user-images.githubusercontent.com/9332836/134700046-3d5cd58b-859b-47e6-a406-5f5d96997050.png)

### Mask Version:

- (Browser) Installed from the extension store (version: 1.36.5 )

### System

- Windows 7 (6.1.7601.24524)

### Platform/Browser

- Latest Firefox (stable channel)

**Comment by Jack-Works** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/5390719/134867882-1b02ed85-e0fb-4eab-b490-133ce2c1ed08.png)
