### ISSUE TITLE
[Bug] Known bugs or features to do in version 2.1

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4474]
## Bug Info

Common Issues:

- [x] If user speed up the contract, it will show the transaction is still loading; @guanbinrui (solution: #4486, workaround: #4491)

Dashboard-Personas:

- [x] Click manage button from plugins(ITO, red packet or Poll) post will jump to Twitter, but compose may cover the plugins’ dialogs. @NikoManiac  @Jack-Works 
- [ ] For the twitter accounts didn’t connect to any persona, it also record the mask post to current persona; @nuanyang233 
- [x] Avatars for contacts will be missing after recovery; @nuanyang233

Dashboard-Wallets:

- [ ] Add “hide” and “View in explorer” features for tokens in Asset page; @NikoManiac 
- [x] Add a prompt message after token sent on the transfer page; @NikoManiac 
- [x] Failed to refresh Collectible list in Asset page if change wallet’s network; @NikoManiac 
- [x] Avoid showing scam tokens in Asset page; @NikoManiac 
- [x] Can not connect mask wallet directly as soon as wallet created or imported; @nuanyang233 
- [ ] Edit Gas limit on Transfer page will mix up the minimum gas limit for next time entering; @UncleBill 
- [x] If Gas fee is edited, re-enter gas fee setting page should always show the latest gas fee we chose; @nuanyang233 @UncleBill 

Popup:

- [ ] Failed to fetch avatar from Twitter in Personas; @nuanyang233 
- [x] Add “Cancel” and “Speed Up” feature to contract activity; @guanbinrui @nuanyang233 
- [ ] Close signature page will show failed message; @guanbinrui 
- [x] Swap page from popup cannot change trading source correctly; @UncleBill 
- [x] #4611
- [x] Can not delete any derived wallet; @guanbinrui 

Minds:
- [x] Cannot fetch Contacts data from connected Minds or Facebook; @zhouhanseng 
- [x] Exists some UI issues bugs for Minds in Dark mode; @zhouhanseng
- [x] Didn't open MASK compose by clicking MASK icon; @zhouhanseng 
- [x] Minds' translation feature didn't work for decrypted text; @zhouhanseng  
- [x] Encrypted comment input box is too long and the encrypted comment sent won't be decrypted automatically; @zhouhanseng 
- [x] Appearance setting doesn't work; @zhouhanseng 

## Environment

develop-2.0

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: Develop-2.0

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
> Cannot receive verification code for Chinese cell phone number

Isn't it a feature?

**Comment by Jackydai-bc** [comment]
get it

**Comment by wenluomask** [comment]
Can find issues left in Jira.
