### ISSUE TITLE
[Bug] Minds.io: The sidebar cannot be fully displayed when the screen is too small

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#4494]
![image](https://user-images.githubusercontent.com/5390719/134889863-b97e34d9-0921-4345-b24c-053a79c9abaf.png)

The sidebar cannot be fully displayed when the screen is too small.

**Comment by zhouhanseng** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/63733714/137674327-12151ed2-0f46-49e8-968f-75373ce7e569.png)
