### ISSUE TITLE
 Problem with add Decrypter - unintended Decrypter in the List 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#45]
<img width="612" alt="Screen Shot 2019-05-29 at 00 09 57" src="https://user-images.githubusercontent.com/6687437/58493976-ae47b500-81a6-11e9-839d-88b8fb405307.png">
Not yet reproduced by my side.

**Comment by Jack-Works** [comment]
I didn't catch the meaning

**Comment by Tedko** [comment]
似乎是用戶覺得很奇怪，他只是A好友，不是B好友，為何B的tag可以加入在解密人里、

**Comment by Jack-Works** [comment]
瞭解了，現在的邏輯是這樣的，只要數據庫裏有這個人的公鑰，就會顯示出來。

**Comment by Tedko** [comment]
現在邏輯沒問題（考慮到share的可能性） 只是可能以後用戶ux方面需要多引導

**Comment by neruthes** [comment]
Will become irrelevant as soon as autogrant is implemented.
