### ISSUE TITLE
[Bug] Incorrect inject position

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4505]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/135035567-6d165cb0-612a-4bd3-9ec4-344a7e2289a6.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
How to open that page?

**Comment by AinuX** [comment]
> How to open that page?

Edit an image.
