### ISSUE TITLE
[Bug] Token list will not changed accordingly after switching network

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4510]
### How to reproduce?

1. Connect Metamask wallt
2. Open ITO or RedPacket dialog 
3. Notice the token list 
4. Change network in Metamask 
5. Notice the token list 

### What happened?
The token list will not refresh after switching

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [x] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Didn't track chain id in the token list component? @NikoManiac

**Comment by NikoManiac** [comment]
The root cause of this problem is change network not work in Firefox. Not only the token list has problems.

**Comment by wenluomask** [comment]
Fixed.
