### ISSUE TITLE
[Bug] UI adjustment for PoolTogether plugin

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4538]
### How to reproduce?

1. Check PoolTogether in this tweet: https://twitter.com/WenLuo04001516/status/1423313736094216195;
2. View it in Eth or Matic network;

### What happened?
The token icon is PoolTogether's icon and the size is too big.
<img width="508" alt="Screen Shot 2021-10-02 at 2 55 53 PM" src="https://user-images.githubusercontent.com/85149605/135706917-83b72f32-e923-4fe6-9348-b076d84a8a1e.png">

### What should happen?
Maybe make the icon smaller or delete it. (Please ask MingMing for suggestions.)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Any updates? @yanzhihong23
