### ISSUE TITLE
[Demand] An united NFT service

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4557]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Wallet)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

### Multi-Providers

+ [ ] OpenSea
+ [ ] NFT Scan
+ [ ] NFT Bank AI
+ [ ] Any third-party provider to integrate in the future.

### Multi-Chains

+ [x] Mainnet
+ [ ] Binance
+ [ ] Polygon

### APIs

+ [ ] Get contract information by the given contract address.

```typescript
getContract(
      contractAddress: string,
      chainId = currentChainIdSettings.value
): ERC721ContractDetailed
```

+ [ ] Get token by the given contract address and token id.

```typescript
getAsset(
    contractAddress: string,
    tokenId: string,
    chainId = currentChainIdSettings.value
): ERC721TokenDetailed
```
+ [ ] Get tokens owned by the given address.

```typescript
getAssets(
    from: string,
    chainId = currentChainIdSettings.value
): ERC721TokenDetailed[]
```
+ [ ]  The same with the above one but in the paged way.

```typescript
getAssetsPaged(
    from: string,
    chainId = currentChainIdSettings.value,
    page?: number?,
    size: string
): ERC721TokenDetailed[]
```

### Related APIs

+ `packages/web3-shared/src/types/index.ts`
+ `packages/maskbook/src/plugins/Wallet/services/assets.ts`
+ `packages/web3-shared/src/hooks/useERC721ContractDetailed.ts`
+ `packages/web3-shared/src/hooks/useERC721ContractBalance.ts`
+ `packages/web3-shared/src/hooks/useERC721TokenDetailed.ts`
+ `packages/web3-shared/src/hooks/useERC721TokenDetailedOwnerList.ts`
+ `packages/web3-shared/src/hooks/useERC721TokenDetailedOwnerAllList.ts`
+ `packages/maskbook/src/plugins/Wallet/apis/opensea.ts`
+ `packages/maskbook/src/plugins/Collectible/apis/opensea.ts`

**Comment by zhouhanseng** [comment]
@yanzhihong23 Most of OpenSea services has been done, but intersperse among several ERC721 related hooks.  E.g. `getERC721TokenDetailedFromOpensea()` locates at `packages/web3-shared/src/hooks/useERC721TokenDetailed.ts`, just migrate it to the new `getAsset.ts`

**Comment by septs** [comment]
@guanbinrui reopen?
