### ISSUE TITLE
[Task] Find all components which are not network-specific but should be network-specific

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#457]
## Metadata

Field | Value
--- | ---
Parent Task/Demand | N/A
Expected Delivery Date | 2019-12-13

## Content

Just figured out that #456 is not as easy as I imagined. And the reason is that the post text template is not network-specific.

By next Friday, we will need to find all these components and plan a roadmap to refactor them.

**Comment by Jack-Works** [comment]
- i18n strings
- gun db hosts
- core encrypt-decrypt logic

**Comment by neruthes** [comment]
Looks like we can mark this as done.
