### ISSUE TITLE
[Bug] Change Dark mode's text colour of pending wallet in Twitter's left menu bar

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4570]
### How to reproduce?

1.Change Twitter to Dark mode;
2. Send a red packet or other operation;
3.When the transaction is pending, check the wallet in Twitter's left menu bar;

### What happened?
The text colour of pending is black in Dark mode.
![Screen Shot 2021-10-09 at 5 23 29 PM](https://user-images.githubusercontent.com/85149605/136652715-0f5a893a-f8a4-4880-817a-c0a67f9eca4e.png)

### What should happen?
The text colour of pending should be white in Dark mode.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
This issue begins from #4532.

**Comment by wenluomask** [comment]
Checked.
