### ISSUE TITLE
[Bug]  Unexpexted Scrollbar

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4606]
### How to reproduce?

![image](https://user-images.githubusercontent.com/52657989/137604774-da8f2d39-f139-427c-805f-ce8d68f5163e.jpeg)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [x] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Can not reproduce.
