### ISSUE TITLE
[Task] Add Japanese localization

### ISSUE THREAD

**Issue by blank71** [DimensionDev/Maskbook#4608]
## Add Japanese localization

I used to work for Mask Japanese localization. Do you need Japanese localization for the major release of Mask 2.0?

https://github.com/DimensionDev/Maskbook/blob/develop/packages/maskbook/src/locales/ja-JP.json
https://github.com/DimensionDev/Maskbook/blob/develop/packages/dashboard/src/locales/ja-JP.json

Are these files what I need to work on?

### Mask 2.0 Beta Bounty

By the way, I'm Mask 2.0 Beta Bounty participant. How can I get the bounty if I finished this issue. Do I need to apply for some form?

### Mask News

I made Japanese article of https://news.mask.io/2021/09/27/we-want-you-join-mask-2.0-beta-test-win-bug-bounties .
Please marge it if it's okay.

https://github.com/DimensionDev/Maskbook-News/pull/23

Do you use another platform for updating Mask-news? Where should I make PR or something for adding Japanese article?

**Comment by Tedko** [comment]
And - yes
We need Japanese for 2.0 release as well:):)):

**Comment by yisiliu** [comment]
yes please do so @blank71
