### ISSUE TITLE
[Demand] Refactor plugins as many single packages

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4609]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

| Plugin         | Assignee      | PR          |
| -------------- | ------------- | ----------- |
| Airdrop        |               | NOT_CREATED |
| Avatar         | @lelenei      | NOT_CREATED |
| Collectible    | @NikoManiac   | NOT_CREATED |
| External       | @Jack-Works   | NOT_CREATED |
| FileService    | @Jack-Works | #5273 |
| Furucombo      | @lelenei      | NOT_CREATED |
| Gitcoin        | @BillySh1     | NOT_CREATED |
| GoodGhosting   | @yanzhihong23 | NOT_CREATED |
| ITO            | @zhouhanseng  | NOT_CREATED |
| MaskBox        | @UncleBill    | NOT_CREATED |
| NFT            |               | NOT_CREATED |
| Polls          | @lelenei      | NOT_CREATED |
| PoolTogether   | @lelenei      | NOT_CREATED |
| RedPacket      | @zhouhanseng  | NOT_CREATED |
| Snapshot       | @zhouhanseng  | NOT_CREATED |
| Trader         | @nuanyang233    | NOT_CREATED |
| Transak        | @BillySh1     | NOT_CREATED |
| UnlockProtocol | @NikoManiac   | NOT_CREATED |
| VCent          | @yanzhihong23 | NOT_CREATED |
| Wallet         | @guanbinrui   | NOT_CREATED |
| Profile        | @lelenei      | NOT_CREATED |
| dHEDGE         | @yanzhihong23 | NOT_CREATED |

### Steps

+ `cp -rf packages/plugins/example packages/plugins/[PLUGIN_FOLDER_NAME]`
+ Edit `.i18n-codegen.json` and run `npx gulp sync-languages`
+ Setup alias `packages/mask/.webpack/config.ts`
+ Register plugin `packages/mask/src/plugin-infra/register.ts`

**Comment by lelenei** [comment]
> Edit pnpm-workspace.yaml

**Comment by septs** [comment]
@Jack-Works

**Comment by Jack-Works** [comment]
> @Jack-Works

We're gradually on the way. no need to keep this issue open
