### ISSUE TITLE
[UX Improvement] Better placeholder text on Facebook comment box

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#462]
## Metadata

Field | Value
--- | ---
Expected UX prototype due | 2019-12-13
Corresponding Pull Request | -
Completion Version | -

## Content

<img width="538" alt="image" src="https://user-images.githubusercontent.com/2139261/70121204-097ec680-1666-11ea-9064-6443fe1593d3.png">

Change the placeholder text to:

```
enUS: Write an encrypted comment...
zhHant: 添加一條加密評論…
```

And make sure that font-family, font-weight, and font-size are the same to the native placeholder of Facebook.

## Notes

None.

**Comment by neruthes** [comment]
Update:

Added i18n.

**Comment by Jack-Works** [comment]
fixed by #464

**Comment by Tedko** [comment]
@Jack-Works is this included in the latest ver? If not, publish a new ver with this fix on Wednesday.
