### ISSUE TITLE
[Bug] Unable to locate profile node when header photo is absent

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#465]
# Bug Report

### System

- OS: macos mojave 
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.8.5
- Installation: Self-Complied
- Build Commit: 979b201bf34e9437b89706347834361f93f52ada

## Reproduce

+ Remove your header photo in twitter profile page
+ BUG! Your profile can not be discovered by Maskbook

**Comment by Tedko** [comment]
is this problem fixed in `v1.8.7`? I still cannot derive pub key from accounts like https://twitter.com/infxyz (without header photo and avatar phx)
