### ISSUE TITLE
[Demand] Add URLs for mobile beta on Dashboard

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#468]
As the title.
For getting more test users.

**Comment by neruthes** [comment]
Nice idea. Will consider.

**Comment by Jack-Works** [comment]
"back URLs"? what's that?

**Comment by Tedko** [comment]
“Add” URLs

**Comment by Tedko** [comment]
Need to be added in the next release.

**Comment by neruthes** [comment]
- Location: Dashboard footer
- Position: After the first item
- Text: Join Tests for Mobile
- Href: https://maskbook.com/download-links/#mobile

Note: The footer element as appeared in #407 should also be added in post-initialization state (#369).
