### ISSUE TITLE
[Bug] Furucombo not work on minds/fb

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4685]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/138862920-11dc14f3-7e0c-4ec9-9b70-559bec2756f6.png)
![image](https://user-images.githubusercontent.com/2582974/138862978-7d750939-eff6-486f-808f-ee29726dca68.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
Furucombo server problem

**Comment by lelenei** [comment]
![image](https://user-images.githubusercontent.com/72531217/144814563-d73f9b83-1c90-4480-b5b4-183a6a18d73d.png)

**Comment by lelenei** [comment]
![image](https://user-images.githubusercontent.com/72531217/144814678-722b2ec0-0fe4-49d9-ad1b-2cd94e33a3db.png)

**Comment by Tedko** [comment]
we just disable furucombo on Fb/minds
