### ISSUE TITLE
[Demand] Add 'Seen by Maskbook' to Twitter

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#469]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Content

Add `seen by maskbook` to twitter.

**Comment by neruthes** [comment]
Yes could be added.

**Comment by Tedko** [comment]
Will prioritize this issue.

**Comment by Tedko** [comment]
@guanbinrui can u deliver this by tmr?

**Comment by Tedko** [comment]
@Jack-Works publish a new ver with this fix and the comment box fix. (If no other )

**Comment by guanbinrui** [comment]
@Tedko 👌

**Comment by Jack-Works** [comment]
closed by #503
