### ISSUE TITLE
[Bug] Style issue in PoolTogether 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4690]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/139013117-4ebb4e31-53bc-4307-be88-013b0c8efe55.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
Seems that the issue still exist.

**Comment by guanbinrui** [comment]
Hi, @lelenei Could you please give a preview image?

**Comment by wenluomask** [comment]
Cehecked.
