### ISSUE TITLE
[Discussion] Is it possible that maskbook do not open a lot of tabs?

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#47]
Users still will figure this easily and this is will definitely make user uncomfortable.

<img width="473" alt="Screen Shot 2019-05-29 at 01 05 48" src="https://user-images.githubusercontent.com/6687437/58497195-06ce8080-81ae-11e9-8d23-1d928915612e.png">

Wondering is there anyway that we achieve this wo opening new tabs? 
Oh do you have to build our own browser sometime?

**Comment by Jack-Works** [comment]
Technically we can do this. But we need permission to modify the network connections and more work to do. If we choose to modify the network connection, users may feel more uncomfortable with their privacy security.

**Comment by Tedko** [comment]
What if we got some support from browser so we got some private API? random thoughs

**Comment by yisiliu** [comment]
We have talked about this multiple times for the past few weeks. The answer is no for now.
We won't re-open this issue until someone proposes a better solution to this problem.

**Comment by Tedko** [comment]
I think we should write this in the FAQ for users until we figure how to fix it.

**Comment by yisiliu** [comment]
I will update the FAQ and the document today.
