### ISSUE TITLE
Use better Regex for detecting pub key on facebook etc

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#470]
> # Emoji Flexibility
>The detection of payload should no longer rely on .split('🔒') or certainty of string payload length, but should prefer .match(/(\d+):([\dA-Za-z\/\+]+=*)/g).

Like #191 

User might post pub keys like this:

![Screen Shot 2019-12-05 at 18 07 42](https://user-images.githubusercontent.com/6687437/70225592-46dc7480-178a-11ea-8f61-96978ef2a77a.png)

**Comment by neruthes** [comment]
Duplicate #191

**Comment by neruthes** [comment]
If you meant that handling this bio was not successful, please report bug instead.
