### ISSUE TITLE
[Bug] Incorrect injection place 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4716]
### How to reproduce?

<img width="839" alt="截屏2021-10-30 02 13 40" src="https://user-images.githubusercontent.com/2582974/139482835-65ce47c7-b195-4c2d-a1f0-3b4f524b8f9b.png">

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Can we not inject this component?

**Comment by wenluomask** [comment]
Checked.
