### ISSUE TITLE
[Bug] Incomplete translation 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4719]
### How to reproduce?

1. Change language setting in dashboard

### What happened?
1. Change to Traditional Chinese or Japanese, some of items are always show English.
2. Change to any language, the front page is always show English.

<img width="846" alt="截屏2021-10-30 03 21 51" src="https://user-images.githubusercontent.com/2582974/139490694-42832f7e-eb98-4031-924d-a8f3e7064e50.png">

### Mask Version:

- [X] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [X] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [X] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Have we left fields in the `message.json`? @yanzhihong23
