### ISSUE TITLE
[Demand] Add UUID to payload at facebook

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#472]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Content

Add a random generated UUID string to the end of payload in order to slient **duplicated post warning** from facebook.

![Clipboard - December 5, 2019 10_27 AM](https://user-images.githubusercontent.com/52657989/70290987-b8f99b80-1814-11ea-8cf9-a301e21dd994.png)

![Clipboard - December 5, 2019 10_28 AM](https://user-images.githubusercontent.com/52657989/70290927-89e32a00-1814-11ea-934d-7648b62e7d71.png)

**Comment by Jack-Works** [comment]
I think use random words from famous public domain text is better than UUID.

**Comment by Tedko** [comment]
> I think use random words from famous public domain text is better than UUID.

+1

**Comment by neruthes** [comment]
> I think use random words from famous public domain text is better than UUID.

Maybe next version.

**Comment by Tedko** [comment]
Maybe use emoji - not uuid

**Comment by yisiliu** [comment]
uuid is more pervasive than emojis as a communication medium

**Comment by Jack-Works** [comment]
> uuid is more pervasive than emojis as a communication medium

But we're not using the uuid to store any information or as an identifier

**Comment by neruthes** [comment]
Use whatever you like

**Comment by yisiliu** [comment]
> > uuid is more pervasive than emojis as a communication medium
> 
> But we're not using the uuid to store any information or as an identifier

but what're the famous quotes carrying?

**Comment by guanbinrui** [comment]
What about a timestamp?

**Comment by Tedko** [comment]
> What about a timestamp?

Can be a quick fix for now. Let's fix it

**Comment by guanbinrui** [comment]
> > What about a timestamp?
> 
> Can be a quick fix for now. Let's fix it

OK!
