### ISSUE TITLE
[Bug] Need to rename RedPacket in picture

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4720]
### How to reproduce?

<img width="185" alt="截屏2021-10-30 03 24 04" src="https://user-images.githubusercontent.com/2582974/139490961-3086936e-ad70-45d6-8675-7e7b0803f7e2.png">

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Fixed.
