### ISSUE TITLE
[Bug] Unable to resend NFT Lucky Drop 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4721]
### How to reproduce?

1. Send a NFT Lucky Drop
2. Then, try to resend it in past 

### What happened?
Unable to resend.

<img width="412" alt="截屏2021-10-30 03 28 12" src="https://user-images.githubusercontent.com/2582974/139491722-7cf1ae7d-e7b7-42f6-b7ab-deff0ec069d1.png">

Note: Token Lucky Drop worked well to resend.
### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Need some investigation from @zhouhanseng.

**Comment by guanbinrui** [comment]
Closed by #4953.
