### ISSUE TITLE
[Bug] Use payment password to encrypt keystore file

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4732]
### How to reproduce?

1.Go to Back up the wallet pages in popup;
2. Enter payment password and export file;
3. Use this file to import wallet;

### What happened?
We can import this wallet by uploading file without any password;

### What should happen?
We need payment password to import this wallet.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by nuanyang233** [comment]
Close with #4741
