### ISSUE TITLE
[Bug] Rollup subprocess might not get killed when the main development process gets killed

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#4738]
## Bug Info

![image](https://user-images.githubusercontent.com/1141198/139663369-d213203c-6f79-45d4-b3ca-60ca1a19c6e5.png)

### How to reproduce?

Start with `pnpm start` and kill it, and repeat for some times.

_P.S._ Might confirm and handle later.

**Comment by Jack-Works** [comment]
Have no idea about this
