### ISSUE TITLE
[Bug] Minds minor UI issues

### ISSUE THREAD

**Issue by manishoo** [DimensionDev/Maskbook#4745]
Great job on the Minds.com integration! It looks awesome. Here are some minor UI issues I've encountered:

Text overflows in comments

![image](https://user-images.githubusercontent.com/16239413/139821848-b04477ec-c8e6-4c50-9a9b-984c24a5b4ab.png)

Mask icon appears outside of the composer when the user is not connected to the site.
![image](https://user-images.githubusercontent.com/16239413/139821987-d3085767-24cc-4181-9bab-b3d4fb36131c.png)

I'll update this issue if I see any other issues

**Comment by yisiliu** [comment]
thanks! We will update the UI accordingly @AinuX
