### ISSUE TITLE
[Bug] Hovering anchors in decoded post cause redecoding payload

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#475]
# Bug Report

### System

- OS: macos mojave 
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.8.7
- Installation: Self-Complied
- Build Commit: 651b4d98b3493c040b94654e3ea3c7cf8afb0eb0

### Expected Behavior

Do not redecode payload when hovering anchors in decoded post.

### How To Reproduce

Hovering in and out frequently on anchors in decoded post.

**Comment by guanbinrui** [comment]
Close due to can not reproduce.

**Comment by guanbinrui** [comment]
Reproduced in v1.10.6

**Comment by SunriseFox** [comment]
This should have been fixed. Currently, we may pay more attention to the performance loss caused by `adoptedStyleSheets`.
