### ISSUE TITLE
[Bug] CORS issue when request resources in minds

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4762]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/140288708-47a0f5e8-996f-4730-a889-070a6b46a877.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
We should also acquire permission to `cdn.minds.com` when initializing minds. About existing users, we may prompt them that some of permissions are missing.

@zhouhanseng

**Comment by zhouhanseng** [comment]
`"optional_permissions": ["<all_urls>"]`  already exists. 🤔

**Comment by Jack-Works** [comment]
> `"optional_permissions": ["<all_urls>"]` already exists. 🤔

That's optional. To use it, you need to call `brower.permission.request` to request it.

**Comment by wenluomask** [comment]
Checked.
