### ISSUE TITLE
[Demand] Allow users to disable Advanced Security Mode

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#478]
## Metadata

Field | Value
--- | ---
Figma Link | -
Expected UX prototype due | -
Actual UX prototype release | -
Expected engineering due | -
Corresponding Pull Request | -
Completion Version | -

## Background

Some users may experience incompatibility with certain applications which also use Shadow Root. We will offer them a way to disabled Advanced Security Mode in Maskbook, so that they may continue using both.

## Content

We will add a switch option in Settings panel, in Advanced 

- Title:
  - en: Advanced Security Mode
  - zh: 高級安全模式
- Tooltip:
  - en: Display confidential information in Shadow Root
  - zh: 敏感信息显示于 Shadow Root 内部
- Right Component:
  - Switch (Default: True)

## Notes

- Unimportant feature, do when free.
- Dependencies:
  - #369
  - #479

**Comment by Jack-Works** [comment]
Maybe we should start a vote to ask how many users are using vimium

**Comment by yisiliu** [comment]
> Maybe we should start a vote to ask how many users are using vimium

Good idea. I've been using Vimium for 6 years and no replacement exists for my demand. My current solution is to copy and paste my messages to the text field when I am using Maskbook.

**Comment by Tedko** [comment]
> Maybe we should start a vote to ask how many users are using vimium

Just encountered one in our Tg group

**Comment by Tedko** [comment]
> > Maybe we should start a vote to ask how many users are using vimium
> 
> Just encountered one in our Tg group

Encountered another 3-4 guys with same problem this month in denver

**Comment by Tedko** [comment]
Meet another several guys encounter similar problems.

Let's prioritize this one. Add an option for compatibility for vimum etc. @neruthes @Jack-Works

**Comment by neruthes** [comment]
A good time to start an evaluation of effort. If not much, we can plan this in M3 or M4.

cc @Jack-Works

**Comment by neruthes** [comment]
Looks like this has been done when implementing #769?

cc @Jack-Works

**Comment by Jack-Works** [comment]
> Looks like this has been done when implementing #769?
> 
> cc @Jack-Works

Nope. Do I need to implement it now?

**Comment by neruthes** [comment]
> > Looks like this has been done when implementing #769?
> > cc @Jack-Works
> 
> Nope. Do I need to implement it now?

No. Let it stay in queue.

**Comment by Tedko** [comment]
<img width="1322" alt="Screen Shot 2020-03-09 at 17 16 24" src="https://user-images.githubusercontent.com/6687437/76268138-5dcbb080-622a-11ea-9713-d0500b62d700.png">


Now this become a must fix problem...

**Comment by Jack-Works** [comment]
Okay, let me investigate it now

**Comment by Jack-Works** [comment]
encountered 2 problems:

1. once an element attaches a shadow root, it can't go back
2. the sync of ValueRef needs time. If it gets switched to false but used before the sync process, it will invoke the problem 1.

maybe come back for this problem in future

**Comment by neruthes** [comment]
My expectation is that requiring the user to restart Chrome is acceptable. If we tolerate this condition, will things get easier?

**Comment by Jack-Works** [comment]
> My expectation is that requiring the user to restart Chrome is acceptable. If we tolerate this condition, will things get easier?

No need to restart Chrome. Refreshing the page is enough but we need to change some design in our code.

**Comment by neruthes** [comment]
> > My expectation is that requiring the user to restart Chrome is acceptable. If we tolerate this condition, will things get easier?
> 
> No need to restart Chrome. Refreshing the page is enough but we need to change some design in our code.

LGTM.
