### ISSUE TITLE
[Bug] Lucky drop with image payload will show payload first in post

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4781]
### What happened?
 Lucky drop with image payload will show payload first in post;
<img width="646" alt="截屏2021-11-08 下午5 59 45" src="https://user-images.githubusercontent.com/85149605/140722724-236273c2-79d4-4e8c-8e4f-655df9c99627.png">

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by zhouhanseng** [comment]
@wenluomask I don't think this is a bug since that text is under the image at minds natively, meanwhile above the image at twitter.

**Comment by wenluomask** [comment]
Okay, never mind.
