### ISSUE TITLE
[Demand] Dashboard Revamp (Stage 4: Settings)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#479]
## Metadata

Field | Value
--- | ---
Previous Stage | #493 
Figma Link | [figma.com/...](___)
Expected UX prototype due | -
Actual UX prototype release | -
Expected engineering due | -
Corresponding Pull Request | -
Completion Version | -

## Overview

The UI should look completely same to the Settings page of Chrome.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/2139261/70405958-efaefc00-1a36-11ea-83c2-52afb3f68187.png">

### Sections Arrangement

Settings options should be divided in several sections:

- General
- Experimental Features
- Compatibility

### Existing Settings Options

Existing options should be adopted.

#### Section: General

- Debug Mode
  - Type: Switch
  - Default: OFF
  - Description: See debug information

#### Section: Experimental Features

- Enable Image-Based Payload
  - Type: Switch
  - Default: OFF
  - Description: Embed information in image instead of text

#### Section: Compatibility

- Background Retrieval
  - Type: Switch
  - Default: OFF
  - Description: For posts created before v1.9.0

## Notes

- This "Debug Mode" is the same flag with the one being shown in the panel in the extension bar.
- The version number for "Background Retrieval" is a placeholder. Should be replaced by the real version number.

**Comment by Jack-Works** [comment]
I like the Chrome settings design, cool!

**Comment by Jack-Works** [comment]
I'm going to investigate this
