### ISSUE TITLE
[Bug] DODO swap doesn't work for any network

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4796]
### How to reproduce?

1. Choose any network and try to swap in DODO;

### What happened?
It shows insufficient liquidity for this trade and faied to fetch swap information.
<img width="1617" alt="截屏2021-11-10 下午4 22 59" src="https://user-images.githubusercontent.com/85149605/141077517-cf43fb83-3fec-4da7-aa4b-095f1362030d.png">
<img width="1575" alt="截屏2021-11-10 下午4 27 35" src="https://user-images.githubusercontent.com/85149605/141077538-286a1eff-eb96-496b-9700-4e5f88bd0084.png">

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by nuanyang233** [comment]
close in #5107
