### ISSUE TITLE
improve i18n CH-hant

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#48]
這裏的中文版，“來解密”變成payload最後了
<img width="286" alt="Screen Shot 2019-05-29 at 01 12 13" src="https://user-images.githubusercontent.com/6687437/58497622-f5d23f00-81ae-11e9-921f-1e8383e3b258.png">
<img width="403" alt="Screen Shot 2019-05-29 at 01 12 06" src="https://user-images.githubusercontent.com/6687437/58497626-f7036c00-81ae-11e9-8f78-4d90d3c2fef9.png">

**Comment by neruthes** [comment]
The title of a bug report should be like "zh-Hant i18n bug" as long as it is a report; do not phrase it like a vague demand.
