### ISSUE TITLE
[Bug] Unlock plugin typo fix

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4806]
### How to reproduce?

1. Start Unlock plugin from compose;
2. Click select lock;

### What happened?
<img width="626" alt="截屏2021-11-12 下午1 43 40" src="https://user-images.githubusercontent.com/85149605/141416270-4ebce0b0-64d9-4ce0-ba59-011ec0bb3512.png">

### What should happen?
Change "Creator Dashboard" to "Unlock protocol Creator Dashboard".

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by czv6803892** [comment]
branch: fix/dashboard-style , done

**Comment by wenluomask** [comment]
Check.
