### ISSUE TITLE
[Bug] Miss token icon in assets list 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4812]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/141746193-bcb321c1-5a76-4e1c-b411-3f16b7e1a92d.png)

![image](https://user-images.githubusercontent.com/2582974/141746024-268fa24d-ff75-4099-84eb-98378e28c02f.png)

ps: The logo url from debank is correct.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Repeat issue: https://github.com/DimensionDev/Maskbook/issues/4784
