### ISSUE TITLE
[Bug] Load NFT that only on Rarible but not OpenSea.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4818]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
Some NFT like Phunk are only available on Rarible. 
https://rarible.com/token/0xf07468ead8cf26c752c676e43c814fee9c8cf402:486?tab=details

## Part 2: Problem to Solve
Support these NFT show on Rarible option.
<img width="636" alt="截屏2021-11-16 下午4 18 54" src="https://user-images.githubusercontent.com/85149605/141947247-10077d6c-3f77-43b3-a745-be893e1fc94d.png">

**Comment by Tedko** [comment]
@wenluomask fixed?

**Comment by wenluomask** [comment]
Not yet. I will arrange this to 2.3.0 version.

**Comment by Tedko** [comment]
@wenluomask fixed?

**Comment by wenluomask** [comment]
Merged to develop but didn't release yet.
<img width="587" alt="Screen Shot 2022-01-17 at 1 33 16 AM" src="https://user-images.githubusercontent.com/85149605/149671071-57da9c1f-d889-4eb5-a2fe-795c86598cb9.png">

**Comment by wenluomask** [comment]
Fixed.
