### ISSUE TITLE
[Bounty] Integrate Solana Into Mask Network

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4861]
## Catalogue
- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 2 weeks

- Bounty Size
  [x] 5000 USD

### Part 1: Problem Description

**Background** Solana is a web-scale blockchain that provides fast, secure, scalable, decentralized apps and marketplaces. The overarching goal of the Solana software is to demonstrate that there is a possible set of software algorithms using the combination to create a blockchain. So this would allow transaction throughput to scale proportionally with network bandwidth satisfying all properties of a blockchain: scalability, security and decentralization. 

**Solution** As the first step of our cooperation, we, Mask Network, would like to integrate Solana as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.
If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like and proceed to the development afterwards.

### Part 2: Resources

https://docs.solana.com/
https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins/Wallet

### Part 3: Contact and Support

@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q Solana discord server: https://discord.com/invite/pquxPsq

**Comment by Tedko** [comment]
this is also done by internal team

https://github.com/DimensionDev/Maskbook/search?q=solana
https://github.com/DimensionDev/Maskbook/tree/feat/solana-wallet

@LindaMask you should do some research b4 post bounties
