### ISSUE TITLE
[Bounty] Integrate FLOW into Mask

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4862]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 4 weeks

- Bounty Size
  [x] $5000

### Part 1: Problem Description
**Background** Flow is a fast, decentralized, and developer-friendly blockchain. Brought to you by the team behind CryptoKitties, Flow is the foundation for entire ecosystems of consumer applications starting with games, collectibles, and the apps that interact with them. Flow is based on a novel architecture that achieves the performance required for mainstream applications without compromising decentralization – or sharding the network. This means developers on Flow can build secure and composable applications to enable new possibilities for billions of consumers around the world.

**Solution** As the first step of our cooperation, we, Mask Network, would like to integrate Flow as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.

If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like and proceed to the development afterwards.

### Part 2: Resources

- https://www.onflow.org/faq
- https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins/Wallet

### Part 3: Contact and Support
@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q Flow discord server: https://discord.com/invite/J6fFnh2xx6

**Comment by Tedko** [comment]
believe this is done by internal team now @guanbinrui @LindaMask

**Comment by Tedko** [comment]
same @LindaMask 
https://github.com/DimensionDev/Maskbook/search?q=flow
