### ISSUE TITLE
[Demand] Introduce Avalanche Chain

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4874]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ DEX: https://app.pangolin.exchange/#/swap (An uniswap-v2 like DEX.)
+ CoinGecko ID: `"avalanche"`
+ CMC ID: `"5805"`
+ Debank ID: `"avalanche"`
+ OpenSea: Not Supported
+ Explorer: https://explorer.avax.network/
+ RPC: https://api.avax.network/ext/bc/C/rpc

## Notes

+ [AVAX](https://www.avax.network/)
+ [Avalanche  Explorer](https://explorer.avax.network/)

**Comment by developerfred** [comment]
Avalanche chain  ✅ 
Pangolin Dex ✅
