### ISSUE TITLE
[Bug]  undefined appears in snapshot plugin

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#4909]
## Bug Info

![image](https://user-images.githubusercontent.com/1141198/143176783-8f9a1b19-cced-434b-82d5-20c39ab44839.png)

### How to reproduce?

1. https://twitter.com/0xTycoon/status/1463355982747095041
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Checked.
