### ISSUE TITLE
[Bug] Failed to connect any social network in Firefox

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4912]
### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
![image](https://user-images.githubusercontent.com/2582974/143205830-9632466c-c6b5-4fc9-a81b-f46731e41b6b.png)

**Comment by Jack-Works** [comment]
fixed in 8d52d4f45d51e727755de6c0aacaeb06e2edba47
