### ISSUE TITLE
[Bug] Decrypt image payload not work 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4915]
### How to reproduce?

https://twitter.com/AinuxA/status/1463438363952771077

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: develop

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
I've tested with LKG version v2.0.0 and it's broken too. Looks like Twitter has changed its DOM structure?

**Comment by AinuX** [comment]
Tried with official build from Chrome Webstore, the image payload function is OK.

**Comment by AinuX** [comment]
Checked with #4932
