### ISSUE TITLE
[Task] Make non eval-source-map also throws in dev mode

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#4919]
Blocked by:

- https://github.com/webpack/webpack/pull/14173
- https://github.com/webpack/webpack/pull/13096

**Comment by Jack-Works** [comment]
bump

**Comment by Jack-Works** [comment]
#5514

**Comment by koto** [comment]
Is this actually blocked by webpack/webpack#14173? That PR is against webpack 4.

**Comment by Jack-Works** [comment]
> Is this actually blocked by [webpack/webpack#14173](https://github.com/webpack/webpack/pull/14173)? That PR is against webpack 4.

No. I found we're well with webpack/webpack#14173 (used in #5514)
