### ISSUE TITLE
Reduce Long waiting time when re-generating QR code for transferring identity

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#492]
See https://dimension.chat/group/maskbook?msg=W7bRkCQzY9XYC3Z8a

For now, for every-time the QR code button is clicked, the QR code will be generated again. This will create long waiting time especially on mobile devices etc. 

Suggestion:
- Temp store QR code once its generated (any potential security flaw?)

**Comment by SunriseFox** [comment]
I will investigate this.

**Comment by Jack-Works** [comment]
It doesn't look slow on your device. But a cache will be great.

**Comment by SunriseFox** [comment]
As persona database breaks the dashboard and database backup/restore interface, a lot of fixes have to be applied before we are able to make QR work again. This might be delayed after #369 and #407.

**Comment by yisiliu** [comment]
Caching the QR code is needed.
