### ISSUE TITLE
[Bug] Invalid Regex expression on Safari

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#4926]
## Bug Info

https://github.com/DimensionDev/Maskbook/blob/e8f7f1f45da63080bde99c1bfa76bdd6e6d160b1/packages/mask/src/social-network-adaptor/facebook.com/collecting/posts.tsx#L150-L161

These two Regex expressions are invalid on Safari:
1. `match(/(?<=story_fbid=)(\d+)/g)`
2. `match(/(?<=posts\/)(\d+)/g)`

Reference: https://stackoverflow.com/q/51568821
Please modify these expressions and test them on Safari (you could test them on the  console of Safari **Mac version**)

### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
It was introduced by #4698.
