### ISSUE TITLE
[Demand] Dashboard Revamp (Stage 3: Export Persona as QR)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#493]
## Metadata

Field | Value
--- | ---
Previous Stage | #369
Figma Link | [figma.com/...](___)
Expected UX prototype due | -
Actual UX prototype release | -
Expected engineering due | 2019-12-15
Corresponding Pull Request | -
Completion Version | -

## Content

<img width="664" alt="image" src="https://user-images.githubusercontent.com/2139261/70438291-61ae3200-1a85-11ea-8972-aa6e347e9383.png">

The third option in "Backup Persona" panel.

## Notes

- The "Backup Persona" panel should always have the same height.
- Implement this after #369 and ship both in the same release.
- Payload format is not defined. Feel free to use any arbitrary format without documentation.

**Comment by Jack-Works** [comment]
```ts
type QRRepresentation = [
    ProfileIdentifier['network'], // string
    ProfileIdentifier['userId'], // string
    Profile['nickname'], // string
    JsonWebKey['k'],  // LocalKey, string
    string, // Compressed publicKey
    string, // Compressed privateKey
    string, // BackupJSONFileLatest['grantedHostPermissions'].join(';'),
]
```

**Comment by SunriseFox** [comment]
> The "Backup Persona" panel should always have the same height

I don't think this could be done without specifying a fixed height, e.g., 200px

**Comment by neruthes** [comment]
> > The "Backup Persona" panel should always have the same height
> 
> I don't think this could be done without specifying a fixed height, e.g., 200px

<img width="849" alt="image" src="https://user-images.githubusercontent.com/2139261/70494551-a24c9080-1b03-11ea-9fb5-f431f13d7eb2.png">

Let the box be 292px for now. The height of the QR code image is 260px. The vertical padding is 16px.

**Comment by SunriseFox** [comment]
We also need something like 'import QR' or it would be useless. By the way, please update Figma.

**Comment by neruthes** [comment]
> We also need something like 'import QR' or it would be useless. By the way, please update Figma.

I will create another Demand issue to specify the behavior of importing QR.
