### ISSUE TITLE
[Bug] Private groups and friends shared between different persona

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#494]
# Bug Report

### System

- OS: macos mojave 
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.8.7
- Installation: Self-Complied
- Build Commit: c6a90099fc6343ab96f59c39e327b55a1216f87b
### Actual Behavior

Private groups and friends data shared between different persona in same machine.

![image](https://user-images.githubusercontent.com/52657989/70492075-2ae82280-1b3e-11ea-9e54-9cf99bf695b2.png)

### How To Reproduce

+ add two different persona and finish the setup steps;
+ add some friends in each persona;

**Comment by Jack-Works** [comment]
Just hiding them may be enough

**Comment by yisiliu** [comment]
hide the non-active ones

**Comment by neruthes** [comment]
Showing only the ones which belong to the current profile should be enough. 🤔

**Comment by guanbinrui** [comment]
As groups we can distinguish by its owner which fixed in #509. 

As friends we do not recorded enough info in DB to know which account discovered it. So let them share across different personas.

**Comment by neruthes** [comment]
Looking forward to a database revamp.
