### ISSUE TITLE
[Demand] Subdivision type JsonWebKey and CryptoKey

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#495]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Background

There was some bugs that caused by the not accurate enough `JsonWebKey` type and `CryptoKey` type. We should turn them into a compile-time type error. I'll do it when I'm free.

**Comment by neruthes** [comment]
You may create Demand issues with <https://gist.github.com/neruthes/dd12b4fa130c32b585fc0fbd42c696b6>.

**Comment by Jack-Works** [comment]
already done with new jwk based crypto worker
