### ISSUE TITLE
[Bug] Select NFT image to set as avatar, will load blank image - occasional problems

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4957]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/143726866-9e3a1c2d-f501-4b5d-af40-e667b39b4335.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: lelenei/fix-nft-avatar-image

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
merged
