### ISSUE TITLE
[Bug] Halo will disappear - occasional problems

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4959]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/143727750-48f6ac94-b643-4ee2-b454-af9d8332c94b.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
The error cannot be reproduced now
