### ISSUE TITLE
[Bug] Show unidentified in NFT lucky drop

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4960]
### How to reproduce?

Contract: 0x533a91100f316477d59e71199d205dd0fb0336aa

![image](https://user-images.githubusercontent.com/2582974/143731195-85f8ee74-e60b-4afe-b823-517153988ac0.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
@zhouhanseng Why not use the contract name or symbol instead of `Unidentited`? Hope we can resolve this in 2.2.0.

**Comment by AinuX** [comment]
Checked
