### ISSUE TITLE
[Bug] Unknown in swap popup dialog

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4961]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/143731590-1b527dc3-afc5-4f0d-abb2-7e8588487d8a.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Fixed in 2.1.0.
