### ISSUE TITLE
[Bug] Fail to upload file via FileService on iOS

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#4962]
## Bug Info
Fail to upload any file via FileService plugin on iOS

### How to reproduce?

1. Send new FileService plugin message
2. Pick any valid file to upload
3. After several seconds of loading, we got the error with the message: `Service unavailable, wait a few minutes and try again`

### Analysis
When uploading begins, an error emitted on Safari's console:
<img width="1434" alt="Snipaste_2021-11-28_14-31-24" src="https://user-images.githubusercontent.com/7972003/143732200-80af135e-668d-4220-8e63-d95a2e25b34f.png">

The root cause seems to be:
By normal, the type of response of `makeAttachment` should be like:
```
{
    block: uint8Array,
    key: string,
    type: string,
}
```
as on Chrome:

<img width="1425" alt="Snipaste_2021-11-28_14-32-59" src="https://user-images.githubusercontent.com/7972003/143732282-0016d923-356e-4bd2-b2e1-7cb6dd68a133.png">

**But on iOS, the response type is:**
```
{
    **block: string,** //This should not be type `string`
    key: string,
    type: string,
}
```

Not sure which part of the codebase convert the `uint8Array` to `string`

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [x] iOS 14

**Comment by Jack-Works** [comment]
Why're we using BigInts?

**Comment by AinuX** [comment]
Still have problem with latest build.
