### ISSUE TITLE
[Bug] Fail to open database on iOS occasionally

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#4965]
## Bug Info
After using Mask Network iOS app for several minutes, occasionally app would fail to load any data from Webview's IndexedDB.
The underlay error message on Safari console is: `Connection to Indexed Database server lost. Refresh the page to try again`
I'm afraid the #4815 does not fix all the IndexedDB issues. @Jack-Works Maybe the last post in this [link](https://developer.apple.com/forums/thread/681201) could do some help.

### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
try #4833
