### ISSUE TITLE
[Bug] Unable to load correct token info in Lucky Drop - occasional problems

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4966]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/143733210-9c30d030-2101-47f1-a034-ecbc58183f36.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
The resend lucky drop, the token claimed was also incorrect. Please check the detail in Jira.
https://mask.atlassian.net/browse/MASK-309
