### ISSUE TITLE
[Bug] Should adjust the display priority of thegraph and onchain data in ITO history

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4967]
### How to reproduce?
1. Create ITO
2. Check the ITO past history
3. Block thegraph api request 
4. Check the ITO past history

https://user-images.githubusercontent.com/2582974/143733985-f0da74a1-730f-496a-b7c2-d7922658bfbc.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Jira：https://mask.atlassian.net/browse/MASK-419
