### ISSUE TITLE
[Bug] GoodGhosting plugin showed consistent but incorrect data for different pool link

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4969]
### How to reproduce?

1. Find some pools in GoodGhosting https://goodghosting.com/#/pools;
2. Post different pools' link in Twitter;
3. Check the data showed;

### What happened?
GoodGhosting plugin showed consistent but incorrect data for different pool link
<img width="715" alt="Screen Shot 2021-11-28 at 4 16 24 PM" src="https://user-images.githubusercontent.com/85149605/143735106-8b6c7444-773d-4c91-b31f-9c053b52bf37.png">
<img width="1519" alt="Screen Shot 2021-11-28 at 4 23 06 PM" src="https://user-images.githubusercontent.com/85149605/143735123-80004200-4f9d-489b-a759-8fc7a787ec60.png">

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
need to configure the contract address of pool 22

**Comment by lelenei** [comment]
https://github.com/Good-Ghosting/mask-plugin-integration/pull/1
