### ISSUE TITLE
[Bug] Web3 tab cannot handle properly the multi-media NFT 

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4972]
### How to reproduce?

1.Go to https://twitter.com/WEN6666661 and check Web3 tab;
2. Find the nft of collection Aircoins Metaverse (https://opensea.io/assets/0x025983cd3530f78b71b4874eb5272c189b357e61/532)

### What happened?
Web3 tab cannot display the NFT image for Aircoins Metaverse collection.
<img width="509" alt="Screen Shot 2021-11-28 at 6 55 11 PM" src="https://user-images.githubusercontent.com/85149605/143765100-0407ce23-c96f-47da-88b3-f8e4692bec41.png">

### What should happen?
Show a default image for these NFT, or show the screenshot like The Immortal Poppy(1).
<img width="325" alt="Screen Shot 2021-11-28 at 7 02 01 PM" src="https://user-images.githubusercontent.com/85149605/143765133-f5bfa349-1a70-4f97-9458-42707910f40a.png">

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
There is a "animation_url" in opensea api response that indicate it has a multi-media resource for the item and the file extensions maybe GLTF, GLB, WEBM, MP4, M4V, OGV, and OGG.

![image](https://user-images.githubusercontent.com/2582974/143767605-2af20d14-e6a9-4cbf-bf15-8efecd510c7c.png)
