### ISSUE TITLE
[Bug] WalletConnect dialog will not close automatically after wallet connected 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4974]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/143768850-709c429d-494b-4692-9276-fab1383343b9.mp4

1. Chose walletConnect to connect wallet 
2. Scan the QR code to connect 
3. Check the walletConnect dialog's state 

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
fixed? @guanbinrui

**Comment by Tedko** [comment]
is this fixed @AinuX @guanbinrui
