### ISSUE TITLE
[Bug] Convert function in collectible did not transfer the swap parameter 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4976]
### How to reproduce?

https://user-images.githubusercontent.com/2582974/143772664-41aca419-49af-44dd-a94f-85554a5a6937.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by lelenei** [comment]
close #5151
