### ISSUE TITLE
[Bug] Need friendly reminder if swap amount is too low on Balancer

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4979]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/143773435-8b26e88f-0975-4fba-973c-f96a0cc8955d.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
The UI has changed.
