### ISSUE TITLE
[Bug] Unable to get swap rate even the DODO website can

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4981]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/143774446-d490987f-9f12-48e4-af7a-9c8f28e20d9c.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Have encountered a CORS error from DODO API.

![image](https://user-images.githubusercontent.com/52657989/143775834-a968422a-2f2c-4461-bf78-7ea8f2d48040.png)

**Comment by wenluomask** [comment]
Fixed in feat/new-swap #4787 , but won't merge to 2.1.0.  Same issue with #4796.

**Comment by Tedko** [comment]
fixed and working wel
<img width="1420" alt="Screen Shot 2022-01-17 at 00 51 17" src="https://user-images.githubusercontent.com/6687437/149669522-7f2c4fef-fa71-49ac-8919-ce4bae3451a3.png">

l
