### ISSUE TITLE
[Bug] Unable to connect SNS account 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4992]
### How to reproduce?

1. Try to connect SNS account from Mask plugin

### What happened?
Nothing happed, unable to connect. 
![image](https://user-images.githubusercontent.com/2582974/143999763-b37fc186-391d-4293-9d5e-e4ac46cc0dae.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
tried with latest ver on ff, cannot reproduce

**Comment by AinuX** [comment]
The issue is  still existed, and further investigation is needed.

**Comment by AinuX** [comment]
![image](https://user-images.githubusercontent.com/2582974/153543533-d8ea982c-77c0-4a4c-8e7c-dcce89338ad2.png)

Still can't connect SNS account with latest build.

**Comment by Jack-Works** [comment]
oh wait let me handle this

**Comment by Jack-Works** [comment]
try this https://github.com/DimensionDev/Maskbook/pull/5645

**Comment by AinuX** [comment]
Tried #5645, error message changed, but still can't connect.
![image](https://user-images.githubusercontent.com/2582974/153555466-85f7b636-0dfe-408e-adc7-b0d79cfcefaa.png)

**Comment by Jack-Works** [comment]
tried #5645 with Firefox + Twitter in dev mode, cannot reproduce this problem.

**Comment by AinuX** [comment]
https://user-images.githubusercontent.com/2582974/153575950-e77acf41-842f-409d-a47a-5172177dfa97.mp4

**Comment by Jack-Works** [comment]
https://user-images.githubusercontent.com/5390719/153798197-1c3900c6-e94d-480c-a231-4310df4c0ed6.mp4

Tried again with Firefox+Twitter in production, also works.
