### ISSUE TITLE
[Bug] Not support using the mainnet coin as minimum position value - MaskBox

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4993]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/144000417-0f52297a-3389-4fdc-898d-b491001e2287.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment]
@AinuX We removed native coin from candidate list of minimum holding coin, so this problem would not happen anymore.
