### ISSUE TITLE
[Bug] Fail to vote via snapshot plugin

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#4996]
### How to reproduce?

URL: https://twitter.com/AinuxA/status/1465611122644422658

https://user-images.githubusercontent.com/2582974/144019228-8dd5899a-6e2e-4993-b15b-a57ebfde11e8.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by AinuX** [comment]
Reopen, still can't vote.

**Comment by zhouhanseng** [comment]
https://github.com/snapshot-labs/snapshot/issues/1153
