### ISSUE TITLE
[Bug] Decryption is displayed multiple times

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#50]
<img width="456" alt="Screen Shot 2019-05-29 at 15 12 55" src="https://user-images.githubusercontent.com/6687437/58536994-8139e780-8224-11e9-831d-3a5a9375154a.png">

**Comment by Jack-Works** [comment]
@Tedko I'm not familiar with Facebook. How to reproduce this problem?

**Comment by Tedko** [comment]
我直接问密码朋克社群的吧

**Comment by neruthes** [comment]
Let them post to Maskbook-Talks.

**Comment by Tedko** [comment]
cannot reproduced. Will open again if there's any update.
