### ISSUE TITLE
[Crash] TypeError: undefined is not an object (evaluating 'ref.eth.toFixed')

### ISSUE THREAD

**Issue by TheDirtyLaos** [DimensionDev/Maskbook#5035]
I was *doing something...*, then Mask reports an error.

> undefined is not an object (evaluating 'ref.eth.toFixed')

Error stack:

<pre>Row@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/options-page.js:4709:101
Ch@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:171:138
gk@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:294:31
fk@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:282:24
ek@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:281:371
Vj@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:281:231
Pj@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:270:478
Pj@[native code]
J@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/521.js:19512:204
R@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/521.js:19513:124</pre>

## Build info
- Version: 1.36.3
- NODE_ENV: production
- target: safari
- build: stable
- architecture: app
- firefoxVariant: false
- resolution: mobile
- BUILD_DATE: 2021-08-26T17:27:07.625Z
- VERSION: v1.29.12-809-g0d6499677

## Git ():

0d6499677 (released) on tag "v1.36.3"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
@DimensionDev/qa
