### ISSUE TITLE
[Demand] Add onchain data fetching fallback for NFT Lucky Drop

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#5042]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
For NFT Lucky Drop, the past history data rely on thegraph, but thegraph has data latency and stable issue, so we need a fallback to make the function more reliable.

## Part 3: Expected Behavior
If thegraph is down, the fallback(onchain fetching) can return the needed data.

**Comment by developerfred** [comment]
I can build a job that consents as onchain information and returns with a query api, and i can do that with github actions, and use block commit time to update an action.
