### ISSUE TITLE
[Demand] Support NFT Lucky Drop on BSC

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#5043]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
Add support for NFT Lucky Drop on BSC.

**Comment by developerfred** [comment]
Assign me on this issue I can implement the contracts and make the lucky drop available.

**Comment by Tedko** [comment]
how @zhouhanseng
