### ISSUE TITLE
[Bug] Change wallet dialog should be closed automatically after changing complete in mask dashboard

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#5059]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/144712083-84d63541-8ac7-49bf-838b-8d6cd9ed9123.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Created issue in Jira:
https://mask.atlassian.net/browse/MASK-405

**Comment by AinuX** [comment]
Checked
