### ISSUE TITLE
[Bug] Chrome extension display incorrect

### ISSUE THREAD

**Issue by LeeSiler** [DimensionDev/Maskbook#5087]
### How to reproduce?

1.
![image](https://user-images.githubusercontent.com/15024097/144784523-9c17a51a-31b5-471c-ba9b-65c18f02d405.png)

2.
3.

### What happened?
receiver should be change sender

## Environment
Linux

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [x] Linux:  ubuntu 20.04

### Platform/Browser

 
- [x ]  Chrome (Version 96.0.4664.45 (Official Build) (64-bit))
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by LeeSiler** [comment]
append  assets  display 0.00

**Comment by AinuX** [comment]
Will be fixed in next release, thanks!

**Comment by wenluomask** [comment]
Fixed.
