### ISSUE TITLE
[Bug] Transaction link should not follow the wallet connected chain 

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#5098]
### How to reproduce?

![image](https://user-images.githubusercontent.com/2582974/144972258-d4f18e07-f663-4fd8-9a01-105e8acccd87.png)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Checked.

**Comment by wenluomask** [comment]
Fixed by #5106
