### ISSUE TITLE
[Discussion] Feature -- Remove Decrypter

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#51]
<img width="549" alt="Screen Shot 2019-05-29 at 15 15 23" src="https://user-images.githubusercontent.com/6687437/58537175-f1e10400-8224-11e9-925b-21ae4de4fc80.png">

**Comment by Jack-Works** [comment]
No this is impossible by design. Once it's on the internet, it's forever on the internet.

**Comment by Tedko** [comment]
Ok.

One of the reason I’m thinking about using Solid is seems like it can rm
the content. We may discuss this later.

**Comment by yisiliu** [comment]
This is possible by editing the post with the new ciphertext encrypted by a new AES key.

**Comment by Jack-Works** [comment]
> This is possible by editing the post with the new ciphertext encrypted by a new AES key.

Not reasonable. Why don't just delete that post and repost a new one?
