### ISSUE TITLE
[Bug] Twitter RT/Reply UX bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#516]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: FF/Chrome
- Browser Version:

### Maskbook

- Maskbook Version: Latest store Ver
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

Able to reply/RT normally 

### Actual Behavior

See:
https://dimension.chat/group/maskbook?msg=gjMnGReBtPdNQXHZF
<img width="1432" alt="Screen Shot 2019-12-14 at 10 46 13" src="https://user-images.githubusercontent.com/6687437/70842507-80cf0a00-1e5f-11ea-9738-0413b49ac3d6.png">

### How To Reproduce

Just RT/Reply someone's post

**Comment by Jack-Works** [comment]
We're going to have a new composition UI now 🙈

**Comment by Tedko** [comment]
Ok ignore and close this issue after we have that. 👍

**Comment by Jack-Works** [comment]
@guanbinrui can we close this now?

**Comment by Tedko** [comment]
Yeah

**Comment by Tedko** [comment]
@Jack-Works @guanbinrui next time with UX bug fixes publish a new version to store

**Comment by guanbinrui** [comment]
Close this issue because release/1.9.0 will be released.
