### ISSUE TITLE
Turn off spell checking for address input

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#5172]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Address input shows spell checking errors in many places, e.g.

![image](https://user-images.githubusercontent.com/1141198/145755325-8ae31bf8-fc7f-45e3-b67b-e26de2eab594.png)

## Part 2: Problem to Solve
We can turn it off with setting `spellcheck` to false.
```tsx
<input spellcheck='false' />
```
![image](https://user-images.githubusercontent.com/1141198/145755620-2f860434-50d2-4a1e-8588-35d72042f95c.png)

**Comment by tylerferrara** [comment]
I'm not seeing spell check Brave or Firefox. Which browser and OS are you using?

<img width="1340" alt="Screen Shot 2021-12-20 at 12 52 08 PM" src="https://user-images.githubusercontent.com/20875599/146810913-1c37429f-7e52-4aa3-8851-330a5fff4a2c.png">

**Comment by UncleBill** [comment]
If you get the input focus, you should see red dot line under the address.

![image](https://user-images.githubusercontent.com/1141198/146866717-3695d11c-be6a-4572-ae92-acff1a9eb371.png)

**Comment by septs** [comment]
```tsx
<input
    spellCheck={false}
    autoCapitalize="off"
    autoComplete="off"
    autoCorrect="off"
/>
```

**Comment by UncleBill** [comment]
Well, I wanted to leave it as a memo here first and resolve it later when we had time, because it's not that important. If  anyone who has time, feel free to fix it.
