### ISSUE TITLE
[Crash] TypeError: trending.coin.symbol is undefined

### ISSUE THREAD

**Issue by mrivero1981** [DimensionDev/Maskbook#5202]
I was *doing something...*, then Mask reports an error.

> trending.coin.symbol is undefined

Error stack:

<pre>TraderView@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/chunk.1365.js:2427:191
Ch@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:171:137
si@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:198:255
gk@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:295:346
fk@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:282:24
ek@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:281:371
Vj@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:281:229
Pj@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/npm.react-dom.js:270:476
J@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/70.js:19512:204
R@moz-extension://b943fc3e-62a9-4881-bc01-abc400e70eec/js/70.js:19513:123
</pre>

## Build info
- Version: 1.36.5
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- firefoxVariant: fennec
- resolution: desktop
- BUILD_DATE: 1970-01-01T00:00:00.000Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A) on tag "N/A"
N/A

**Comment by guanbinrui** [comment]
Please upgrade your extension to the latest version.
