### ISSUE TITLE
[Bug] Multiple Injected Mask buttons in Twitter mobile composing dialog

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#5211]
## Bug Info

<img width="380" alt="Snipaste_2021-12-16_14-54-30" src="https://user-images.githubusercontent.com/7972003/146322767-47e24c77-3559-4e50-899e-a5d6aee37d47.png">

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by tylerferrara** [comment]
@jk234ert Could you please populate the fields for this Bug?
It gives developers a better idea of where the issue may be rooted to make a quick fix.
