### ISSUE TITLE
Sort imports with eslint

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#5241]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other
  - /_List it here_/

## Part 1: Introduction and Background

**To reduce merge conflicts of imports**, let's align import orders by a standard.

## Notes

Add sort-imports rule. https://eslint.org/docs/rules/sort-imports

**Comment by Jack-Works** [comment]
Notice: Import order might be important. Be aware of that.
