### ISSUE TITLE
[Bug] Incorrectly reporting profile connecting failure when actually connected

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#529]
# Bug Report

### System

- OS: Mac OS
- OS Version: High Sierra

### Browser

- Browser: Chrome
- Browser Version: 79.0.3945.79 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: #427 
- Installation: ZIP
- Build Commit: N/A

### Expected Behavior

Should report that the profile connecting is successful.

### Actual Behavior

It reports that the connecting has failed.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/2139261/70975268-78661180-20a1-11ea-960c-daeaf3f6af17.png">

### How To Reproduce

Connect in initialization process.

**Comment by SunriseFox** [comment]
The main causes of this problem have been identified. 

+ On facebook, they don't return bio content in DOM.

+ On twitter, our script executes too quick before, twitter content has loaded.

**Comment by SunriseFox** [comment]
After #545, this procedure will be deprecated. It will not affect the setting up process anymore.

**Comment by Tedko** [comment]
Assume we fix this with #545 and #543 . Reopen if reproduced
