### ISSUE TITLE
gungame.herokuapp.com deleted, remove from code, throwing errors

### ISSUE THREAD

**Issue by amark** [DimensionDev/Maskbook#53]
Hey sorry, gungame.herokuapp.com got deleted (heroku complaining I'm using too many hours) and I need the hours for my scaling tests (please don't use the testing peer).

I should have checked first before deleting it, cause I see it now in your code. 

The problem is now that I've deleted it, any peer connected to it will start throwing errors constantl, as it'll try reconnecting every 2 seconds and fail.

So sorry about this! None of those peers were intended for production use. 

The good news is the scaling tests are going super well, so expect a bunch of new peers with AXE that will auto DHT peer discovery and stuff! Hopefully next several months it'll be out!

This issue is a heads up warning about the deleted peer and the resulting errors throwing.

**Comment by Jack-Works** [comment]
Thanks!

**Comment by Tedko** [comment]
👍👍
