### ISSUE TITLE
[Bug] #5294 incompatible on iOS WebView

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#5302]
## Bug Info
#5294 makes Mask Network JS files totally fail to run on iOS Mask Network mobile app.
Since this PR does not bring any new feature nor fix issues, @Jack-Works @guanbinrui  please **REVERT IT** before we find the root cause and resolve the compatibility issue.

### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
reverted.
