### ISSUE TITLE
[Demand] Prevent rate limiting with Infura RPC URLs

### ISSUE THREAD

**Issue by NoblePaladin** [DimensionDev/Maskbook#5304]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other

## Part 1: Introduction and Background

I've noticed that Mask's infura URLs can get rate limited. Most notably, when doing development, I've noticed this happening:

```bash
full.mjs?f5ef:553
Object: daily request count exceeded, request rate limited(-1)
@dfot957sfqs<remote stack not available>
```

## Part 2: Problem to Solve

Two things should happen here:

1. Increase rate limit for Maskbook's Infura URLs.

2. Attempt to fallback to Metamask's RPC URLs if Maskbook's Infura's URLs are rate limited.

## Part 3: Expected Behavior

It should not show this error in prod or dev environments.

**Comment by guanbinrui** [comment]
We are using a shared infra node for development. You may replace it with your owned key in `packages/web3-constants/evm/rpc.json`. That will no longer get bothered by other developers.

**Comment by NoblePaladin** [comment]
Okay! Perfect! Thanks for the clarification @guanbinrui!
