### ISSUE TITLE
[Demand] New procedure for setting up mobile Maskbook

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#531]
Now we require a full procedure from installing our mobile application to being able to use Maskbook with facebook.

Special notice: 
From application startup, should we open facebook or Maskbook dashboard?
If facebook, how to direct user to open our dashboard and begin setting up? to which step?
If dashboard, how to direct user to login to facebook and go back to dashboard to continue?

## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
This is what #409 is designed to enable. Will be considered in the next stage of network-specific guides.

**Comment by SunriseFox** [comment]
I don't care it's in which stage. Be aware, our mobile app will not work without this.

**Comment by Tedko** [comment]
I guess, 

- Login Fb first (will able to use OS's pw management, like iCloud keychain)
- Have some banner like functionality so that we can redirect user to Maskbook Dashboard
> OR - Just redirect user to Dashboard
- Setting up: send Proof post/update bio; etc?

**Comment by neruthes** [comment]
All platforms should use the same initialization procedure. The affinity of the #407 procedure with mobile devices should be enough. The UI for smaller screens will be drawn in Figma. Case-by-case critics on the mobile-affinity matter are welcomed.

**Comment by Tedko** [comment]
Updates?

We will start to working on growth. Need fix this before lunar new yr.

**Comment by neruthes** [comment]
#409 is the ultimate solution for this matter.

**Comment by SunriseFox** [comment]
I don't think #409 is suitable for mobile devices, for example, screen width, complexity...

**Comment by Tedko** [comment]
+1

**Comment by neruthes** [comment]
> I don't think #409 is suitable for mobile devices, for example, screen width, complexity...

Elaborate the factors which you concern, please? 🤔

**Comment by SunriseFox** [comment]
+ This guide is to set up profiles, not personas, not `from starting up an app to being able to use it`.

+ A mobile user is more likely to restore backups and en/decrypt posts, not setting up new personas or new profiles.

+ A traditional mobile screen cannot hold such amount of data.

I think it‘s obvious.

**Comment by neruthes** [comment]
> This guide is to set up profiles, not personas, not `from starting up an app to being able to use it`.

Creating the first persona is a part of the initialization procedure according to #369. #409, like #600, is a replacement for the original non-immersive ConnectProfile modal as specified in #369.


> A mobile user is more likely to restore backups and en/decrypt posts, not setting up new personas or new profiles.

Having a persona is a mandatory condition of actually using Maskbook. This is part of the initialization procedure. After initialization, the user may still import database backups to merge data. Personae may be added in various ways.


> A traditional mobile screen cannot hold such amount of data.

Some minor adjustments should be enough for this matter.

**Comment by Tedko** [comment]
Updates on this one? We need a stand alone mobile app (which means can set up properly) now.

**Comment by neruthes** [comment]
After we implement #600 & #397 (and fix several bugs), mobile version should be usable.
