### ISSUE TITLE
[Demand] Icons in dim mode

### ISSUE THREAD

**Issue by nuanyang233** [DimensionDev/Maskbook#5339]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Now Twitter has three theme modes (light, dark, dim). 

## Part 2: Problem to Solve

However, `createPaletteAwareIcon` only supports light and dark.

## Part 3: Expected Behavior

We need to be able to define the icon in dim mode with `createPaletteAwareIcon`

It would be nice if the current theme color of the tweet could be used for the fill and other attributes of the icon

![image](https://user-images.githubusercontent.com/28348152/147575838-6557a217-27d4-451a-af3c-c95dc5cb666f.png)

**Comment by Jack-Works** [comment]
memo to self, create a context, and use that context to retrieve a more precise icon theme.
