### ISSUE TITLE
Unintended $self in 'add Decrypter'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#54]
![9831559667613_ pic](https://user-images.githubusercontent.com/6687437/58899212-f3339480-872e-11e9-82b7-c38b69104e5c.jpg)
![Screen Shot 2019-06-05 at 01 00 26](https://user-images.githubusercontent.com/6687437/58899215-f464c180-872e-11e9-88db-d08def441471.png)

如果这个下个版本按照JN的设计会没有的话就不用管了。

**Comment by Jack-Works** [comment]
That's internal representation in the old database. The new database has launched yesterday.

**Comment by Tedko** [comment]
ok
