### ISSUE TITLE
[Bug] Long waiting time when clicking 'Developer Options' in dashboard

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#541]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: Chrome/FF
- Browser Version: latest stable

### Maskbook

- Maskbook Version: Latest stable store ver
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info

 Long waiting time when clicking 'Developer Options' in dashboard
(>5s on my side)

### Expected Behavior

Normal respond time

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by SunriseFox** [comment]
Identified. It happens if there are too many profiles from Twitter. Maybe we could hide those without keys (or don't store them at the beginning) @Jack-Works #562

**Comment by Jack-Works** [comment]
Yes, we'd better hide the profiles with no public key. Maskbook will also store the profile with no public key because once they have one, Maskbook can display the avatar and nickname in no time.

In the avatar DB, the "last used" property is stored so we can remove the unused profile when we want

**Comment by Tedko** [comment]
better hide the profiles with no public key. +1

do it :D
