### ISSUE TITLE
[Bug] Best Price is not accurate on TraderView

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#5453]
## Bug Info

<img width="1420" alt="Screen Shot 2022-01-17 at 00 48 08" src="https://user-images.githubusercontent.com/6687437/149669417-23e00b56-ee99-415a-815d-643d2843c6e4.png">

### How to reproduce?

1. search token like $gtc 
2. try sell/purchase a relative large amount
3. best not accurate 

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by developerfred** [comment]
@Tedko I made a simple change of logic for the plugin to work. I believe he was prioritizing the lowest gas
<img width="784" alt="Screenshot 2022-01-16 at 18 47 40" src="https://user-images.githubusercontent.com/57037080/149671822-69b50ff7-3a2b-47c9-be48-5f8f9922af90.png">

**Comment by nuanyang233** [comment]
The [fix](https://github.com/DimensionDev/Maskbook/pull/5434) will be available in the next release.
