### ISSUE TITLE
[Bounty] Integrate Pangolin, a Dex into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5470]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 150 $MASK or $2000

## Part 1: Problem Description

**Background**
Pangolin is a decentralized exchange (DEX) on Avalanche Blockchain, uses the same automated market-making (AMM) model as Uniswap, features a native governance token called PNG that is fully community distributed and is capable of trading all tokens issued on Ethereum and Avalanche. In a crowded marketplace with multiple contenders, Pangolin offers three critically important benefits: fast and cheap trades, community-driven development, and a fair and open token distribution.

**Solution**
Create a plugin that integrates Pangolin into Mask. The UI should be identical to other swaps

<img width="538" alt="Screen Shot 2022-01-17 at 5 58 04 PM" src="https://user-images.githubusercontent.com/94482490/149847779-a8fbc11c-274c-425d-93d7-adcdd46617af.png">

<img width="538" alt="Screen Shot 2022-01-17 at 6 05 07 PM" src="https://user-images.githubusercontent.com/94482490/149847797-6816e979-9d82-4996-8cc8-49196dfef3e3.png">

See the existing polygon swaps and ETH swaps.

Any link cashtag with a viable ticker, like $Avax on Twitter, should trigger the plugin. 

Suggested Verbiage
I just swapped $aa worth of xxx token for yyy token, using Mask Plugin. Will I make money?

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://pangolin.exchange/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Pangolin discord server: https://github.com/pangolindex

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5470 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
@LindaMask done here -> https://github.com/DimensionDev/Maskbook/pull/5289
