### ISSUE TITLE
[Bounty] Integrate Azuro, a Betting/Prediction Market Protocol into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5495]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks 
- Bounty Size
  - [x] 150 $Mask or 2000 USD 

## Part 1: Problem Description
**Background**
Azuro Protocol is an open source public-domain software including a set of smart contracts, written in Solidity that can be deployed on the Ethereum Blockchain, and/or other blockchains. Azuro utilizes smart-contracts to build a decentralized betting protocol deploying an innovative solution for liquidity provision and allocation. Betting becomes transparent and trustless, while depth of betting events, markets and UX remains as good as it gets.

Furthermore, Azuro democratizes the business of betting by breaking down the role of the traditional bookmaker into several smaller roles, openly available for anyone to benefit from: liquidity provision, front-end management, data provision via oracles, decentralized (DAO) governance. As a result we envision a rich, fun betting environment with decreased cost of service to players, full transparency, community-run and with a commitment to responsibility.

**Solution**
Integrate Azuro into Mask. The UI could resemble Dhedge in a card style with different tabs serving different purposes

![121800209-102ac880-cc63-11eb-8e99-4e9788c7d387](https://user-images.githubusercontent.com/94482490/150068560-d9ddb727-0608-4052-abeb-d5e4062a2ed1.png)

_Details page for a market on Azuro_

<img width="1159" alt="Screen Shot 2022-01-19 at 12 21 47 AM" src="https://user-images.githubusercontent.com/94482490/150069109-263983f8-fe6d-4146-a35d-1816320e4cf2.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://azuro.org/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Azuro discord server: https://discord.com/invite/nQ4JVcQdQN

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5491 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design

**Comment by harjaapdhillon16** [comment]
I wanna start working on this @LindaMask is it open to work upon ?

**Comment by LindaMask** [comment]
Hi @harjaapdhillon16 yes it is still open. Please reach out to me on telegram @lin_dao and I will take you through our bounty process.

**Comment by SebastianLF** [comment]
I'm working on this one.
