### ISSUE TITLE
[Bounty] Integrate Idea Market, A Commodity Market into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5535]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 200 $Mask or 2000 USD

## Part 1: Problem Description
**Background** Idea markets use investments to establish credibility for ideas and narratives without trusting a centralized third party. Fundamentally, idea markets use price discovery to advance discovery. Idea markets is currently available on Arbitrum

**Solution**
Build an Idea Market plugin on Mask. The UI could resemble Dhedge in a card style with different tabs serving different purposes

_Dhedge UI_
![121800209-102ac880-cc63-11eb-8e99-4e9788c7d387 (1)](https://user-images.githubusercontent.com/94482490/151283980-f82e0428-75ea-4d04-aab0-e1b0e638d19f.png)

_Idea Marketplace_
<img width="792" alt="Screen Shot 2022-01-26 at 10 03 44 PM" src="https://user-images.githubusercontent.com/94482490/151284697-aa40d7f2-d2a3-494a-a512-8216409afc51.png">

Please let us know what your ideas are on UI before beginning work

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://ideamarket.io/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Idea Market discord: https://discord.com/invite/TPTHvutjnc

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5535 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by SebastianLF** [comment]
I'm working on this integration.
