### ISSUE TITLE
[Bug?] Compose post window are not closed and rendered in the wrong place after posting encrypted post

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#56]
![Screen Shot 2019-06-10 at 17 32 54](https://user-images.githubusercontent.com/6687437/59186634-f05cf780-8ba5-11e9-820f-59211b0db883.png)

Cannot reproduce after relaunch Chrome. Suspect this is from some glitch of Chrome.

**Comment by Jack-Works** [comment]
Maybe they changed the dom structure again hmm

**Comment by Tedko** [comment]
Fail to reproduce this bug.
我用brave reproduce失败了。重启一下chrome试试看。有可能是我chrome卡爆了之后出现了一些奇怪的情况。。。

**Comment by neruthes** [comment]
Should be irrelevant in next major version

**Comment by Tedko** [comment]
Cannot reproduce. suspect on Chrome. Will close this first since it wont be a problem soon.

**Comment by Jack-Works** [comment]
Maybe related to holoflows kit
