### ISSUE TITLE
[Bug] FileService UI compatible on mobile devices

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#5648]
### How to reproduce?

1.Create a file service plugin or view a file service plugin on mobile devices

### What happened?
File service UI components lay beyond the right edge of screen

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by orange187** [comment]
Checked
