### ISSUE TITLE
[Bounty] Integrate Convex, A Yield Farming Platform into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5779]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 200 $MASK or 1000 USDC
## Part 1: Problem Description
Background: Convex Finance, a platform built to boost rewards for CRV stakers and liquidity providers alike, all in a simple and easy to use interface. Convex aims to simplify staking on Curve, as well as the CRV-locking system with the help of its native fee-earning token: CVX.

If you’ve ever been a Curve LP, you know it is somewhat non-trivial to maximize your boost by depositing/maintaining your veCRV balance. If you’ve never been a Curve LP, it may be intimidating to do so without being a DeFi power user. Convex aims to make this process easy and bring the CRV boost ecosystem to everyone.

Liquidity providers earn trading fees and claim boosted CRV without locking CRV themselves. Convex has no deposit or withdrawal fees, and a low performance fee, which is distributed to CRV stakers and CVX token holders.

Solution: Integrate Convex under the savings button in the entry page.
The savings page will list all savings options provided by AAVE, Compound, YFI ,etc and include both stablecoin savings and non-stable token savings (staking/farming etc).

See our mock design in the link, does not need to be 1 to 1 but should follow the flow
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/TwitterV1?node-id=17600%3A374185

_The Entry Page_
![image](https://user-images.githubusercontent.com/94482490/156705809-69a8db28-c405-4f8e-98bb-bd5b3f3b2a59.png)

_The Savings Page_

![image](https://user-images.githubusercontent.com/94482490/156705921-223200df-d2a1-432a-88bf-b487bf238184.png)

_The Supply Page_

![image](https://user-images.githubusercontent.com/94482490/156705958-50795522-8927-48ef-aaf6-5e75e762b3f6.png)

_Convex Convert and Stake Page_

<img width="1190" alt="Screen Shot 2022-03-04 at 12 44 08 AM" src="https://user-images.githubusercontent.com/94482490/156706741-da8f40b4-e457-4a03-90f2-392830e41021.png">

Please condense the Convex info into the existing design. Please talk to us about ideas regarding design.

Required Verbiage to help spread the word: "I just deposited xxx dollars into xxx. Will I make money this week?"

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://docs.convexfinance.com/convexfinance/
- https://github.com/convex-eth/platform

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Convex discord server: https://discord.com/invite/uAwvZfs9qU

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5779  so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
@LindaMask I'm working on this
