### ISSUE TITLE
[Bounty] Integrate MDEX, A Trading Platform used for AMM Technology for Swap Pools into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5796]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks 
- Bounty Size
  - [x] 1000 USDC or $MASK equivalent 

## Part 1: Problem Description
**Background** MDEX, an acronym to Mandala Exchange, is a leading decentralized exchange protocol built on the Huobi chain. A trading platform using the automated market maker technology for fund pools.

It is part of MDEX plan to build a creative DEX, DAO, and IMO/ICO on ETH and Heco. This is to provide a configuration and asset selection that is more reliable and safe for users.

It uses a mixed or dual mechanism in its mining operations which are, transaction and liquidity mechanisms. Similar to other Cryptocurrencies, MDEX tokens (MDX) can be used for various purposes, including; serving as a medium for trading, voting, repurchase, and fundraising, among others.

**Solution** Create a plugin that integrates  MDEX on BSC and ETH into Mask. The UI should be identical to other swaps. 

![image](https://user-images.githubusercontent.com/94482490/156946339-5a9f8e59-0d97-4d8b-962d-d830d9fc6448.png)

![image](https://user-images.githubusercontent.com/94482490/156946348-0ed4afc4-808f-491d-905d-87250b12610e.png)

_MDEX Swap Page_
<img width="775" alt="Screen Shot 2022-03-06 at 6 14 00 PM" src="https://user-images.githubusercontent.com/94482490/156946454-9456df0b-378a-40af-8df7-8f71c526831d.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://mdexdoc.gitbook.io/doc/
- https://github.com/mdexSwap
- https://bsc.mdex.com/#/swap?lang=en

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
MDEX Discord: https://discord.com/invite/3TYDPktjqC

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5796  so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
Hi @LindaMask you opened a bounty (https://github.com/DimensionDev/Maskbook/issues/5796) for Mdex exchange but I already opened a pull request with this integration here: https://github.com/DimensionDev/Maskbook/pull/5789

**Comment by developerfred** [comment]
I will open a separate pull request only with DEX

**Comment by LindaMask** [comment]
fixed by #5798
