### ISSUE TITLE
Notice: All Issues Here Must Be Within Current Milestone

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#58]
If not, should be moved to https://github.com/DimensionDev/Maskbook-Talks.

**Comment by Jack-Works** [comment]
Split issues and codebase into 2 repo will bring management chaos.

**Comment by neruthes** [comment]
> Split issues and codebase into 2 repo will bring management chaos.

We have seen enough maybe-next-year requests for features. They bring chaos.
