### ISSUE TITLE
[Bounty] Integrate Platypus, An Open-liquidity  Swap into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5801]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USDC or $MASK equivalent 

## Part 1: Problem Description
**Background** The Platypus Finance protocol is a single-side AMM (decentralized exchange) designed for exchanging stable cryptocurrencies (ERC20 tokens) on the Avalanche blockchain. 
The protocol is implemented as a set of smart contracts; designed to prioritize censorship resistance, security, self-custody and maximum capital efficiency. 
Platypus features single-token provision, eliminating impermanent loss risk for liquidity providers, and minimizing slippage for traders.

**Solution** Create a plugin that integrates Platypus into Mask. The UI should be identical to other swaps.

![image](https://user-images.githubusercontent.com/94482490/156971239-a4059757-350d-4c66-9bed-fe49413cb3aa.png)

![image](https://user-images.githubusercontent.com/94482490/156971250-76d5ed8d-5d82-4688-978a-0cfb7f9aaa39.png)

**Platypus Swap Page**

<img width="732" alt="Screen Shot 2022-03-07 at 12 05 06 AM" src="https://user-images.githubusercontent.com/94482490/156971355-39ab8335-5020-441d-a769-88ccd142ea3f.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://app.platypus.finance/swap
- https://docs.platypus.finance/platypus-finance-docs/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Platypus Discord: https://discord.com/invite/B6ThAvev2A

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5801  so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
@LindaMask I'd like to work on this issue
