### ISSUE TITLE
[Bounty] Integrate Pangolin Finance, A DEX on Avalanche into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5803]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USDC or $MASK equivalent 

## Part 1: Problem Description
**Background**  Pangolin is a decentralized exchange (DEX) which runs on Avalanche, uses the same automated market-making (AMM) model as Uniswap, features a native governance token called PNG that is fully community distributed and is capable of trading all tokens issued on Ethereum and Avalanche.

**Solution** Create a plugin that integrates Pangolin into Mask. The UI should be identical to other swaps

![image](https://user-images.githubusercontent.com/94482490/156975451-5feb4cb7-dc37-4059-94ae-84e9d42d9f8b.png)

![image](https://user-images.githubusercontent.com/94482490/156975459-6054cbca-a10b-48ca-a6d6-c40bf6d557ea.png)

_Pangolin Pool Page_
<img width="489" alt="Screen Shot 2022-03-07 at 12 46 45 AM" src="https://user-images.githubusercontent.com/94482490/156975796-192cab98-b9f0-4b32-b812-a8d18d404be3.png">

Please condense the info on Pangolin's pool page into the existing design. Please talk to us about ideas regarding design.

Required Verbiage to help spread the word: "I just deposited xxx dollars into xxx. Will I make money this week?"

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://app.pangolin.exchange/#/swap
- https://github.com/pangolindex

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Pangolin discord server: https://discord.com/invite/PARrDYYbfw

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5803 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
this dex is also already installed in the mask.  here is the pull request for its installation made by me https://github.com/DimensionDev/Maskbook/pull/5289

along with the network I installed the following dexs: 
- traderjoe, 
- pangolin and sushiswap
