### ISSUE TITLE
[Bounty] Integrate Solidex, A Protocol to Optimize Yield, Voting Power, and Liquidity Provisioning on Solidly.

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5821]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks 
- Bounty Size
  - [x] 1000 USDC or $MASK equivalent 

## Part 1: Problem Description
**Background** Solidex is a protocol to optimize yield, voting power, and liquidity provisioning on Solidly. Solidly is a decentralized exchange (AMM) where tokens may be swapped using liquidity provided by users. Those users earn SOLID emissions. Those who lock SOLID receive veSOLID and a higher share of SOLID rewards. veSOLID or vote escrowed SOLID, is a concept first introduced by Curve Finance which aims to reward long term users of a protocol. Those who hold veSOLID earn trading rewards from the protocol as well as voting power to direct SOLID emissions.

If you wish to lock SOLID, Solidex allows you to earn a larger share of trading fees and rewards, as well as a share of boosted SOLID emissions received by liquidity providers in exchange for you providing boost to the protocol.

If you wish to be a liquidity provider, Solidex means you can earn boosted SOLID rewards without having to lock SOLID for several years, as well as additional SEX rewards.

If you wish to maximize voting power and influence over SOLID emissions and gauges, Solidex ensures veSOLID is always max locked in order to maximize voting power. This influence is then controlled through the SEX token which can be locked for up to 16 weeks and earn additional rewards.

Solidex has no deposit or withdrawal fees and a minimal performance fee that is distributed to SOLID and SEX lockers in its entirety. 

**Solution**  See our mock design in the link, does not need to be 1 to 1 but should follow the flow
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/TwitterV1?node-id=17600%3A374185

_The Supply Page_ 

![image](https://user-images.githubusercontent.com/94482490/157125119-968747cb-5336-415a-ba7d-911d7af3374c.png)

_The Savings Page_ 

![image](https://user-images.githubusercontent.com/94482490/157125186-39b6ac2b-becd-4026-a976-dd5a3f058dc5.png)

_Solidex Pool Page_ 

<img width="1384" alt="Screen Shot 2022-03-07 at 5 01 43 PM" src="https://user-images.githubusercontent.com/94482490/157125389-3790b7ad-27c4-4e64-8c78-fd36bc1681c7.png">

Please condense the info on Solidex's pool page into the existing design. Please talk to us about ideas regarding design.

Required Verbiage to help spread the word: "I just deposited xxx dollars into xxx. Will I make money this week?"

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://solidexfinance.com/#/pools
- https://github.com/solidex-fantom/
- https://docs.solidexfinance.com/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Solidex Telegram: https://t.me/SolidexOfficial

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5821 so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by f8al3rr** [comment]
I'd like to work in this

**Comment by Tedko** [comment]
> I'd like to work in this 

Hi sorry- we decide to close this bounty for now. Pls take a look of all other opening bounties and welcome ur input!

**Comment by f8al3rr** [comment]
thanks for your reply, I requested to work on #5475
