### ISSUE TITLE
[Bounty] Integrate Pickle Finance, a Yield Aggregator on Moonbeam into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5828]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks 
- Bounty Size
  - [x] 1000 USDC or $MASK equivalent 

## Part 1: Problem Description
**Background**  Pickle Finance is a yield aggregator, auto-compounding users LP positions saving them time and money. The governance token PICKLE can be staked as DILL, to earn a share of the protocols revenues and boost users farm APY. 

**Solution**  Integrate Pickle  under the savings button in the entry page. The savings page will list all savings options provided by AAVE, Compound, YFI ,etc and include both stablecoin savings and non-stable token savings (staking/farming etc).

See our mock design in the link, does not need to be 1 to 1 but should follow the flow
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/TwitterV1?node-id=17600%3A374185

_The Supply Page_ 

![image](https://user-images.githubusercontent.com/94482490/157138936-5b44e881-d3a9-4395-bb7a-9aeffc7f330e.png)

_The Savings Page_ 

![image](https://user-images.githubusercontent.com/94482490/157138958-50529ec7-da59-4231-8652-fe6bc620d97c.png)

_Pickle Jars and Farm_ 

<img width="1201" alt="Screen Shot 2022-03-07 at 7 03 09 PM" src="https://user-images.githubusercontent.com/94482490/157139076-f9988a5c-68ab-4536-97aa-bced2a6afa12.png">

Please condense the info om Pickle's page into the existing design. Please talk to us about ideas regarding design.

Required Verbiage to help spread the word: "I just deposited xxx dollars into xxx. Will I make money this week?"

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://www.pickle.finance/
- https://docs.pickle.finance/
- https://github.com/pickle-finance/contracts

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Pickle discord server: https://discord.com/invite/uG6WhYkM8n

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5828  so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process. 

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by 3scava1i3r** [comment]
so in this bounty you only want pickle finance contracts from moonbeam to be added?

**Comment by Tedko** [comment]
> so in this bounty you only want pickle finance contracts from moonbeam to be added?
> 
> 

@3scava1i3r  hi there. Sorry due to the curr situation of Pickle finance etc. we will close this bounty for now. Pls refer to other cool bounties that are still open!

**Comment by LindaMask** [comment]
closed
