### ISSUE TITLE
[UI][Question] Confusing behavior by clicking 'opitions'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#59]
![Screen Shot 2019-06-28 at 14 07 38](https://user-images.githubusercontent.com/6687437/60321024-1cea7f00-99ae-11e9-8135-df4943de64f6.png)

We should have better interface for _opitions_

**Comment by Tedko** [comment]
Since we will have a step to step guide to teach user 'how to use maskbook', try to fix this first.

@Jack-Works FYI, the meetup is on July 5th 7pm -

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/60404888-6b329480-9bdf-11e9-9dd3-41d58c755565.png)

Use this as a temp solution.
