### ISSUE TITLE
[Bug] Twitter Token View

### ISSUE THREAD

**Issue by developerfred** [DimensionDev/Maskbook#5980]
### How to reproduce?

1. go to twitter and search to $COW
2.
3.

### What happened?

When I look for a token in the COW example, the platform must prioritise the token that has the highest liquidity to be displayed in the COW protocol case, currently it looks like this:

<img width="711" alt="Screenshot 2022-03-29 at 03 36 27" src="https://user-images.githubusercontent.com/57037080/160522305-48841713-1bc7-46ad-870a-7106734db071.png">

<img width="540" alt="Screenshot 2022-03-29 at 03 36 40" src="https://user-images.githubusercontent.com/57037080/160522319-a0c1e9cd-64c0-4e13-a696-2b3149e8514a.png">

It should be like this:
<img width="482" alt="Screenshot 2022-03-29 at 03 41 02" src="https://user-images.githubusercontent.com/57037080/160522331-7190cc5f-fa66-43fc-8a37-bda01c5e629e.png">

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment]
Any advice to sort those tokens?

**Comment by developerfred** [comment]
> Any advice to sort those tokens

Ranking position and marketcap in the last 24h are good filters
