### ISSUE TITLE
[UI][Question] Confusing interface on Dashboard

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#60]
![Screen Shot 2019-06-28 at 14 08 58](https://user-images.githubusercontent.com/6687437/60321095-5e7b2a00-99ae-11e9-83ac-2fcc6f2ce81c.png)

- the clickable area for **X** should not include 'Welcome to Maskbook' (@neruthes )
- Should able to detect that the user already installed and have pub/pri keypairs stored locally, and display user interface accordingly @Jack-Works

**Comment by Jack-Works** [comment]
For question 2, no it's impossible to detect if the user has keypair backup before.

Question 1 is already fixed in the master branch.
