### ISSUE TITLE
[Demand] Immersive profile connecting experience

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#600]
## Metadata

Field | Value
--- | ---
Previous Stage | #369
Figma Link | [figma.com/...](https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=2092%3A82)
Expected UX prototype due | 2020-01-03
Actual UX prototype release | -
Expected engineering due | N/A
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Generic Procedure
- Error Handling
- System States
- Relations with Existing Components

### Overview

This floating window will appear in the center of the viewport, and it is draggable. However, the drag-control area (AppBar) must always have at least a 50px*50px subarea visible in the viewport.

### Invocation

This floating window will be invoked automatically when certain conditions are satisfied:

- The value of `ForceDisplayImmersiveConnectProfileWindow` is `true`

### Step 1

<img width="463" alt="image" src="https://user-images.githubusercontent.com/2139261/71707084-eddf1b00-2ddf-11ea-9c02-1664bc74685a.png">

### Step 2

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2139261/71707083-e91a6700-2ddf-11ea-82ea-3a187d27b684.png">

Click "Next" to test if the setup is successful. If the public key is not found in the profile bio, show `Error 600.1` alert.

### Success Screen

<img width="474" alt="image" src="https://user-images.githubusercontent.com/2139261/71707177-7362cb00-2de0-11ea-8c0b-d88c7b079515.png">

When entering this screen, the database will be updated to record that the profile is connected to the persona.

By clicking "Done", the floating window shall be dismissed.

### Error 600.1: Setup Failure

<img width="707" alt="image" src="https://user-images.githubusercontent.com/2139261/71707293-0a2f8780-2de1-11ea-9152-362458548d47.png">

### Overview

Name | Type | Lifecycle | Scope
--- | --- | --- | ---
ActiveSetupSessions | Map\<SocialNetworkDomainName := PersonaIdentifier> | Permanent | Global
ForceDisplayImmersiveConnectProfileWindow | Bool | Browser Process | Global

### State: ActiveSetupSessions

When the user clicks "Connect ${SocialNetworkDomainName}" in component PersonaProfilesList, the value of `ActiveSetupSessions[SocialNetworkDomainName]` will be set as the identifier of the corresponding persona.

When the user successfully connects a profile to a persona, `ActiveSetupSessions` will lose the key `SocialNetworkDomainName` so that the value of `ActiveSetupSessions[SocialNetworkDomainName]` will become `undefined`.

### State: ForceDisplayImmersiveConnectProfileWindow

When the user clicks "Connect ${SocialNetworkDomainName}" in component PersonaProfilesList, the value of `ForceDisplayImmersiveConnectProfileWindow` will be set as `true`.

When an "ImmersiveConnectProfile" window is manually closed by the user by clicking Close button (in AppBar) or Done button (in Success Screen), the value of `ForceDisplayImmersiveConnectProfileWindow` will be set as `false`.

When a profile is successfully connected to a persona, the value of `ForceDisplayImmersiveConnectProfileWindow` will be set as `false`.

## Part 4: Relations with Existing Components

Before this, some components (embedded in webpages on social network websites) may prompt the user to continue the setup procedure, in a less modal-like way. These components will remind the user to setup when certain conditions are satisfied:

- A username is detected
- The currently detected username is not connected to any user-owned persona
- The value of `ActiveSetupSessions[SocialNetworkDomainName]` is a valid PersonaIdentifier
- Currently no "ImmersiveConnectProfile" window is being displayed in the scope of the current webpage.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/2139261/71708152-10286700-2de7-11ea-99b2-53d815b93bea.png">

https://www.figma.com/file/oFrOUZmDnOWL2pu6SNf4P7/Dashboard-v2?node-id=2093%3A11

By clicking "Resume", ImmersiveConnectProfile window will appear in the center of the viewport.

## Notes

- Max width of the "ImmersiveConnectProfile" window is 400px.
- This will not solve the problems with mobile initialization process. It remains to be solved with #409. 
- This will be replaced by #409 in future.

**Comment by Jack-Works** [comment]
do we really need the dialog 600.1? and it's better not to specify the implementation detail like system states I guess

**Comment by neruthes** [comment]
> better not to specify the implementation detail like system states I guess

Without specification how can I define the behaviors of a software? 🤔

**Comment by neruthes** [comment]
This PRD is mostly ready for delivery. Reviews are requested.

All reviews are expected to be addressed before 2019-01-06 MON 01:50 UTC.

cc @yisiliu @Jack-Works @SunriseFox @guanbinrui

**Comment by Tedko** [comment]
Request for comment from evans

**Comment by SunriseFox** [comment]
⚰️ :awsl: I agree with jack

**Comment by neruthes** [comment]
Discussion period ended. Removed draft status.

**Comment by Tedko** [comment]
Better response @jack & @sunrisefox ‘s comment and discuss with them 1st.

**Comment by neruthes** [comment]
Discussion summary:

Normal priority. Prepare for delays.

**Comment by SunriseFox** [comment]
As we are no longer requiring users to update their bio
+ Should the step of updating bio be updated?
+ Should success / error state of verifying bio be removed?

**Comment by neruthes** [comment]
I would advise everyone not to consider a total revolution of the basic communication mechanism at this moment. Any of such reforms should wait, till the design specification of existing mechanisms are well documented and robustly implemented.

In my estimation, we may investigate the motion of abolishing "public key in bio" around July.

**Comment by SunriseFox** [comment]
Unlink a persona from here requires some work. I have made some adjustments here #767 . If that's ok then let it be.

**Comment by Jack-Works** [comment]
@neruthes what's next

**Comment by neruthes** [comment]
> @neruthes what's next

Scheduled in M3. Avoid another postponing if possible.

**Comment by Tedko** [comment]
> @neruthes what's next

600 is almost done Right? We can ship what’s done for M3.

**Comment by Tedko** [comment]
> As we are no longer requiring users to update their bio
> 
> * Should the step of updating bio be updated?
> * Should success / error state of verifying bio be removed?

‘Add it for me’ functionalities (already delivered) is really good for UX. That part let’s definitely keep it as it.

**Comment by neruthes** [comment]
@SunriseFox You may ask me to explain how certain decisions were made if you find elaborate explanations helpful. I will introduce the reasoning behind them.

**Comment by neruthes** [comment]
Implemented when implementing #862.
