### ISSUE TITLE
[Demand]  add some common functions in @masknet package

### ISSUE THREAD

**Issue by Randolph314** [DimensionDev/Maskbook#6031]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
I am developing a plugin which need some common functions like
```
export function useLastRecognizedIdentity() {
    return useValueRef<SocialNetworkUI.CollectingCapabilities.IdentityResolved>(
        activatedSocialNetworkUI.collecting.identityProvider?.recognized || default_,
    )
}
export function useCurrentVisitingIdentity() {
    return useValueRef<SocialNetworkUI.CollectingCapabilities.IdentityResolved>(
        activatedSocialNetworkUI.collecting.currentVisitingIdentityProvider?.recognized || default_,
    )
}
```

## Part 2: Problem to Solve
add these functions into @masknet package

**Comment by Jack-Works** [comment]
Please don't do that. It should be provided via Plugin Context, instead of access them directly.

**Comment by Randolph314** [comment]
@Jack-Works I create a plugin file under `plugins`, how can I  acquire current persona and platform?

**Comment by Jack-Works** [comment]
Let me add it for you

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/162916210-347deeb9-0f1f-4481-b0ce-93e4608ed8ab.png)

See https://github.com/DimensionDev/Maskbook/pull/6064
