### ISSUE TITLE
[Request] Blacklist those users if we failed to find their public key

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#605]
If a user posts an encrypted post but their prove post does not exist or no longer exist, we will continue to look for their public key over and over again. So maybe we could blacklist them (at least for this session or for 1 day) to prevent this behavior.

**Comment by Tedko** [comment]
Good idea. Maintain a local blacklist? I guess we can set the Timeout for
like several minutes at least?

Ideally we can maintain that list in a P2P manner.

**Comment by neruthes** [comment]
Good time to restart the discussion of whether to suspend the support for proof post till pollution-resistance is operational.

**Comment by Tedko** [comment]
Not related to this issue

**Comment by Tedko** [comment]
We might need a keybase like solution (for fetch binding relationship) - in
a more p2p way

**Comment by yisiliu** [comment]
> We might need a keybase like solution (for fetch binding relationship) - in a more p2p way

You are talking about this: 
> Good time to restart the discussion of whether to suspend the support for proof post till pollution-resistance is operational.

**Comment by SunriseFox** [comment]
finding public key disabled by default kow
