### ISSUE TITLE
[Bug] : cannot import {useWeb3State} from '@masknet/plugin-infra' in plugins

### ISSUE THREAD

**Issue by Randolph314** [DimensionDev/Maskbook#6092]
### What happened?
<img width="1237" alt="截屏2022-04-17 14 31 05" src="https://user-images.githubusercontent.com/97870249/163703559-c6e7f5be-7c27-48a4-a8f2-4cf58a0ad28d.png">

`entry.ts`  in `@masknet/plugin-infra` lack of

```
export * from './web3'
```
### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Jack-Works** [comment]
Not a bug. You should import from '@masknet/plugin-infra/web3'
