### ISSUE TITLE
[Bug] Decrypted by Mask doesn’t work, Mask Network (dev) 2.6.0

### ISSUE THREAD

**Issue by mariiaSynoverska** [DimensionDev/Maskbook#6100]
### How to reproduce?

1. Go to some plugin
2. Create and post encrypted tweet
3. Go to tweet

### What happened
Decrypted by Mask doesn’t work, tweet's content doesn’t unavailable although Mask is installed.

### What should happen?
User should see Decrypted by Mask tweet.

## Environment
Dev environment, last version of develop branch, commit: https://github.com/DimensionDev/Maskbook/commit/e49cd5c0e54339ef602de598be62f7eb28ad7407

<img width="1742" alt="Screenshot 2022-04-18 at 11 14 46" src="https://user-images.githubusercontent.com/32291396/163794440-de83d91b-fee9-4466-bb38-aaa812c982f6.png">

### Mask Version:
- [ ] (Browser) Chrome Version 100.0.4896.75
- [ ] (Mask App) Installed from the local build. (`/dist`)
- [ ] Develop branch
- [ ] Build of version/commit hash: commit hash: e49cd5c0e54339ef602de598be62f7eb28ad7407

### System
- [ ] Mac OS X Catalina

### Platform/Browser

- [ ] Chrome Version 100.0.4896.75

https://user-images.githubusercontent.com/32291396/163794513-bcd41010-3d62-44d6-9a3a-1eb679143d03.mov

<img width="685" alt="Screenshot 2022-04-18 at 11 15 04" src="https://user-images.githubusercontent.com/32291396/163794526-5e99d8ae-7f8d-4533-961e-5d8bac3c7b14.png">
<img width="908" alt="Screenshot 2022-04-18 at 11 15 21" src="https://user-images.githubusercontent.com/32291396/163794531-4430cded-8c3f-42b5-8149-bf00a317e4c3.png">

<img width="1742" alt="Screenshot 2022-04-18 at 11 14 46" src="https://user-images.githubusercontent.com/32291396/163794506-8fc114ff-a562-4ce7-b5a5-5a76d1cc7378.png">

**Comment by Jack-Works** [comment]
Confirmed. Working on this
