### ISSUE TITLE
Remove `HashRouter` in the SNS Adaptor

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#6135]
Wait, this does not look right. Why you're adding `HashRouter` in the SNS Adaptor? That's definitely wrong.

_Originally posted by @Jack-Works in https://github.com/DimensionDev/Maskbook/pull/5986#discussion_r851869533_

cc @guanbinrui

**Comment by guanbinrui** [comment]
Already removed.

**Comment by Jack-Works** [comment]
Where? It still in the main branch
