### ISSUE TITLE
Problem occurring in Savings Plugin

### ISSUE THREAD

**Issue by badri001** [DimensionDev/Maskbook#6178]
## Bug Info
Savings plugin not showing any aave and lido stake values (Which were already there),
seems like a UI error 

### How to reproduce?

1. clone the repo ( commit  hash: dfc4f3b)
2. pnpm  install && start
3. reload the MaskBook Dev extension |or| load the MaskBook Dev extension

### What happened?
Not showing any Lido and Aave platforms Stake options.

### What should happen?
They should appear while Ethereum Network is chosen   
### Mask Version:

- [ no] (Browser) Installed from the extension store (version: MaskBook Dev)
- [ no] (App) Installed from the app store (version: )
- [ yes] master branch
- [ x ] Build of version/commit hash: [dfc4f3b](https://github.com/DimensionDev/Maskbook/commit/dfc4f3be96f0290d5f2020bdff2b39d52994777a)

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [x] Linux: Ubuntu

### Platform/Browser

 
- [x] Latest Chrome (stable channel) : 100.0.4896.127 (Official Build) (64-bit)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by Tedko** [comment]
@wenluomask same as the one i mentioned

**Comment by wenluomask** [comment]
Will be fixed in next version.
