### ISSUE TITLE
[Demand] locale-kit should not remove nesting keys

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#6221]
Nesting is a useful feature of `i18next`:  https://www.i18next.com/translation-function/nesting

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/1141198/167404433-542b3760-d50a-40fc-b2f7-abc1e28106e4.png">

Update the script to support nesting or disable it from commit hook.

**Comment by Jack-Works** [comment]
I suggest disable it 🤔 how do you think @septs

**Comment by septs** [comment]
accepted
