### ISSUE TITLE
[Bug] Unhandle getBackgroundColor error 

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#623]
# Bug Report

### System

- OS: macos mojave 
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version:
- Installation: Self-Complied
- Build Commit: 0f958ba2983232a2e644a98e3f710f91c05e98f6

## Bug Info

`getBackgroundColor` will run into error in firefox.

**Comment by Jack-Works** [comment]
maybe have a default color if the detection goes wrong

**Comment by guanbinrui** [comment]
> maybe have a default color if the detection goes wrong

It happens when `element?.style?.backgroundColor` return `''`. Set white as default color.
