### ISSUE TITLE
[Bug] Not ignoring pubkey-profile connection declarations when browsing any profile representing a public key which belongs to a persona whose private key is available in the local database

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#629]
# Bug Report

### System

- OS: -
- OS Version: -

### Browser

- Browser: -
- Browser Version: -

### Maskbook

- Maskbook Version: 1.9.0
- Installation: GitHub ZIP
- Build Commit: -

### Expected Behavior

Record friendship and profile metadata.

Ignore the public key.

### Actual Behavior

The public key is recorded into the database.

### How To Reproduce

Visit a profile which does not actually belong to a local persona but declares a public key whose owner is the local persona.

**Comment by Tedko** [comment]
👍

**Comment by neruthes** [comment]
Already fixed #aba0a826fe384f0ecbe3a8c990b3e62e4d157cb8

**Comment by Tedko** [comment]
How can the user fix their current DB if they accidentally record someone else
>a public key which belongs to a persona whose private key is available in the local database 

example for me:
<img width="808" alt="Screen Shot 2020-01-12 at 01 09 07" src="https://user-images.githubusercontent.com/6687437/72207943-32ea0800-34d8-11ea-90d3-2b1eeea765cb.png">

**Comment by Tedko** [comment]
Is this feature delivered in 1.9.2?

**Comment by SunriseFox** [comment]
@Tedko this fix came with 1.9.0, but it has nothing to do with previously wrongly auto-connected identities(i.e. bad records in the database). You may manually disconnect them or delete them. They will not appear again next time.

**Comment by Tedko** [comment]
> @Tedko this fix came with 1.9.0, but it has nothing to do with previously wrongly auto-connected identities(i.e. bad records in the database). You may manually disconnect them or delete them. They will not appear again next time.

Seems like even on v1.9.2 I will still be affected by this issue. Already rm'ed bad records.

**Comment by Tedko** [comment]
Umm, 😐 I cant reproduce this bug. Seems like its fixed already.
