### ISSUE TITLE
[Bug] Maskbook Database Restore Failed

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#638]
# Bug Report

### System

- OS: OSX Latest
- OS Version:

### Browser

- Browser: Chrome Lateste stable ver
- Browser Version:

### Maskbook

- Maskbook Version: 1.9.2
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */ store
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info
<img width="1403" alt="Screen Shot 2020-01-11 at 23 42 07" src="https://user-images.githubusercontent.com/6687437/72207778-f7027300-34d6-11ea-93ff-95ffa34d78d7.png">

https://dimension.chat/group/maskbook?msg=m2jQFd9CjnicqvsqZ

(Video Below)
https://chat.dimension.hk/group/maskbook?msg=LfZxGhLH8Wt8T2psJ

### Expected Behavior

Import successfully.

/* Write the expected behavior here. */

### Actual Behavior

Import failed. See the video.

/* Write the actual behavior here. */

### How To Reproduce

See the video.

**Comment by SunriseFox** [comment]
closed by #643
