### ISSUE TITLE
[Bug] Cannot select recipients as a new user

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#639]
# Bug Report

### System

- OS: -
- OS Version: -

### Browser

- Browser: -
- Browser Version: -

### Maskbook

- Maskbook Version: 1.9.2
- Installation: Store

### Expected Behavior

Should be able to select recipients in composition modal.

### Actual Behavior

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2139261/72232814-6f426480-35bb-11ea-9ff6-48747f6e57ec.png">

Cannot select recipients.

### How To Reproduce

Initialize and have 0 non-self record of profile connection witness in the database.

**Comment by neruthes** [comment]
3 days till 2020-01-24. Expedition requested. cc @guanbinrui

**Comment by neruthes** [comment]
Postponed to a later milestone.

**Comment by SunriseFox** [comment]
This relies on some low-level adjustments. I'll work on this.

**Comment by Tedko** [comment]
For the twitter version now you can select on everyone and me.
But the detection for friends are now working very well
