### ISSUE TITLE
[Demand] Backup Alert

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#645]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- Alert UI
- Conditions of Appearance
- Future Improvements

## Part 1: Alert UI

<img width="708" alt="image" src="https://user-images.githubusercontent.com/2139261/72429169-3656eb00-3787-11ea-9a8e-2b5717f6075b.png">

## Notes

- None.

**Comment by Jack-Works** [comment]
A Notification is better.

**Comment by neruthes** [comment]
> A Notification is better.

It belongs to another issue.

**Comment by Jack-Works** [comment]
I'm suggesting a replacement of this demand so it should not belong to another issue

**Comment by neruthes** [comment]
> I'm suggesting a replacement of this demand so it should not belong to another issue

Creating this issue does not necessarily mandate that this feature should be implemented. This is created for recording purposes.

**Comment by septs** [comment]
@neruthes reset "Backup Alert" condition, after "Import Backup"?

**Comment by neruthes** [comment]
> @neruthes reset "Backup Alert" condition, after "Import Backup"?

This should be included.

**Comment by Tedko** [comment]
@OiCkilL ideas? 

Also its time to consider this

**Comment by OiCkilL** [comment]
Different color in different circumstance.
Red: error
Yellow: warning
Green: successful
Blue or white: general
So, We can use yellow when it must be backup, and use a white or blue background for the first backup.

**Comment by Tedko** [comment]
good point about color
