### ISSUE TITLE
[Demand] Implement "Everyone" in recipients selection section of Twitter composing modal

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#648]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | -
Expected UX prototype due | -
Actual UX prototype release | -
Expected engineering due | 2020-01-22
Corresponding Pull Request | -
Completion Version | -

## Content

Previously defined in #412, but not implemented. Now it may be the good time to implement it.

## Notes

- None.

**Comment by guanbinrui** [comment]
Implemented in #672
