### ISSUE TITLE
[Bug] Incorrect behavior of Advance Recipients Selection chip in Twitter composing modal

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#649]
# Bug Report

### Maskbook

- Maskbook Version: 1.9.2
- Installation: Store

### Expected Behavior

See #397.

The chip should be hidden when debug mode is false.

### Actual Behavior

<img width="962" alt="image" src="https://user-images.githubusercontent.com/2139261/72585400-da56a880-38e5-11ea-81f4-198599b8ffc2.png">

It is visible when debug mode is false.

### How To Reproduce

N/A.

**Comment by Jack-Works** [comment]
closed by 4b737f1f365cb4b28dbe212b902d97c6a1142ced
