### ISSUE TITLE
[Task] Specify when a new tab will be opened to fetch data

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#652]
## Metadata

Field | Value
--- | ---
Parent Task/Demand | N/A
Expected Delivery Date | 2020-01-17

## Content

Elaborate the behavior, please.

**Comment by SunriseFox** [comment]
+ When we find an encrypted post that doesn't come with a public key, and we don't know its public key, we open both profile page and post page (if exists) (at most 10 times) to find its public key.

**Comment by neruthes** [comment]
GJ 👍🏻
