### ISSUE TITLE
[Demand] Scheduling Revamp

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#656]
## Metadata

Field | Value
--- | ---
Previous Stage | N/A
Figma Link | [figma.com/...](___)
Expected engineering due | 2020-01-22 (WED)
Corresponding Pull Request | -
Completion Version | -

## Content

Here we shall design a new scheduling mechanism to avoid opening too many sessions simultaneously.

<img width="1440" alt="Screen Shot 2020-01-19 at 06 05 22" src="https://user-images.githubusercontent.com/2139261/72675840-32c2ad00-3a82-11ea-94f2-b29654ff0737.png">

## Notes

- None.

**Comment by neruthes** [comment]
## Session Amount Control (SAC)

Total active sessions should be limited.

Probably `4` is a good choice.

## Page Frequency Control (PFC)

The frequency of a page being visited should be limited. A page should not be visited again if it has been visited in the past X seconds.

Probably `300` is a good choice.

**Comment by neruthes** [comment]
Postponed to a later milestone.

**Comment by yisiliu** [comment]
This is a truly useful direction to optimize. However, we should not just limit to this method. Let's discuss it next Monday then.

**Comment by neruthes** [comment]
Good

**Comment by Jack-Works** [comment]
Now only old payload will open a new window. we can switch the settings `disableOpenNewTabInBackgroundSettings` from false to true and wait for community feedback

**Comment by neruthes** [comment]
@Jack-Works Would you like to document the mechanism of background task scheduling?
