### ISSUE TITLE
[Astar] Request to deploy contracts on [BalanceChecker]

### ISSUE THREAD

**Issue by developerfred** [DimensionDev/Maskbook#6645]
Request to depoly contracts on .

## Chain Info

https://chainlist.org/chain/592

## Checklist

The following contracts are requested.

- [x] + BalanceChecker 
- [x] + Multicall
- [x] + UniswapInterfaceMulticall

**Comment by guanbinrui** [comment]
@DimensionDev/dev-smartcontract

**Comment by SpaceStation09** [comment]
These contracts have already been deployed on Astar. You could check the contract address at <https://github.com/DimensionDev/misc_smart_contract#balancechecker-uniswapinterfacemulticall--multicall>

**Comment by developerfred** [comment]
@SpaceStation09 can you give me the addresses i don't have access to the repository

**Comment by SpaceStation09** [comment]
> @SpaceStation09 can you give me the addresses i don't have access to the repository

BalanceChecker: [`0x70553bBeC6F7d2C5e6E1Bc02f821F6863546D11e`](https://blockscout.com/astar/address/0x70553bBeC6F7d2C5e6E1Bc02f821F6863546D11e);
UniswapInterfaceMulticall: [`0x1410304B91a280ad083196B0B50e9d8df749d860`](https://blockscout.com/astar/address/0x1410304B91a280ad083196B0B50e9d8df749d860);
Multicall: [`0x906DaD0a02D3EDd26207CF06168449ee66650c20`](https://blockscout.com/astar/address/0x906DaD0a02D3EDd26207CF06168449ee66650c20);

**Comment by developerfred** [comment]
> > @SpaceStation09 can you give me the addresses i don't have access to the repository
> 
> BalanceChecker: [`0x70553bBeC6F7d2C5e6E1Bc02f821F6863546D11e`](https://blockscout.com/astar/address/0x70553bBeC6F7d2C5e6E1Bc02f821F6863546D11e); UniswapInterfaceMulticall: [`0x1410304B91a280ad083196B0B50e9d8df749d860`](https://blockscout.com/astar/address/0x1410304B91a280ad083196B0B50e9d8df749d860); Multicall: [`0x906DaD0a02D3EDd26207CF06168449ee66650c20`](https://blockscout.com/astar/address/0x906DaD0a02D3EDd26207CF06168449ee66650c20);

thanks
