### ISSUE TITLE
[Demand] Screen capture for bug report

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#6670]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other
  - /_List it here_/

## Part 1: Introduction and Background

Hard to identify bugs like https://github.com/DimensionDev/Maskbook/issues/6669

## Part 2: Problem to Solve

Provide an option to take a screenshot.

https://developer.chrome.com/docs/extensions/reference/tabCapture/

**Comment by Jack-Works** [comment]
It requires the `tabCapture` permission 🤔
