### ISSUE TITLE
[Bug] Should not be able to select specific friends as recipients when debug mode is false

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#673]
# Bug Report

### Maskbook

- Maskbook Version: 1.9.2
- Installation: CircleCI

### Expected Behavior

#397

### Actual Behavior

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/2139261/72773878-81965100-3c00-11ea-867a-1a3e5d3a5354.png">

### How To Reproduce

N/A.

**Comment by neruthes** [comment]
3 days till 2020-01-24. Expedition requested. cc @guanbinrui

**Comment by neruthes** [comment]
Postponed to a later milestone.

**Comment by Tedko** [comment]
Without this functionality user wont be able to know who's the recipient - and it's a quiet common usage to only send to 1-2 people (virtual group? but too early for this)
Also Debug is for devs, this part should be not put into debug.

**Comment by Tedko** [comment]
<img width="380" alt="Screen Shot 2020-02-12 at 18 50 53" src="https://user-images.githubusercontent.com/6687437/74393926-a4afbd00-4dc8-11ea-8736-902933321993.png">
