### ISSUE TITLE
[Demand] Revamp: Recipients Options for Twitter

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#676]
## Metadata

Field | Value
--- | ---
Previous Stage | -
Expected UX prototype due | -
Actual UX prototype release | -
Expected engineering due | 2020-01-24
Corresponding Pull Request | -
Completion Version | -

## Abstract

This issue documents an update on the previously ratified #412 documentation.

## Background

- https://github.com/DimensionDev/Maskbook/wiki/UserGroup-Abstraction-Model
- #397
- #412

## Definition

Type|Description|Data-Exchange Group ID (DEGID)|Internal Group Identifier (IGI)
---|---|---|---
Virtual Group|Everyone on `twitter.com`|`twitter.com::*`
Virtual Group|Followers of Alice|`twitter.com::{ username_alice }>>>FR`|`group:twitter.com/{ username_alice }/followers`
Virtual Group|Followed by Alice|`twitter.com::{ username_alice }>>>FG`|`group:twitter.com/{ username_alice }/followings`
Virtual Group|FR∩FG|`twitter.com::{ username_alice }>>>F0`|`group:twitter.com/{ username_alice }/friends`
Virtual Group|Myself|`twitter.com::{ username_alice}>>>ME`|`group:twitter.com/{ username_alice }/ME`

## UI Display

All options must follow the order as specified in this list.

### en-US

- Friends
- Followers of ${profile.nickname}
- Followed by ${profile.nickname}
- Everyone
- Myself

### zh-Hant

- 互粉好友
- ${profile.nickname} 的關注者
- ${profile.nickname} 關注的人
- 任何人
- 我自己

## Notes

- Related: #638.
- Related: #648.
- Related: #673.

**Comment by neruthes** [comment]
Postponed to a later milestone.

**Comment by Jack-Works** [comment]
@guanbinrui what's the difference between current impl and this demand?

**Comment by guanbinrui** [comment]
> @guanbinrui what's the difference between current impl and this demand?

Group names should be changed in current impl.
