### ISSUE TITLE
[Discussion] Let's find the most graceful way to manage multiple devices

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#68]
# Background

In recent months we have proposed a few different ideas on this:

- P2P keystore transfer over GUN
- Mnemonic words

Today I would like to bring another proposal which to some extent combines them together.

----------

# Interdevice Synchronization

## Basics

- Every device has its own device keypair.
- The to-be-authorized device presents its device public key (in whatever way).

### Initial Establishment

- Device 01 receives the device public key of device 02.
- Device 01 signs a certificate payload.
- Device 01 device sends the certificate to device 02 along with the device public key of device 01.
- The user, on device 02, confirms that the fingerprint is correct as displayed on the screen of device 01 and authorizes device 01 on device 02.
- Bidirectional synchronization established.

### Synchronizing More Than Two Devices

After completing the steps of *Initial Establishment*:

- Device 02 shall receive the device public keys of all other devices which device 01 previously authorized.

### Hardware-Specific Operation Rules

- Cameraful devices should always be the authorizer in the round 1.
- Cameraful devices can scan a cameraless device over QR.
- Cameraless devices can receive information over mnemonic words (round 1) and P2P network communication (round 2).

- Two cameraful devices: scan; P2P comm.
- A cameraful device and a cameraless one: scan; P2P comm.
- Two cameraless devices: type words; P2P comm.

### Disconnect Devices

We have two options here:

- Renouncing one device in the network is a right of every equal peer.
- One device may only quit the network and may not instruct other devices to kick some device away.

Both options may be reasonable in different ways. This will require more discussion.

## Imoto Trust Chain

Since D01 and D02 have established their misakanet, when a new imoto, D03, joins through D02, it has to present its certificate from D02 to convince D01 that D01 belongs to the same misakanet which D01 belongs to.

Therefore, we have the concept of trust chain. Each of D01 and D02 generates a tree of device trusthood, in which it is the root node. Without any premade network communication, the certificate chain itself is enough to convince another device, whether it is in the same tree or in the other tree, that they belong to the same misakanet.

### Anonymity of Devices

Only a few ending bits of the digest of the device public key shall be used as inbox identifier. This will make tracking relations between device keys less possible.

**Comment by yisiliu** [comment]
**Disconnect Devices** is a little bit tricky here. We can probably do it in PGP way.

**Comment by neruthes** [comment]
Let's take the metaphor of Misaka network. One Misaka may leave the Misaka network which she lives in and create a new one, but cannot instruct the whole network to remove another Misaka. If the whole network is about to implement removal of member, there must be a consensus mechanism, which seems to be an overkill in our scenario.

**Comment by yisiliu** [comment]
One may have multiple Misakas in Misaka network and so does DWeb. Let's not consider any removal consensus mechanism here. One may delete their stuff at their own wish only. One good word to describe multiple identities is persona. The only thing that matters is the ownership.

**Comment by neruthes** [comment]
Since there has been no further discussion for a season, we will follow the path of Misakanet.
