### ISSUE TITLE
[Demand] Delete everything about proof post

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#683]
## Metadata

Field | Value
--- | ---
Previous Stage | N/A
Figma Link | N/A
Expected UX prototype due | -
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Content

Delete everything about proof post.

## Notes

- None.

**Comment by Jack-Works** [comment]
Currently, users can not see words like "verify by proof post"

**Comment by neruthes** [comment]
> Currently, users can not see words like "verify by proof post"

Will Maskbook installations try to find a proof post in any condition?

**Comment by neruthes** [comment]
The behavior of proof post retrieval has reportedly changed in the last month. So probably, this issue may be marked done? 🤔

**Comment by Tedko** [comment]
Let’s Wait until we finished the fb UX update.

**Comment by Jack-Works** [comment]
> The behavior of proof post retrieval has reportedly changed in the last month. So probably, this issue may be marked done? 🤔

Now proof post does not request and embedded into every post user posted.
But the old proof post is still recognized by Maskbook and if Maskbook find an old version payload (which have no proof post embedded) it will try to find the proof post.

**Comment by neruthes** [comment]
Discussion summary:

Only the users who intend to decrypt ancient posts will interoperate with proof posts. We can safely assume that proof post will no longer bother anyone.
