### ISSUE TITLE
[Bug] A connected profile is considered not connected

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#686]
# Bug Report

### System

- OS: -
- OS Version: -

### Browser

- Browser: Chrome
- Browser Version: -

### Maskbook

- Maskbook Version: 1.9.2
- Installation: -

## Bug Info

See #452.

## Notes

- @Tedko recently reproduced #452.
- @SunriseFox insists that this a different bug and should be tracked with a separate issue.

**Comment by Jack-Works** [comment]
closed by d10fb3f1
