### ISSUE TITLE
[Task] Migrate to yarn 2

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#696]
https://next.yarnpkg.com/advanced/migration

**Comment by Jack-Works** [comment]
https://github.com/yarnpkg/berry/tree/master/packages/plugin-typescript

**Comment by Jack-Works** [comment]
I have studied about upgrading to yarn 2. Strongly not recommend to upgrade now. Problems include: PnP

**Comment by septs** [comment]
@Jack-Works The task canceled?

**Comment by Jack-Works** [comment]
Low priority.

**Comment by Jack-Works** [comment]
If we must drop yarn 1, maybe we should switch to npm instead of yarn 2

**Comment by Tedko** [comment]
Go ahead. npm LGTM
