### ISSUE TITLE
[Task] Validate JSON with custom json-schema

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#7067]
## Introduction and Background

To validate json files in `packages/web3-constants/evm/`.

## Content

Some tools might be useful

- https://json-schema.org/understanding-json-schema/index.html
- https://github.com/vega/ts-json-schema-generator
- https://github.com/StefanTerdell/zod-to-json-schema

**Comment by Jack-Works** [comment]
Note: we're currently using https://www.npmjs.com/package/z-schema to validate JSON schemas in runtime.
