### ISSUE TITLE
[Bug] UX bug when claim red packet with multiple wallet 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#713]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version: latest store
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info
https://dimension.chat/group/maskbook?msg=9NpA4WXWJveFXFT9k

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce
Claim a red packet *(with multiple wallet in Maskbook)

/* Specify how it may be produced here. */

**Comment by SunriseFox** [comment]
Need to talk if we could:
+ set a wallet as default and use it to claim / send by default

**Comment by Tedko** [comment]
I think Jack said it’s doable before

**Comment by Jack-Works** [comment]
Able to do. but only for v1.10.0+ user

**Comment by neruthes** [comment]
FYI https://github.com/DimensionDev/Maskbook-Talks/issues/20 if anyone need

**Comment by SunriseFox** [comment]
I am talking about `set as default` not `default`.

**Comment by Tedko** [comment]
> I am talking about `set as default` not `default`.

Yes - @Jack-Works @neruthes 

With multiple wallet available, we can `set one as default`

But we can fix this bug 1st. just some display error

**Comment by neruthes** [comment]
Is "remember most recently used wallet" enough?

**Comment by SunriseFox** [comment]
> But we can fix this bug 1st. just some display error

Which display error? I didn't quite understand.

> Is "remember most recently used wallet" enough?

I mean, replacing the procedure that `a user has to select a wallet before claim a red packet` with that `a user can set their default wallet to claim red packer with no need to select it when claiming a red packet`.

**Comment by neruthes** [comment]
> I mean, replacing the procedure that `a user has to select a wallet before claim a red packet` with that `a user can set their default wallet to claim red packer with no need to select it when claiming a red packet`.

Ok. I got your point. Let us note this for future reference.

**Comment by Tedko** [comment]
is this fixed?

**Comment by Tedko** [comment]
Not fixed yet:
<img width="1398" alt="Screen Shot 2020-02-12 at 17 43 03" src="https://user-images.githubusercontent.com/6687437/74390664-361a3180-4dbf-11ea-9bc5-93766f61c60d.png">
<img width="1398" alt="Screen Shot 2020-02-12 at 17 43 09" src="https://user-images.githubusercontent.com/6687437/74390667-374b5e80-4dbf-11ea-92d2-908df355fbf3.png">

Try claim a red packet with multi wallet in Maskbook

**Comment by OiCkilL** [comment]
> Not fixed yet:
> <img alt="Screen Shot 2020-02-12 at 17 43 03" width="1398" src="https://user-images.githubusercontent.com/6687437/74390664-361a3180-4dbf-11ea-9bc5-93766f61c60d.png">
> <img alt="Screen Shot 2020-02-12 at 17 43 09" width="1398" src="https://user-images.githubusercontent.com/6687437/74390667-374b5e80-4dbf-11ea-92d2-908df355fbf3.png">
> 
> Try claim a red packet with multi wallet in Maskbook
> 
> Some selector error?

The sidebar highlight icon color may something wrong?

**Comment by Tedko** [comment]
> > Not fixed yet:
> > <img alt="Screen Shot 2020-02-12 at 17 43 03" width="1398" src="https://user-images.githubusercontent.com/6687437/74390664-361a3180-4dbf-11ea-9bc5-93766f61c60d.png">
> > <img alt="Screen Shot 2020-02-12 at 17 43 09" width="1398" src="https://user-images.githubusercontent.com/6687437/74390667-374b5e80-4dbf-11ea-92d2-908df355fbf3.png">
> > Try claim a red packet with multi wallet in Maskbook
> > Some selector error?
> 
> The sidebar highlight icon color may something wrong?

checkout the chat in rocket chat. It’s already fixed.

This is a front end problem Probably some selector error.
