### ISSUE TITLE
[Bug] Firefox reports Maskbook slowing Firefox down

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#723]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: Firefox
- Browser Version:

### Maskbook

- Maskbook Version: latest store ver(Mozilla)
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info

https://t.me/maskbook_group/6271

### Expected Behavior

Browser not reporting Maskbook slow the browser 
/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by guanbinrui** [comment]
Fixed by #726
