### ISSUE TITLE
[Bug] Twitter timeline is blocking

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#725]
# Bug Report

### System

- OS: MacOS 
- OS Version: Mojave 10.14.6

### Browser

- Browser: Google Chrome 
- Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.10.15
- Installation: Self-Complied
- Build Commit: fbbf2cbefdfcb72edc034143f0490c758ee0fe16

### How To Reproduce

```typescript
'Lori Hendry TEXT TRUMP TO 88022'.match(/((.+\s*)*)@(.+)/)
```

**Comment by Tedko** [comment]
Should be same issue for the Firefox one
