### ISSUE TITLE
Automatically retrieve public keys of friends from profile bio

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#74]
This feature should have been proposed and demanded a few months ago. Now let's record it. Hope someone may work on this soon! ([I:b])

**Comment by Jack-Works** [comment]
Don't we already have this feature yet?

**Comment by neruthes** [comment]
> Don't we already have this feature yet?

@Misaka-0x447f reported this problem to me.

@yisiliu told me this has been fixed.

Never mind.

But this gives good implications on how to handle similar situations.
