### ISSUE TITLE
[Task] Upgrade to TypeScript 3.8.0

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#740]
TypeScript 3.8.0 brings a group of amazing feature including

- New `export * as ns` Syntax
- Top-Level Await
- Private Fields
- `import type` syntax

Blocking by
- [x] ESLint support (https://github.com/typescript-eslint/typescript-eslint/issues/1436)
- [x] Prettier support (https://github.com/prettier/prettier/issues/7263)
- [x] TypeScript 3.8.0 final release (https://github.com/microsoft/TypeScript/issues/34898)

Tasks
- [x] Upgrade those packages
- [x] Switch all possible imports to `import type` syntax.

**Comment by septs** [comment]
@Jack-Works The week upgrade?

**Comment by Jack-Works** [comment]
> @Jack-Works The week upgrade?

No, we need to wait for prettier and eslint support new syntax
