### ISSUE TITLE
[Demand] ECCRP: Default wallet feature

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#742]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...

## Notes

- None.

**Comment by SunriseFox** [comment]
Is it something like this ok?
![image](https://user-images.githubusercontent.com/14029711/74316559-b5eece80-4db4-11ea-8346-1e7b2037f8fa.png)
![image](https://user-images.githubusercontent.com/14029711/74316600-cb63f880-4db4-11ea-8579-1f44f4f1e849.png)

**Comment by neruthes** [comment]
Nice idea. I think this should be enough for now; a good balance between usability and code complexity.

In addition, we should add a checkbox in [SelectWallet](https://www.figma.com/file/pOQaNCE3cmeA3mxrmUKHX9/Twitter-Red-Packet-Demo?node-id=315%3A119) modal. The checkbox is unselected by default. 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/2139261/74325524-afdefa80-4d80-11ea-9515-f89154247884.png">
