### ISSUE TITLE
[Bug] When a post is shared to everyone, user should not be able select/edit recipients later

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#745]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: chrome
- Browser Version:

### Maskbook

- Maskbook Version: store ver
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info
<img width="1398" alt="Screen Shot 2020-01-29 at 17 28 08" src="https://user-images.githubusercontent.com/6687437/74013932-2def6b80-4953-11ea-8243-c6f10555c044.png">

### Expected Behavior
When a post is shared to everyone, user should not be able select/edit recipients later; should have some place to indicate 'this is shared to everyone'
/* Write the expected behavior here. */

### Actual Behavior
For a post shared to everyone, user can still click and edit the recipients. see the pictures above.
/* Write the actual behavior here. */

### How To Reproduce
- post a tweet, shared with everyone;
- click and edit the recipients. 
/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Will consider designing an "edit post" feature, along with Post payload v4.

For now, we may simply change the text of the link to "Manage Recipients". Upon clicking, it will show a slightly different modal (600px * 400px for desktop), which only contains a list of profiles and nothing else.

```
┌────────────────────────────┐
│ X   Manage Recipients      │
├────────────────────────────┤
│ Shared to: Everyone        │
│ List of recipients:        │
│ (user1) (user2) (user3)    │
│ (another.profile)          │
│                            │
│                            │
│                            │
└────────────────────────────┘
```

**Comment by Jack-Works** [comment]
I need to notify you that the feature of "edit post" is not possible if the platform does not support post editing; and it will increase the complicity of codebase.

**Comment by neruthes** [comment]
Edit post will not come until saturation key retrieval mechanism and cooperative friendship discovery mechanism is implemented.

**Comment by Jack-Works** [comment]
Actually you can reuse the old key
