### ISSUE TITLE
[Bug] Unreliable implementation of Dashboard drawer header

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#759]
# Bug Report

### Maskbook

- Maskbook Version: 1.10.6
- Installation: Store

### Expected Behavior

Local asset.

Auto height.

### Actual Behavior

https://github.com/DimensionDev/Maskbook/blob/53ffcfd2666cf1e83e608ae724ed0fc0df7dba09/src/extension/options-page/Drawer.tsx#L62-L68

https://github.com/DimensionDev/Maskbook/blob/53ffcfd2666cf1e83e608ae724ed0fc0df7dba09/src/extension/options-page/Drawer.tsx#L94-L95

### How To Reproduce

N/A.

**Comment by SunriseFox** [comment]
#748
