### ISSUE TITLE
[Crash] TypeError: x.content[src_entry.je.Tips].filter is not a function

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#7629]
I went to others' twitter profile page, then Mask reports an error.

> x.content[src_entry.je.Tips].filter is not a function

Error stack:

<pre>
usePublicWallets/walletsFromCloud&lt;/tipWallets&lt;@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/chunk.5968.js:1599:123
usePublicWallets/walletsFromCloud&lt;@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/chunk.5968.js:1599:59
Ci@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:388:119
5578/exports.useMemo@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/7515.js:31:208
usePublicWallets@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/chunk.5968.js:1593:47
TipButton@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/chunk.5968.js:1723:43
Xh@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:376:137
dj@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:406:258
Wk@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:501:88
Vk@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:489:391
Uk@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:489:322
Jk@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:489:180
Ok@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:480:88
Hk@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/npm.react-dom.js:477:429
J@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/284.js:3069:204
R@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/js/284.js:3070:128
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:3283:12
run@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:3257:5
listener@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:3268:6
EventHandlerNonNull*@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:3306:5
__webpack_require__@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:48:30
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:3210:41
__webpack_require__@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:48:30
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:3200:20
__webpack_require__@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:48:30
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:137:20
__webpack_require__@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:48:30
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:112:18
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:115:10
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:4146:15
@moz-extension://1951e958-b355-4a40-b458-73ef486774a8/polyfill/ecmascript.js:4147:4
</pre>

## Build info
- Version: 2.11.3
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- BUILD_DATE: 2022-10-09T03:12:08.481Z
- VERSION: v1.29.12-2856-g62bac7ca4

## Git (*):

62bac7ca4 (HEAD)
https://github.com/DimensionDev/Maskbook

**Comment by guanbinrui** [comment]
Found this error might have the source from `packages/mask/src/plugins/Tips/hooks/usePublicWallets.ts` in v2.11.2.

```ts
    const walletsFromCloud = useMemo((): TipAccount[] | null => {
        if (!kv?.ok) return null
        const { proofs } = kv.val
        if (!proofs.length) return null
        const configuredTipsWallets = proofs.some((x) => x.content[PluginId.Tips])
        if (!configuredTipsWallets) return null

        const tipWallets = first(
            proofs.map((x) => x.content[PluginId.Tips]?.filter((y) => y.platform === NextIDPlatform.Ethereum)),
        )
        if (!tipWallets) return null
        return tipWallets
            .filter((x) => {
                if (nextIdWallets) {
                    // Sometimes, the wallet might get deleted from next.id
                    return x.isPublic && nextIdWallets.find((y) => isSameAddress(y.address, x.identity))
                } else {
                    return x.isPublic
                }
            })
            .map((x) => ({ address: x.identity, verified: true }))
    }, [kv, nextIdWallets])
```

**Comment by UncleBill** [comment]
Fixed by https://github.com/DimensionDev/Maskbook/pull/7645
