### ISSUE TITLE
[Crash] TypeError: bindings.find is not a function

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#7677]
I recovered backup  and then went to application board, then Mask reports an error.

> bindings.find is not a function

Error stack:

<pre>useTipsWalletsList/result<@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/chunk.114.js:820:43
useTipsWalletsList@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/chunk.114.js:817:31
TipsEntranceDialog@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/chunk.114.js:2020:36
Xh@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:376:137
dj@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:406:258
Wk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:501:88
Vk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:489:391
Uk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:489:322
Jk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:489:180
Ok@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:480:88
Hk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:477:429
J@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/284.js:3069:204
R@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/284.js:3070:128
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3283:12
run@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3257:5
listener@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3268:6
EventHandlerNonNull*@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3306:5
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3210:41
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3200:20
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:137:20
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:112:18
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:115:10
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:4146:15
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:4147:4
</pre>

## Build info
- Version: 2.11.3
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- BUILD_DATE: 2022-10-13T04:37:05.208Z
- VERSION: v1.29.12-2858-g459860840

## Git (*):

459860840 (hotfix/2.11.3)
https://github.com/DimensionDev/Maskbook

**Comment by UncleBill** [comment]
`bindings` here could be a non-array object.
https://github.com/DimensionDev/Maskbook/blob/4598608405bc9f95fe4222363e5150d11836624f/packages/mask/src/plugins/Tips/hooks/useTipsWalletsList.ts#L22-L26
