### ISSUE TITLE
Vulnerability Type : Click Jacking

### ISSUE THREAD

**Issue by raza234** [DimensionDev/Maskbook#7870]
Hi team, 

This time i found this vulnerability in your website: 
https://mask.io/

Clickjacking (User Interface redress attack, UI redress attack, UI redressing) is a malicious technique of tricking a Web user into clicking on something different from what the user perceives they are clicking on, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous web pages.

The server didn't return an X-Frame-Options header which means that this website could be at risk of a click-jacking attack. The X-Frame-Options HTTP response header can indicate whether a browser should be allowed to render a page in a <frame> or <iframe>. Sites can use this to avoid click-jacking attacks, ensuring that their content is not embedded into other sites.

This vulnerability affects the Web Server.

Here are the steps to reproduce the vulnerability:

1. open notepad and paste the following code.
<!DOCTYPE HTML>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>i Frame</title>
</head>
<body>
<h3>This is clickjacking vulnerable</h3>
<iframe src=" https://mask.io " frameborder="2 px" height="500px" width="500px"></iframe>
</body>
</html>

2.save it as <anyname>.html eg s.html

3. and just simply open that...

OR
Copy the link below and paste it into your updated browser (Chrome, Firefox).
[https://clickjacker.io/test?url=](https://clickjacker.io/test?url=https://mask.io/ .
As far as I know, this data is enough to prove that your site is vulnerable to Clickjacking
according to OWASP it's more than enough.

https://www.owasp.org/index.php/Testing_for_Clickjacking_(OWASP-CS-004) 

SOLUTION: 

https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet

Check this out and here is the solution for that.

I hope that you will fix this issue as soon as possible. Looking forward to hearing from you. Thank you

Sincerely,
Hassan Raza

**Comment by raza234** [comment]
Any Update on this??

**Comment by Jack-Works** [comment]
Can you explain what's the _real_ threat of this vulnerability? Mask.io does not include _any_ dynamic functionality, it is just an information-displaying website. Clicking anywhere is safe.

**Comment by raza234** [comment]
![image](https://user-images.githubusercontent.com/49674699/199925596-effeb2b9-204c-4fea-a9e6-7691a5c5dcca.png)

**Comment by raza234** [comment]
Clickjacking is an attack that tricks a user into clicking a webpage element that is invisible or disguised as another element. This can cause users to unwittingly download malware, visit malicious web pages, provide credentials or sensitive information, transfer money, or purchase products online.

**Comment by Jack-Works** [comment]
although I don't think there is any meaningful attack surface, adding an HTTP header/meta tag is easy.
cc @guanbinrui

**Comment by raza234** [comment]
Yes, this is easy when you add a header you should fix this vulnerability.
Any reward for me from your bounty program??

**Comment by raza234** [comment]
@guanbinrui Any Update on this?

**Comment by raza234** [comment]
Hello Team, 
Any Update on this from your side??

**Comment by Jack-Works** [comment]
I need to point out again, mask.io is a news website, it does not handle any user data. "Click hijacking" doesn't harm this website in any sense.

If this counts as a vulnerability, maybe you should also suggest we add [Cross-Origin-Opener-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) and [Cross-Origin-Embedder-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy) right?

Finally, thanks for your interest in our security!

**Comment by raza234** [comment]
Yes, you are right you should also add these. Any reward for me from your side?

**Comment by Jack-Works** [comment]
OK, let me be clear. This is not a vulnerability for us, therefore no reward.
