### ISSUE TITLE
[Bug] Use 'cannot' instead of 'can not'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#790]
# Bug Report

https://github.com/DimensionDev/Maskbook/blob/66161f09feec2160ef270484fca53776b9b03bd6/src/_locales/en/messages.json#L198

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Allocated for M3.

**Comment by Tedko** [comment]
Also please check other grammar issues.
