### ISSUE TITLE
[Demand] Add back post for ‘specific friends’ functionalities

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#791]
## Metadata

This should not be an advanced functionality. It’s already making user confused (no way to check who’s recipient or adjust recipient before post a tweet).

The previous version with ‘ (+ specific friend)’ works fine.

Field | Value
--- | ---
Previous Stage | ...
Figma Link | [figma.com/...](___)
Expected UX prototype due | YYYY-MM-DD
Actual UX prototype release | -
Expected engineering due | YYYY-MM-DD
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
Maskbook is not email. On Facebook, the user does not need to know who are his friends when composing a post which is set to be shared with "Friends". Friends are just Friends.

**Comment by Tedko** [comment]
> Maskbook is not email. On Facebook, the user does not need to know who are his friends when composing a post which is set to be shared with "Friends". Friends are just Friends.

Fb can post to specific group of people.

**Comment by Tedko** [comment]
![6EA1A6CB-1893-4A59-A0E0-40088C54503D](https://user-images.githubusercontent.com/6687437/75125725-570a3e80-566b-11ea-9c47-22d88c3cc440.png)

**Comment by neruthes** [comment]
Good argument. My considerations focus on the visual weight. This feature should not be too accessible. We will need more researches and consult the opinions of @OiCkilL before proceeding to any further conclusion. In the meantime, let the component be as it is right now.
