### ISSUE TITLE
[Task] Migrate to Jira (internal site)

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#807]
## Metadata

Field | Value
--- | ---
Parent Task/Demand | /* Issue Number*/
Expected Delivery Date | 2020-03-09

## Content

Plan:
1. M3 to M5, Clean up non-migratable tasks
2. M6, Use Jira replace GitHub milestone task management pattern

\* M-prefix, Milestone -> M
\* M3 = 2020-W09 
\* M4 = 2020-W10
\* M5 = 2020-W11
\* M6 = 2020-W12
\* non-migratable tasks, avoid cross-issue-tracker discussion.
**Tasks scheduled to be completed on GitHub need to be completed on GitHub**

**Comment by Tedko** [comment]
Tasks can still somewhat remains on Github but it has to be associated with Jira kanban  etc soon

**Comment by neruthes** [comment]
> Tasks can still somewhat remains on Github but it has to be associated with Jira kanban etc soon

The migration process will be taken care of well while you focus on your own priorities.

**Comment by yisiliu** [comment]
I will create a bridge to connect the issues.

**Comment by Tedko** [comment]
> I will create a bridge to connect the issues.

Do it :D

**Comment by neruthes** [comment]
Will need to do this again...

**Comment by septs** [comment]
https://www.atlassian.com/migration/journey-to-cloud

**Comment by septs** [comment]
Migrate Failed.
