### ISSUE TITLE
[Bug] native implemented BarcodeDetector cannot detect QR code as expected

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#810]
Tested on Chrome 82.0.4070.0 

Expected QR value, got `Error: DOMException: Invalid element or state.` at `scanner.current.detect(video.current)`

**Comment by Jack-Works** [comment]
It's expected. Back to when I implement it, this API on chrome is broken. And there is no need to fix it

**Comment by SunriseFox** [comment]
Maskbook is currently using the native BarcodeDetector in the latest chrome canary (with default flags)... So I wonder if this is eventually shipped, our QR scanning feature may break.

**Comment by Jack-Works** [comment]
Yes. Breaking on Chrome is expected. The main usage of QR scanning is on Firefox and Safari, those two platforms need QR. 🤔

**Comment by Tedko** [comment]
So I can’t transfer key into chrome ext through bar code?

**Comment by Tedko** [comment]
Also any idea of when chrome will fix this api?

**Comment by Jack-Works** [comment]
This is an experimental API so there is no guarantee for that. To fix that is simple : ignore the chrome built-in implementation but I prefer not to do that and wait for Chrome to fix that.

**Comment by Tedko** [comment]
Ok.

How about let’s make the chrome version don’t have this QR code
functionality? And wait chrome to fix it?

**Comment by neruthes** [comment]
Desktop editions do not need QR scanning before we start to work on Misakanet. Let it be as it is now till June.

**Comment by Jack-Works** [comment]
Now the polyfill has been enabled for Chrome either.
