### ISSUE TITLE
[Bug] Fb comment UX bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#811]
# Bug Report

This is an annoying bug. Better fix asap. See pics below.

### System

- OS:
- OS Version:

### Browser

- Browser: Chrome(chromium) latest
- Browser Version:

### Maskbook

- Maskbook Version: Chrome store latest
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

One comment/comment box only show up once

### Actual Behavior

<img width="1330" alt="Screen Shot 2020-02-26 at 12 11 42" src="https://user-images.githubusercontent.com/6687437/75383846-f0b33500-5891-11ea-9120-dc88841a8203.png">
<img width="1330" alt="Screen Shot 2020-02-26 at 12 12 25" src="https://user-images.githubusercontent.com/6687437/75383851-f4df5280-5891-11ea-9c55-4ccb6688949b.png">
<img width="1330" alt="Screen Shot 2020-02-26 at 12 05 43" src="https://user-images.githubusercontent.com/6687437/75383861-f872d980-5891-11ea-81ef-24fa42129078.png">
<img width="1552" alt="Screen Shot 2020-02-26 at 12 05 25" src="https://user-images.githubusercontent.com/6687437/75383873-fc9ef700-5891-11ea-9222-dd4f8b1f941e.png">

### How To Reproduce

Write a lot of comments (10+?) under one post with many different accounts.

**Comment by Tedko** [comment]
Hopefully this can be fixed within M3. If not lets do a hotfix after M3

**Comment by SunriseFox** [comment]
It happens when a nested comment is replied again. Possibly some problem related to holoflows-kit...

**Comment by Tedko** [comment]
@Jack 🤔

**Comment by Tedko** [comment]
@Jack-Works

**Comment by neruthes** [comment]
Looks like that we want to prioritize this.

Adjusted to P1.
