### ISSUE TITLE
[Bounty] Contribute to Next.ID via Educational Video Intros or Articles

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#8169]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [x] Educational
  - [x] Next.ID
  - [x] Mask Plugin
 ### 1. Action Items

Background: [Next.ID](http://next.id/) - Connect All Digital identities**

[Next.ID](http://next.id/), the world’s first protocol offering Decentralized-Identity-as-a-Service (DIaaS), is a decentralized identity aggregation protocol that integrates all Web2 and Web3 digital identities, offering a comprehensive and verifiable identity database for open-source developers and projects to innovate and build dApps on.

[Next.ID](http://next.id/) creates an identity infrastructure that securely aggregates users’ identities into Avatars, making it the primary touch point for interfacing with any app or dApp.

Operating as a DAO (Decentralized Autonomous Organization), [Next.ID](http://next.id/) would always be run by the community. In order to call for the awareness of self-sovereign digital identities and enrich the development ecosystem, we’d like to generate more user-facing educational content in the format of videos or articles to help the masses (developers and potential social graph projects) to better understand Next.ID and what we are building (must include task 1, you can choose any of the tasks listed in 2 - 5):

1. What is [Next.ID](http://next.id/)?
2. How can developers start building with [Next.ID](http://next.id/) and what should the community expect in the long run to win together with the growth of the protocol?
3. [Next.ID](http://next.id/) vs other DID protocols/projects: the difference and what makes Next.ID stand out uniquely.
4. The potential scope for a social-graph project to build upon/integrates with [Next.ID](http://next.id/).
5. What are the DID-related apps that can be built with [Next.ID](http://next.id/) and other identity / social graph infrastructure?

**Desired submissions (we’re selecting 3 winners from all submissions):**

1. Video introductions to [Next.ID](http://next.id/) (≥ 5 minutes, English, there is no need to show up faces)
2. Articles into [Next.ID](http://next.id/) ((≥ 800 words, English)

Don’t hesitate to reach out to us before you start so the content you create has a better chance to win!

**Prizes for Videos:**

- 1st place: 400 USD
- 2nd place: 300 USD
- 3nd place: 200 USD

**Prizes for Articles:**

- 1st place: 300 USD
- 1st place: 200 USD
- 1st place: 100 USD
++++
- Every participant who successfully makes a submission can get one OAT (on-chain achievement token) powered by Galxe! Collating certain amount of such OATs will get the hodlers to enjoy future benefits from the [Next.ID](http://next.id/) DAO.

### **Resources**

**Notion**
[https://nextid.notion.site/Next-ID-Home-0fb4ba9200d6458ab6c4fa81778f6a7b](https://www.notion.so/Next-ID-Home-0fb4ba9200d6458ab6c4fa81778f6a7b)

**Docs**
[https://docs.next.id/](https://docs.next.id/)

**GitHub**
[https://github.com/nextdotid/community](https://github.com/nextdotid/community)

**Twitter**
[https://twitter.com/nextdotid](https://twitter.com/nextdotid)

**Telegram**
[https://t.me/NextDotIDofficial](https://t.me/NextDotIDofficial)

**Discord**
[https://discord.gg/tepa9K7E55](https://discord.gg/tepa9K7E55)

### Contact and Support
**Telegram**
[Charles](https://t.me/Charles_12345)
[Linda](https://t.me/Lin_DAO)

**Comment by shubhiscoding** [comment]
Is it necessary to do both creating video and writing article or we could just either create a video or write and article?
