### ISSUE TITLE
Investigate why salt in posts become isolated nodes after 1 or 2 days

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#82]
In our GUN database, there are lots of isolated nodes, which were ought to be connected by maskbook->posts->[salt]. Such isolated nodes cannot be retrieved by `gun.get('maskbook').get('posts').get(salt)`. When trying to decrypt others' posts, `queryPostAESKey` always returns undefined, causing `service_not_share_target` to be displayed. We need to investigate it as soon as possible.

Behavior:

+ Posts that we can once decrypt becomes no longer decryptable after some time(?) / reinstall plugin(?).

Possible reason: 

+ Someone executed  `gun.get('maskbook').get('posts').get(salt).put(null)`
+ Gun stores it wrong or queries it wrong

Possible solution: 

+ Examine our code to ensure that we are not accidently putting null to the database
+ Upgrade GUN server to latest version
+ Disable putting null to database in case of bad guy

**Comment by Jack-Works** [comment]
@amark

**Comment by SunriseFox** [comment]
With some unreasonable analyses:

+ took one detached node **i7XpYYAw5+UlvL4yI9GnlA==** as an example
+ Searching the rad file, find its parent node is **jyr26jqr01aefvhRXetfZq5** 
+ Continue searching,  find that **jyr26jqr01aefvhRXetfZq5**‘s parent node is itself
+ **jyr26jqr01aefvhRXetfZq5** has a level 0 direct parent node **jyrzyme1WqUoCsJ7K2MU**
+ Analysing its children, find that this node contains all the orphan nodes in the database

Filter the nodes:

```javascript
let obj = await gun.get('jyrzyme1WqUoCsJ7K2MU').once().then()
let nodes = []
Object.keys(obj).forEach(async k => nodes.push(await gun.get('jyrzyme1WqUoCsJ7K2MU').get(k).once().then()))
// wait some time (that is confusing as some of the promises never resolve)
let posts = nodes.filter(i => Object.keys(i).some(k => k.endsWith('=='))).reduce((a, c) => ({...a, ...c}), {})
```

Then we got all the posts in the GUN.

**Comment by Jack-Works** [comment]
I have no idea why that happened.
It doesn't like we using gun in a wrong way

**Comment by Tedko** [comment]
Let’s ask @amark

**Comment by SunriseFox** [comment]
We've seen that the main obstacle that prevents us performing the database recovery and upgrading is that dot(`.`) is the seperator of the nodes in that version of GUN but in the latest version it uses `\0` instead, which causes the newer version of GUN can no longer read the data stored. 

Unfortunately, some users' facebook ID contain dot, So it is really hard to distinguish the seperator or the user ID. I think the loss is because GUN is confused too. 

Trying to restore the data manually but the recovery chance is minimal.

**Comment by SunriseFox** [comment]
Data recovery has finished. 551 detached posts and 114 users are connected and 4 orphan provePostIds are dropped. Maybe a fix of #69.

**Comment by amark** [comment]
@SunriseFox you are correct that we had to move away from `.` because it produced (rare) indeterminate query problems.

Was this the reason salts got separated? Or still investigating?

Will look over more of this GitHub as I'm trying to catch up from the weekend.

**Comment by SunriseFox** [comment]
I may discucss it in a further issue.

**Comment by amark** [comment]
@SunriseFox sounds good, let me know if you need help or anything.
