### ISSUE TITLE
[Bug] 'Select Specific friend' number not updated

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#831]
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version: 1.10.9
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

The number of 'Select Specific friend' should be the number of selected friends
### Actual Behavior

See pics:

<img width="1440" alt="Screen Shot 2020-03-02 at 17 29 46" src="https://user-images.githubusercontent.com/6687437/75736837-19349800-5cb3-11ea-8e4b-f01788f4d6a6.png">
<img width="1440" alt="Screen Shot 2020-03-02 at 17 29 55" src="https://user-images.githubusercontent.com/6687437/75736839-1afe5b80-5cb3-11ea-8ca7-30af57cd19cb.png">

### How To Reproduce

Try to send a post to 'Friends' - the 'Select Specific friend' number not updated (=0)

**Comment by guanbinrui** [comment]
The group members are not selectable in `Select Specific Friends Dialog` and not affect the total selected count.

**Comment by Tedko** [comment]
> The group members are not selectable in `Select Specific Friends Dialog` and not affect the total selected count.

I mean the number of selected should not be 0
