### ISSUE TITLE
[Bounty] 

### ISSUE THREAD

**Issue by wlanroot** [DimensionDev/Maskbook#8374]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [x] Mask Core Feature
  - [x] Mask Plugin
  - [x] Security/Cryptography Feature
  - [x] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] *PLACEHOLDER*
- Bounty Size
  - [x] *PLACEHOLDER*

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

**Comment by guanbinrui** [comment]
Please add more bounty information. I will close it for now.
