### ISSUE TITLE
[Demand] Proposal: Add some parameters to an Ethereum smart contract

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#859]
## Metadata

Field | Value
--- | ---
Previous Stage | N/A
Figma Link | N/A
Expected UX prototype due | N/A
Actual UX prototype release | N/A
Expected engineering due | 2020-03-14
Corresponding Pull Request | -
Completion Version | 1.10.10

## Proposal: Add some parameters to an Ethereum smart contract

We have experienced a couple of hotfix problems before especially when we were dealing with the red packet. I think part of the parameters in our extension, e.g. smart contract address and Infura api key, could be loaded to an Ethereum smart contract and each time we do the query, the extension would automatically check if the corresponding field on the smart contract has been changed. Reading state variables on Ethereum is free of charge so this won't cost us anything.

If you guys agree with this, we could start by curating a list of variables that could take this advantage.

**Comment by neruthes** [comment]
*Agree*

I think we do need this remotely-controlled feature activation list. With this, we will be able to enable and disable certain features to match certain campaigns. This practice has been commonly adopted; we do not risk inventing anything.

**Comment by neruthes** [comment]
Ref: #935

**Comment by Tedko** [comment]
parameters we can add to an Ethereum smart contract:

- Red Packet img url addr (so we can do hot patch); different img for different erc20 token?
- Img payload base img url addr 
- Fb/tw selector details

for urls we can also use ipfs through public gateway etc.

**Comment by Tedko** [comment]
Not Stale yet
