### ISSUE TITLE
[Bug] Cannot decrypt comments

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#863]
# Bug Report

### System

- OS: MacOS Mojave
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.10.9
- Installation: Self-Complied
- Build Commit: ce02294509cbbe24220a49b9963238746af55e1e

## Bug Info

Cannot decrypt comments.

**Comment by guanbinrui** [comment]
Related to #811.

**Comment by Tedko** [comment]
@guanbinrui lets release a hotfix version of this on chrome/ff store today

**Comment by guanbinrui** [comment]
> @guanbinrui lets release a hotfix version of this on chrome/ff store today

OK
