### ISSUE TITLE
[Bug] Firefox Android Maskbook not working for Twitter

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#867]
# Bug Report

<img width="535" alt="Screen Shot 2020-03-06 at 17 55 37" src="https://user-images.githubusercontent.com/6687437/76137459-09d68700-5ff2-11ea-8114-19eaa729b324.png">
<img width="562" alt="Screen Shot 2020-03-06 at 17 55 46" src="https://user-images.githubusercontent.com/6687437/76137460-0b07b400-5ff2-11ea-8b51-91e4aa3f17ae.png">

Report from Mindey.
On Firefox Desktop it works fine 

### System

- OS:
- OS Version:

### Browser

- Browser: Firefox Android
- Browser Version:

### Maskbook

- Maskbook Version: Latest ver on firefox store
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by guanbinrui** [comment]
![Uploading Screen Shot 2020-03-09 at 1.51.18 PM.png…]()


Add a Maskbook icon beside the 'More Options' button?

**Comment by guanbinrui** [comment]
> <img alt="Screen Shot 2020-03-09 at 1 51 18 PM" width="327" src="https://user-images.githubusercontent.com/52657989/76186438-4c27e000-620d-11ea-86cc-ac0fe3a18221.png">
> 
> Add a Maskbook icon beside the 'More Options' button?

<img width="328" alt="Screen Shot 2020-03-09 at 5 20 58 PM" src="https://user-images.githubusercontent.com/52657989/76199184-602e0a80-622a-11ea-8e90-c42983a15108.png">

**Comment by Tedko** [comment]
@mindey
