### ISSUE TITLE
Chain linter in all dev scripts

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#88]
consider https://microsoft.github.io/just/docs/doc-start.html
linter can be switched off in local

**Comment by SunriseFox** [comment]
If the linter could be switched on and off according the user's willing… we could just add something like npm or yarn script. If we need to lint, then run it, if we don't, then don't run it.

I think what we actually need is a filesystem monitor like yarn watch does, but lint the updated files instead. VS code's prettier plugin works well but it relies on a specific text editor. So… something like prettier-cli might help.

**Comment by Misaka-0x447f** [comment]
webstorm prettier plugin also works but sometimes we need some tool to ask contributor to install that. This is what I'm doing now.  
You cloned the project, you tried to contribute, but as a beginner you can't always do what you should to. So im going to config a linter that force you enable all other linter.

**Comment by Jack-Works** [comment]
Vscode has a project specified file that can suggest user install some
extensions for this project. Does webstorm has this too?

**Comment by Jack-Works** [comment]
Your script doesn't work on my environment

Ubuntu, yarn complains `Error: EACCES: permission denied, access '/usr/lib'` when installing global dependencies.

You run `npm i -g ` manually but I think someone(me) maybe want to use yarn instead, by the way, `yarn global add ...` works for me.

**Comment by SunriseFox** [comment]
> Your script doesn't work on my environment
> 
> Ubuntu, npm complains `Error: EACCES: permission denied, access '/usr/lib'` when installing global dependencies.
> 
> You run `npm i -g ` manually but I think someone(me) maybe want to use yarn instead, by the way, `yarn global add ...` works for me.

`npm` global install requires `root` permission to work. You may alter this by claim ownership of  node_modules folder by something like `sudo chown -R $(whoami) /usr/local/lib/node_modules`.

**Comment by Misaka-0x447f** [comment]
fixed, no global dep now
