### ISSUE TITLE
[Bug] Safari doesn't support BigInt

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#883]
The red packet feature relies on it. The red packet feature is temporarily disabled.

- Add a polyfill for it?
    - Requires rewrite code to support mathematical operation and store/restore to/from the indexed db

**Comment by guanbinrui** [comment]
Have we used the `n` suffix?

**Comment by yisiliu** [comment]
My suggestion is to adjust the precision to 15 since floor(log_10 (2^53-1))=15 as the fallback plan.

**Comment by Jack-Works** [comment]
> Have we used the `n` suffix?

Nope.

> TypeScript 3.2 brings type-checking for BigInts, as well as support for emitting BigInt literals when targeting esnext.

-- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint

But we need extra working on using a polyfill

**Comment by Jack-Works** [comment]
https://bugs.webkit.org/show_bug.cgi?id=179001

**Comment by septs** [comment]
@Jack-Works https://www.npmjs.com/package/bignumber.js

The library can replace `bigint`?

(bulit-in typescript definiton)

**Comment by Jack-Works** [comment]
> @Jack-Works https://www.npmjs.com/package/bignumber.js
> 
> The library can replace `bigint`?
> 
> (bulit-in typescript definiton)
> 

Looks good to me

**Comment by Tedko** [comment]
Let’s use it

**Comment by neruthes** [comment]
Also remember Number Precision Control Strategy.
 https://confluence.dimension.chat/display/~neruthes/2020/03/23/Number+Precision+Control+Strategy

**Comment by septs** [comment]
@neruthes This is just a switch implementation ([bigint](https://mdn.io/bigint) -> [bignumber.js](https://npmjs.com/bignumber.js))

**Comment by Jack-Works** [comment]
closed by https://github.com/DimensionDev/Maskbook/pull/915
