### ISSUE TITLE
[Demand] Unify the posting UX for Maskbook on twitter/fb

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#898]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

<img width="704" alt="Screen Shot 2020-03-17 at 17 54 22" src="https://user-images.githubusercontent.com/6687437/76844810-d1983980-6878-11ea-9408-0150e8706a93.png">
<img width="777" alt="Screen Shot 2020-03-17 at 17 54 36" src="https://user-images.githubusercontent.com/6687437/76844814-d2c96680-6878-11ea-8d61-b602c842a7a5.png">

Right now on Maskbook for twitter user can post encrypted post directly. This UX should be adopted by fb side as well.

**Comment by Tedko** [comment]
BTW now the twitter/fb mobile posting UX are pretty much the same.

**Comment by neruthes** [comment]
See #397 "Composing State Ephemerality Classification".
