### ISSUE TITLE
DOM Inserts Break Isolated Worlds

### ISSUE THREAD

**Issue by amark** [DimensionDev/Maskbook#9]
This was a tricky thing I struggled with.

Chrome offers Isolated Worlds for extensions to manipulate DOM without host knowing.

However, any DOM inserts/etc. can be witnessed by host.

This lets hosts fingerprint users for what extensions they are using, and also identify extensions.

So it is better to avoid any DOM inserts until necessary (for instance, decrypting*, and in your case, showing encryptor UI).

https://github.com/project-maskbook/Maskbook/blob/16c31b803a578888a91f48477a7dbc57a382d371/src/extension/injected-script/index.ts#L7

*it is vital that decryption is not inline or else host can scrape decrypted text after the fact, that is why I use an iframe which prevents them from scraping decryption, tho it is much harder to get the render right. Ultimately, DOM insert is inevitably going to occur, so this issue is kinda FUD, but I'll be following up by looking (or could you link?) at how decrypt is handled, cause that is much more serious.

And again, just making notes now while I have some time, keep focused on launching with the epic timing of all this crazy stuff going down.

**Comment by Jack-Works** [comment]
Yeah, there are risks where hosts can detect user are using extensions.
But after all, you need to post something encrypted to the social network so you must be using extensions.

To prevent users' encrypted text leaks here is some way to bypass this. For example, closed shadow root, or prevent input event bubbles in the capture parse. (We are not implemented that yet, here's some problem with our UI framework and shadow root)

**Comment by Jack-Works** [comment]
The injected script you're referencing seemed to be the only way to do this: maskbook needs to hack addEventListener to mock a paste event.

**Comment by amark** [comment]
Oh right, thats an even more obvious one hahahaha. Altho detecting at a server level versus a client level makes a small bit of difference.

Yeah, addEventListener is still Isolated World tho, so that is chill.

Should probably just rename this to focus on the decryption, since you are right, detecting extension is inevitable. Are you sure shadow DOM is safe? I don't think so, I think it is only safe when it isn't visible (aka, when it is shadow), but as soon as it gets rendered, it is getting added back into the real DOM and thus scrape-able. Canceling event bubbling might make it harder for them to "listen" for change, but a trivial setTimeout can get around that... especially since lots of them use React, every render trigger they have a diff to check.

**Comment by Jack-Works** [comment]
Yes, shadow root is safe when it is closed. If I attached a closed shadow root in a span element, in the outer world it just like an empty span.

**Comment by amark** [comment]
fascinating!!!! I'd love to use this myself, any links to tutorials on it?

**Comment by Jack-Works** [comment]
Just search shadow dom

**Comment by neruthes** [comment]
Just moving back to check if this issue should necessarily remain open any longer after 4 days of silence \*cough\*

**Comment by Jack-Works** [comment]
Note: Stay this open. We need to do shadow dom isolation in the future.

**Comment by Jack-Works** [comment]
Implemented in c381b4612d35e37e53b30db6f667826579203de2 and 6ffa8b3ed802f950967680f9850a46572d4fe660

cc @amark

**Comment by Tedko** [comment]
@amark we should better use this as a standard way and make it easy for other to implement this as well

**Comment by Jack-Works** [comment]
> @amark we should better use this as a standard way and make it easy for other to implement this as well

Yes. This function is provided by `DomProxy.beforeShadow` / `DomProxy.afterShadow` in @holoflows/kit now.
