### ISSUE TITLE
Replace puppeteer with playwright if it's better

### ISSUE THREAD

**Issue by Artoria2e5** [DimensionDev/Maskbook#901]
https://github.com/microsoft/playwright

**Comment by Artoria2e5** [comment]
wait a second... i did not tag this...

**Comment by guanbinrui** [comment]
Why it's better than pptr? I have written two stories with pptr.

**Comment by yisiliu** [comment]
https://dev.to/yashints/if-you-consider-puppeteer-cool-then-playwright-is-awesomeness-i5a
Playwright is made by the same team of Puppeteer.

**Comment by guanbinrui** [comment]
The APIs look similar to pptr's. Maybe we need this for running E2E testing on Firefox in case of some feature missing in [pptr for Firefox](https://aslushnikov.github.io/ispuppeteerfirefoxready/).

**Comment by yisiliu** [comment]
`The lessons learnt are incorporated into it, APIs are testing-friendly, and it will be a cloud native product. For example all the user agent/device emulation is setup consistently on an object called BrowserContext to enable multi-page scenarios, click waits for the element to be available and visible by default, there is a way to wait for network and other events, etc.`

Sounds good

**Comment by yisiliu** [comment]
I will close this issue first. 
When we finish all the tests, we will re-open this and consider moving our code to Playwright.
