### ISSUE TITLE
[Demand] Initialization Logic Minor Update

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#917]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Documentation | https://confluence.dimension.chat/pages/viewpage.action?pageId=2064444
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

### Logic Change

- If (any Persona already exists):
  - Maskbook deletes all existing Personas.

### Elaboration

The user may click the "Back" button and re-enter "Create Persona" screen. All existing Personas should be deleted when a new Persona is being created during Initialization.

## Notes

- None.

**Comment by Jack-Works** [comment]
Deleting any persona is a dangerous operation. We should never do it automatically without user confirmation.

**Comment by neruthes** [comment]
> Deleting any persona is a dangerous operation. We should never do it automatically without user confirmation.

The precondition of entering this screen is that the Persona has no Profile attached. No need to worry about it.

**Comment by Jack-Works** [comment]
> > Deleting any persona is a dangerous operation. We should never do it automatically without user confirmation.
> 
> The precondition of entering this screen is that the Persona has no Profile attached. No need to worry about it.

So what will happen if I have setup then disconnect a profile?

**Comment by guanbinrui** [comment]
> Deleting any persona is a dangerous operation. We should never do it automatically without user confirmation.

I agree. Better delete persona by the user only. Otherwise, the user may be confused.

**Comment by neruthes** [comment]
> > > Deleting any persona is a dangerous operation. We should never do it automatically without user confirmation.
> > 
> > 
> > The precondition of entering this screen is that the Persona has no Profile attached. No need to worry about it.
> 
> So what will happen if I have setup then disconnect a profile?

When reloading Dashboard, since there is 1 Persona in the database and the only Persona has no Profile, the macro state should be HalfInit. The user will see "Connect Profile" screen in Initialization story.

**Comment by neruthes** [comment]
Postponed indefinitely. Will continue this when a significant amount of users report confusion with too many Personas after initialization.

**Comment by septs** [comment]
Reference: https://github.com/DimensionDev/Maskbook-Talks/issues/30
