### ISSUE TITLE
[Bug] Maskbook Composition Textarea cannot capture keydown events

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#919]
# Bug Report

### Browser

- Browser: Chrome
- Browser Version: -

### Maskbook

- Maskbook Version: v1.10.8-78-gfd84b82a
- Installation: Store

### Expected Behavior

Hit keys to input.

### Actual Behavior

![Clipboard - March 27, 2020 8-12 AM](https://user-images.githubusercontent.com/2139261/77743697-608f1980-7010-11ea-9d49-986cb89ebce1.png)

### How To Reproduce

...

**Comment by Tedko** [comment]
been fixed already for a while. Chrome store ver haven’t update for 3 weeks.
