### ISSUE TITLE
[Bug] Potential non reproducible build for Firefox

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#920]
https://github.com/DimensionDev/Maskbook/blob/d2331704c2c786e4e18b930cd8e4edb76bf7ad16/webpack.config.js#L94

When the extension is submitted to the Firefox store, the source code does not contain a ".git" folder.
But when build on the CI, there is.

So the reviewer won't be able to build the same result as CI.

**Comment by Tedko** [comment]
We can write a comment to rivewer and let them know?

**Comment by septs** [comment]
```
VERSION: git.describe(), 
```

Then we cannot know if this code has been MODIFIED.
