### ISSUE TITLE
[Demand] Database Backup File Integrity

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#921]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Signature

Should sign the export with all Personas whose private keys are available.

## Verification

If verification fails, warn the user before merging the import.

Text for dialogue:

- Title:
  - en: Risky Backup File
  - zh: 备份文件有风险
- Body:
  - en: The backup file may be corrupted. Do you want to continue importing it with caution?
  - zh: 备份文件可能已被篡改，是否仍然要导入？

## Downgrade

There should be a downgrade management strategy. The old unsigned backup should be deprecated sometime later (suppose 2020 Oct 01). Before deprecation date, everything works as before. After deprecation date, the backups in the old format is treated as risky backup files.

## Notes

- None.

**Comment by septs** [comment]
based ndjson.org file formatter?

**Comment by neruthes** [comment]
I would like to leave the spec question open for implementers.

**Comment by septs** [comment]
Merge #645 to this feature?

**Comment by septs** [comment]
New backup file format:

1. The format based zip archive ()
2. Tree structure

```plain
README.txt

# core file integrity check
files.json # file hash list with manifest* and README.txt

# the backup metadata
manifest.json
  - version
  - created at
  - build info
  - maskbook version = 3?
  - type = maskbook-backup
  - files = file hash list without manifest* and README.txt

# manifest.json with persona private key signing
manifest-[persona-pubkey-hash].signed

permissions.json # original backup file "grantedHostPermissions" field.
user-groups.json # original backup file "userGroups" field.
posts.json # original backup file "posts" field.
profiles.json # original backup file "profiles" field.
personas.json # original backup file "personas" field.
```

**Comment by septs** [comment]
@Jack-Works @SunriseFox @guanbinrui 
maybe require **internal backup format definition**

```
backup file <-> backup format transformer <-> internal backup format
```

Use this method to clear version differences.

**Comment by Jack-Works** [comment]
Should each part of the backup format manage its own version? e.g. post backup v3 + permissions v1 in a single zip

**Comment by septs** [comment]
> Should each part of the backup format manage its own version? e.g. post backup v3 + permissions v1 in a single zip

Then need to be defined as:
- Container Format
- Data Format

**Comment by septs** [comment]
```
manifest.json
    - version = 3 // the is backup container format

posts.json
    - version = 1 // the is posts data format
```

**Comment by septs** [comment]
- <https://github.com/kravets-levko/tinytar>
Tiny Tar file
