### ISSUE TITLE
[Bug] Official site (mask.io) does not render on Chrome

### ISSUE THREAD

**Issue by newt0** [DimensionDev/Maskbook#9220]
### How to reproduce?

1. Accessing mask.io with Chrome on a Macbook Pro

### What happened?
I cannot open the mask.io website.
The screen renders for a moment and then immediately goes blank.

■ This occurs in the following environments
- Macbook Pro 13-inch, M1, 2020
- Ventura 13.2.1
- Latest Chrome
- Japan, Tokyo

■ Here's what I've tried that didn't work
- Hard reload
- Delete cookies
- Restarting Chrome
- Restarting Mac
- Change the Google account you are logged into Chrome with
- Change WiFi

**BUT, when I access the site from the Brave browser, it appears fine.**

■ Below is a video of the screenshot:
https://user-images.githubusercontent.com/56229817/229350801-e6038571-a874-4c4c-9304-0b91e01def26.mov

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)

**Comment by newt0** [comment]
I thought it might be due to a Chrome extension, so I tried seek mode as well. However, it still did not render.
https://user-images.githubusercontent.com/56229817/229351366-e005a0d3-6c4a-49d4-be58-5bf6c1eac9e0.mov

**Comment by Jack-Works** [comment]
webgl problem? 🤔

**Comment by zhouhanseng** [comment]
Are there any errors in devtool?  @newt0

**Comment by hanszhoou** [comment]
@newt0  Thanks for your feedback! I see there's an error thrown from `scheduler.production.min.js` in the video which not belongs to the source of mask.io. What about removing the extension which comes with the error, then have another try?

**Comment by Jack-Works** [comment]
scheduler.production.min.js is from React.
