### ISSUE TITLE
[Bug] Unable to link Mask to Instagram account on Brave browser

### ISSUE THREAD

**Issue by newt0** [DimensionDev/Maskbook#9222]
### How to reproduce?

1. Install Mask Extension in Brave Browser
2. Select Instagram from Mask
3.

### What happened?
When I try to link Mask to my Instagram account on the Brave browser, it does not respond.
Twitter and Facebook could be linked.

■ This occurs in the following environments
- Macbook Pro 13-inch, M1, 2020
- Ventura 13.2.1
- Latest Brave
- Japan, Tokyo

■ Here's what I've tried that didn't work
- Hard reload
- Delete cookies

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)

**Comment by guanbinrui** [comment]
Hi @newt0. We apologize for any inconvenience this may have caused you. After investigating the matter, we have discovered that the connection prompt is not appearing on some devices when attempting to connect an Instagram account. Thank you for your patience in addressing this bug.
