### ISSUE TITLE
[Demand] Able to enable image payload in Maskbook post view

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#923]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by guanbinrui** [comment]
<img width="617" alt="Screen Shot 2020-03-30 at 8 05 29 PM" src="https://user-images.githubusercontent.com/52657989/77910514-d53caf00-72c1-11ea-994b-b94bde74dc8d.png">


@OiCkilL Any ideas?

**Comment by OiCkilL** [comment]
> <img alt="Screen Shot 2020-03-30 at 8 05 29 PM" width="617" src="https://user-images.githubusercontent.com/52657989/77910514-d53caf00-72c1-11ea-994b-b94bde74dc8d.png">
> 
> @OiCkilL Any ideas?

I think we may give the user a choice, let users provide their own picture.

**Comment by guanbinrui** [comment]
> I think we may give the user a choice, let users provide their own picture.

The customizable image payload is another story. We may talk about it in another issue. This issue only adds a shortcut for the user to enable image payload in the post view.

**Comment by OiCkilL** [comment]
> > I think we may give the user a choice, let users provide their own picture.
> 
> The customizable image payload is another story. We may talk about it in another issue. This issue only adds a shortcut for the user to enable image payload in the post view.

OK, I think it's OK, but we may give some captions for this function.

**Comment by guanbinrui** [comment]
For now, we only have one switch here. So I put the switch into the footer part. Actually, It should not look like the components in the main content. Maybe we can change the switch to checkbox and choose a smaller font size.

Feel free to change the UI part.

**Comment by Tedko** [comment]
customizable image Sounds great. We can do it after fulfill this issue

**Comment by neruthes** [comment]
This position is reserved for Profile Switch button, which is a text label `Not ${Persona.Name}?`.

Try placing it as a dedicated row, like Recipients and Plugins.

**Comment by guanbinrui** [comment]
<img width="601" alt="Screen Shot 2020-04-07 at 11 43 54 AM" src="https://user-images.githubusercontent.com/52657989/78627873-200f8580-78c5-11ea-9772-2dc2e9a8a7d4.png">

Guys, How about this?

**Comment by neruthes** [comment]
LGTM.

**Comment by Tedko** [comment]
Good.

Make if default on ;)

**Comment by yisiliu** [comment]
It should be off by default and users can switch it in the setting.

**Comment by neruthes** [comment]
> It should be off by default and users can switch it in the setting.

+1

**Comment by Tedko** [comment]
Default on is much better for growth

**Comment by neruthes** [comment]
Robustness first.

**Comment by Tedko** [comment]
@guanbinrui is image payload robust enough now?

**Comment by guanbinrui** [comment]
For Twitter, we can reach the original image since it's robust enough.

For Facebook, the image payload will be highly compressed in some situations. I found that there are two data attributes refs to different quantity images at the Facebook desktop version (old edition). They are `data-ploi` and `data-plsi`, the front one has a quantity that enough for decoding.

The mobile version in both sites is not supported yet.

**Comment by neruthes** [comment]
Thanks for the info. As I interpret it, mobile devices cannot interpret image-based payloads properly at this moment. Since we are not going to abandon mobile users any time soon, it has no ground to make image-based payload the default option.

**Comment by Tedko** [comment]
Ok let’s keep the original default setting for M4 and keep working on
robustness of image payload
