### ISSUE TITLE
[RFC] Image Steganography (v1)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#93]
Work in Progress.

-------

# Purpose & Background

Sometimes we want to encode ciphertext into an image to avoid being detected as a countermeasure against surveillance and censorship.

# Criteria

- Only legitimate recipients may figure out it is actually a payload in Maskwork protocol.
- Others cannot determine whether a given image includes the payload.

# Fundamentals

## Inspiration from QR Code

Regardless of the actual size pre-upload image, we always divide its width into 128 columns and divide its height into rows of a height equal to the width of the columns, so that each cell is a square. Such a square is called a `macropixel`. We use macropixels to encode information.

## Eliminating Patterns

If we really use these macropixels to present a QR code, the pattern will be detectable by third parties. Therefore, we will have to employ something else.

## Bitstream as a Pattern Extractor

With that in mind, we can use a high-entropy bitstream to cherry-pick macropixels to fill the desired bits, by pairing each connected two into `macropixel pairs`. Out of a row, there will be 64 macropixels; if the image is a square, we will have 4096 macro pixels and each can encode 2 bits, totaling 1024 bytes in the image. This bitstream is called `cherry key`, and is shared to legitimate recipients in ways previously introduced. Even though anyone knows that this image may possibly include some binary payload with half macropixels, others do not know which half of the bits is used.

# Encoding

Suppose all images have color depth of 8 bits.

For the first macropixel (`matrix[0,0]`), we remove the last 2 bits of R and B channels of all the pixels in the macropixel, and fill each of the last 2 bits of R channels with `ciphertextBits[0]`, and fill each of the last 2 bits of B channels with `ciphertextBits[1]`. Other macropixels follow the same. Notice that only the chosen half are filled this way. Unchosen ones are filled with random bits. I recommend using unchosen macropixels for checksum to make errors more detectable or even correctable.

For better elimination of pattern, we may intentionally increase the stddev of manipulated bits. Therefore, the macropixels will be less detectable while the mean brightness of the macropixels remains the same.

# Decoding

The decoding procedure is really similar. A legitimate recipient will choose the correct half of the macropixels with the cherry key. They can extract the 2 last bits of R channel of all pixels in the macropixel, and will calculate the mean brightness of the pixels; only the 36% area (3x3 out of 5x5) at the center of the macropixel counts to the mean brightness. If the mean brightness of R channel of the macropixel falls in the brighter half, the first bit of the macropixel is `1`, otherwise the first bit of it is `0`. In this way, a legitimate recipient may recover the whole ciphertext.

# Scale

If using 2 bits is not enough, we can use the last 3 bits. Scaling bitstream length is easy and will not require much effort to modify the code. However, we might need to add length indicator in the macropixel-encoded bitmap payload. If we use the last 3 bits, there will be an color accuracy loss of 3.125%, which may be acceptable.

**Comment by Tedko** [comment]
Shouldn't we consider functionalities like encrypted Picture 1st？

**Comment by yisiliu** [comment]
They are the same. We need to solve the anti-compression problem.

**Comment by yisiliu** [comment]
no longer necessary
