### ISSUE TITLE
[Demand] Remote Feature Availability Control

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#935]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Requirements

https://confluence.dimension.chat/pages/viewpage.action?pageId=2064616

## Design Specs

// TODO: @septs

## Notes

- None.

**Comment by Jack-Works** [comment]
This behavior is far more than our goal: no central network

**Comment by neruthes** [comment]
> This behavior is far more than our goal: no central network

Needed for future campaigning events like ECCRP.

**Comment by neruthes** [comment]
Requirement document WIP: https://confluence.dimension.chat/pages/viewpage.action?pageId=2064616

**Comment by neruthes** [comment]
This may be subject to postponement if #996 is too complex.
