### ISSUE TITLE
[Task] Launch on Opera Extension Store

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#936]
## Metadata

Field | Value
--- | ---
Parent Task/Demand | /* Issue Number*/
Expected Delivery Date | 2020-W??-5

## Content

/* Actual content here... */

**Comment by Jack-Works** [comment]
@asonmine register an org Opera developer account? 🙈

**Comment by yisiliu** [comment]
Any update on this? @asonmine has already registered the account.

**Comment by Tedko** [comment]
@jack

**Comment by neruthes** [comment]
This should be expedited.

**Comment by yisiliu** [comment]
Wait until @AinuX has tested fully on Opera and resolve all the bugs there is one. Then we can start the procedure to submit to the Opera store, again. @Jack-Works can you do it please?

**Comment by Jack-Works** [comment]
I have submitted to the opera store.

**Comment by Jack-Works** [comment]
we've already published on opera store
