### ISSUE TITLE
[Demand] Platform-agnostic cryptographic provider

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#937]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

The current API we are using is based on the Web Crypto API. But the Web Crypto API is missing support for secp256k1, therefore, it (polyfill) is running in the main thread and slow down the calculation.

Design goal:

- Polyfills run in the worker, make it truly async (not consuming main thread computation resource)
- Minimal API set (that we're currently using) instead of an isomorphic of Web Crypto API.
- Still use platform native (Web Crypto API as backend) if it is possible
- Friendly to test environment
- Possibility to switch to WASM/other backends in the future.
- [?] API design friendly to smart card

**Comment by yisiliu** [comment]
One of our goals at https://github.com/dimensiondev/ntge is providing such a cryptography library. In the implementation,  we are also taking WASM into consideration. We will notify you guys here when it's done.

**Comment by Jack-Works** [comment]
Already shipped
