### ISSUE TITLE
[Demand] Scheduling Revamp (Stage 2)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#948]
## Metadata

Field | Value
--- | ---
Previous Stage | #656 
Figma Link | N/A
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Background

In #656, we optimized the scheduling of web operations.

In this issue, we are going to optimize for computation-intensive operations so that they will no longer create lagging in the main thread.

## List of Operations to Migrate

// TODO: @Jack-Works 

## Notes

- None.

**Comment by Jack-Works** [comment]
please checkout https://github.com/DimensionDev/Maskbook/pull/938 and https://github.com/DimensionDev/Maskbook/issues/937

**Comment by Tedko** [comment]
shipped
