### ISSUE TITLE
[Demand] Figure out a way to not force user to add pubkey in bio

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#951]
## Metadata

As many feedback we got, it’s hard to let user keep the pubkey in the bio. 
- they may have no space left in bio
- they may want to remove the pubkey after having a try since its misleading etc.

Potential solution - 
1. emoji based pubkey (Hanji etc based pubkey wont work, no more discussion on this)
2. A better way than add pub key in bio. There’s some tech limitation for proof post, maybe we have better alternatives as well.

We will start the growth campaign etc soon. Need speedy solution for this.

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
Emoji does not work. No more discussion.

Fundraising is more important than software reliability. I hereby permit the dismantlement of pasting public key in bio.

**Comment by yisiliu** [comment]
We need to find a place that can be **publicly verified** to store the mapping between a public key and an SNS account. So far, I haven't found a better place than the bio field. 
Regarding your question here, how does an emoji based public key help?

**Comment by Tedko** [comment]
> We need to find a place that can be **publicly verified** to store the mapping between a public key and an SNS account. So far, I haven't found a better place than the bio field.
> Regarding your question here, how does an emoji based public key help?

Any way can make user 1. not delete their punkey in bio 2. Feel more friendly
