### ISSUE TITLE
[Demand] Delete all bio-related features

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#952]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

I have decided to relinquish my position on the necessity of including public key in bio. All bio-related features should be deleted according to the consensus of other members of our team.

## Documentation Changes

[Story: Initialization](https://confluence.dimension.chat/x/PIAf) (Section "Workflow 2: Connect Profile") has been updated.

## Catalogue

- Profile Connecting Logic Revamp
- Persona-Profile Pair Witness Logic Revamp

## Part 1: Profile Connecting Logic Revamp

See https://confluence.dimension.chat/x/PIAf Section "Workflow 2: Connect Profile".

[Figma Link](https://www.figma.com/file/4DmpRxZk4jDeqrfA5xrPCp/Dashboard-v3?node-id=764%3A28)

![image](https://user-images.githubusercontent.com/2139261/82795931-40d76e80-9e64-11ea-9f98-3ef12a03964c.png)

![image](https://user-images.githubusercontent.com/2139261/82795945-459c2280-9e64-11ea-9988-d7f3a3181740.png)

When the username is confirmed, the user will be advised to create the first encrypted post under the profile.

## Part 2: Persona-Profile Pair Witness Logic Revamp

// TODO

## Notes

- This will affect #600 & #409. 
- This will affect https://confluence.dimension.chat/x/V4Af.
- This will affect https://confluence.dimension.chat/x/VIAf.

**Comment by yisiliu** [comment]
As I mentioned in #951, if we are abandoning bio, where should we keep that mapping?

**Comment by neruthes** [comment]
> As I mentioned in #951, if we are abandoning bio, where should we keep that mapping?

Optional strategy: If cannot find a public key declaration (Post, ECCRP, etc) in the most recent X (e.g. 50) posts, consider the profile unconnected.

**Comment by Tedko** [comment]
We need to figure out potential solutions for
With pub key in bio -

1. have some ways to make user not delete their pub key in bio (not by making them confuse)
2. Feel more friendly about the pub key in bio. Make is something like tattoo (cool). PGP fingerprint did some good job in a small group users.

Without pub key in bio - 
1. method to keep the main functionalities (encrypt/decrypt) working and 
2. easy to setup etc. Post proof-post like experiences.

**Comment by Jack-Works** [comment]
> > As I mentioned in #951, if we are abandoning bio, where should we keep that mapping?
> 
> Optional strategy: If cannot find a public key declaration (Post, ECCRP, etc) in the most recent X (e.g. 50) posts, consider the profile unconnected.

Searching so many posts is more dangerous than the bio way

**Comment by neruthes** [comment]
Discussion Summary:

The discovery of pairing can be passive, like described in Confluence.

cc @yisiliu

**Comment by neruthes** [comment]
This should be delivered together with #1124.

**Comment by Tedko** [comment]
@guanbinrui  @OiCkilL 

so now we have 2 options:
- user chose `Say Hello` or `Bio`. Back to the `proof post or bio` situation.
- rm bio related feature first. Add it back only when we have ENS like domain ready. ( `alice.maskbook.xyz` can be linked to pub key of Alice by blockchain contracts). 

What do you think? I prefer option 1 for now. We can user a relatively centralized key server for the mapping alice.maskbook.xyz<>pub key; which i mentioned to @jk234ert b4

**Comment by Tedko** [comment]
or we can use Arweave as a key server for `proof post url`<>`fb/twitter uuid/url`

**Comment by neruthes** [comment]
Ref: https://github.com/DimensionDev/Maskbook-Talks/issues/49

**Comment by Tedko** [comment]
Fixed by binrui
