### ISSUE TITLE
[Bug] Wallets disappear after restoring from a backup

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#954]
# Bug Report

### Browser

- Browser: Chrome
- Browser Version: -

### Maskbook

- Maskbook Version: 1.10.9
- Installation: Store
- Build Commit: -

### Expected Behavior

All wallets should remain after restoration.

### Actual Behavior

![Clipboard - April 8, 2020 7-53 AM](https://user-images.githubusercontent.com/2139261/78758904-5ce38700-796e-11ea-9b4d-4fa30eaa8b12.png)

### How To Reproduce

Backup, reinstall, and restore from the backup file.

### Notes

- We should also make sure that the data of plugin "Red Packet" is included in the backup.
- See also #1337.

**Comment by Jack-Works** [comment]
Because the wallet is not contained in the backup yet. (it was a plugin back in time.)

**Comment by septs** [comment]
Temporary solution: #958

**Comment by neruthes** [comment]
> Because the wallet is not contained in the backup yet. (it was a plugin back in time.)

Plugin-specific data tables should be included in the backup, although not explicitly stated in #634. 

Also, avoid losing plugin data when new plugins are introduced.
