### ISSUE TITLE
[Bug] Connect to Twitter not working

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#956]
# Bug Report

### System

- OS: macOS
- OS Version: 10.15.4

### Browser

- Browser: Chrome
- Browser Version: 80.0.3987.163

### Maskbook

- Maskbook Version: 1.10.11
- Installation: Self-Complied
- Build Commit: first bad commit, https://github.com/DimensionDev/Maskbook/commit/65f672edca541da0d8a43d8037202fb6c5e8e514

### Expected Behavior

Fix show `Connect Profile`.

### Actual Behavior

`Connect Profile`, Step by step not working.

### How To Reproduce

```
git checkout 65f672edca541da0d8a43d8037202fb6c5e8e514
yarn build
```

**Comment by septs** [comment]
@Jack-Works Click "Connect Profile" Panel - "Finish" Button
Not Respond

**Comment by guanbinrui** [comment]
> @Jack-Works Click "Connect Profile" Panel - "Finish" Button
> Not Respond

I created an issue for this just a moment ago. # 959

**Comment by septs** [comment]
@guanbinrui ACK
