### ISSUE TITLE
[Bug] Cannot finish immersive guide

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#959]
# Bug Report

### System

- OS: MacOS Mojave
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.10.10
- Installation: Self-Compiled
- Build Commit: a921183eb9988850fd90a62f548f94b75094845f

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Reproduced successfully.

**Comment by Tedko** [comment]
Bug report:
![IMG_6798 PNG](https://user-images.githubusercontent.com/6687437/79087423-c6e69c80-7d71-11ea-9759-832a2429402e.jpeg)
![IMG_6799 PNG](https://user-images.githubusercontent.com/6687437/79087440-d1a13180-7d71-11ea-862c-7e8e64825b1f.jpeg)


Video:
https://dimension.chat/group/maskbook?msg=axJSpsv5w6ihTdKvQ

Might be related with this issue -

**Comment by guanbinrui** [comment]
> Bug report:
> ![IMG_6798 PNG](https://user-images.githubusercontent.com/6687437/79087423-c6e69c80-7d71-11ea-9759-832a2429402e.jpeg)
> ![IMG_6799 PNG](https://user-images.githubusercontent.com/6687437/79087440-d1a13180-7d71-11ea-862c-7e8e64825b1f.jpeg)
> 
> Video:
> https://dimension.chat/group/maskbook?msg=axJSpsv5w6ihTdKvQ
> 
> Might be related with this issue -

I'm afraid not. This bug will prevent the user from creating a persona. We might trace the bug in another issue.
