### ISSUE TITLE
Next generation storage backend with authorizing and information hiding

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#96]
##### How we currently use GUN:
1. posts, we use it to store post salt, protocol version, target user and derived keys (very important for it to function).
2. users, we use it to cache provePostId (less important).

##### Current flaw:
1. **All data stored are volatile**. Anyone can modify or delete any of them. Whenever such thing happens, all previously encrypted posts are lost and all nodes get synced so that recovery is not possible.
2. As userID is not encrypted, any subscribed user can easily have a peek about who are using our product and who are posting to whom.

##### Design limitations:
1. We cannot hide anything in GUN, all keys and values are accessible to any subscribed users. 
2. We can only implement an access control system to limit write access on 'legal users' and 'authorized superpeers', but not bad users and bad superpeers. So it is end users' responsibility to verify and reject retrieved data to prevent potential attacks.

##### What we want now:
1. Add a permission control system for every trusted node, so that they can sign all pushed data with current node's private key and verify the fetched data and reject them if not signed or corrupted. 
2. Hash the user id to make it hard to identify but still queryable. e.g, only the actual target can decrypt one of the elements in the `target[]` using their private key.

#####  How we do that:
1. Integrated it with SEA, but we need to use (or rebase it on) their key deriving and distributing approach.
2. ...

// TODO

**Comment by Tedko** [comment]
Considering using IPFS/(textile) in some cases?
