### ISSUE TITLE
[Bug] Cannot backup Persona through QR if no SNS connected

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#965]
# Bug Report

<img width="1245" alt="Screen Shot 2020-04-10 at 15 00 43" src="https://user-images.githubusercontent.com/6687437/78970536-1a6fa500-7b3c-11ea-99b0-42a174194efc.png">

### System

- OS:
- OS Version:

### Browser

- Browser:Firefox
- Browser Version:

### Maskbook

- Maskbook Version:1.10.11
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

Create a new Persona such as '123' pw '123'.
Try to backup Persona through QR -> cant render QR code
/* Specify how it may be produced here. */

**Comment by guanbinrui** [comment]
At least one SNS identifier should be connected.

**Comment by Tedko** [comment]
> At least one SNS identifier should be connected.

@guanbinrui So this is Expected Behavior?

**Comment by guanbinrui** [comment]
> @guanbinrui So this is Expected Behavior?

I think it's a bug.

**Comment by Tedko** [comment]
Ok let’s fix this

**Comment by septs** [comment]
No Camera available, require hint message.
