### ISSUE TITLE
[Demand] Better Chinese Translation for term 'Persona'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#971]
## Metadata

So far, I received several feedback about the proper translation of this word:

<img width="612" alt="Screen Shot 2020-04-12 at 00 50 06" src="https://user-images.githubusercontent.com/6687437/79049695-b8a45d80-7c57-11ea-9e86-971e7ad8e1c8.png">
<img width="510" alt="Screen Shot 2020-04-12 at 00 50 31" src="https://user-images.githubusercontent.com/6687437/79049696-ba6e2100-7c57-11ea-9ca5-bfd210a1be19.png">
<img width="424" alt="Screen Shot 2020-04-12 at 00 50 40" src="https://user-images.githubusercontent.com/6687437/79049697-bc37e480-7c57-11ea-9457-4535e21480e3.png">
<img width="532" alt="Screen Shot 2020-04-12 at 00 50 55" src="https://user-images.githubusercontent.com/6687437/79049700-be9a3e80-7c57-11ea-9ee5-3caaebac8b9d.png">

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by Tedko** [comment]
Potential Solution:

- Just use 'Persona' without translation (same thing happen for cookie / bug, but since we're facing end user not developer, we might need to think carefully)
- Use something like ‘身份’ etc, and try not use 'ID' in the same page etc.

**Comment by neruthes** [comment]
Good point. Ideas are welcome.

**Comment by OiCkilL** [comment]
Some philosophical references:
https://www.douban.com/note/152887295/

**Comment by Tedko** [comment]
👍

**Comment by yisiliu** [comment]
Let's just ignore the translations then. Note that persona has two plural forms: `personae` and `personas`. And the former one is usually used.

**Comment by Tedko** [comment]
Actually personas
Is usually used according to Firefox Persona etc

**Comment by Tedko** [comment]
will use 角色 for now
