### ISSUE TITLE
[Bug] Popup UX error

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#974]
# Bug Report
<img width="289" alt="Screen Shot 2020-04-13 at 11 17 17" src="https://user-images.githubusercontent.com/6687437/79089446-c4d40c00-7d78-11ea-9fcf-4a3ae503bb2c.png">

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
Notice the button margins as well.

**Comment by Tedko** [comment]
<img width="1347" alt="Screen Shot 2020-04-26 at 03 05 59" src="https://user-images.githubusercontent.com/6687437/80288708-50cc3780-876c-11ea-998e-abeb0e59d23f.png">
Another Line Height UX problem

**Comment by neruthes** [comment]
This line-height does look inappropriate. Probably @OiCkilL may have some suggestion.

**Comment by guanbinrui** [comment]
> This line-height does look inappropriate. Probably @OiCkilL may have some suggestion.

I copy the `line-height` from the native composing view.

**Comment by Tedko** [comment]
> > This line-height does look inappropriate. Probably @OiCkilL may have some suggestion.
> 
> I copy the `line-height` from the native composing view.

![Screen Shot 2020-04-26 at 17 56 26](https://user-images.githubusercontent.com/6687437/80304277-6e8ab280-87e7-11ea-97a1-9986ead18b56.png)
![Screen Shot 2020-04-26 at 17 56 22](https://user-images.githubusercontent.com/6687437/80304281-7185a300-87e7-11ea-9206-ed200d6d8018.png)
@guanbinrui

**Comment by guanbinrui** [comment]
I did that in the patch commit https://github.com/DimensionDev/Maskbook/commit/586671c06fce1094047481ec783664cfa01b957d.

**Comment by Tedko** [comment]
fixed

**Comment by guanbinrui** [comment]
> fixed

This bug will be fixed in [M3A](https://github.com/DimensionDev/Maskbook/milestone/8)
