### ISSUE TITLE
[Bug]Web3 Profile, already linked to wallet but prompted, need to link to wallet

### ISSUE THREAD

**Issue by qqqzhch** [DimensionDev/Maskbook#9748]
## Bug Info
![image](https://github.com/DimensionDev/Maskbook/assets/3917994/f0f25eae-0700-4f55-b520-8387d22ec0f3)
![image](https://github.com/DimensionDev/Maskbook/assets/3917994/59d1efde-e7ca-405e-9cff-06fa4049e0fc)

### How to reproduce?

1.click Web3 Profile 
2. click nfts 
3. click the btn is  addwallet
The first time I clicked on Add Wallet, a pop-up box appeared, suggesting that a signature and other actions were required, I clicked on the button a few times and didn't see a pop-up for a signature, so the action should have been unsuccessful
Then I clicked Add Wallet again and it opened the list of wallet assets, it looks like I need to add assets, I don't know if the prompt here is to chain the wallet or to add assets

### What happened?
1 Authorized signature did not complete and was not successful
2 The text for adding a wallet is confusing and should be changed to Signature Authorization if it is required
### What should happen?
If you need to authorize a signature, the first click on Add Wallet Authorization Signature failed and the second click should also result in an authorization signature pop-up

## Environment 
win 11  chome
### Mask Version:2.20.2

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [x] Windows 11
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)

**Comment by qqqzhch** [comment]
/dashboard.html#/personas
I've linked to twitter in my browser add-on wallet

**Comment by hanszhoou** [comment]
@qqqzhch Thanks for your feedback. 
We have erased the NFT part from Web3 Profile in the latest version.
