### ISSUE TITLE
[Demand] Able to select file when importing Persona via QR code

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#975]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Function Entry

In the Import Persona screen, a button "Select File" (zh: 選取圖像文件) should be added below the camera preview area in the "QR" option tab.

When the user clicks the button, Maskbook shows a file selection dialogue, in which the user may choose an image file from the local file system.

## Ideal Workflow

After a file selection is made, Maskbook finds the QR code in the image, and imports the Persona directly without further confirming.

(Q: Should Maskbook ask the user for permission to access the websites which this Persona has profiles on?)

### Cannot find QR in image

The user will see an alert:

Language | Title | Text | ButtonText
--- | --- | --- | ---
en | Error: Cannot Find Any QR Code | Maskbook cannot find any QR code in the image. Try another file? | OK
zh | 錯誤：未能找到 QR | Maskbook 未能於圖像中找到 QR。嘗試別的文件？ | 好

### QR content is not a valid Persona backup

The user will see an alert:

Language | Title | Text | ButtonText
--- | --- | --- | ---
en | Error: Invalid Backup | The QR code does not contain a valid backup. Try another file? | OK
zh | 錯誤：无效的 QR | 图中的 QR 是无效的，其中没有包含备份。嘗試別的文件？ | 好

## Notes

- Ref: #970.

**Comment by neruthes** [comment]
A few moments ago @septs just mentioned the idea of using a testcard image for the preview when there is no camera signal input.

![](https://upload.wikimedia.org/wikipedia/commons/b/b4/Chinese_Testcard.jpg)

Looking forward to feedbacks.

**Comment by Tedko** [comment]
> A few moments ago @septs just mentioned the idea of using a testcard image for the preview when there is no camera signal input.
> 
> ![](https://camo.githubusercontent.com/6ddee1d3f55e9966b59ddf928119802ee585f8ac/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f622f62342f4368696e6573655f54657374636172642e6a7067)
> 
> Looking forward to feedbacks.

This pic is bad..

use the one with Masks (used for our social network)
