### ISSUE TITLE
[Bug] Fix image based payload on Maskbook Mobile

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#976]
# Bug Report
For now these are several problems about image based payload on Mobile

- [x] Cannot compose image based payload on Maskbook iOS/Android

- [ ] Fb only: Hard to fetch proper img for decryption on facebook mobile site.

- [x] Fix decrypt image based payload for **Twitter mobile site**

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by neruthes** [comment]
P2 is good.

**Comment by Tedko** [comment]
@guanbinrui known problem for image payload on Firefox?
<img width="1347" alt="Screen Shot 2020-04-26 at 03 21 46" src="https://user-images.githubusercontent.com/6687437/80288820-3181da00-876d-11ea-95ae-dd596071e22f.png">

**Comment by guanbinrui** [comment]
> @guanbinrui known problem for image payload on Firefox?
> <img alt="Screen Shot 2020-04-26 at 03 21 46" width="1347" src="https://user-images.githubusercontent.com/6687437/80288820-3181da00-876d-11ea-95ae-dd596071e22f.png">

That's wired. I can decrypt your image payload from https://twitter.com/suji_yan/status/1254125316747825153.

**Comment by Tedko** [comment]
update:

- Now able to decrypt Twitter img payload on ios/android

**Comment by Jack-Works** [comment]
so close this?

**Comment by Tedko** [comment]
@jk234ert @Jack-Works not able to decrypt img payload on iOS TF ver again.

eg Case: https://twitter.com/suji_yan/status/1327057013310799872?s=20

**Comment by Tedko** [comment]
> @jk234ert @Jack-Works not able to decrypt img payload on iOS TF ver again.
> 
> eg Case: https://twitter.com/suji_yan/status/1327057013310799872?s=20

Oh its working... its just very slow on ios tf ver

**Comment by Tedko** [comment]
I will close this issue and open other following ups

Now we can:
- Decrypt img payload on both iOS and Android on Twitter;
- For fb this bug is blocked by #1813  

We need to followup on 
- Decryption speed is very slow for img payload
- Fix Fb after #1813 
- Able to send img payload through ios/android

**Comment by Tedko** [comment]
Also 
`Able to send img payload through ios/android`
is related with #1786
