### ISSUE TITLE
[Demand] Plugin System (Stage 1)

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#987]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Brainstorming

https://github.com/DimensionDev/Maskbook-Talks/issues/31

## Documentation

https://confluence.dimension.chat/x/9IAf

## Notes

- None.

**Comment by yisiliu** [comment]
Are you sure M4?

**Comment by neruthes** [comment]
Looks like the release of M5 can be submitted to Chrome Web Store before May 10 if we submit M4 quickly. If we submit M4 today or tomorrow, moving this to M5 will be good.
