### ISSUE TITLE
[Demand] Reduce App size for Maskbook iOS build

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#988]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Catalogue

- ...
- ...
- ...

**Comment by neruthes** [comment]
Indeed necessary.
