### ISSUE TITLE
[Demand] i18n revision

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#990]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L86
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/en/messages.json#L86

-------

https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L205
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/en/messages.json#L205

I think `某些` not applicable, it may apply `部分` instead

| Old | New |
| - | - |
| 需要某些網站的訪問許可 | 需要部分網站的訪問許可 |
| 如果您發現某些舊帖子無法解密 | 如果您發現部分舊帖子無法解密 |

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L67

Add space symbol to Chinese / English before and after?

**Comment by neruthes** [comment]
> https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L67
> 
> Add space symbol to Chinese / English before and after?

Yes we need Space characters.

**Comment by neruthes** [comment]
For the "某些" vs "部分" question, I suggest that using "相关" is a more native option.

**Comment by septs** [comment]
About "Dark mode" converation:
https://github.com/DimensionDev/Maskbook/commit/c3662a4700659839a521f23b89db5954de2132c0

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L146-L147

```
"正在生成 QR 碼…" -> "正在生成 QR Code…"
"請不要保存或將此 QR 碼分享給他人！" -> "請不要保存或將此 QR Code 分享給他人！"
```

Reference:
https://www.twmp.com.tw/News/Detail/-%E5%8F%B0%E7%81%A3%E8%A1%8C%E5%8B%95%E6%94%AF%E4%BB%98-APP%E6%8E%A5%E8%BB%8C%E5%9C%8B%E9%9A%9B-%E5%B9%B4%E5%BA%95%E5%89%8D%E6%94%AF%E6%8F%B4%E4%BF%A1%E7%94%A8%E5%8D%A1QR-Code-2018-07-06--1555998914
https://technews.tw/2019/07/20/qr-code-payment/

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L148-L150

How to spell "payload" correctly?

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L151

`安裝新版`? replace to `升级`?

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L190

`我們認為這不是 Maskbook 備份。`?

**Comment by yisiliu** [comment]
A thorough review of these i18 messages is necessary now. Let's create a PR on this.

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L56

`導出 Keystore`?

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L139
`沒有搜寻结果`?

**Comment by neruthes** [comment]
> https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L190
> 
> `我們認為這不是 Maskbook 備份。`?

I would like to discourage the use of first person pronouns. Use passive voice when possible, e.g. "The file is not a valid backup" & "This format has been deprecated".

Finally, when a subject is inevitable, use "Maskbook".

**Comment by neruthes** [comment]
> https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L151
> 
> `安裝新版`? replace to `檢查更新`?

I think the current text is good enough.

**Comment by neruthes** [comment]
> https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L57
> 
> 
> https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L146-L147
> 
> ```
> "正在生成 QR 碼…" -> "正在生成 QR Code…"
> "請不要保存或將此 QR 碼分享給他人！" -> "請不要保存或將此 QR Code 分享給他人！"
> ```
> 
> Reference:
> https://www.twmp.com.tw/News/Detail/-%E5%8F%B0%E7%81%A3%E8%A1%8C%E5%8B%95%E6%94%AF%E4%BB%98-APP%E6%8E%A5%E8%BB%8C%E5%9C%8B%E9%9A%9B-%E5%B9%B4%E5%BA%95%E5%89%8D%E6%94%AF%E6%8F%B4%E4%BF%A1%E7%94%A8%E5%8D%A1QR-Code-2018-07-06--1555998914
> https://technews.tw/2019/07/20/qr-code-payment/

"QR Code" and "QR 碼" both look good to me personally. But unification is necessary.

**Comment by septs** [comment]
> > https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L151
> > 
> > `安裝新版`? replace to `檢查更新`?
> 
> I think the current text is good enough.

https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L197

**Comment by neruthes** [comment]
> > > https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L151
> > > 
> > > `安裝新版`? replace to `檢查更新`?
> > 
> > 
> > I think the current text is good enough.
> 
> https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L197
> 
> require unification is necessary.

Deprecated payload format and unknown newer version are different cases and I believe that they should be distinguished since they require different user operations.

**Comment by septs** [comment]
> > https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L57
> > 
> > https://github.com/DimensionDev/Maskbook/blob/f8362366ddda2a9a7bb0a6b184c0dcde67994000/src/_locales/zh/messages.json#L146-L147
> > 
> > ```
> > "正在生成 QR 碼…" -> "正在生成 QR Code…"
> > "請不要保存或將此 QR 碼分享給他人！" -> "請不要保存或將此 QR Code 分享給他人！"
> > ```
> > 
> > 
> > Reference:
> > https://www.twmp.com.tw/News/Detail/-%E5%8F%B0%E7%81%A3%E8%A1%8C%E5%8B%95%E6%94%AF%E4%BB%98-APP%E6%8E%A5%E8%BB%8C%E5%9C%8B%E9%9A%9B-%E5%B9%B4%E5%BA%95%E5%89%8D%E6%94%AF%E6%8F%B4%E4%BF%A1%E7%94%A8%E5%8D%A1QR-Code-2018-07-06--1555998914
> > https://technews.tw/2019/07/20/qr-code-payment/
> 
> "QR Code" and "QR 碼" both look good to me personally. But unification is necessary.

We need to respect the local culture!
