### ISSUE TITLE
[Demand] Not popup the permission alert on Maskbook Android 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#993]
## Metadata

- So we won't have the ask for permission alert anymore ![IMG_5568](https://user-images.githubusercontent.com/6687437/79598638-e6394d00-8116-11ea-815f-2297c6819abd.jpg)

Field | Value
--- | ---
Parent Task/Demand | /* Issue Number*/
Expected Delivery Date | 2020-W??-5

## Content

/* Actual content here... */

**Comment by Jack-Works** [comment]
🤔

**Comment by Tlaster** [comment]
This permission alert is from Facebook and it is a web standard API https://developer.mozilla.org/zh-CN/docs/Web/API/notification/requestPermission

**Comment by Tedko** [comment]
Seems like iOS side already removed this alert manually (web view -shim).
🤔 Seems not easy to do so for Gecko view.

**Comment by Tedko** [comment]
is this possible to achieve (like the iOS)? @Tlaster @Jack-Works

**Comment by Jack-Works** [comment]
Yes, close this if it is already fixed

**Comment by Tedko** [comment]
@Jack-Works I guess need more work on Andriod side?

**Comment by Jack-Works** [comment]
In the codebase, it already grants all site permissions so theoretically this problem won't appear again

**Comment by neruthes** [comment]
Will reopen when reproduced.
