### ISSUE TITLE
[Bug] Timestamp bug when importing Persona through QR code

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#994]
# Bug Report

- Should not display 1970/1/1 etc. This is very unfriendly. We should not assume our users are *nix geeks.
- Display 'Create at unknown time or the timestamp might be inaccurate' instead. More suggestions are welcomed.
- Should we check if the timestamp is before 2019/04/01? if before that date it should be viewed as invalid as well. 

<img width="600" alt="Screen Shot 2020-04-18 at 02 00 26" src="https://user-images.githubusercontent.com/6687437/79599729-9b203980-8118-11ea-86aa-5625ed920610.png"><img width="600" alt="Screen Shot 2020-04-18 at 02 04 42" src="https://user-images.githubusercontent.com/6687437/79600080-2a2d5180-8119-11ea-9960-acbfc09ab651.png">

<img width="300"  src="https://user-images.githubusercontent.com/6687437/79599841-c571f700-8118-11ea-8712-62ab597ae7db.PNG"><img width="300"  src="https://user-images.githubusercontent.com/6687437/79600188-51841e80-8119-11ea-8962-0b23b9eff136.jpg">

### System

- OS: iOS Android & web
- OS Version:

### Browser

- Browser: ff & chrome
- Browser Version: latest 

### Maskbook

- Maskbook Version: latest of App store/ google play/ firefox/ chrome store
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

Import persona through QR code. If its a code persona generated in the previous several ver you will see restore from 1970/1/1 etc

**Comment by neruthes** [comment]
Can someone fix this UI bug as well?

<img width="121" alt="image" src="https://user-images.githubusercontent.com/2139261/79732971-f0f50d00-82e3-11ea-92ce-244bdffeafc8.png">

**Comment by Tedko** [comment]
@guanbinrui @septs try fix this bug asap?

**Comment by Jack-Works** [comment]
Hmm it's a design decision that for backup files created at unknown time (e.g. from the very old version 1), the timestamp will be  0 when upgraded into newer version.

And IMO I explicitly noted that UI should display it as "unknown" if timestamp is 0.

----------------------

IIRC this will only affect users that use older version of backup file, new users won't be affected.

**Comment by Tedko** [comment]
> Hmm it's a design decision that for backup files created at unknown time (e.g. from the very old version 1), the timestamp will be 0 when upgraded into newer version.
> 
> And IMO I explicitly noted that UI should display it as "unknown" if timestamp is 0.
> 
> IIRC this will only affect users that use older version of backup file, new users won't be affected.

ok. 

Yeah lets change 1970 to `unknown` pls. @Jack-Works @guanbinrui

**Comment by Jack-Works** [comment]
Db won't fix this cause there is nothing to do. It's UI related work

**Comment by Tedko** [comment]
ok lets fix this tmr then

@guanbinrui
