### ISSUE TITLE
[Demand] Plugin: Gitcoin

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#996]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | https://www.figma.com/file/6YeqA0eCTz67I1HVFXOd4X/Plugin-Gitcoin
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Documentation

https://confluence.dimension.chat/x/OYEf (WIP)

## Notes

- None.

**Comment by Tedko** [comment]
‘Gitcoin’

**Comment by Tedko** [comment]
Not Capital C

**Comment by neruthes** [comment]
<img width="512" alt="Screen Shot 2020-04-22 at 08 05 03" src="https://user-images.githubusercontent.com/2139261/79957119-a785f880-8470-11ea-9ce4-746ea96e1b36.png">

Can someone remind me of a list of supported tokens? 🤔

**Comment by yisiliu** [comment]
This is tricky. Is this the real UI on gitcoin?

**Comment by Tedko** [comment]
Some grant support only specific token (determined by the grant creator)

Some accept all tokens(token allowed by gitcoin). You can go to the
maskbook grant and take a look.
